### ISSUE TITLE
Establish a mechanism for communicating with the API

### ISSUE THREAD

**Issue by dylanmccall** [pg-irc/pathways-frontend#10]
At the moment we have a store for getting data from an HSDA locations endpoint, using mobx-rest. This is a pretty solid starting point, but we need quite a bit more:

- [ ] Add a SearchAPIStore that talks to our (hypothetical) search API, described in pg-irc/pathways-backend#93.
- [ ] Add a SearchStore that processes data from SearchAPIStore and, using serializr, converts this data into smart objects (with type checking, relationships, and convenience functions).
- [ ] Move API stores (stores based on mobx-rest) into a private stores subdirectory. These should all be named like [Resource]APIStore. Code outside of stores should not talk to these directly.
- [ ] Start using SearchStore in our service map code.

**Comment by rasmus-storjohann-PG** [comment]
Closing, we have an established pattern for how to do the service search
