### ISSUE TITLE
Suggestion Page for Feedback Module

### ISSUE THREAD

**Issue by aron-chen-pg** [pg-irc/pathways-frontend#1004]
Some terminology to be defined:

- **Service detail**: Content regarding a particular service. For instance, service name, service provider, service description, address, phone, etc...
- **Service Detail Page**: The UI that is used to show the service detail regarding a particular service.
- **Suggestion Page**: The UI that is used to make suggestions to the service details regarding a particular service.

The Suggestion Page for Feedback Module provides users with the ability to make suggestions to the individual parts of the service detail (i.e. service name, description, address, etc..). Unlike the Service Detail Page, the suggestion page should not have a clear visual hierarchy (i.e. Service name owns the heaviest visual weight). All service detail shown within the Suggestion Page should have the same visual treatment so that the users can easily skim through all the content without being distracted. 

Here is the updated mock: https://zpl.io/VDwj8kw

### Acceptance Criteria 
- [ ]  Checking the individual checkbox will expand and reveal the input field for the user to type in their suggestion for individual parts. Once the editing is done (the keyboard is closed), the user input will appear in teal colour.
- [ ]  Individual labels (both customized or existing labels) and description should have the same appearances (same font style, same font size)
- [ ]  Clear divider (grey, extends full width) to section off different parts of the service detail. 

### Steps for QA: 
1.

**Comment by bensinjin** [comment]
Notes from talk from Aron:

- The light grey divider now replaces the existing tan one, this is a universal change and should appear full width everywhere
- The labels in the designs are only in edit mode
- We really need to be able to render these fields as consistently as possible which means dropping styling (ie H1s) and making it look as close to the designs as possible
- The entire "Suggest an update" with checkbox section should be clickable

**Comment by bensinjin** [comment]
Both issues outlined here have their own tickets now: #1016 & #1017
