### ISSUE TITLE
iOS Distribution Certificate will no longer be valid on March 4, 2020

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1007]
Your iOS Distribution Certificate will no longer be valid in 30 days. To generate a new certificate, sign in and visit Certificates, Identifiers & Profiles.

Certificate: iOS Distribution
Team ID: <blank>

To learn more about expired certificates, visit the certificates support page.

Best regards,
Apple Developer Program Support

**Comment by tomy-pg** [comment]
Generated new iOS Distribution Certificate.
Expiry date: March 16, 2021.
