### ISSUE TITLE
Service list refreshes every time 'load more services' is clicked

### ISSUE THREAD

**Issue by aron-chen-pg** [pg-irc/pathways-frontend#1012]
Every time when the 'load more services' button is clicked, the whole service listing refreshes. Users would lose their scrolling position and have to scroll down again in order to explore more services. The experience gets progressively worse since the list will only grow longer every time the button is clicked, thus consuming more of users' time to scroll. In addition, since all the services are listed in text format without any visual cue, it became incredibly difficult to rediscover the service the users were last on.

The experience is recorded here in the link below:
https://drive.google.com/file/d/1-14TLSFv10B_BO08w3BcDi4nZEa-9GEv/view?usp=sharing

To address the bug, the ideal experience would be to retain the scrolling position upon clicking the 'load more services' button. That way users can simply continue their search without having to spend time to scroll down the list again.

### Acceptance Criteria
- [ ] After clicking onto the 'load more services' button, the scrolling position is retained.

**Comment by ian-lin-PG** [comment]
This issue is related to issue #892. Wrapping the Flatlist and loadmore button in a scrollview sometimes mitigate the issue but is ill advised as it causes warning.

**Comment by tomy-pg** [comment]
This will be an Acceptance Criteria as part if Issue #1058
