### ISSUE TITLE
Bookmarking a service in some lists resets the scroll position

### ISSUE THREAD

**Issue by bensinjin** [pg-irc/pathways-frontend#1016]
We currently are encountering a bug initially reported here: https://github.com/pg-irc/pathways-frontend/issues/892#issuecomment-579996788. Basically in some places where we render bookmark-able items in lists the state change in Redux caused by bookmarking an item triggers a re render that refreshes the scroll state of the list (it scrolls back up to the top of the list). This is not a new bug and has previously been fixed by properly using FlatList's "HeaderComponent" prop to render anything above the list, you can see this working properly for topic services.

There are two main instances we see this bug currently: Services search & bookmarked services/topics. 

I can see two approaches to fix this:

1. Properly use "HeaderComponent"

2. Initialize local state from Redux in these lists and then bulk write out bookmarks when we navigate away from these screens

The first approach is a substantial change that *may* not work nicely with our tabs and Algolia components (a quick hack locally did not prove fruitful)

The second approach I've proven works locally and seems like the path of least resistance to me.

Please provide thoughts.

### Acceptance Criteria 
- [ ]  

### Steps for QA: 
1.

**Comment by rasmus-storjohann-PG** [comment]
I don't understand how the header component is used to fix this issue. The solution with storing the changes to bookmarks in local state makes sense to me. But perhaps if I understood the header fix it would be better....

**Comment by bensinjin** [comment]
The `listHeaderComponent` prop is meant to accommodate cases where you need to render something above your flatlist. It seems in instances where you have a connected component and you're changing state the only way we've been able to get that state to no reset the scroll state is to use this prop. I'm not sure exactly how it work but it does :P I think I'll try a bit more.

**Comment by bensinjin** [comment]
I was actually able to rebuild the search properly using the `ListHeaderComponent` and it did not fix the problem. Which is confusing.

**Comment by bensinjin** [comment]
This is such a headache, I've tried to trace through the FlatList code to understand why this happens but I'm really not sure. The local state route didn't appear to actually work once fully implemented due to the component (Infinitehits) holding the state constantly un mounting and causing loops writing to Redux and re rendering. Moving the local state up the component tree puts us back at square one. It seems this is related: https://github.com/facebook/react-native/issues/25239 which has had very recent activity. At this point I wonder if we're going to have to try to re write the search with a simple HTTP Get in order to get similar behaviour to our topic services. I'm at a bit of a loss here.

**Comment by rasmus-storjohann-PG** [comment]
Closing this issue, the solution is to change how we use Algolia, see #1030
