### ISSUE TITLE
Routing issues

### ISSUE THREAD

**Issue by bensinjin** [pg-irc/pathways-frontend#102]
@rasmus-storjohann-PG @tnightingale. Please take a minute to peruse this as I'm currently a bit blocked on Issue #44 due some issues outlined here.

I think we’re currently misusing our router and I can't help but feel we may want to rethink our routing solution. Redux-first-router was built primarily with the assumption it was being used in a web based environment.  This is my current understanding of our routing in Pathways and some issues I'm noticing:

- Redux-first-router imposes we map particular routes to actions meaning that when a route is hit a particular action is fired.
- The primary purpose of this action firing is to allow dynamic portions of the url to be substituted with their appropriate values from the action’s payloads if you’re not doing this you generally don’t do any work in the reducer (just return null according to the docs) this is where we run into problems …
- We need to do work here; primarily set the “currentPage” value in the store so our component in charge of rendering the correct page component knows to re render itself (this is how we're currently doing it .. maybe this is the questionable piece?)
- This is our misuse and seems to be OK when you have pages like “questionnaire” and “plan” but when you require a parameterized path ie. “task/:id” we now need the reducer to return an id when the router triggers the action or an updated copy of the store when it’s trigger from other sources ie. through the ui…

So I’ve tried a few different things to get this working and really it all just feels wrong. I can’t help but think we’re taking a bit too much of a web approach to this and should potentially be looking at other options. After a quick poke around https://reactnavigation.org/ seems popular, well documented, and looks to have a section on deep linking. It could be worth looking at.

**Comment by ApolloMuses** [comment]
React-navigation is one of the most popular routing libraries and work very
well with react native. If you needed something even more powerful, there
is always react-native-router-flux. But for most projects, react-navigation
suffices.

**Comment by tnightingale** [comment]
Alternatively, we've had pretty good experience with [react-router](https://reacttraining.com/react-router/native/guides/philosophy) in the past. It has an opinionated view of how routing state is managed that is different to the approach we've been hoping for (spoiler: managed outside of redux) but it has been reliable. Here's an explanation of the state of redux integration: https://reacttraining.com/react-router/native/guides/redux-integration.

**Comment by rasmus-storjohann-PG** [comment]
Closing, this functionality has been completed under a different story
