### ISSUE TITLE
Service detail icons on android are cut off 

### ISSUE THREAD

**Issue by tomy-pg** [pg-irc/pathways-frontend#1025]
On the service detail page some of the icon, e.g phone, website are being cut-off.

![Screenshot_20200227-094531.png](https://images.zenhubusercontent.com/5c6c8cff9d62b128eab447ff/f48e383c-9f2e-4f9e-8791-9c425893e782)

### Acceptance Criteria 
- [ ]

### Steps for QA: 
1.

**Comment by ian-lin-PG** [comment]
As shown by the the screenshot below, the issue has been fixed.
![Screenshot_20200303-155031](https://user-images.githubusercontent.com/52009863/75830916-eea41700-5d66-11ea-99ef-8e0e638d6beb.jpg)
