### ISSUE TITLE
Remove bookmark from topic and search services lists and header picture

### ISSUE THREAD

**Issue by tomy-pg** [pg-irc/pathways-frontend#1026]
In response to the bookmarking bug we are facing in #1016, remove bookmarking from both the topic and search service lists. This will then only enable users to bookmark services from the service detail page. 

After discussing this with @cherrielam, she recommends we remove the header image from the service detail page to make the bookmarking icon more obvious to the user. Please refer to the image below:

![Screenshot_20200227-100032.png](https://images.zenhubusercontent.com/5c6c8cff9d62b128eab447ff/16adbfe5-c1e9-47b9-b15b-7a6d88342171)

### Acceptance Criteria 
- [x]  Bookmarking icon no longer appears in topic and search services lists 
- [ ] Header image no longer appears in service detail page

### Steps for QA: 
1.

**Comment by bensinjin** [comment]
This also affect services on bookmark screen

**Comment by ian-lin-PG** [comment]
Bookmarked services don't have the bookmark button.
![Screenshot_20200306-093900](https://user-images.githubusercontent.com/52009863/76108070-bed75800-5f8e-11ea-8394-d55114e23d58.jpg)
Topic services don't have bookmark button
![Screenshot_20200306-093920](https://user-images.githubusercontent.com/52009863/76108074-c0088500-5f8e-11ea-9106-6089bb944ce2.jpg)
Search service don't have bookmark button
![Screenshot_20200306-093910](https://user-images.githubusercontent.com/52009863/76108076-c139b200-5f8e-11ea-9f8a-59d3dc28a9d3.jpg)
Service detail don't have icon banner.
![Screenshot_20200306-093930](https://user-images.githubusercontent.com/52009863/76108079-c1d24880-5f8e-11ea-813c-5f3f84ed99d8.jpg)
Topic detail don't have banner icon
![Screenshot_20200306-093941](https://user-images.githubusercontent.com/52009863/76108080-c1d24880-5f8e-11ea-85e5-a240c144a581.jpg)
