### ISSUE TITLE
Refactor search to not use Algolia instantsearch

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1030]
InstantSearch from algolia gives us grief with no benefit, there is not enough screen area devoted to the search results to be able to tell that the results change while typing, and the location entry field also doesn't make sense with instant search. We also have #1016 which we have not been able to solve using instant search.

Solution is to use a simpler approach where we hit the Algolia REST API directly rather than using the algolia client side library for this. We can then reintroduce the bookmark on/off functionality to the service listings, effectively reverting the change that was made under #1026.

Issue to re-introduce bookmarking can be found here: #1046 

### Acceptance Criteria 
~~Services can again be bookmarked from service search result list, without resetting the list position as happened under #1026.~~
- [x] Search functions are before without performance hit. (extra re-renders)

### Steps for QA: 
1.

**Comment by ian-lin-PG** [comment]
@rasmus-storjohann-PG @tomy-pg I believe this issue can be closed, but can the acceptance criteria be changed. It may cause confusion in the future.

**Comment by tomy-pg** [comment]
@ian-lin-PG the Acceptance criteria seems a bit off here. I will adjust the acceptance criteria for QA.
