### ISSUE TITLE
"Near my location" is invalid location

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1031]
Enter any string as search term and "My location" as location. Observe that the "Invalid location" error screen appears. Expected is that "My location" is always a valid location.

Version: 1.21.0

**Comment by rasmus-storjohann-PG** [comment]
![image](https://user-images.githubusercontent.com/32307781/75581776-0dc93e80-5a1f-11ea-8d62-b7adce4604b1.png)

**Comment by tomy-pg** [comment]
Staging version 1.34.0: PASS
![Uploading Simulator Screen Shot - iPhone X - 2020-05-25 at 15.25.34.png…]()

**Comment by rasmus-storjohann-PG** [comment]
This issue came back, in staging now on version 1.38.0

**Comment by ian-lin-PG** [comment]
It works on my devices. @tomy-pg try it as well? I will also run it on an android simulator.

**Comment by tomy-pg** [comment]
Staging version 1.40.0 - works for me.
![Uploading Screenshot_20200714-130722_Arrival Advisor.jpg…]()

**Comment by ian-lin-PG** [comment]
From using a few simulators I found that Nexus 5 with android 7 is stuck at loading screen when using `My Location`. Whereas, Pixel 3 with android 10 have no issues what so ever. I am leaning towards that older Android versions might have problem with the GPS. Pending further investigation.

**Comment by rasmus-storjohann-PG** [comment]
Closing this as CNR
