### ISSUE TITLE
Search Tab Opens Empty Search Page

### ISSUE THREAD

**Issue by jparlina** [pg-irc/pathways-frontend#1032]
When a user selects a service record from the Search results, then click on the the search icon from the navigation bar, it should open an empty search page. Currently it shows the last search results. 

### Acceptance Criteria 
- [ ]  When a user selects a service record from the Search results, then click on the the search icon from the navigation bar, it should open an empty search page. 

### Steps for QA: 
1.  Open the search page
2. Enter keyword and location, then click Search 
3. Select a service record from the search results
4. Click the search icon on the navigation bar
- [ ] You should see an empty search page, not the previous search result page

**Comment by rasmus-storjohann-PG** [comment]
@jparlina  I'm not sure about the AC on this story. According to Algolia presentations I have seen (I can dig them up), the search result page should ideally never be empty.

**Comment by jparlina** [comment]
@aron-chen-pg Any thoughts on this user experience?

**Comment by aron-chen-pg** [comment]
From looking at other platforms, I agree with @rasmus-storjohann-PG. Ideally, we don't want search result page to be empty other than when users first access the feature per launch. Showing the last search result makes sense to me. One more conventional pattern though would be to simply remove the bottom navigation bar whenever users click on a service. That way the only way to get back is to click on the back arrow on the top of the header bar.

**Comment by jparlina** [comment]
Thanks @aron-chen-pg and @rasmus-storjohann-PG, I'm closing this issue then.
