### ISSUE TITLE
Removing Org from Service List Item, Styling on Service Detail, and Bookmark issue

### ISSUE THREAD

**Issue by cherrielam** [pg-irc/pathways-frontend#1041]
1. Because Organizations are not clickable (on service list items), let's remove the  "Provided by" line on the service list item since the Org itself is in the title.

![IMG_8046.PNG](https://images.zenhubusercontent.com/5823860ee40e5714b1700133/6b5ffb89-52b4-4b01-be89-319c0f8e42a0)

2. See above Service List Item: The Maple Ridge address runs off to the right. Let's make sure the addresses cut off at the same place that the rest of the text cuts off. If all addresses are currently single line items, then let's just keep it consistent and have the text run off (like "V2X..."). If addresses are wrapped (double line items) then wrap below. 

3. Make the font size on the Service List Item slightly bigger (by 1 pt?) and increase margin/padding between the address and the description (maybe Slack Cherrie on these tweaks)

4. On the Service Detail page, since the Organization is not clickable, remove the teal bold styling. Please style identical to all other fields (eg. Phone, Address...) including same font size, etc.

5. Bookmark on iOS under iPhone X is too high and needs to be lowered. See image below:

![IMG_8047.PNG](https://images.zenhubusercontent.com/5823860ee40e5714b1700133/4dff5846-7416-4c89-87f1-b9608c34e88e)

6. Ideally let's have the horizontal rule (line) styling updated here to grey and all the way across

### Acceptance Criteria 
- [x]  "Provided by [Organization]" line is removed from the Service List Item
- [x] Addresses no longer trail into the right side empty space on the Service List Item
- [x] Increased font size on Service List Item from previous, improved readability
- [x] Spacing between address and description is larger than line spacing of the description itself
- [x] On Service Detail page, Organization is not clickable and text styled in the same way as other fields (address, phone, etc.)
- [x] Bookmark is at the correct height on all iPhones under iPhone X
- [x] Horizontal rule is grey and goes all the way across

### Steps for QA: 
1.

**Comment by rasmus-storjohann-PG** [comment]
@bensinjin keep in mind that we're planning to hook up the org detail page in the future, so when removing the org links, don't rip out a lot of code that needs to go back in in a couple of months.

**Comment by cherrielam** [comment]
@bensinjin 
Font size looks good. Two issues:
- Horizontal rule is not uniform. See below - the one under "Read More" is longer and touches the edges, others do not. Also, make the colour of the line #DEDEDE
![Screenshot_20200312-152915](https://user-images.githubusercontent.com/21990736/76572369-171ec600-6477-11ea-885f-f8d827fe0bbc.png)

- Service List wrapping seems a bit weird. Screenshot from Rasmus' android shows that address appears to wrap earlier than the rest of the text. Seems like "BC" should still fit before the wrap on some of the addresses.
![Screenshot_20200312-153023](https://user-images.githubusercontent.com/21990736/76572413-387fb200-6477-11ea-9b4e-6e2100329ab3.png)

**Comment by bensinjin** [comment]
Ok, horizontal rule issues addressed in most recent commit. I tested on a Nexus 1 (Android) and this is what that service looks like:
<img width="304" alt="Screen Shot 2020-03-13 at 3 38 11 PM" src="https://user-images.githubusercontent.com/3228323/76664192-bd82ce00-6540-11ea-9687-9ae544025d00.png">

Which looks good, I think what we see on Rasmus's phone may fall into the "React Native quirks" category, I've noticed margins, floats, word wraps etc... seem to act inconsistently for RN on some Android devices we have have to live with it.

**Comment by cherrielam** [comment]
QA'ed all the acceptance criteria and it looks good :) closing
