### ISSUE TITLE
Enable and populate organization detail page

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1042]
Currently the detail page component is done and in the app, but it is not used, because we don't have the plumbing in place to pull the organization data from the server. Under #1041 some non-functional links from service detail to org detail were removed. See #842 for all the details. This story is to make sure that the links are put back so that the user can navigate from service detail page to organization detail page, and that the organization detail page has data on it.

### Acceptance Criteria 
- [ ] In the service detail page, clicking the organization name (see mock) opens up the organization detail page
- [ ] The organization detail page is populated with data from our server, hitting the /v1/organizations/{organization_id} endpoint. Follow the pattern for retrieval of service data.  

### Release
This change is out of scope for the feedback release, it should go into the next release after that.

**Comment by bensinjin** [comment]
Some thoughts based on https://app.zeplin.io/project/5bc7bfa42e72260acb03aa86/screen/5d929aa5e4bb44026858ebbf

- An organization can have 0..N locations either we don't include location info or we have to pick one
- Currently for topic services we hit the services_at_location endpoint, we need services for organizations to be in this form so they work/look consistent with services for topics. The organization/<id>/locations and organization/<id>/services endpoints are not currently sufficient. Maybe we can build out services_at_location to work with organizations.

**Comment by rasmus-storjohann-PG** [comment]
Suggestions for solution:
* If an organization has exactly one location associated with it, show that address in the organization detail, otherwise don't show any address. Verify that this will mean most organizations will have an address.
* The `services_at_location` end point is appropriate because there is a many-to-many relationship between services and locations. There is a one-to-many relationship from organizations to services, so the correct REST end point to use is `organization/{id}/services/`.

**Comment by bensinjin** [comment]
Sounds good, Rasmus also stated to work off this branch: https://github.com/pg-irc/pathways-backend/pull/505

**Comment by cherrielam** [comment]
Organization Detail screens have been updated in Zeplin to reflect Arrival Advisor's most recent UI patterns:

[Org Detail - About](https://app.zeplin.io/project/5bc7bfa42e72260acb03aa86/screen/5d929aa5e4bb44026858ebbf/)
[Org Detail - Services](https://app.zeplin.io/project/5bc7bfa42e72260acb03aa86/screen/5d929aa5a78fc061803c87ca/)
