### ISSUE TITLE
Re-introduce bookmarking to topic services and search services lists

### ISSUE THREAD

**Issue by tomy-pg** [pg-irc/pathways-frontend#1046]
Since we have refactored search to using Algolia's rest API in Issue #1030, we can now re-introduce bookmarking.
Bookmarking was previously removed in Issue #1026.

Unbookmarking services / topics will still result in the Flatlist to reset to the top in the bookmarks page. This will be addressed in #1047

### Acceptance Criteria: 
- [ ] Bookmarking in both topic services and search services is re-implemented

### Steps for QA:
1. Navigate to the search page and make a search
2. Bookmark some of the services in the list.
- [ ] Ensure when bookmarking that you are not brought back to the top of the page
3. Navigate to the bookmark page
- [ ] Ensure the bookmarked services are in the bookmarked services tab

**Comment by tomy-pg** [comment]
This pr also addresses issue #1069

**Comment by aron-chen-pg** [comment]
Tested on both Samsung 8 and iPhone x. The described behaviours were all functional.

- [ ] Bookmarking in both topic services and search services are re-implemented
- [ ]  Ensure when bookmarking that you are not brought back to the top of the page
- [ ]  Ensure the bookmarked services are in the bookmarked services tab

A couple of issues to be aware of, not sure if they already exist elsewhere.
1. On Search, clicking into a service and clicking back will bring users back to the top of the page. On Bookmarks, clicking into and back from a service will bring users back to the bookmarked topics view. This problem exists for both iOS and Android. This posts a high usability issue when users attempt to navigate between different services.
Screenshots captured on iPhone X.
![image](https://user-images.githubusercontent.com/54860686/78425073-ed486180-7626-11ea-8b8b-b0f8e8b676bd.png)
![image](https://user-images.githubusercontent.com/54860686/78425166-c63e5f80-7627-11ea-8802-0aa774e794f9.png)

2. When saving/removing a bookmark, the notification appears right on top of the bottom navigation bar. While the notifications are on, users cannot click onto any of the tabs. This issue exists for both Android and iOS. The notification should be visually above the bottom navigation bar. Please refer to [mockup](https://app.zeplin.io/project/5bc7bfa42e72260acb03aa86/screen/5dcb61e36f58b8bf61595e6f/) for notification placement
Screenshot captured on iPhone X
![91534653_1492220687624452_6781309634427748352_n](https://user-images.githubusercontent.com/54860686/78427211-c559fd80-7628-11ea-8d05-c5d9b80469f2.jpg)

**Comment by jparlina** [comment]
Tested onStaging V1.26.0, server V1.3.25 on iPhone 7 Plus:
Acceptance Criteria:
- [x] Bookmarking in both topic services and search services is re-implemented

Steps for QA:
1. Navigate to the search page and make a search
2. Bookmark some of the services in the list.
- [x] Ensure when bookmarking that you are not brought back to the top of the page
3. Navigate to the bookmark page
- [x] Ensure the bookmarked services are in the bookmarked services tab

Note: Issue #2 noted by @aron-chen-pg above doesn't occur on iPhone 7 Plus, the "Bookmark added" notification appears correctly above the navigation bar
![Screen Shot 2020-04-05 at 8.19.04 PM.png](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/8e59fe99-421b-4989-9189-94578af87899)

In addition to the issues @aron-chen-pg mentioned above, also note that the bookmark icon for Topics appear on the left whereas the bookmark icon for Services appear on the right on both the My Bookmarks as well as on topic/service listing. This might create confusion from UX perspective.

![Screen Shot 2020-04-05 at 8.51.08 PM.png](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/af71ec1b-ceba-4657-8cd1-4f455914fd96)

**Comment by cherrielam** [comment]
Thanks @jparlina this is a known issue, in our design backlog. It most likely won't be tackled for this release, but the next one.

https://github.com/PeaceGeeksSociety/pathways-ux-ui/issues/108
