### ISSUE TITLE
Add location search on Topic>Services List

### ISSUE THREAD

**Issue by cherrielam** [pg-irc/pathways-frontend#1049]
We would like to add the location search function to the topic-services page. This is because: As a user, I would like to adjust the service results on a topic in order to search in the location that is of interest to me. This is particularly important for users who want to use AA pre-arrival.

Mock is [here](https://app.zeplin.io/project/5bc7bfa42e72260acb03aa86/dashboard?seid=5e6ab3e4e90d37189ac6645e)

### Acceptance Criteria 
- [ ]  Topic>Services List has location search function as reflected in mocks, and service list updates according to the input location.

### Steps for QA: 
1.

**Comment by bensinjin** [comment]
Closing this as we already have a ticket here: https://github.com/pg-irc/pathways-frontend/issues/1048
