### ISSUE TITLE
Partial Localization - Search Feature

### ISSUE THREAD

**Issue by jparlina** [pg-irc/pathways-frontend#1057]
The strings "near" and "My Location" were not translated once they are selected on the search page (see screenshots below)

<img width="425" alt="Screen Shot 2020-03-16 at 4 29 56 PM" src="https://user-images.githubusercontent.com/48343061/76807976-734d5700-67a3-11ea-91f8-10afdb2fbdda.png">

<img width="367" alt="Screen Shot 2020-03-16 at 4 30 13 PM" src="https://user-images.githubusercontent.com/48343061/76807982-78aaa180-67a3-11ea-89fe-185d8ff1de94.png">

### Acceptance Criteria 
- [ ]  "near" should be localized on the search page
- [ ]  "My Location" should be localized once selected by the user

### Steps for QA: 
1. Select non-English version of the app 
2. Go to Search
3. Enter keywords in the search field and select "My Location" as Location
- [ ] ensure My Location is translated upon clicking My Location
4. Click Search
- [ ] ensure the words the collapsed search input is localized - (**This will have to be tested on a later date when this is localized**)
5. Go to topic services
6. Click My Location
- [ ] ensure My Location is translated upon clicking My Location

**Comment by tomy-pg** [comment]
TODO: Translate new strings for this issue

**Comment by tomy-pg** [comment]
![Screenshot_20200514-155951_Arrival Advisor](https://user-images.githubusercontent.com/47794846/81994332-71b1db00-95fc-11ea-84a9-793aae5420c1.jpg)

**Comment by tomy-pg** [comment]
Above does not show up in development.

**Comment by tomy-pg** [comment]
related to this lingui issue: https://github.com/lingui/js-lingui/issues/388

Lingui works differently in production and development

**Comment by tomy-pg** [comment]
`{searchTermInput} near {searchLocationInput}` is not a string found in the compiled messages catalogue `messages.js` which causes this issue. 
Here is the PR where I add this string with a blank translation.
https://github.com/pg-irc/ui-strings/pull/44 

Next staging release, we will need to run `lingui compile` without the `--strict` flag

**Comment by ian-lin-PG** [comment]
Lingui issue resolved, closing this issue.
