### ISSUE TITLE
Re-introduce load more services button

### ISSUE THREAD

**Issue by tomy-pg** [pg-irc/pathways-frontend#1058]
When the Algolia's rest API can return more than 20 services, show the **Load more services** button. 
When this button is clicked, the next 20 services should show up.

### Acceptance Criteria 
- [ ]  Load more services button is present and loads the next 20 services
- [ ] Flatlist position is retained when the load more services button is clicked

### Steps for QA: 
1.

**Comment by ian-lin-PG** [comment]
Loadmore buttons disappears when navigating back for service detail to search page.

**Comment by tomy-pg** [comment]
Staging version 1.26.0. 
Load more services as back and it is maintained after navigation to different pages of the app.
