### ISSUE TITLE
Language switcher in header

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#106]
Button in app header (visible on all screens):

![screenshot from 2018-06-08 14-03-24](https://user-images.githubusercontent.com/32307781/41180915-b90017ec-6b24-11e8-947a-54c447a446de.png)

List of languages, with scroll behaviour, note how Arabic slides behind the "English" label:

![screenshot from 2018-06-08 14-04-41](https://user-images.githubusercontent.com/32307781/41180961-e7bea238-6b24-11e8-89e3-2132f51e7ca1.png)

Note: The list of languages are defined in the fixtures, it will be a much smaller list, check with Michael.

**Comment by rasmus-storjohann-PG** [comment]
Closed as a dupe of #118.

**Comment by tnightingale** [comment]
I think this should remain open and #100 should be closed as the duplicate.

**Comment by rasmus-storjohann-PG** [comment]
Reopened, thanks github for making PRs look just like issues.

**Comment by tnightingale** [comment]
Putting this (pull req #118) back into "In Progress" to address styling issues.
