### ISSUE TITLE
Chinese (Simplified) Mistranslations: Search Page & My Bookmarks

### ISSUE THREAD

**Issue by jparlina** [pg-irc/pathways-frontend#1060]
As per @ian-lin-PG's [language QA](https://github.com/pg-irc/arrival-advisor-qa/issues/36) on Mar 17, 2020: 

### 1. Remove duplicate character:
![Screen Shot 2020-03-17 at 5 27 11 PM](https://user-images.githubusercontent.com/48343061/76913681-f4285380-6874-11ea-862b-c48b75a3f36c.png)

### 2. Edit translation for "My Bookmarks":
![Screen Shot 2020-03-18 at 3.42.15 PM.png](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/9485a73c-ebe8-45a4-9bbf-ab746569d606)

Uploaded the updated [csv file ](https://docs.google.com/spreadsheets/d/1kztu23tjdbVim2tFkQnHSPZqt8dIMhmt4McEl86oTEY/edit#gid=738692491) to weblate. 

Need to QA once revisions are released to staging.

**Comment by jparlina** [comment]
@ian-lin-PG Please QA the following revisions from Staging V1.25.0, server V1.3.24 based on your feedback from last QA detailed above: 

### 1. Duplicate character removed
![Screen Shot 2020-03-31 at 11.44.19 AM.png](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/74b02300-ea6f-402f-8a95-8ccdc19f223c)

### 2. Edited "My Bookmarks"
![Screen Shot 2020-03-31 at 11.48.35 AM.png](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/90f6cf49-13bb-43c0-b40d-34743aff2b57)

**Comment by ian-lin-PG** [comment]
The fix is correct, closing this issue.
