### ISSUE TITLE
Chinese (Traditional) Mistranslations: Search Page & My Bookmarks

### ISSUE THREAD

**Issue by jparlina** [pg-irc/pathways-frontend#1065]
As per @ian-lin-PG 's [language QA](https://github.com/pg-irc/arrival-advisor-qa/issues/37) on Mar 18, 2020:

### 1. Remove duplicate character:
![Screen Shot 2020-03-18 at 2 49 31 PM](https://user-images.githubusercontent.com/48343061/77010829-cc45f800-6927-11ea-8c0e-3df854cc55c5.png)

### 2. Fix mistranslation for "My Bookmarks":
![Screen Shot 2020-03-18 at 3.47.15 PM.png](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/cde5727c-13dd-4eb3-a866-baec68eaec61)

Uploaded the updated [csv file](https://docs.google.com/spreadsheets/d/1d9JfxHJLrpwz5ykXqNzvJC5mVeyLY4hek0dAbN4b5AQ/edit#gid=1238011844) to weblate.

Need to QA after revisions are released to staging.

**Comment by jparlina** [comment]
@ian-lin-PG Please QA the following revisions from Staging V1.25.0, server V1.3.24 based on your feedback from last QA detailed above:

### 1. Removed duplicate character
![Screen Shot 2020-03-31 at 11.53.43 AM.png](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/5a67a674-505b-4c05-83ea-52529e79225e)

### 2. Revised "My Bookmarks"
![Screen Shot 2020-03-31 at 11.54.28 AM.png](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/29efa1d1-c4bc-42d7-b343-2422af9afbac)

**Comment by ian-lin-PG** [comment]
The fix is correct, closing this issue.
