### ISSUE TITLE
Add COVID card on the home screen

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1067]
Make a card for the home screen with a link to reliable BC government issued information about covid

### Acceptance Criteria 
- [x]  There is a card on the home screen with a button with a link to http://www.bccdc.ca/health-info/diseases-conditions/covid-19 
- [x] Add analytics event to the click on the button.
- [x] Send screenshots of the finished screen to ewan@peacegeeks.org

[Mock on Zeplin is here](https://zpl.io/bWEN84P)

**Comment by niko-pg** [comment]
Hi @cherrielam I followed your advice to scrap the image since I had hard  time fitting it to the content.

**Comment by cherrielam** [comment]
Got a look at this when I was running the simulator, it looks great! @niko-pg can we make the padding at the top and the bottom of the card equal? Right now the padding above the title looks smaller than the padding below the body text.

![IMG_8237](https://user-images.githubusercontent.com/21990736/77599230-54e10d00-6ec1-11ea-8ac5-3b9ec762054d.PNG)

**Comment by cherrielam** [comment]
> Got a look at this when I was running the simulator, it looks great! @niko-pg can we make the padding at the top and the bottom of the card equal? Right now the padding above the title looks smaller than the padding below the body text.
> 
> ![IMG_8237](https://user-images.githubusercontent.com/21990736/77599230-54e10d00-6ec1-11ea-8ac5-3b9ec762054d.PNG)

Just QA'ed in Staging, can we address the above?

And also, can we increase the margin between the COVID-19 card and the card below it (Questionnaire) - 1.5x what it is currently?

I added a comment above re: AC #2, and I will let @jparlina take care of QA-ing the languages and analytics event (or someone else?). Lmk if you want me to send to Ewan once it's final.

**Comment by niko-pg** [comment]
@cherrielam Sorry, I got busy with the onboarding improvements last week. Will push on the styling improvements in a bit.

**Comment by cherrielam** [comment]
Looks good to me, I will send the screenshot to Ewan. @jparlina @tomy-pg what is the process for QA-ing the different languages?

**Comment by tomy-pg** [comment]
@cherrielam for languages we screenshot it in the different languages and send it to translators for language QA.
For analytics we go to google analytics -> ArrivalAdvisorStaging -> Real-time -> Events
and ensure that when the link is pressed the event action is fired. See screenshot.
https://analytics.google.com/analytics/web/#/realtime/rt-event/a30770107w206673584p199569352/
![Screen Shot 2020-04-03 at 2 01 57 PM](https://user-images.githubusercontent.com/47794846/78404774-f0563a00-75b3-11ea-8a70-9a0af7dfc8fc.png)

**Comment by jparlina** [comment]
Completed language QA: 
- [x] [Arabic](https://github.com/pg-irc/arrival-advisor-qa/issues/46)
- [x] [Chinese Simplified](https://github.com/pg-irc/arrival-advisor-qa/issues/47)
- [x] [Chinese Traditional](https://github.com/pg-irc/arrival-advisor-qa/issues/48)
- [x] [French](https://github.com/pg-irc/arrival-advisor-qa/issues/49)
- [x] [Korean](https://github.com/pg-irc/arrival-advisor-qa/issues/50)
- [x] [Punjabi](https://github.com/pg-irc/arrival-advisor-qa/issues/51)
- [x] [Tagalog](https://github.com/pg-irc/arrival-advisor-qa/issues/53)

**Comment by cherrielam** [comment]
Great looks all good to me. @jparlina ready to Close then?
