### ISSUE TITLE
Arabic Mistranslations: My Bookmarks, Search Input, Service Detail

### ISSUE THREAD

**Issue by jparlina** [pg-irc/pathways-frontend#1068]
As per [Arabic QA - Mar 2020](https://github.com/pg-irc/arrival-advisor-qa/issues/34), the 3 translation issues listed below need to be fixed. [Here](https://docs.google.com/spreadsheets/d/1RPEABZfvuatyfxA-GZydfY67Iwo5WBRCEG0f4hudAbk/edit#gid=0)'s the updated csv that was uploaded to weblate. Need to QA revisions once released to staging.

### 1. My Bookmarks
![Screen Shot 2020-03-19 at 1.40.38 PM.png](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/1b3ec187-1d06-464a-a5b7-e7106506d1f4)

### 2. Search Input 
![Screen Shot 2020-03-19 at 1.50.48 PM.png](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/8023cefa-cef8-4dea-8af6-d10ec2ca03c6)

### 3. Service Detail - "Provided by"
![Screen Shot 2020-03-19 at 2.36.59 PM.png](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/270cb7b7-243d-446c-8cad-662e72c23ceb)

**Comment by tomy-pg** [comment]
Staging version 1.27.0:
Mistranslations have been addressed.
