### ISSUE TITLE
Empty bookmark image

### ISSUE THREAD

**Issue by cherrielam** [pg-irc/pathways-frontend#1069]
The empty bookmark image in the app is not correct, it should be replaced with this one:

https://zpl.io/2j0vAxm - image is downloadable from Zeplin

### Acceptance Criteria 
- [x]  Empty bookmark image is the one reflected in the Zeplin

### Steps for QA: 
1.

**Comment by tomy-pg** [comment]
This has been addressed in issue #1046

**Comment by cherrielam** [comment]
Closing, looks good
