### ISSUE TITLE
French Service Detail Page - insert a non-breaking space before the colon

### ISSUE THREAD

**Issue by jparlina** [pg-irc/pathways-frontend#1073]
As per [French QA - Mar 2020](https://github.com/pg-irc/arrival-advisor-qa/issues/33), need to insert a non-breaking space before colon for all French labels (see red arrows on screenshots) on Service Detail Page. Colon was not part of the translated strings on weblate.

![Screen Shot 2020-03-20 at 1.38.21 PM.png](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/ca7f7236-bfa7-470e-94b8-37ae7a155267)

![Screen Shot 2020-03-20 at 1.46.43 PM.png](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/49eec819-aa0f-42fe-9b8a-91704334ba91)

![Screen Shot 2020-03-20 at 1.46.31 PM.png](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/0a78df4a-0c9e-4fd7-9c8d-7ec0eeb57d77)

The colon missing from being inside the `t` macro or `Trans` tag is the cause of this issue. There needs to be a full sweep of all strings to ensure their punctuations are within these tags and not outside of it. 

Acceptance Criteria:
- [ ] All app strings include punctuation inside `t` macro or `Trans` tag
- [ ] Also QA #1091 which was fixed as part of this PR

**Comment by tomy-pg** [comment]
This issue arises when 
1 - We do not place `:` inside our `<Trans>` tags or `t` macro.

When I extract strings form our app, any punctuation not included in the tag or macro are lost.
This is important to include because some languages use `:` different than others.

**Comment by jparlina** [comment]
Tested on Staging V1.26.0, server. V1.3.25 on iPhone 7s

![Screen Shot 2020-04-03 at 6.38.44 PM.png](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/59413e2d-23c6-472e-ac45-94adb807e747)
