### ISSUE TITLE
Update "Information is only in English" dialog to indicate that "Search is in beta"

### ISSUE THREAD

**Issue by cherrielam** [pg-irc/pathways-frontend#1076]
On the Search page, we would like to update the dialog that informs users that the services information is only in English to also say that "Search is in beta". 

Mock is now here: https://zpl.io/bAyJZ88 

The copy that needs to be translated is: "Search is currently in beta and only available in English." and "Give Feedback" - @jparlina and @tomy-pg can you add to weblate for translations?

We have removed the "Don't show again" button on this dialog to reduce the clutter of buttons, and replaced it with the "Give Feedback" button. This means that the _Search in beta_ dialog is not dismissable, but it does scroll with the rest of the cards, so should hopefully not be too intrusive.

Clicking "Give Feedback" should open an email titled "Arrival Advisor - Feedback on Search" in the subject line, to: info@arrivaladvisor.ca, and if possible, in the body: Version # - populate with the app version that the user has.

**Note:** On _topic-services_, the dialog should still be the previous one that says "Information about services is currently only available in English.... Don't show again". So the dialogs on _topic-services_ and _Search_ will be different.

Also the padding around the text in the dialog is different from the Services cards. Please make the padding the same.

### Acceptance Criteria 
- [ ]  On _Search_, the dialog should now say "Search is currently in beta and only available in English. For support in other languages, please call BC211" and button "Give Feedback"
- [ ] The dialog is localized in all languages
- [ ] Clicking "Give Feedback" opens the user's email client with subject line: "Arrival Advisor - Feedback on Search" mailto: info@arrivaladvisor.ca, and if possible Version # of the user's app in the email body.
- [ ] The _Search_ dialog is different from the dialog on _topic-services_. _Topic-services_' dialog should still say "Information about services is currently only available in English... Don't show again"
- [ ] _Topic-services_ dialog is dismissable, _Search_ dialog is not. Both scroll with the services.
- [ ] Padding around the text in the dialog is the same as the padding around the text in the Services cards.

### Steps for QA: 
1.

**Comment by tomy-pg** [comment]
The new copy has been added to Weblate.

**Comment by tomy-pg** [comment]
QA:
Get Feedback is not translated in app because of the difference between capitalization in the source string and the app string. This has been fixed in Weblate. See here: https://github.com/pg-irc/ui-strings/commit/ac48f7684bf6e28809fed588d40f4389fbfcbe7d

**Comment by jparlina** [comment]
Tested on Staging V1.29.0 Server V1.3.289 on iPhone 7 Plus:

**Acceptance Criteria:**

- [x] On Search, the dialog should now say "Search is currently in beta and only available in English. For support in other languages, please call BC211" and button "Give Feedback"

- [x] The dialog is localized in all languages - QA completed:
- [Arabic](https://github.com/pg-irc/arrival-advisor-qa/issues/65)
- [Chinese Simplified](https://github.com/pg-irc/arrival-advisor-qa/issues/67)
- [Chinese Traditional](https://github.com/pg-irc/arrival-advisor-qa/issues/68)
- [French](https://github.com/pg-irc/arrival-advisor-qa/issues/69)
- [Korean](https://github.com/pg-irc/arrival-advisor-qa/issues/70)
- [Punjabi](https://github.com/pg-irc/arrival-advisor-qa/issues/71)
- [Tagalog](https://github.com/pg-irc/arrival-advisor-qa/issues/52)

- [x] Clicking "Give Feedback" opens the user's email client with subject line: "Arrival Advisor - Feedback on Search" mailto: info@arrivaladvisor.ca, and if possible Version # of the user's app in the email body.
- [x] The Search dialog is different from the dialog on topic-services. Topic-services' dialog should still say "Information about services is currently only available in English... Don't show again"
- [x] Topic-services dialog is dismissable, Search dialog is not. Both scroll with the services.

**Comment by jparlina** [comment]
@cherrielam Please confirm the last AC and close this issue if it's satisfactory: 

- [ ] Padding around the text in the dialog is the same as the padding around the text in the Services cards.

![Screen Shot 2020-04-21 at 5.18.09 PM.png](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/c395d832-2635-429d-bed9-22ad7a2ade51)

![Screen Shot 2020-04-21 at 5.17.57 PM.png](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/58f96d72-2789-4df5-9d28-8ab8230dfe58)

**Comment by cherrielam** [comment]
yes looks good, thank you!
