### ISSUE TITLE
Search does not run if keyword is empty - needs an alert

### ISSUE THREAD

**Issue by cherrielam** [pg-irc/pathways-frontend#1078]
Currently, the search does not run when the keyword is empty. However, the user is still able to click search and the search bar collapses. This appears to be buggy to the users, because a user gets the impression that they can run the search, except nothing actually happens. 

![ezgif.com-resize.gif](https://images.zenhubusercontent.com/5823860ee40e5714b1700133/d918236e-7221-42c6-a121-ea4c05ea2e9f)

**Recommendation:**
- If there is no keyword and the search will not run, when the user clicks the "Search" button, the search bars should **not** collapse into the single search bar. This gives users the false impression that their search will run.
- When a user clicks search and the keyword is empty, user should be alerted that they need to fill in a keyword. For the time being, can we just use a system alert that says "Please enter a keyword to search"? - System alert like below:
![url-schemes-8.png](https://images.zenhubusercontent.com/5823860ee40e5714b1700133/4f79c118-1309-445d-9a3f-dd5c3bcf4f27)

^ @jparlina this string "Please enter a keyword to search" will need to be translated if this is implemented. @rasmus-storjohann-PG or whoever is developing this will need to confirm if this copy is adequate for an alert, or if other copy is needed.

- Ideally, the search button should appear inactive (deactivated/greyed out) until the search can be run. Do we currently have a deactivated button state built? I believe this was mocked up but not sure if it is implemented anywhere.

### Acceptance Criteria 
- [ ]  Search bars don't collapse when the user clicks "Search" button and then keyword search is empty
- [ ]  Clicking "Search" button when the keyword search is empty gives the user a system alert that they need to enter a keyword.
- [ ]  Optional: inactive state for search button when the keyword search is empty

### Steps for QA: 
1.

**Comment by bensinjin** [comment]
I've talked to Cherrie about this. Due to simplicity we've decided to make these buttons disabled (non clickable) and reduce opacity when we have no text in the field. The popup goes against the idea that the button is disabled so we're not moving forward with it.

**Comment by tomy-pg** [comment]
Staging version 1.27.0:
Pass
