### ISSUE TITLE
Search bar text "near my location" capitalization inconsistency

### ISSUE THREAD

**Issue by cherrielam** [pg-irc/pathways-frontend#1079]
On the new _topic-services_ search, "My Location" is all in caps, whereas in _Search_ this is "My Location" in the double search bars and "my location" in the single search bar. Can we make it all "My Location" (both words capitalized) across all instances?

### Acceptance Criteria 
- [x]  "My Location" is capitalized across all instances.

### Steps for QA: 
1.

**Comment by ian-lin-PG** [comment]
'My Location' is consistent with all three location outlined in the original issue.
