### ISSUE TITLE
Add click state for external links, & link styling across app

### ISSUE THREAD

**Issue by cherrielam** [pg-irc/pathways-frontend#1080]
Right now for links in Topic Detail, About Arrival Advisor, and Disclaimer, that open into an external page, there is no click state. This means users will not be informed whether they've clicked on to the link or not. This can cause some usability issues especially when the internet is slow or when the app is experiencing performance issues.
As a user, he/she would want to be informed on the status of the app, this includes showing a click state of a text link.

Also, the styling of external links is inconsistent between Topic Detail and the following pages: About Arrival Advisor, Disclaimer. Can we make these consistent — teal, same font weight?

Recommendation:
Since parts of Arrival Advisor already indicate a click state (eg. on Service Detail), we could just replicate the same transition to all the intext links. For instance, in the staging app, clicking on different links on service detail will reduce its opacity (example [here](https://drive.google.com/open?id=1TsLRK_TeALRaEe9vowKNs1u0ZL0aUpqQ)). 

@aron-chen-pg made a quick prototype below for demonstration of click state should look like: 
![Intext-link-clickstate](https://user-images.githubusercontent.com/54860686/77418955-de3ef500-6d84-11ea-95b3-128040641f39.gif)

For consideration: @rasmus-storjohann-PG, @bensinjin & others please weigh in —  Should (and could) we add a system alert before the user goes into the external page? In other apps, sometimes you get a confirmation link to "Open link in browser?" with options like "Don't show me again/Always open the link without asking". I am suggesting this because we know from testing that users get confused when they open an external page and are often unclear how to get back to the app.

### Acceptance Criteria 
- [ ]  Click state added on in-text links (within Topic Detail). Same click state already exists on links in Service Detail.
- [ ]  Decision made as to whether a system alert to "Open link in browser" is added. If so, this system alert should pop up when the user clicks an external link that is in browser. If possible, add a way for users to dismiss future asks.
- [ ] Styling of links in Topic Detail and About Arrival Advisor, Disclaimer is consistent. All links in teal and same font weight.

### Steps for QA: 
1.

**Comment by aron-chen-pg** [comment]
Regarding opening a disclaimer dialogue, I made another prototype to kind of replicate how that might look like:
![Intext-link-interaction v2](https://user-images.githubusercontent.com/54860686/77575448-c6549780-6e90-11ea-9b60-a47b6f156f80.gif)

In addition, I think it's also worth time considering opening links within the app since we do a lot of links. This way users don't need to always go back and forth between Arrival Advisor and the browser app of their devices. Here is an initial concept:
![Intext-link-interaction v3](https://user-images.githubusercontent.com/54860686/77576082-c903bc80-6e91-11ea-8608-e61a4d59849e.gif)

**Comment by cherrielam** [comment]
Thanks @aron-chen-pg!! I think for the time being, my sense is the thin thread version of this kind of thing would be a system-generated alert. The styled alert or even better, in-app links would be great for the future. 

Thoughts from others?

**Comment by ian-lin-PG** [comment]
@cherrielam @aron-chen-pg I can definitely add in the system level alert, here is a screenshot sample:
![Screenshot_20200511-131826](https://user-images.githubusercontent.com/52009863/81607825-2abcaf00-938a-11ea-8119-fbb0b1c14ec4.jpg)

**Comment by aron-chen-pg** [comment]
Is there a way to incorporate a "do not show me again" option? Otherwise, the repetitive alerts would be quite annoying every time a user tries to click a link.

**Comment by cherrielam** [comment]
@ian-lin-PG Can we revise the copy to make it more plain language:

#### Opening external link
This link will open in your device's browser.

Don't show again
OK
Cancel

**Comment by cherrielam** [comment]
Also the link styling on iOS is incomplete — can we make the font weight the same as the links in Topic Detail (currently in About/Disclaimer) they are bolded. They should be regular font weight.

Can we also add a space between the link and the link icon?

![IMG_8754](https://user-images.githubusercontent.com/21990736/83689535-09736b00-a5a4-11ea-9501-6667a8e7a2bd.PNG)
![Screenshot_20200603-140904](https://user-images.githubusercontent.com/21990736/83689540-0bd5c500-a5a4-11ea-9106-583e26adfdf9.jpg)

**Comment by ian-lin-PG** [comment]
Here is the updated links in the new [PR](https://github.com/pg-irc/pathways-frontend/pull/1187). Here are the screenshots:
![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-06-03 at 15 05 38](https://user-images.githubusercontent.com/52009863/83694428-e13c3a00-a5ac-11ea-9837-77c481afd6bc.png)
![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-06-03 at 15 05 45](https://user-images.githubusercontent.com/52009863/83694436-e305fd80-a5ac-11ea-8454-3e0ccb269377.png)
![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-06-03 at 15 05 58](https://user-images.githubusercontent.com/52009863/83694439-e39e9400-a5ac-11ea-9246-ceb004dbc40f.png)

**Comment by tomy-pg** [comment]
Staging 1.38.0 - PASS
