### ISSUE TITLE
[Due Mar 27] Research In-App Feedback Survey SDKs that work with Expo/our app

### ISSUE THREAD

**Issue by cherrielam** [pg-irc/pathways-frontend#1082]
We would like to purchase In-App Feedback Survey SDK/Software with our IRCC research funding. But, the SDK needs to be one that works with the app.

Task: someone needs to research which in-app feedback survey SDKs work with Expo/our app. Here are some SDKs I found:
https://survicate.com/
https://usabilla.com/products/apps/
https://www.surveymonkey.com/mp/mobile-sdk/
https://instabug.com/

If others can do some additional research and offer a sense of which one is best from a tech viability and security perspective, that would be super helpful.

### Acceptance Criteria 
- [x] Decision made as to which (if any) In-App Feedback SDK to purchase. Decision needs to be made by **Mar 27**.

### Steps for QA: 
1.

**Comment by cherrielam** [comment]
Assigning @rasmus-storjohann-PG to figure out who can hop on this. Unfortunately I'm lacking the tech visibility to know what will work. Let me know how I can assist!

**Comment by rasmus-storjohann-PG** [comment]
Looks like Survicate requires us to eject from Expo, see https://github.com/Survicate/react-native-survicate

**Comment by rasmus-storjohann-PG** [comment]
Usabilla pricing: Starting at EUR 10,000 per year ... oh.

**Comment by rasmus-storjohann-PG** [comment]
Survey monkey minimum cost is $27 CAD / user / month billed annually...

**Comment by rasmus-storjohann-PG** [comment]
So far it looks like all of these tools require us to eject from expo, so they will be hard to use.

**Comment by cherrielam** [comment]
Thanks @rasmus-storjohann-PG, looks like we won't get down this route. Looking at other options eg. Airtable for logging feedback responses should we build our own in-app feedback mechanism

**Comment by cherrielam** [comment]
I'm closing this issue as we've decided not to purchase an SDK. Thanks!!
