### ISSUE TITLE
Make "My Location" on services search work as it does on topic services search

### ISSUE THREAD

**Issue by bensinjin** [pg-irc/pathways-frontend#1084]
As per @cherrielam's request: "My Location" on services search should be hidden when the location field value is "My Location", as it is for topic services search. Currently on the services search screen, you can press "My Location", the button dissapears, then you can delete a letter and the button stays hidden, also, you can type: My Location and the button stays visible.

### Acceptance Criteria 
- [  ] "My Location" works as it does on topic services search  

### Steps for QA: 
1.

**Comment by tomy-pg** [comment]
Staging version 1.34.0: PASS
![Simulator Screen Shot - iPhone X - 2020-05-25 at 15 26 27](https://user-images.githubusercontent.com/47794846/82846105-1ef9de00-9e9c-11ea-925d-b55c752d4b5e.png)
