### ISSUE TITLE
By June 1: New requirements for Apple App Store in effect in a month

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1085]
See email received March 27:

The deadline for adhering to the requirements below has been extended to *June 30, 2020*.

* Apps for iPhone or iPad must be built with the iOS 13 SDK or later and use an Xcode storyboard to provide the app’s launch screen.
* iPhone apps must support all iPhone screens and all iPad apps must support all iPad screens.
* Apps for Apple Watch must be built with the watchOS 6 SDK or later.
* Apps that authenticate or set up user accounts must support Sign in with Apple if required by guideline 4.8 of the App Store Review Guidelines.
* Apps in the Kids category must be in full compliance with guideline 1.3 and guideline 5.1.4. of the App Store Review Guidelines.
 * Apps using HTML 5 must be in full compliance with guideline 4.7 sections 4, 5, and 6 of the App Store Review Guidelines.

Thank you for your continuing efforts to serve your users during this time. If you have any questions, contact us.

**Comment by tomy-pg** [comment]
I have been doing some reading on this. 
I believe the first to points are ones we would be concerned about:

> Apps for iPhone or iPad must be built with the iOS 13 SDK or later and use an Xcode storyboard to provide the app’s launch screen.
iPhone apps must support all iPhone screens and all iPad apps must support all iPad screens.

Expo's managed workflow takes care of this as stated by an Expo team member. 
https://forums.expo.io/t/does-react-native-on-expo-meet-the-apples-recent-launch-screen-requirement/35020
