### ISSUE TITLE
Side Menu Overhaul

### ISSUE THREAD

**Issue by aron-chen-pg** [pg-irc/pathways-frontend#1090]
### Description of design change:
The UI layout in the hamburger menu is greatly varied from device to device. The teal block on top that is supposed to serve as header has was not used at all. We should re-unify the UI and ensure all elements are utilized and functional. The side menu overhaul is important from the aspect to maintain UI consistency across all devices. A [deck](https://drive.google.com/open?id=1-_sVZIyVbgPoo265ySHs53JJOFYuq3VG) was made to demonstrate the changes and also explains the rationale behind the new proposed design.

### Difficulty, impact:
Depending on if there is the need to customize in order to get both iOS and Android systems aligned, the difficulty can vary. The current side menu does not affect users from using Arrival Advisor, but an accumulation of these UI inconsistency issues will result in poor user experience which may turn users off from using the app. 

### Visual reference:
The image below was captured from the current staging app. The first screenshot is from an iPhoneX and the second is from an android phone (Samsung 8 ).
![Android vs iOS.png](https://images.zenhubusercontent.com/5d6ea767bc3e240001df648b/2fa91e4a-f742-4119-8ac5-20f02aaae6e2)

Below is the proposed design for both Android and iOS.
![Proposed design - android vs iOS](https://user-images.githubusercontent.com/54860686/78078972-09ff4380-7360-11ea-8d53-5b6e747b97d5.png)

### Acceptance Criteria 
- [ ]  Header space (in teal) extends all the way to the top edge of the screen cross-device (both Android and iOS) with the Arrival Advisor logo and title placed within.
- [ ] ~~Overlay opacity adjusted to 90% than the previous 60%.~~
- [ ] Each menu item is equally spaced out regardless of the existence of an icon or not (refer to Zeplin [mockups](https://app.zeplin.io/project/5bc7bfa42e72260acb03aa86/dashboard?seid=5e8406523232ce6dc56aeee6)).
- [ ] Beige background at the bottom is removed with the replacement of a grey divider to section off the two segments.

### Steps for QA: 
Make sure this is tested on an Android and iOS device
1. Open the side menu and ensure the AC are met.

**Comment by tomy-pg** [comment]
As discussed with Aron, increase the overlay to 90% is buggy with native-base and has been moved to a separate issue.

**Comment by aron-chen-pg** [comment]
Tested on Samsung 8, version 1.32.0
2 items to address:
1) Center-align the icons
2) reduce spacing between the two sections

Here is a spec sample as a reference
![Side menu spec sample](https://user-images.githubusercontent.com/54860686/81969037-2e427700-95d2-11ea-8b31-2ef99744b00d.png)
