### ISSUE TITLE
Re-order Bullet Points on Search Error Message - No Results Found

### ISSUE THREAD

**Issue by jparlina** [pg-irc/pathways-frontend#1091]
As discussed with team on #pathways-dev slack channel on Mar 30, 2020, switch the order of the first and the third bullet points (see screenshot below) of the Error Message "No results found" so it should show up in the following order:
- Ensure your search is in English
- Double check for spelling
- Search for a different keyword 

![Screen Shot 2020-03-31 at 3.16.24 PM.png](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/b0bab233-1293-4cd0-9e2b-8ce7e3abe40d)

### Acceptance Criteria 
- [ ]  the bullet points under Search Error Message "No results found" should show up in the following order:
- Ensure your search is in English
- Double check for spelling
- Search for a different keyword 

### Steps for QA: 
1. Go to Search page
2. Enter some gibberish to search
3. Check the bullet points under the Error Message "No results found. Try:"; they should be in the order as detailed above.

**Comment by rasmus-storjohann-PG** [comment]
This was fixed as part of issue #1073

**Comment by jparlina** [comment]
Tested on Staging V1.26.0, server V1.3.25 on iPhone 7s
Acceptance Criteria
- [x] the bullet points under Search Error Message "No results found" should show up in the following order:
- Ensure your search is in English
- Double check for spelling
- Search for a different keyword
<img width="440" alt="Screen Shot 2020-04-03 at 6 45 09 PM" src="https://user-images.githubusercontent.com/48343061/78416104-425e8600-75db-11ea-82e6-b7d546c1843c.png">
