### ISSUE TITLE
Reduce left padding - FIND A SERVICE on Search Page

### ISSUE THREAD

**Issue by jparlina** [pg-irc/pathways-frontend#1092]
Too much padding on the left of "FIND A SERVICE" title on the Search page, especially for the non-English version on Staging V1.25.0.  See the English and Korean examples on the screenshots below. 

![Screen Shot 2020-03-31 at 4.55.52 PM.png](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/0e62f8fa-cecd-44e6-b1af-079d75de07c3)

![Screen Shot 2020-03-31 at 4.58.20 PM.png](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/9b2911c3-ba60-4ba4-87ec-ed28b0ab474b)

### Acceptance Criteria 
- [ ]  

### Steps for QA: 
1.

**Comment by tomy-pg** [comment]
Staging version 1.32.0 - passes
