### ISSUE TITLE
Missing Last Verified Date on Service Details

### ISSUE THREAD

**Issue by jparlina** [pg-irc/pathways-frontend#1093]
"Last Verified" date does not show up on any of the Service Detail page on Staging V1.25.0 Server V1.13.24 
![Screen Shot 2020-03-31 at 6.23.31 PM.png](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/3a652daa-1954-4def-9e81-a975d0cf1dae)

### Acceptance Criteria 
- [x]  Last Verified date shows up at the bottom of Service Detail

### Steps for QA: 
1.  Click on a topic
2. Click "Find related services near me"
3. Select a service record to open the service detail
4. Scroll to the bottom of the service detail
5. Check if the Last Verified date shows up

**Comment by niko-pg** [comment]
@tomy-pg Just want to clarify, is this an issue of missing data or do I need to add the `verificationDate` attribute myself from the backend? I've traced the service request and doesn't seem like the API response includes the `verificationDate`

**Comment by tomy-pg** [comment]
the `DateLastVerified` is available data in the `bc211` data set so I think you will need to ensure its being sent along with the rest of the data set attributes we want. Let me know if you need access to the `bc211` data. 
![Screen Shot 2020-04-07 at 10 14 54 AM](https://user-images.githubusercontent.com/47794846/78701141-5b0cbb80-78bb-11ea-962c-6f138c4b1c90.png)

**Comment by niko-pg** [comment]
@tomy-pg  sure. is this data different from the one found in `bc211/data` folder?

**Comment by rasmus-storjohann-PG** [comment]
OK, so fixing this issue actually requires changes all the way from the DB and the data importer to the REST API. It's complicated by the fact that there is a large server side refactoring PR sitting waiting to be merged. Pretty much nothing else has been changing on the server side for a while. Still, we need to have a conversation about how these two changes should be handled.

In terms of how to make the fix, the data verified field is sitting on the `ResourceInfo` node under the `SiteService` node that gets imported into the Service table. The server side code is heavily unit tested, so I would start out with `ServiceParserTests` and add a new `test_can_parse_date_last_verified()`.

**Comment by niko-pg** [comment]
@rasmus-storjohann-PG I spent the last couple days getting familiarized with the backend code plus getting ramped up with Django. I don't see this change making a lot of dent. Just wondering if I can proceed according to the current system and not worrying about your changes.

**Comment by jparlina** [comment]
Tested on Staging V1.31.0, server V1.3.30 on iOS:
- [x]  Last Verified date shows up at the bottom of Service Detail

<img width="442" alt="Screen Shot 2020-05-01 at 11 44 04 AM" src="https://user-images.githubusercontent.com/48343061/80832257-2978ce80-8ba1-11ea-94f0-112144a4a7bc.png">
