### ISSUE TITLE
Android header adding extra margin

### ISSUE THREAD

**Issue by tomy-pg** [pg-irc/pathways-frontend#1096]
As per Expo's latest app update on March 31st, we have been seeing extra margin between our Android's statusbar and our app's headers. 

### Acceptance Criteria 
- [x]  There should be no extra margin between the statusbar and our header.

### Steps for QA: 
The behaviour of the app is different depending on whether it runs in expo or as a real app. 
- [x] It needs to be tested on expo as well as in the staging app on both iOS and Android.
- [x] There has also been some issues with the footer scrolling below the lower edge of the screen, keep an eye out for that.

**Comment by tomy-pg** [comment]
This looks different when running the app locally versus the app from the Play store.

**Comment by ian-lin-PG** [comment]
Expo and staging app has the same expected behavior of header not encroaching on the status bar. I haven't noticed any problem scrolling and footer.
