### ISSUE TITLE
Article with related tasks and articles

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#110]
![screenshot from 2018-06-08 14-22-12](https://user-images.githubusercontent.com/32307781/41181636-5d4645ea-6b27-11e8-9b83-8288c28b7308.png)

Use triangle/circle graphic for now.

Out of scope for this story: 
* Need help button, set language button
* Heart button
* Share button
* "This article is relevant for..."
* Recommendation star on tasks

**Comment by robinpuga** [comment]
Link to your initial set of Articles from the Task details page, Learn More section...see https://projects.invisionapp.com/d/main/default/#/console/14398949/299441951/preview 

Also, when you are creating the look of the Learn More related article card please use the horizontal layout (with image beside text) as shown here: https://projects.invisionapp.com/d/main/default/#/console/14398949/300196080/preview#project_console and here https://projects.invisionapp.com/d/main/default/#/console/14398949/300196079/preview#project_console
