### ISSUE TITLE
No Services under some topics although csv has many services

### ISSUE THREAD

**Issue by jparlina** [pg-irc/pathways-frontend#1104]
Tested on Staging V1.26.0, server V1.3.25 on iPhone 7 Plus in Burnaby:

Clicked "Find related services near me" under the topic "Help for young people", and the result was "No services to show". This is inconsistent with the services that are on the [csv based on taxonomy ](https://docs.google.com/spreadsheets/d/1CSNCvpNwqX8VnxGESbcKOo_nlhcINZHXhrmCPyyvBXQ/edit#gid=13026324).

Also "No results to show" for the following topics:
- Community and recreation centres
- Services for refugees and refugee claimants

Tested topic "Register for English classes" -  only 6 services show up on Staging vs 30 services (max) on Production V1.7.0

### Acceptance Criteria 
- [ ]  service results are consistent with [csv based on taxonomy ](https://docs.google.com/spreadsheets/d/1CSNCvpNwqX8VnxGESbcKOo_nlhcINZHXhrmCPyyvBXQ/edit#gid=13026324).

### Steps for QA: 
1.  Click on topic "Help for young people"
2. Click "Find related services near me" 
3. Compare results with services listed on [csv based on taxonomy ](https://docs.google.com/spreadsheets/d/1CSNCvpNwqX8VnxGESbcKOo_nlhcINZHXhrmCPyyvBXQ/edit#gid=13026324).

**Comment by tomy-pg** [comment]
Staging version 1.27.0:

**Help for young people:**
![Screenshot_20200414-132315_Arrival Advisor](https://user-images.githubusercontent.com/47794846/79271183-3d5bcb00-7e54-11ea-846f-aab42cc824de.jpg)

50+ services

Top ten services: All but one included in the csv based taxonomy. Foundry Ridge which was number 5 on my list was not in the list. This could be  a new service from the new BC211 dataset.

**Community and recreation centres:**

![Screenshot_20200414-132253_Arrival Advisor](https://user-images.githubusercontent.com/47794846/79271334-7dbb4900-7e54-11ea-951f-dbf019de0720.jpg)

27 services
Top ten services: Can all be found in the csv taxonomy.

**Services for refugees and refugee claimants:**

![Screenshot_20200414-132758_Arrival Advisor](https://user-images.githubusercontent.com/47794846/79271398-97f52700-7e54-11ea-93ec-252fd900262d.jpg)

50+ services
Top ten services: All found in the csv taxonomy.
