### ISSUE TITLE
Navigating from Service Detail to Service List/My Bookmarks should not bring users back to top of page

### ISSUE THREAD

**Issue by jparlina** [pg-irc/pathways-frontend#1106]
As noted by @aron-chen-pg when testing bookmarks on issue #1046:
When a user selects a service record to get the service details from service listing under a topic or My Bookmarks, and then back to the service listing under a topic/My Bookmarks, the user should be brought back to the position of the service that they just clicked on. Users should not be brought back to the top of the page. This problem exists for both iOS and Android. This posts a high usability issue when users attempt to navigate between different services. 

### Acceptance Criteria 
- [x]  Clicking back from Service Details to topic services should bring users back to that service on the flatlist.
- [x]  Clicking back from Service Details to My Bookmarks should bring users back to that service on the flatlist.

### Steps for QA: 
1. Select a service service listing under a topic/My Bookmarks
2. Click the back. button from the Service Detail page
- [ ]  You should be directed to the position of the service that you just selected on the service listing under a topic/My Bookmarks.

**Comment by rasmus-storjohann-PG** [comment]
Solved as part of #1120

**Comment by jparlina** [comment]
This issue reoccurred on Staging V1.33.0, Server 1.3.30

**Comment by tomy-pg** [comment]
This issue is linked to https://github.com/pg-irc/pathways-frontend/issues/1047 :
In summary, I think we will have to use a different library for tab navigation as it is affecting how the flatlist works.

**Comment by tomy-pg** [comment]
I conducted a binary search of this regression and it seems to have occurred when we replaced the `flatlist` in `src/components/search/search_results_component.tsx` with an `AnimatedFlatList`. @niko-pg are you able to look into this?

**Comment by niko-pg** [comment]
@tomy-pg sorry just to verify the issue here. So the bug is that the scroll positions resets to the top when a service is clicked on right?

**Comment by tomy-pg** [comment]
@niko-pg that's right. This is happening in the services in the search list, topic services list and bookmarks list.

**Comment by rasmus-storjohann-PG** [comment]
QA: Places in the UX where we navigate from a detail page to a list page by clicking the back button:
- [ ] Home page -> Topic detail -> Back to home page: Does not remember the position within the home page
- [ ] Bookmark page -> Topics pane -> Topic detail -> Back to bookmark page: Does not remember list position
- [x] Bookmark page -> Services pane -> Service detail -> Back to bookmark page: It remembers the list position
- [ ] Home page -> Learn section (e.g. Education) -> Topic detail -> Back to Learn section: It does not remember
- [x] Topic detail -> Related services -> Service detail -> Back to related services: It remembers
- [x] Service search result -> Service detail -> Back to service search result: It remembers

**Comment by ian-lin-PG** [comment]
Position maintains from services going back toward topic-services list, bookmark services list, search result list.

Topic detail going back to topic bookmark does not save. There is no position tracking on the learn page or home page as of yet.

**Comment by ian-lin-PG** [comment]
@rasmus-storjohann-PG should another issue be opened to track the home page and learn page?

**Comment by tomy-pg** [comment]
The outstanding issues can be found in this new issue:
https://github.com/pg-irc/pathways-frontend/issues/1190
