### ISSUE TITLE
Tweak app icon

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1112]
This is from the google app store:

<img width="876" alt="image" src="https://user-images.githubusercontent.com/32307781/78835636-5fad9e80-79a5-11ea-85a5-831a48b7d69d.png">

We need to update the icon to have a non-transparent background, @cherrielam to decide on the tweak. I suggest we take the grey of the circle and extend it to the edge of the icon, but there may be better solutions.

**Comment by cherrielam** [comment]
https://drive.google.com/open?id=1qVY0CqXn-IK8zOM_dcPbsCLcuYr3xiFU Would the current Apple App store one suffice?

**Comment by tomy-pg** [comment]
Done as part of Production release 1.30.0
