### ISSUE TITLE
Notifications - Simple example of notification when adding a task

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#113]
AC: Implement a scalable pattern that can be used for notifications throughout the UX of the app.

Design:
* There should be a notification store and corresponding reducer
* The reducer should update the store to create state that then drive notifications getting rendered in the view.
* There should *not* be dedicated "create notification" actions. Instead, the notifications reducer should respond to other existing actions, such as that representing adding a task to My Plan, and update its state to create a notification.
** Notifications that should disappear after N seconds should use a saga to set the timer for the clearing of the notification. 
** Notifications with a dismiss button should have an event handler on the dismiss button which emits an action that causes the notification reducer to clear the notification state. 
** Notifications with a button that navigates the user to a given page should have an event handler which emits an action that causes the notification reducer to clear the notification state and the route reducer to set the current route to the relevant page. 
* Notifications generally lead to patterns where the same action causes changes in more than one reducer. This is a good pattern. By comparison, it is an anti-pattern for one action to *immediately* trigger the dispatch of a second action. It *is* OK for an action to trigger a second action after some delay, using a saga.
* The reducer should know what needs to go into the notification based on the actions it responds to. If there are things needed for the notifications that the notifications reducer doesn't have access to, these things should be included in the action. Examples would be something like a message string for the notification.
* There may be situations where data is needed for the notification that is outside the responsibility of both the action creator and notification reducer to know about. We'll see what we do at that point.

**Comment by robinpuga** [comment]
A simple example in the mockups can be found here: https://projects.invisionapp.com/share/3VJJSE3NG28#/screens/299441984
