### ISSUE TITLE
Side menu behaviour

### ISSUE THREAD

**Issue by aron-chen-pg** [pg-irc/pathways-frontend#1130]
The side menu in the current production app closes after users have selected a language, which is the expected behaviour. The staging app though does not do that. The side menu would continue to remain present despite the overlay shadow has disappeared. Users will have to dismiss the side menu manually which could cause frustration overtimes.

**Current side menu behaviour** 
recording for the current staging app (1.29.0):
![side menu misbehaviour.gif](https://images.zenhubusercontent.com/5d6ea767bc3e240001df648b/29f4e7bf-aac8-4940-a190-954b28c376b7)

**Expected side menu behaviour** 
recording from the current production app (1.7.0):
![side menu correct behaviour.gif](https://images.zenhubusercontent.com/5d6ea767bc3e240001df648b/8b93b775-95f4-40b3-ac28-2eb817f38969)

### Acceptance Criteria 
- [ ]  Upon selecting a language, the side menu closes along with the overlay shadow.

### Steps for QA: 
1.  Open the side menu by clicking on to the hamburger icon.
2. Select any language except Arabic (since Arabic resets the whole app).

**Comment by ian-lin-PG** [comment]
An side effect of the app not reloading enough is that the token language doesn't get updated. Non arabic languages to arabic and vice versa will trigger an update on the token to the correct language, but switching between non arabic languages does not.

**Comment by ian-lin-PG** [comment]
QA Passesd.
