### ISSUE TITLE
Bottom navigation bar gets pushed above keyboard

### ISSUE THREAD

**Issue by aron-chen-pg** [pg-irc/pathways-frontend#1131]
When clicking on to a text input field, the bottom navigation bar, which was supposed to be covered underneath the keyboard would get pushed above instead. This happens throughout the app, including Search and Topic Services. The issue was tested for both iOS (iPhones) and Android (Samsung 8) and was only found on Android. 

Below is the video demonstration for staging version 1.29.1 on Android:
![Bottom navigation behaviour.gif](https://images.zenhubusercontent.com/5d6ea767bc3e240001df648b/e5ec13f2-9b7e-446a-a3a8-f286b8c5d453)

### Acceptance Criteria 
- [ ]  When a text input field is clicked/focused, the bottom nav is covered underneath the keyboard.

### Steps for QA: 
1.  Go to Search.
2.  Click on any text input field.

**Comment by tomy-pg** [comment]
Staging 1.32.0 - passes
