### ISSUE TITLE
Review how many screenshots are needed for the app

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1135]
Currently making the screenshots is time consuming. 

Acceptance criteria:
- [ ] Look into whether the number of screenshots (9) can be reduced
~~Look into automatically generating the screenshots~~ Duplicate to Issue [#366](https://github.com/pg-irc/pathways-backend/issues/366)

**Comment by tomy-pg** [comment]
**Apple**
Our app requires one screenshot each for iPhone's with 6.5 inch screens and iPhone's with 5.5 inch screens. We can have a maximum of 10 screenshots **per locale**. 

According to Google, our app requires at least 2 screenshots in total. We can have a maximum of 8 screenshots **per locale**. 

https://thetool.io/2019/app-store-google-play-screenshot-sizes-guidelines
https://help.apple.com/app-store-connect/#/dev910472ff2

Apps do this differently in that they vary in how many screenshots they show and if they display their new feature as part of the screenshots or if they just show a few select screens (IE home page, search page, questionnaire). We currently have 8 screenshots for our app for each locale.
