### ISSUE TITLE
Geocoder is throttling results

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1140]
Geocoder is throttling results leading to very slow UX for search. Client side caching of commonly used location strings could make this a lot better. 

Acceptance criteria:
- [ ] When repeatedly searching with the same location string (a very common use case it seems to me), the geocoder request is only sent out once. Cache size of 1 could really make a difference here, or we can build something little more powerful.

**Comment by tomy-pg** [comment]
Staging version 1.33.0: PASS
