### ISSUE TITLE
Notification token language does not update immediately

### ISSUE THREAD

**Issue by ian-lin-PG** [pg-irc/pathways-frontend#1152]
When a user changes their language in app, their notification token should change to the new language. This allows us to send notification in the language that matches the app.

### Acceptance Criteria 
- [ ]  Token language changes when in app language changes

### Steps for QA: 
1.  Open the app in English
2. Connect to staging DB through postico
3. Open the notification table
4. Change the app language to Arabic
5. Find the token entry that changed from English to Arabic
6. Change app language to another non Arabic language (Korean in this example)
7. Check the same token entry changed to Korean
8. Change app language to yet another non Arabic language (Tagalog)
9. Check token entry updated to Tagalog, THIS IS MOST IMPORTANT TO PASS QA.

**Comment by tomy-pg** [comment]
Not seeing notification token for my Samsung S9.

**Comment by tomy-pg** [comment]
Staging version 1.33.0: PASS
