### ISSUE TITLE
Update location error screen with a better example

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1159]
* Open the app, go to the search screen, enter "Housing" for search term and something invalid for location, e.g. "djeiejed".
* Observe error screen contains examples for what to type for location.
* Observe that one of the examples is not a good way to search, the suggestion is "Kingsway"
* Expected is to have a suggestion that would give a valid result, such as "1356 Kingsway Vancouver"

**Comment by tomy-pg** [comment]
Staging 1.38.0 PASS
