### ISSUE TITLE
Search page animation causes scroll to sometimes not work

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1163]
On my Android device I will occasionally run into this issue. Search for services, scroll through the search results. Observe that sometimes the search result list cannot be scrolled, it sort of stutters and the header/footer animation stutters too. Kinda hard to explain.

### Acceptance Criteria 
- [ ]  Search result scrolling always works

**Comment by niko-pg** [comment]
Hi @rasmus-storjohann-PG  can you please provide more details? Couldn't produce this on my android phone. May I know what phone model you are using?

**Comment by rasmus-storjohann-PG** [comment]
Sure, it's a Moto Z Play, Android v 8.0.0. I will spend some time with the device to see if I can get better repro steps. It looks like a race condition or something, so it might be worth going over the code and see if there are any patterns that might cause that...

**Comment by rasmus-storjohann-PG** [comment]
There is another issue, related, 100% reproducible but not quite as bad: On the search result screen, scroll so that the footer is half hidden. Click on one of the footer buttons. Observe that the page changes to the expected page, but that the footer remains half hidden. Expected is that the footer is fully shown.

**Comment by rasmus-storjohann-PG** [comment]
I'll file that as a separate issue

**Comment by rasmus-storjohann-PG** [comment]
Have not seen this issue in a while, closing as Cannot Reproduce.
