### ISSUE TITLE
Animated footer remains half hidden after page switch

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1165]
* Open the app, go to the search screen, search for a service, observe a search result list.
* Scroll the result list a little bit, until the footer is half hidden.
* Click on one of the footer buttons, e.g. to go to the Learn page. 
* Observe that the page changes to the expected page, but that the footer remains half hidden. 
* Observe that the footer no longer is animated when scrolling on the Learn page.
* Expected is that the footer is fully shown after switching to a different page.

This bug is 100% reproducible.

**Comment by tomy-pg** [comment]
@niko-pg @rasmus-storjohann-PG this is linked to [958](https://github.com/pg-irc/pathways-frontend/pulls#workspaces/arrival-advisor-5977956f40fbe90e67bb4155/board?repos=98336819,99282566,201988978&showPRs=false&showPipelineDescriptions=false) in the **Staging Bugs** swim lane.

**Comment by tomy-pg** [comment]
Staging version 1.35.0: PASS
