### ISSUE TITLE
Link from peacegeeks.org to arrival advisor app

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1179]
On [this page](https://peacegeeks.org/arrival-advisor), make these changes:
- [x] On the banner image, remove the google store and apple store buttons (they are not clickable)
- [x] Below the banner, add clickable buttons to both stores
- [x] See [this page](https://arrivaladvisor.ca/) for the graphics and links to use for the buttons.

### Acceptance Criteria 
- [x]  On the peacegeeks.org home page there are links to the google and apple store entries for arrival advisor. Should look like the links that are already on the arrivaladvisor.org website.

**Comment by ian-lin-PG** [comment]
@rasmus-storjohann-PG updated website found [here](https://peacegeeks.org/arrival-advisor).
