### ISSUE TITLE
Feedback flow UI polish

### ISSUE THREAD

**Issue by cherrielam** [pg-irc/pathways-frontend#1186]
Note: this issue covers UX and UI issues remaining from checking out Rasmus' work-in-progress branch related to #1171. Some work may have been done since I checked out the branch, so some bullet points may already be addressed.

- [ ] **High Priority** — Change receiving updates to contact information

- [ ] **High priority**  — Enter your email if you would like to ~receive updates~ be contacted about this issue

- [ ] **LOW Priority** — Don't show the discard information confirmation modal if no data has been entered in the form

- [ ] **LOW Priority** — Disable the Submit button when there is no data in the form

The following are all styling issues. I have included the suggested code where known:

- [x] **LOW PRIORITY** — Fix styling on Feedback Module modals/pages

   - [x] In **`choose_mode_modal.tsx` (line 41)** under `const HeaderComponent`, change  `<View style={{ ... marginTop: 10 ... }}` to `marginTop: 8`

   - [x] In **`choose_mode_modal.tsx` (line 43)** change `Suggest an Update` to `Suggest an update` (lowercase U) - our titles are currently mostly sentence case

   - [x] In **`choose_mode_modal.tsx` (line 62)** increase spacing around `OptionButton` so they're more easily clickable:  `<TouchableOpacity style={{marginVertical: 20}} onPress={props.onPress}>`

   - [x] In **`choose_mode_modal.tsx` (line 54)** as a result of increasing spacing around `OptionButton`, reduce spacing at the top and bottom of `ButtonsComponent` to make the menu look cleaner. This is a bit hacky but I added a negative marginVertical to make this possible. `<View style={{ marginHorizontal: 10, marginVertical: -10 }}>`

   - [x] In **`choose_mode_modal.tsx` (line 70-71)** Increase spacing around the subtitle component so it matches the rest of the menu, and reduce the font size: `<View style={{ marginHorizontal: 10, marginBottom: 15 }}>
        <Text style={[textStyles.paragraphSmallStyleLeft, { fontSize: 14 }]}>`

   - [x] In **`discard_changes_modal.tsx` (line 17)** Reduce `borderRadius` of modal: `<View style={{ backgroundColor: colors.white, borderRadius: 15, padding: 20 }}>`

   - [x] In **`discard_changes_modal.tsx` (line 36)** Add button padding for `KeepEditingButton`. Update style: `style={[applicationStyles.whiteTealButton, { paddingVertical: 10, paddingHorizontal: 15, marginRight: 5 }]}`

   - [x] In **`discard_changes_modal.tsx` (line 47)** Add button padding for `DiscardButton`. Update style: `style={[applicationStyles.tealButton, { paddingVertical: 12, paddingHorizontal: 17,  marginLeft: 5 }]}`

   - [x] In **`feedback_component.tsx` (line 35)** Fix the left and right alignment of text. Under `export const FeedbackComponent`, change `paddingHorizontal` from `return (
        <View style={{ marginVertical: 10 }}>
            <View style={{ paddingHorizontal: 15, marginBottom: 10 }}>` to `return (
        <View style={{ marginVertical: 10 }}>
            <View style={{ paddingHorizontal: 10, marginBottom: 10 }}>`

   - [x] In **`feedback_component.tsx` (line 76)** Under `ToggleInputComponent`, add `marginTop: 5`

   - [x] In **`feedback_component.tsx` (line 105)** Under `const ToggleTextInputComponent... <Icon type... name... style.../>`, change Icon `style={{ padding: 5, color: getEditingColor(props.isEditing) }}` to `padding: 0` (or just remove the padding)

   - [x] In **`feedback_component.tsx` (line 165)** Change colour of Suggest an update toggle buttons to be a bit darker. Change `isEditing ? colors.teal : colors.grey` to `isEditing ? colors.teal : colors.darkerGrey`

   - [ ] In **`feedback_component.tsx` (I think?)** Update the input text font to Avenir. When you toggle on Suggest an update, the text that says "Comment or suggest edits" should be in Avenir, not the system font.

   - [x] In **`feedback/header_component.tsx` (line 14)** Header is too close to the top. Add `marginTop` to `<Header>`: `<Header style={[styles.headerContainer, { marginTop: 5 }]}>`

   - [x] In **`other_remove_service_component.tsx` (line 50)** Change title from `Other feedback about this service.` to `Other suggestions`. @rasmus-storjohann-PG I suggest this change because we don't want to use the word "feedback" to give people the sense that they can give Yelp-like feedback about the service. I'm open to other wording. Also please remove periods from titles.

   - [x] In **`other_remove_service_component.tsx` (line 55)** Remove period at the end of `This service no longer exists.`

   - [x] In **`other_remove_service_component.tsx` (line 68)** Add `marginHorizontal` around the `Label` to match the spacing of the title. Update to `<Label style={[textStyles.suggestionText, {paddingBottom: 10, marginHorizontal: 10 }]}>`

   - [x] In **`other_remove_service_component.tsx` (line 77)** Add `marginHorizontal` around the `<Input>` to match the spacing of the title. Update to `<Input... style={[styles.input, { marginHorizontal: 10 }]}...`

   - [ ] In **`other_remove_service_component.tsx`** Remove the divider/border under the input box. Not sure why it's there/where to find it

   - [ ] In **`other_remove_service_component.tsx`** Update the input text font to Avenir

   - [x] In **`expandable_content_component.tsx` (line 152)** change to `paddingHorizontal: 5`

   - [ ] In **`receive_updates_modal.tsx` (I think?)** Update the input text font to Avenir. The fields for "Enter email", "Enter your name", "Enter your organization name", "Enter your job title", should all be in Avenir, not the system font.

   - [ ] In **`receive_updates_modal.tsx` (I think?)** Update the button font for "Finish without email/Email me updates" to Avenir.

   - [x] In **`receive_updates_modal.tsx` (line 46)** Add `marginBotton` under the title, change to: `<Text style={[textStyles.headlineH2StyleBlackLeft, { marginBottom: 15 }]}>`

   - [x] In **`receive_updates_modal.tsx` (line 49)** Add `marginBottom`. Change to: `<Text style={[textStyles.paragraphStyleBrown, { marginBottom: 10 }]}>`

   - [x] In **`receive_updates_modal.tsx` (line 111)** Add `marginBottom`. Change to: `<Text style={[textStyles.headline6, { color: colors.black,  marginBottom: 5 }]}>`

   - [x] In **`receive_updates_modal.tsx` (line 122)** Update `marginTop` and add `marginBottom`: `<Text style={[textStyles.headline6, { color: colors.black, marginTop: 20, marginBottom: 5 }]}>`

   - [x] In **`receive_updates_modal.tsx` (line 133)** Update `marginTop` and add `marginBottom`: `<Text style={[textStyles.headline6, { color: colors.black, marginTop: 20,  marginBottom: 5 }]}>`

- [x] **LOW PRIORITY** — Fix the alignment on Service Detail fields

   - [x] In **`address_component.tsx` (line 63)** add `View style={{ marginHorizontal: 5 }}` to `export const renderSingleAddress = (address: Address): JSX.Element => (`

   - [x] In **`email_component.tsx` (line 43)** same as above, add `View style={{ marginHorizontal: 5 }}` 

   - [x] In **`phone_numbers_component.tsx` (line 62)** same as above, add `View style={{ marginHorizontal: 5 }}` 

   - [x] In **`missing_service_detail_component.tsx` (line 11)** same as above, add `View style={{ marginHorizontal: 5 }}` 

   - [x] In **`website_component.tsx` (line 42)** same as above, add `View style={{ marginHorizontal: 5 }}` 

   - [x] In **`card_button_component.tsx` (line 13)** under `export const CardButtonComponent = (props: CardButtonProps): JSX.Element => {` change `View style={{ alignItems: 'center' }}` to `alignItems: 'flex-start` 

   - [x] In **`close_button_component.tsx` (line 26)** change `paddingRight: 15` to `paddingRight: 5` 

   - [x] In **`content_layout/divider_component.tsx` (line 6)** change marginVertical to `marginVertical: 15` 

   - [x] In **`content_layout/divider_component.tsx` (line 6)** change marginVertical to `marginVertical: 15` 

   - [x] In **`content_verification_component.tsx` (line 7, 26)** remove `import { DividerComponent }` and delete `<DividerComponent />`

- [x] **LOW PRIORITY** — Add a drop shadow under the bottom nav, to help make it more visible and also make the disappearing nav (on search) more intuitive:

   - [x] In **`footer_component.tsx` (line 14)** add `import { applicationStyles } from '../../application/styles';`

   - [x] In **`footer_component.tsx` (line 90)** change `FooterTab` styles to `<FooterTab style={[{ backgroundColor: colors.lightTeal}, applicationStyles.boxShadowAbove ]}>`

   - [x] In **`styles.tsx` (line 413-415)** change `boxShadowAbove` styles to `shadowOffset: { width: 0, height: -3 },
        shadowOpacity: 0.25,
        shadowRadius: 5,` (I checked that nowhere else uses boxShadowAbove currently)

- [x] **LOW PRIORITY** — In **`topic_list_heading_component.tsx` (line 31)** add `marginBottom` under Explore Icon on Topics list: add `marginBottom: 5`

**Comment by tomy-pg** [comment]
Removed:
- [ ] **HIGH Priority** — Hide the bottom nav on "This service no longer exists" and "Other" mode views. [See video](https://drive.google.com/file/d/1_6J-csIDQ7DXbxyDMxkxUys6LWTRRzc1/view?usp=sharing). "Change name and other details" mode hides the bottom nav, but the other modes "This service no longer exists" and "Other" do not hide the bottom nav. In the latter two, the user can navigate away from the feedback page and go to Bookmarks/Home, etc. and then return to search. When they click another service, it awkwardly opens the service in feedback mode (since they never properly exited feedback mode).
Addressed as part of #1171

**Comment by tomy-pg** [comment]
Taking on the rest of the issues.

**Comment by ian-lin-PG** [comment]
The bottom nav no longer shows up in different feedback screens, that offered opportunity to break feedback flow. Submit feedback button is disabled if the fields are empty. Closing on an empty feedback form does not trigger the discard modal as there is nothing to discard.

PASSED in staging 1.39.0
