### ISSUE TITLE
Back button should consistently bring UX back to the correct scroll position

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1190]
Places in the UX where we navigate from a detail page to a list page by clicking the back button:
- [x] Home page -> Topic detail -> Back to home page: Does not remember the position within the home page
- [ ] Learn page -> Learn section -> Back to learn page: Does not remember the position within the learn page
- [x] Bookmark page -> Topics pane -> Topic detail -> Back to bookmark page: Does not remember list position
- [x] Bookmark page -> Services pane -> Service detail -> Back to bookmark page: It remembers the list position
- [ ] Home page -> Learn section (e.g. Education) -> Topic detail -> Back to Learn section: It does not remember
- [x] Topic detail -> Related services -> Service detail -> Back to related services: It remembers
- [x] Service search result -> Service detail -> Back to service search result: It remembers

### Acceptance Criteria 
- [ ]  The app remembers the scroll location in all the cases listed above. This would complete the work started under #1106 

See also #1275 , try to fix it too as part of this work

**Comment by cherrielam** [comment]
Agree, overall this would be a good issue to tackle

_Home page -> Topic detail -> Back to home page: Does not remember the position within the home page_ is **higher priority** due to the sheer length of the page, and number of sections. However, this may be rendered moot if we decide to amend the homepage experience.

**Comment by rasmus-storjohann-PG** [comment]
QA sweep:

- [ ] Home page -> Topic detail -> Back to home page: Does not remember the position within the home page
- [ ] Learn page -> Learn section -> Back to learn page: Does not remember the position within the learn page
- [ ] Bookmark page -> Topics pane -> Topic detail -> Back to bookmark page: Does not remember list position
- [ ] Bookmark page -> Services pane -> Service detail -> Back to bookmark page: It remembers the list position
- [ ] Home page -> Learn section (e.g. Education) -> Topic detail -> Back to Learn section: It does not remember
- [ ] Topic detail -> Related services -> Service detail -> Back to related services: It remembers
- [ ] Service search result -> Service detail -> Back to service search result: It remembers

**Comment by rasmus-storjohann-PG** [comment]
Closing this story, opened #1319 with remaining issues.
