### ISSUE TITLE
Flip graphic in Arabic

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1191]
This looks funny, the image should be flipped so the person faces the text on the right

![image](https://user-images.githubusercontent.com/32307781/84183033-272b4f00-aa40-11ea-821e-3e7c16b214a2.png)

**Comment by cherrielam** [comment]
Here is the flipped image: https://zpl.io/2GKdnoj

**Comment by tomy-pg** [comment]
Staging version 1.42.0 - PASSES
