### ISSUE TITLE
Can't go back from feedback submit modal

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1200]
Minor usability problem: Go through the service information feedback flow, hit submit. Note that from the submit modal it is not possible to go back to the feedback form and make additional changes.

Along with this, the `Contact information` modal is being hidden by the keyboard and there is no way of scrolling to view hidden fields. @cherrielam has created a [mock](https://app.zeplin.io/project/5bc7bfa42e72260acb03aa86/screen/5f036183f06da85dd2a8edaa
) which turns this modal into a screen. This is covered in detail in Issue #1210. This will be addressed in this PR for simplicity.

ACs:
- [x] Implement the contact information screen
- [x] There is a way to go back from the contact information screen. This returns the user to the feedback form with the information as there was when they hit the Submit button.

Steps for QA:
1. Suggest an update using any of the existing three options.
2. Submit feedback
- [x] Ensure you are navigated to a new **Contact information screen**
- [x] Ensure the header title matches the Suggest an Update option you choise IE _Other Suggestions_
3. Click on the back button on the header
- [x] Ensure you are navigated back to the previous screen
- [x] Ensure the feedback you entered still exists on the page

**Comment by cherrielam** [comment]
I updated the AC to say "go back" instead of "close" the modal. Closing doesn't match the user's mental model (because it is confusing as to whether "close" would have the user to finish without email or delete their suggestion entirely. Please use a back arrow (top left) or "Back" on the bottom left next to the "Finish without email/Email me updates" button

**Comment by ian-lin-PG** [comment]
The PR passes AC. Slight observation, the android back button and the header back button behaves differently on step 3. Should android back button also go back to before submit screen? It is currently disabled.

**Comment by ian-lin-PG** [comment]
Test Pass 1.42.0
