### ISSUE TITLE
Feedback: Submit button can be hard to find

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1202]
When supplying feedback information, the on screen keyboard can obscure the Submit button. In some cases (depends on the device?), the user needs to click to exit the keyboard in order to be able to see the button at all. On Android with staging version 1.38.0, the submit button moves up above the on screen keyboard, so it's visible always but leave very little screen space for seen the text the user is editing. Maybe the Submit button needs to be smaller when the on screen keyboard is visible?

https://reactnative.dev/docs/textinput.html#returnkeytype

### Acceptance Criteria 
- [ ]  It is easy to submit feedback data through the form

**Comment by cherrielam** [comment]
When filling the form, the "return" button on the keyboard should change to say "Done" on iOS and show the "Done" action button on Android

![image](https://user-images.githubusercontent.com/21990736/86066592-72c18f00-ba27-11ea-879d-5d9ae8168820.png) - this is what the keyboard is supposed to look like on iOS. See https://developer.apple.com/documentation/uikit/uitextinputtraits for details

![image](https://user-images.githubusercontent.com/21990736/86066642-984e9880-ba27-11ea-8540-4590ee19dbc1.png) - this is what it should look like on Android. This may help? I'm not sure: https://medium.com/flutterpub/flutter-keyboard-actions-and-next-focus-field-3260dc4c694

Please apply this to all similar form fields

**Comment by tomy-pg** [comment]
This needs to be fleshed out a bit more for different cases such as:

Multi-line text boxes (feedback): Should we replace the return key with a `done` button that closes the keyboard? 

Cases where users want to input on more than one different field (feedback, search): Not all users will want to submit right after one input.

**Comment by tomy-pg** [comment]
Multi-line text box examples:
They all keep the return button but have varying ways of making the submit button visible to users.

**LinkedIn**
![Screenshot_20200708-111414_LinkedIn](https://user-images.githubusercontent.com/47794846/86955563-a168f500-c10c-11ea-83ac-827a7aa78ce7.jpg)

**Reddit**
![Screenshot_20200708-110734_Reddit](https://user-images.githubusercontent.com/47794846/86955557-9f9f3180-c10c-11ea-9d7a-8c58a3b43f04.jpg)

**Instagram**
![Screenshot_20200708-110804_Instagram](https://user-images.githubusercontent.com/47794846/86955558-a0d05e80-c10c-11ea-98c7-7081d69adf16.jpg)

**Messenger**
![Screenshot_20200708-111124_Messenger](https://user-images.githubusercontent.com/47794846/86955561-a168f500-c10c-11ea-8df1-01af702cf235.jpg)

**Comment by cherrielam** [comment]
Here's another pattern I found that seems to match our style well ![image](https://user-images.githubusercontent.com/21990736/87065519-f9affd80-c1c5-11ea-88b3-4f27c886b598.png)

**Comment by cherrielam** [comment]
@tomy-pg My recommendation for multiline (return) + done in the Feedback module is following the pattern of Done above the keyboard:

See https://zpl.io/adwL9kp and https://zpl.io/brpgmEO for mocks

As for Search, and other single-line inputs, the keyboard "Return" button should ideally be "Done" (I think the text is still "Return" on iOS currently). 

Single line "Done" buttons should close the keyboard (NOT submit the search immediately, because we have a separate submit button) — I don't believe we currently have a need for a keyboard action that submits a single-line input immediately, though that may be explored in the future.

**Comment by tomy-pg** [comment]
@cherrielam for the multi-line Done buttons, they should close the keyboard as well, not submit right?

**Comment by cherrielam** [comment]
Yes, close the keyboard

**Comment by rasmus-storjohann-PG** [comment]
Looks good to me on one real android device and one simulated ios device. @ian-lin-PG and @tomy-pg is that good enough?

**Comment by tomy-pg** [comment]
Looks good when I tested on iPhone X as well.
