### ISSUE TITLE
Suggest an update missing (investigate)

### ISSUE THREAD

**Issue by ian-lin-PG** [pg-irc/pathways-frontend#1205]
@ian-lin-PG commented on [Thu Jun 25 2020](https://github.com/pg-irc/pathways-backend/issues/540)

During user testing, the user could not find suggest an update on service detail page. This could be an isolated incident, but if we have code for hiding that button we need to review it more clearly.

@ian-lin-PG to try to reproduce

### Acceptance Criteria 
- [ ]  Identify code that may hide the suggest an update button
- [ ] Suggest an update button should always be present

### Steps for QA: 
1.  Open a service
2. See suggest and update is at the bottom of service detail page

**Comment by rasmus-storjohann-PG** [comment]
CNR
