### ISSUE TITLE
Find settlement agencies list does not load

### ISSUE THREAD

**Issue by ian-lin-PG** [pg-irc/pathways-frontend#1206]
When navigating to help page and click `Find a settlement agency near me` the topic services took a really long time to load. Clear the cache and find potential regression.
Topic services are cached when it loads, may require clearing cache for most accurate results.

### Acceptance Criteria 
- [ ]  Topic service shouldn't take more than 5 seconds to load

### Steps for QA: 
1.  Navigate to help page by clicker on the question 
2. Click on `Find a settlement agency near me`
3. Services should load in 5 seconds

**Comment by jparlina** [comment]
Tested on Staging V1.41.0 Server V1.3.34 on iOS: 

- [x] Topic service shouldn't take more than 5 seconds to load (took about 3 seconds)
