### ISSUE TITLE
Submit update modal pushed too far up

### ISSUE THREAD

**Issue by ian-lin-PG** [pg-irc/pathways-frontend#1207]
On some android phones the keyboard may push the `Receiving updates` modal too high. Require screenshot for user who used samsung galaxy S3 as a reference.

### Acceptance Criteria 
- [ ]  Receive update modal should scale to what the device dimension is or should be smaller to avoid screen usage

### Steps for QA: 
1.  Submit a feedback to a service
2. On the receive update page click on email
3. Take a screenshot

**Comment by rasmus-storjohann-PG** [comment]
This is no longer a modal
