### ISSUE TITLE
Suggest an update stop working 

### ISSUE THREAD

**Issue by ian-lin-PG** [pg-irc/pathways-frontend#1208]
When in the `This service no longer exists` page, pressing the back button (on android) will break the `Suggest an update` button.

When in `Suggest an update` modal back button (on android) does nothing.

Both problems are related to the back handler on android not supporting modals. See [this documentation](https://docs.expo.io/versions/latest/react-native/backhandler/). Possibly trigger an alert when the back button is pressed on android signalling the back button is not allowed.

### Acceptance Criteria 
- [ ]  The `Suggest an update` button will not break after pressing back buttons on android from `this service no longer exist page`
- [ ] The back button on android closes the `suggest and update` modal

### Steps for QA: 
1.  Open any service detail page
2. Click on `Suggest an update` button
3. Press back button on android should close the `Suggest an update` modal
4. Click on `Suggest an update` button again
5. Click on `This service no longer exists` button
6. Press android system back button
7. Click on `Suggest an update` button should reopen the `Suggest an update` page

**Comment by ian-lin-PG** [comment]
After consulting with @cherrielam, the best case solution would be for the back button to behave the same as existing close button for consistency of behaviour. The bare minimum is for the back button to not respond in the `Service no longer existing` page to avoid the show stopper bug of bricking the `suggest an update` button. In the case if either solution are not possible, further alternatives will be seeked.

**Comment by tomy-pg** [comment]
Staging version 1.41.0 - PASSES.
