### ISSUE TITLE
"Contact information" modal is covered by the keyboard

### ISSUE THREAD

**Issue by cherrielam** [pg-irc/pathways-frontend#1210]
When a form field is selected (to fill in) from the "Receiving updates" modal (eg. Name, Organization, Job Title), the modal gets covered by the keyboard and the user is unable to scroll down. This is especially problematic on the "Job Title" field, where the keyboard covers the field itself and the user is unable to see what they are typing in. Form field should scroll up above the keyboard (as per behaviour on the "Change name and other details" page). 

If this is difficult to do because this page is a modal, I would recommend changing this modal page style to a full page style (like the "Change name and other details" page). I (Cherrie) can provide design if needed.

### Acceptance Criteria 
- [ ]  Form fields on "Receiving updates" modal are no longer hidden by the keyboard

### Steps for QA: 
1.

**Comment by tomy-pg** [comment]
Mocks for Contact information screen:

**Comment by tomy-pg** [comment]
This will be addressed as part of Issue #1200. Closing to prevent duplication.
