### ISSUE TITLE
Upgrade client packages

### ISSUE THREAD

**Issue by ian-lin-PG** [pg-irc/pathways-frontend#1212]
Describe the issue and expected behaviours. If this is a bug, describe the steps to reproduce the problem, what you observe, and what you expected to observe.

### Acceptance Criteria 
- [ ]  

### Steps for QA: 
1.  Go to search page on iOS simulator
2. Hamburger should not be covered
3. Change language to a different one (traditional chinese for instance)
4. Check that the token on the server DB changes to the appropriate language.

**Comment by tomy-pg** [comment]
Staging version 1.41.0 - PASSES.
