### ISSUE TITLE
Make a list of all the library branches in the lower mainlaind

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1213]
BC211 dataset does not contain service records for library branches

### Acceptance Criteria 
- [ ]  We have a list of all library branches in the lower mainland. For each branch, we have name, description, organization id (the org id of the corresponding municipal library organization), address, phone numbers, email, website address.
- [ ] The library branches show up in the app when searching for services near me.
- [ ] The data is in a formal that allows for simple import into our database, @rasmus-storjohann-PG and @ian-lin-PG to assist

### Steps for QA: 
1.  +

**Comment by jparlina** [comment]
[Here]( https://docs.google.com/spreadsheets/d/1vaGo-DZQGlaulrz1GM0B_kwDZQoSfa3l4loQmRxk4tY/edit#gid=597963664)'s the list of Public Libraries in Lower Mainland to add as service records.

**Comment by rasmus-storjohann-PG** [comment]
Review of Jean's libraries file:
* Organizations
    - [ ] There are no organization entries, because all the organizations are already in BC211, I guess?
* Services
    - [ ] `id` column is not populated
* Locations: Look good
* Addresses: Look good, location_id column populated
* Phones look good
* Service at location
    - [ ] service id is not populated
* Taxonomy:
    - [ ] vocabulary is BC211, should be PeaceGeeks
* Services taxonomy:
    - [ ] service id is not populated

**Comment by rasmus-storjohann-PG** [comment]
This is done says Jean

**Comment by ian-lin-PG** [comment]
The library data is now imported. OF the random samples I took, first entry of `Bob Prittie Metrotown Branch` shows up correctly in the app. The last entry `West Vancouver Memorial Library` is a duplicate. This is an edge case where Jean's data and Theresa's data overlap with a different service id. Then there's `Ocean Park Branch` which has no description.

**Comment by ian-lin-PG** [comment]
`West Vancouver Memorial Library` is no longer a duplicate. `Ocean Park Branch` now also has service description. I duplicated Jean's Library csv and removed all the Y entries which prevents double entry with Theresa's dataset. I also duplicated the service description from the organization description for all the related services. So now there's no more empty description. PASS QA 1.59.0

**Comment by tomy-pg** [comment]
Staging 1.62.0 - Spot checked 10 libraries in the list. They were all in the app.
