### ISSUE TITLE
Service list UX looks bad for services with the same name as their organization

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1214]
Service list entries show the organization name and the service name. 

A Service list entry for such a service will be repeated, e.g. "Peace Portal Alliance Church - Peace Portal Alliance Church".

### Acceptance Criteria 
- [ ]  In cases where the service name and organization name are identical, show just the service name in the service listing.

**Comment by tomy-pg** [comment]
Staging 1.42.0 - PASS
