### ISSUE TITLE
Arabic Labels on Feedback Form should be RTL - issue on iOS only 

### ISSUE THREAD

**Issue by jparlina** [pg-irc/pathways-frontend#1221]
Staging V 1.40.0: Arabic labels on Feedback Forms (screenshots 1, 2, 3) should be RTL. This issue seems to be on iOS only. Android looks fine. 

1. Suggest an update Form: 
![Screen Shot 2020-07-16 at 9 48 07 AM](https://user-images.githubusercontent.com/48343061/87699856-540f0800-c74a-11ea-8876-4706c6651c2f.png)

2. This service no longer exists - “e.g. Service is permanently closed”
![Screen Shot 2020-07-16 at 1.47.10 PM.png](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/1a840e38-a4f3-45a8-b0ec-0626271ac88a)

3. Other Suggestions - “Comment or suggest edits”
![Screen Shot 2020-07-16 at 1.45.44 PM.png](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/74949adc-1280-4c09-b5f2-87380d74ded2)

### Acceptance Criteria 
- [ ]  Arabic labels on Feedback Forms on iOS should be RTL

### Steps for QA: 
1. Test the Arabic version of the app on iOS
2. Select a topic
3. Click "Find related services near me"
4. Open a Service Details page
5. Click "Suggest an update"
5a. Select _Change name or other details_: 
- [x] Arabic labels on Feedback Form should be RTL 
5b. Select _This service no longer exists_: 
- [x] "e.g. Service is permanently closed" should be RTL 
5c. Select _Other suggestions_:
- [x] "Comment or suggest edits" should be RTL

**Comment by tomy-pg** [comment]
Staging 1.42.0 - Passes
