### ISSUE TITLE
Post-MVP cleanups

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#123]
* Simplify task store data structure
* Think about reducers not ever actually being called with undefined actions, but they are called with `any` action.
* Maybe replace locale builder with locale generator functions similar to `aString()`, i.e. `aLocale()`, `aLocaleWithCode(code)`, etc.

# Selectors

Reorgnanize selectors, by creating the following categories of functions (where not far from this now, it just needs more consistency). 

Given that these functions may be composed in many different ways, the hope is that many of them will be shared, the most flexible arrangement is to have each function in its own file, named to match the function name. Given the consistent function naming scheme, I think discovering and reusing existing functions will work well and we should avoid needless duplication of functionality. 

* selectors: named `selectFoo()`, all accept `app.Store` as their only argument, and return types such as `selectors.Task` (as opposed to `stores.Task`). Can be named `selectCurrentFoo()` when they also accept the route and return the item with id from the current route. Their implementations consist exclusively of calls to the helper functions below, and they contain no loops or branches --- this is so that they need not be unit tested. Selector functions need to be aggressively broken up into smaller selector functions and other helpers, because many are too big. Big bonus: we avoid unit tests that work with the entire app store. They are called from `mapStateToProps()` functions. They are closely coupled to the view, since they build data structures exactly as the views need them to be. Another big bonus: since there is no massaging or other logic in `mapStateToProps()` functions, we don't need to unit test those either.
* pickers: named `pickFoo()`, all accept `app.Store` as their only argument, and return a collection from some sub store, or pickFooById(id: string, store: app.Store)` to return a single entity by its `id`. These functions are the only ones outside of reducers that know the details of how the store is structured. They are all one-line functions and are not unit tested.
* filters: named `filterFooByBar()`, they contain the logic for taking one or more collections of store data and returning the subset needed for the view, such as the tasks tagged with a given taxonomy. They accept and return types such as `stores.Task` (as opposed to `selectors.Task`. These functions are unit tested.
* builders, named `toSelectorFoo()` or `toSelectorFooFromBarAndBaz()`, they accept one or more collection of `stores` data structures such as `stores.Task` and `stores.TaskUserSettings`, and return data structures as needed for the view, i.e. collections of `selector` data structures such as `selectors.Task`. These functions are unit tested. 
* All functions should work with the "model" flavour of objects, only the selectors and buiders should return the "selector" flavour of objects.
* other helper functions named `getFoo()` and `isFoo()` will also be needed.
* Each function is stored in its own file. Files are located in `src/selectors/foo` where foo is the return type of the function, foo can be tasks, articles, exploreSections, etc., i.e. all functions that return the same kind of entity (whether the store or selector flavour) are located together.
* To avoid circular dependencies, selector types need to be defined in their own files too, in `/src/selectors/task/types.ts` etc.

This naming scheme, we should be able to list the files in a directory in sorted order and get a nice, readable table of the functions, grouped by subject area.

**Comment by tnightingale** [comment]
Here is an approach to handling generic Redux Actions in reducers:
```typescript
// @types/redux.d.ts
// This makes these types global, but they could be placed anywhere.

declare interface Payload {}

declare interface Action<P extends Payload = Payload> {
    readonly type: string;
    readonly payload: P;
}
```

Now your reducer can be:
```typescript
interface MyStoreActionPayload extends Payload {
    /* ... */
}

function myStoreActionCreator(arg1: string, arg2: number, ...): Action<MyStoreActionPayload> {
    return {
        "type": constants.MYSTORE_ACTION,
        "payload": { /* ... */ },
    };
}

function reducer(store: MyStore = buildDefaultMyStore(), action: Action) {
    switch(action.type) {
        case constants.MYSTORE_ACTION: {
            const myStoreActionData = action.payload as MyStoreActionPayload; // This cast is as safe as it's going to get.
            // ...
        }
    }
}

**Comment by rasmus-storjohann-PG** [comment]
https://scotch.io/amp/tutorials/3-useful-typescript-tips-for-angular contains some useful ideas

**Comment by rasmus-storjohann-PG** [comment]
https://medium.com/netscape/redux-reducers-functional-approach-69c0f6bacdc2
