### ISSUE TITLE
Wrong hyperlink on Feedback Explainer

### ISSUE THREAD

**Issue by jparlina** [pg-irc/pathways-frontend#1239]
The hyperlink for updates@bc211.ca directs to support@expo.io instead of to updates@bc211.ca.

![Screen Shot 2020-07-31 at 4.15.29 PM.png](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/efaf60da-c4b8-4c38-8c19-6e8ab0faa219)

### Acceptance Criteria 
- [ ]  when clicking updates@bc211.ca in the third section on the Feedback Explainer, it should create an email to updates@bc211.ca.

### Steps for QA: 
1.  Open a service detail record
2. Click Suggest an update
3. Click Learn more to open "Feedback Explainer"
4. Go to the last section on the Feedback Explainer
5. Click "updates@bc211.ca" 
- [ ] it should create a new email to updates@bc211.ca

**Comment by tomy-pg** [comment]
Staging version 1.44 - PASS
