### ISSUE TITLE
Arabic: Search Error - Invalid Location: Incorrect Order LTR/RTL

### ISSUE THREAD

**Issue by jparlina** [pg-irc/pathways-frontend#1243]
As per [Arabic QA](https://github.com/pg-irc/arrival-advisor-qa/issues/73) on Aug 6, 2020: 
The third bullet point under Search Error - Invalid Location:
Order of sentence should match English. If possible, add a LTR mark before number to fix, or leave as is if not possible. 

![Screen Shot 2020-08-06 at 5.14.25 PM.png](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/20121213-b971-4cd3-8a14-a9990688924f)

### Acceptance Criteria 
- [ ]  "1356 Kingsway Vancouver" in the third bullet point under Search Error - Invalid Location should match the English version

### Steps for QA: 
1.  Go to Search page
2. Enter a keyword and an invalid location
3. "1356 Kingsway Vancouver" in the third bullet point under Search Error - Invalid Location should match the English version

**Comment by tomy-pg** [comment]
Should see this fixed on next staging release.

**Comment by jparlina** [comment]
Fixed on Staging V1.43.0
![Screen Shot 2020-08-14 at 5.35.14 PM.png](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/d5011fc3-2514-4db4-86d2-447d64f7bf0d)
