### ISSUE TITLE
Target Android 10 by November 2020

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1253]
Hello Google Play developer,

This is a reminder that starting November 2, 2020, updates to apps and games on Google Play will be required to target Android 10 (API level 29) or higher.  After this date, the Play Console will prevent you from submitting new  app bundles and APKs with a targetSdkVersion less than 29. Please note  that Wear OS apps are not subject to the API level 29 requirement. This will not impact your existing listing on the Play Store.

Configuring  your app to target a recent API level ensures that users benefit from  significant security and performance improvements, while still allowing  your app to run on older Android versions (down to the minSdkVersion). 

### Action required

Please  ensure that your apps are configured to target at least Android 10 (API  level 29) by November 2, 2020. For technical advice on how to change  your app's target API level to meet these requirements, refer to the migration guide.

### Affected apps

The  apps included below have one or more app bundles or APKs—in production  or testing tracks—that aren't currently targeting API level 29 or  higher. Apps are listed with the maximum version code and corresponding  targetSdkVersion. If you have more than 20 apps that could be affected  in your account, please check the Play Console for a full list.

**Comment by tomy-pg** [comment]
Expo team seems to be on this. https://github.com/expo/expo/issues/8469

**Comment by ian-lin-PG** [comment]
I agree with @tomy-pg, closing this issue.
