### ISSUE TITLE
Set app lat/long to any value for use in demo sessions

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1259]
This feature will be deployed to the staging environment only. It is expected to be needed for the week of Sep 21, 2020.

When demoing the app for an audience located in a particular region, it can be useful to set the location of the app to be in that region, even though the person doing the demo might be located elsewhere (these are assumed to be remote Zoom sessions). Suggested UX for this is to

### Acceptance Criteria 
* Go to the Find a Service page (magnifying glass)
- [ ] In the location field, enter the lat long like so "Sticky:49.246292,-123.116226". The app will then use this lat/long for the device location in all contexts.
- [ ] Validate the input values, so that if they're way off, nowhere near BC (especially if lat and long are reversed), there is a friendly error message.
- [ ] To clear the sticky location, home screen > Help & support > Click "Delete all user data"

**Comment by tomy-pg** [comment]
Staging version 1.48.0 - PASS
