### ISSUE TITLE
Load BC211 organization data from the server

### ISSUE THREAD

**Issue by ian-lin-PG** [pg-irc/pathways-frontend#1260]
Right now the organization page is hard coded with a dummy organization. Make the organization detail page render with the correct information.

### Acceptance Criteria
- [x]  Create an organization interface for front end consumption (store, props etc.)
- [x]  Create aync API call to fetch organization data
- [x]  Save organization data to the store of state where appropriate
- [x]  Organization detail page is live with respect to which service page it is directed from
- [ ] Check with @cherrielam what the ordering of the services should be in the list of services for an organization

### Steps for QA: 
1.  Open any service detail page
2. Click on the Organization name
3. The title of the organization page matches the organization name in the previous page
4. Click on the services tab to see the services associated with this organization
5. Click on the bookmark icon and see the correct bookmark icon and feedback
6. Click on one of the services opens the service detail page.

**Comment by tomy-pg** [comment]
Staging version 1.56.1 - PASS
