### ISSUE TITLE
clicking back after sending feedback sends users to Contact information screen

### ISSUE THREAD

**Issue by tomy-pg** [pg-irc/pathways-frontend#1262]
Steps to reproduce error:
1. From a service list, click on any service
2. From the service detail screen, click on `Suggest an Update` and choose any of the 3 options.
3. Write some feedback and submit it.
- [ ] Observe that you are brought back to the service detail page
4. From this page either click on the back button on the header or click on Androids built in back button
- [ ] Observe that you are brought to the `Contact information` screen with the title `Other suggestions`
See [video](https://drive.google.com/file/d/1xsGbWbz8QT3Gbg70ToOf4weIAYGTBkhv/view?usp=sharing)
 
The expected behaviour is to return to the screen they were on prior to the service detail page which is either the search service list, topic service list or bookmarks service list. 

### Acceptance Criteria 
- [ ]  clicking back after sending feedback should return user to the screen they were previously on
- [ ] unit tests to catch errors 

### Steps for QA: 
1.  From a service list, click on a service
2. Once on the service detail page, suggest an update for `Change name or other details`
3. Send feedback
4. Once you return to the service detail page, click the back button.
- [x] ensure you return to the service list screen you were just on

**Comment by rasmus-storjohann-PG** [comment]
Fixed
