### ISSUE TITLE
feedback header cuts off close button

### ISSUE THREAD

**Issue by tomy-pg** [pg-irc/pathways-frontend#1263]
In Tagalog and French locales on Feedback, the close button on the header is either cut off or is completely removed.

![Screenshot_20200901-111012_Arrival Advisor.jpg](https://images.zenhubusercontent.com/5c6c8cff9d62b128eab447ff/19262736-22a7-4bfa-ad92-6064b005499c)![Screenshot_20200901-111026_Arrival Advisor.jpg](https://images.zenhubusercontent.com/5c6c8cff9d62b128eab447ff/e221208c-e6d6-40c1-9c28-c884c3f252aa)
![Screenshot_20200901-143646_Arrival Advisor](https://user-images.githubusercontent.com/47794846/91908645-c2f3e200-ec60-11ea-9db4-7b795e33f633.jpg)

### Acceptance Criteria 
- [x]  The header close button can be seen in all locales

### Steps for QA for Developers: 
IF you do not see translations for feedback enter these commands in your terminal

git submodule update --remote --merge  
./bin/strings.sh --combine-pos

go to package.json and remove `--strict` flag from `yarn build-strings`
yarn build-strings
yarn build
yarn start -c

Steps for QA in General:
1. Change to either French or Tagalog
2. Navigate to Feedback Explainer or Suggest an Update - Change name or other details
- [ ] Observe that the X button is not cut off.

**Comment by rasmus-storjohann-PG** [comment]
Fixed
