### ISSUE TITLE
Change name or other details - suggest an update should put the text input in focus

### ISSUE THREAD

**Issue by tomy-pg** [pg-irc/pathways-frontend#1265]
Steps to reproduce:
1. On the `Change name or other details` screen click on `Suggest an update` on any service detail
- [ ] observe that the keyboard does not open and the text input is not on focus
2. Click on the Suggest an update again
- [ ] observe that the keyboard opens and the text input is on focus

The expected behaviour is that by clicking `Suggest an update` that the keyboard shows up right away and the text input is in focus.

### Acceptance Criteria 
- [ ]  clicking `Suggest an update` puts the text input in focus and the keyboard shows up on screen

### Steps for QA: 
1. On the `Change name or other details` screen click on `Suggest an update` on any service detail
- [ ] observe that the keyboard opens and the text input is on focus

**Comment by rasmus-storjohann-PG** [comment]
This story has a tight time box on it, if it takes too long to fix, this story is out of scope for the feedback point release and will be fixed as part of the organization release

**Comment by rasmus-storjohann-PG** [comment]
So this could be made even better:
* Go to the "Change name or other details"
* Fill in some text in one field
* Click to fill in some text in a different field
* Observe that it takes two clicks to shift the focus, the first one removes focus from the first field, the second click gives focus to the second field
* Expected is that the focus will shift from the first to the second field with one click on the second field

**Comment by rasmus-storjohann-PG** [comment]
Final issue is too low priority to fix, closing this out
