### ISSUE TITLE
Adding/removing a service bookmark should not scroll screen back to the top

### ISSUE THREAD

**Issue by jparlina** [pg-irc/pathways-frontend#1275]
When adding or removing a bookmark on a service, the screen should not scroll to the top. It's confusing for users. 

### Acceptance Criteria 
- [ ]  Select a topic
- [ ]  Click "Find related services near me"
- [ ]  Scroll down the list of services and bookmark a service

### Steps for QA: 
1. Select a topic
2. Click "Find related services near me"
3. Scroll down the list of services and bookmark a service
- [ ] The screen should stay at the service that you just bookmarked, not scroll back up to the top of the list
4. Remove the bookmark
- [ ] The screen should stay at the service that you just bookmarked, not scroll back up to the top of the list

**Comment by ian-lin-PG** [comment]
The bookmarking still occasionally shift the user to a different place on the list. As @tomy-pg have discussed with me, different drag action seem to register the offset or not leading to this inconsistent behaviour. Not closing this issue yet.

**Comment by rasmus-storjohann-PG** [comment]
So the solution is not perfect, but I don't think fixing this is going to be high priority now. Closing this issue, and if this comes up as a bug a new issue should be created.
