### ISSUE TITLE
Close button on feedback headers adds path to history stack instead of going back

### ISSUE THREAD

**Issue by tomy-pg** [pg-irc/pathways-frontend#1276]
1. Go to any feedback screen.
2. Press on the close button
3. Click back on the service detail screen or on the Android built in back button
4. Notice that you do not go anywhere
5. Click the back button again
6. You are then re-routed to the previous services list

### Acceptance Criteria 
- [ ]  close button does not add path to history stack

### Steps for QA: 
1.  Follow above description and see that you go back to services list on first back button click

**Comment by rasmus-storjohann-PG** [comment]
Back button does what's expected in the feedback flow.
