### ISSUE TITLE
Android location permissions: Allow only while using the app does not work

### ISSUE THREAD

**Issue by tomy-pg** [pg-irc/pathways-frontend#1288]
When users choose this permission, the app does not provide valid location data and brings up the `Enable location services screen`.

### Acceptance Criteria 
- [ ]  When this permission is granted, location data is provided.

### Steps for QA: 
1.

**Comment by rasmus-storjohann-PG** [comment]
There should be a simpler fix to this than changing this permission. Spend some time looking into why this stopped working
