### ISSUE TITLE
explicitly add ACCESS_BACKGROUND_LOCATION to Android permissions 

### ISSUE THREAD

**Issue by tomy-pg** [pg-irc/pathways-frontend#1289]
Without adding ACCESS_BACKGROUND_LOCATION to Android permissions in `app.json`, location permissions on Android devices only give users two options: _Allow only while using the app_ and _Deny_. Currently if _Allow only while using the app_ does not properly provide us with correct location data. See #1288.

### Acceptance Criteria 
When prompted to give location permissions, Android users have the choice of 3 options
- [ ] Allow all the time
- [ ] Allow only while using the app
- [ ] Deny

### Steps for QA: 
1.

**Comment by ian-lin-PG** [comment]
PASS staging QA: 1.51.0
