### ISSUE TITLE
Upgrade Client packages including Expo 39

### ISSUE THREAD

**Issue by ian-lin-PG** [pg-irc/pathways-frontend#1291]
Upgrade expo to 39.

### Acceptance Criteria 
- [ ]  

### Steps for QA: 
1.  `rm -rf node_modules`
2. `yarn`
3. `yarn cbt`
4. `expo client:install:ios`
5. `yarn start -c`

**Comment by tomy-pg** [comment]
Tested on both Android / IOS Staging version 1.51 - PASS
