### ISSUE TITLE
Footer disappears on other screens when service is bookmarked

### ISSUE THREAD

**Issue by tomy-pg** [pg-irc/pathways-frontend#1298]
See video [here](https://drive.google.com/file/d/1wm0dznVz3WHrO6dZiS4d3rxjckzeuTi5/view?usp=sharing)

1. Notice that when a user bookmarks a service **while** the header and footer are hidden from animation, the header and footer reappear.
2. After this, if a user navigates to a different seen either by using the android hardware back button or the footer navigation buttons, the footer does not initially appear on that screen

**Correction**
This occurs on both platforms. This does not require a user to have an Android back button, rather, a user just needs to navigate to a different page to reproduce this error.

### Acceptance Criteria 
- [ ]  When a user bookmarks a service, the state of the animation persists.
- [ ]  When a user navigates to a different screen after bookmarking, the footer appears.

### Steps for QA: 
1.  Follow the steps outlined in the video seen above
- [ ] Ensure the footer no longer disappears

**Comment by tomy-pg** [comment]
@Elvislogan could you QA this?

**Comment by brandon-PG** [comment]
This issue was not reproducible on iOS or Android.
