### ISSUE TITLE
Keeps re-appearing: Failed building JavaScript bundle. Unable to resolve "./lib/application" from "App.js"

### ISSUE THREAD

**Issue by tomy-pg** [pg-irc/pathways-frontend#1300]
Should be top priority as this is affecting client side development productivity.

Running the following commands seems to temporarily fix this problem but this problem eventually re-appears:
```
rm -rf node_modules
yarn
yarn global add expo-cli
expo client:install:ios
expo client:install:android
```
Some clues:
Appears to be a problem that emerged when we upgraded Expo to SDK 39. 
Appears to be that our `./lib/` directory is empty sometimes. Could be related to `tsconfig`
It may also be related to incremental builds, try to delete `tsconfig.tsbuildinfo` and rebuild

### Acceptance Criteria 
- [ ]  This issue is fixed and does not reappear. Probably by refining exactly what `year clean` deletes, it probably deletes a file that should be kept.

### Steps for QA: 
1.

**Comment by rasmus-storjohann-PG** [comment]
Closing as fixed, now that yarn clean does what it needs to do
