### ISSUE TITLE
Push Notification : SNAPP Information Page. 

### ISSUE THREAD

**Issue by DenizASC** [pg-irc/pathways-frontend#1302]
Describe the issue and expected behaviours. If this is a bug, describe the steps to reproduce the problem, what you observe, and what you expected to observe.

Push notification text: Want to connect with a local professional in your field? Join our new program called Snapp! For more information, click...

Page: 
**Title:** Connect with a local professional in your field
**Body:** New to Canada and want to build your professional network? Snapp matches newcomers with local professionals to share employment advice. Snapp is a pilot program by PeaceGeeks. 
[Register to participate](https://bit.ly/2TgVvDs)
**Button or Link** "Register to participate" goes to https://bit.ly/2TgVvDs (forwards to https://snapp.peacegeeks.org/)
**Timing**: Thu Oct 29 3:30PM
### Acceptance Criteria 
- [x] Push notification directs the user to the Snapp Info Page

### Steps for QA: 
1.  Push notification click.
2. The link on the page goes to Snapp website.

**Comment by DenizASC** [comment]
The link should be: https://bit.ly/2TgVvDs

**Comment by tomy-pg** [comment]
Notifications sent to users on October 29, 2020.
