### ISSUE TITLE
Add Google Analytics tag to AA.ca pages

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1303]
We want to understand better the use of the aa.ca website. 

From our marketing consultants:

If possible we recommend if you or another team member of PeaceGeeks can insert a Google Tag Manager (GTM) in the back-end of the website ArrivalAdvisor.ca. The code and instructions are attached, the GTM will allow us to track more in depth users’ journey and behavior. With the current reporting we are able to see the page views, attribution, time spent on a page, bounce rate etc.. and with the  GTM we will be able to collect even more data.

Please let us know once it is installed and if you have any technical issues let us know and we’ll be happy to help.

### Steps for QA: 
Currently we don't get analytics data for a user doing this: Go to the AA website, click on the buttons to go to the Apple or Google store to install our app on their device. The mechanism for getting analytics for this is google tag manager. We already use that tech for other things I think.

### Acceptance Criteria 
- [x]  Google tags are added to all the pages on aa.ca, see [here](https://developers.google.com/tag-manager/quickstart) and [here](https://docs.google.com/document/d/1mOyQxIvpiq93gbQ3sZxOICcnaT5k9H2BHhk-MBNUSsI/edit)
- [x]  When a user clicks on the button to download the app to their device, analytics data will reflect this.

![image](https://user-images.githubusercontent.com/32307781/123321884-66f89380-d4e8-11eb-9817-71b3704c18ce.png)

**Comment by tomy-pg** [comment]
@rasmus-storjohann-PG I am not sure how to review this

**Comment by alysha-PG** [comment]
Yep, we can see exits to apple app store and exits to google play store on Google analytics.
