### ISSUE TITLE
Review and update SWIS and school disctrict data in the app

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1304]
- [ ] Export data from 211 dataset regarding these kinds of services
- [ ] Review to find missing data
- [ ] Add in missing data

This will be imported into the AA dataset for the Organizations release.

**Comment by rasmus-storjohann-PG** [comment]
This is 1/3 done says Jean, we'll get a link once it's done

**Comment by jparlina** [comment]
[Here](https://docs.google.com/spreadsheets/d/1J7yRi1s-Ctk-zRUHvsgN3t7ZUhYKqaGZ586WDQLK718/edit#gid=597963664)'s the list of service records that will need to be created by copying the school district org records from bc211 LATEST csv. I emailed updates@bc211.ca on Dec 3, 2020 regarding information that need to be updated. Will need to confirm these updates when we get the next bc211 csv. 

@rasmus-storjohann-PG @ian-lin-PG - Next steps as noted on the spreadsheet after your review of the data: 
1. Create a service record for each row; use AAResourceID as primary key (i.e. ParentAgencyNum-s1)
2. Copy the LATEST bc211 org data based on ParentAgencyNum into the corresponding newly-created service record
3. Make sure these service records can also be found under **Topic Search** "Registering your child in a public school" based on location AND not just under keyword search.

**Comment by ian-lin-PG** [comment]
I can confirm the SWIS data from bc211 csv have made it to the database.

**Comment by jparlina** [comment]
Thanks @ian-lin-PG! There will be at least one new SWIS record to be created as per my email request to bc211 last week. So we'll need to update and confirm the SWIS data based on the latest csv.

**Comment by ian-lin-PG** [comment]
Keeping this issue open. What I found is that a lot of libraries offer a service or two which meant that they weren't duplicated by Theresa's csv. The services referenced are much more specific in scope than what the school district as a whole can provide. As such more effort will be put into importing Jean's csv.

**Comment by ian-lin-PG** [comment]
@jparlina I checked the school district and SWIS are in Richmond and Burnaby. Close the issue after your QA.

**Comment by jparlina** [comment]
Tested on Staging V1.61.0, Server V1.3.50 on iOS: 

- [x] Used Easter egg to set location to SWIS at Vancouver School Board address 1000 59th AVE E, Vancouver, BC V5X1Y7 (49.215647, -123.084316). Searched under topics "Registering your child in a public school" and "Contact workers at your local settlement agency, SWIS at Vancouver School Board shows up at the top of the search results. **PASS**
- [x] Used Easter egg to set location to SWIS at Surrey School District address 7525 KING GEORGE BLVD , Surrey, BC V3W5A8 (49.139600, -122.846028). Searched under topics "Registering your child in a public school", SWIS at Surrey School District shows up at the top of the search results, followed by Surrey School District. **PASS**
- [x] Searched under topic "Registering your child in a public school" in Burnaby, Burnaby School District (which only has an org record in bc211 database) shows up at the top of the search results. **PASS**
