### ISSUE TITLE
Feedback 2.0: Mocks

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1306]
### Acceptance Criteria 
- [x]  We have mocks for FEEDBACK 2.0 - Services feedback: comment
- [x]  We have mocks for FEEDBACK 2.0 - Services feedback: rating, (thumbs up/down), or emojis for user’s reactions to the usefulness of certain content
- [ ]  We have mocks forFEEDBACK 2.0 - newcomers commenting on their settlement experience

### Steps for QA: 
1.

**Comment by cherrielam** [comment]
Based on our discussion Dec. 15, 2020 - we are focusing on Services Feedback, not Topic Feedback. The Services Feedback design is now here: https://zpl.io/aMy3Gdo

**Comment by cherrielam** [comment]
The last acceptance criteria, based on discussions between @Melanie-PG, I, and Deniz, is considered no longer relevant

**Comment by cherrielam** [comment]
Hi all - based on discussions today, here are two versions of the Feedback Flow: one with the "unlimited reviews" and one with persisted review: https://www.figma.com/file/0Fhv64lm9QeljUKOvaJ128/AA-Feedback-2.0?node-id=459%3A1576 - see "FOR PRODUCTION - Services Feedback"
