### ISSUE TITLE
Add SIN form link to the SIN topic in AA

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1307]
There is a form for getting your SIN number. Have the SIN number topic in BC in AA link to this form.

At the bottom of current SIN number topic, add this line:
Apply for a SIN number online: https://sin-nas.canada.ca/en/Sin/

For the other 7 languages, see translated strings [here](https://docs.google.com/spreadsheets/d/117uF7Gxr_2pZNxXrHji4o4u8S4l2ObctbQ7YULULROw/edit?usp=sharing)!

**Comment by rasmus-storjohann-PG** [comment]
Need a little bit of design from Cherrie

**Comment by Kaylee-PG** [comment]
I can confirm that the text from the translated string forms align with each language and all of the links in each language viewing open to the correct SIN application form.
