### ISSUE TITLE
Update copy following changes to the questionnaire

### ISSUE THREAD

**Issue by jparlina** [pg-irc/pathways-frontend#1311]
On both production V1.46.2 and Staging V1.52.0, the dialog "New topics. have been recommended based on your answers! See recommendations" doesn't show up after answering Q2 although the recommended list gets updated based on the answers. 

### Acceptance Criteria 
- [ ]  The dialog "New topics have been recommended based on your answers! See recommendations" should show up for every instance where the answer(s) to any of the questionnaire changes the recommended list. 
- [ ] New copy: "Your recommended topics have been updated based on your answers"

### Steps for QA: 
1.  Click "Answer questions" button on the home screen
2. Select an answer or skip Q1
3. Select one or more answers under Q2
4. Click X at the top right corner to close the Questionnaire 
5. The dialog "New topics have been recommended based on your answers! See recommendations" should pop up then you click "See recommendations" button to see the updated recommended list.

**Comment by rasmus-storjohann-PG** [comment]
This is as expected, but it's tricky. Try these steps:

1. Delete all data off the app
2. Go to the home screen, observe that "Apply for Social Insurance Number (SIN)" shows up in the list of things to do right away
3. Click Answer Questions
4. Skip the first question
5. On the second question, mark that "I have a Social Insurance Number"
6. Click X, observe that you do not see the dialog (this is counter-intuitive but I would argue, correct behaviour)
7. Go to the home screen, observe that "Apply for Social Insurance Number (SIN)" no longer shows up in the list of things to do right away

The thing is that Q2 is special, in that marking questions *removes* recommended topics, doesn't add them. That is why you don't get the dialog. 

I'm open to talk about how we can make this clearer.

**Comment by rasmus-storjohann-PG** [comment]
New copy: "Your recommended topics have been updated based on your answers", button still says "See recommendations"

**Comment by tomy-pg** [comment]
Moving this back from In Review to product team backlog.

**Comment by rasmus-storjohann-PG** [comment]
Related to #1539
