### ISSUE TITLE
Left alignment on dynamic content

### ISSUE THREAD

**Issue by cherrielam** [pg-irc/pathways-frontend#1313]
The title and the body text in the dynamic content card is misaligned, and should be realigned so the left sides match up.

![IMG_6205.PNG](https://images.zenhubusercontent.com/5823860ee40e5714b1700133/0bd0bc35-63e6-416b-a397-249d3b83e607)

### Acceptance Criteria 
- [ ]  The title and body text on the dynamic content card are aligned on all devices

### Steps for QA: 
1.

**Comment by tomy-pg** [comment]
@ian-lin-PG taking this issue from you

**Comment by ian-lin-PG** [comment]
Pass with release 1.56.1
