### ISSUE TITLE
Remove slight line on bookmarks page

### ISSUE THREAD

**Issue by cherrielam** [pg-irc/pathways-frontend#1314]
There is a slight beige border or line on the left and right sides of the "Topics" and "Services" tabs on the Bookmarks page. Please remove border or change to white.

See image below:
![IMG_6206.PNG](https://images.zenhubusercontent.com/5823860ee40e5714b1700133/97d78498-06c6-4aed-80f9-092ace7d1b42)

This appears on iPhone XS, not sure about other devices

### Acceptance Criteria 
- [ ]  The slight beige border on the left and right sides of "Topics" and "Services" tabs on the Bookmarks page are no longer visible on all devices

### Steps for QA: 
1. Navigate to Bookmarks and Organization page and ensure the borders are no longer there

**Comment by ian-lin-PG** [comment]
![Screenshot_20210104-112443](https://user-images.githubusercontent.com/52009863/103571429-b508d480-4e7f-11eb-8dec-983e7d416626.jpg)
Line no longer visible behind the tabs. Passed QA 1.56.1
