### ISSUE TITLE
Change expected address schema for id should expect string over integer

### ISSUE THREAD

**Issue by tomy-pg** [pg-irc/pathways-frontend#1328]
The API response for topic services in invalid now that we generate a hash of type `string` for address_ids as part of the iCarol to Open referral csv conversion. 

In Tomy's issue 564, id was explicitly added to the `Address` model to expect a string. The client has not been changed to reflect this and AJV Schema validation for Addresses expects address id's to be integers. 

Here is the warning message:
`data[0].location.addresses[0].address.id should be integer`

### Acceptance Criteria 
- [ ]  Address schema expects address id to be of type string

### Steps for QA: 
1.

**Comment by ian-lin-PG** [comment]
Topic services work normally in the staging app. Pass 1.56.1
