### ISSUE TITLE
Upgrade Expo to SDK 40

### ISSUE THREAD

**Issue by tomy-pg** [pg-irc/pathways-frontend#1333]
### Acceptance Criteria 
- [x] Upgrade to Expo SDK 40  

### Steps for QA: 
1.

**Comment by tomy-pg** [comment]
This upgrade contains a regression that breaks iOS devices when we try to flip text orientation and reload the app.

**Comment by ian-lin-PG** [comment]
The aforementioned issue is tracked in #1388. A work around with sleep time is being used for the time being.
