### ISSUE TITLE
Create service entries for organizations without services to show on Arrival Advisor

### ISSUE THREAD

**Issue by ian-lin-PG** [pg-irc/pathways-frontend#1335]
Importing the bc211 through the csv currently results in 3000 organization without services when compared to 76 from importing through xml. This is due to the xml format having a constraint that enforces all organization to have a service. This is accomplished through duplicating the organization information to create a service with the service_id of the organization_id it is copied from.

The csv data does not have the same constraint which means we may end up with much less services when compared to the previous xml import. Until we can query and access organization data to the same extent as service data on our app, our stop gap measure is to create a duplicate service entry for organization without services. This is so that organization data are still somewhat accessible through the app.

We also need to be mindful of the additional services that Jean has created for existing organizations. The primary issue may be duplicate services from our automatic service creation and the ones Jean manually creates. Based on this observation, we should consider the service_id of both sources carefully to avoid duplicates.

### Acceptance Criteria 
- [ ]  Most of the organization from here https://docs.google.com/spreadsheets/d/1uT7F9xRpczgO9vYEcC7NapbLkmco8eqyAFhfK_2BsJo/edit#gid=746884071 should be accessible on the app.

### Steps for QA: 
1.

**Comment by jparlina** [comment]
Based on discussion with @rasmus-storjohann-PG and @ian-lin-PG on Jan 11, 2021, once the service records are created by duplicating the corresponding org records, we'll need to ensure that those service records show up on the app under relevant topics.

**Comment by ian-lin-PG** [comment]
A more updated list of organization without services can be found [here](https://docs.google.com/spreadsheets/d/1gglZoIGiNqf3F_MIGetNOAL75DuGQRJN18TtHvhf9po/edit#gid=1096190107).  Random sampling of the data showed all the entries sampled are included in the dataset. This also covers many libraries that didn't have any branches listed. PASS 1.59.0
