### ISSUE TITLE
UX Polish: Inconsistent behaviour between unbookmarking topics and services

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1343]
Repro steps:
* Open the **Staging** app, make sure there are some topics that are bookmarked, and some services that are bookmarked
* Navigate to the bookmarks page
* On the topics tab, unbookmark a topic. Observe that the topic remains visible in the list, but with an open bookmark icon
* On the service tab, unbookmark a service. Observe that the service disappears from the list
* Expected is that the behaviour between both tabs is consistent. Probably the item disappearing from the list is the least surprising, in which case it would be super if there is an "Undo" CTA on the "Bookmark removed" toast notification

### Acceptance Criteria 
- [ ]  Behaviour of both bookmarks should match — see **Production** app for the what the appropriate behaviour should be. Unbookmarking topics and services should have them disappear from the list, and bring up the "Bookmark removed" toast. 
There is currently no "Undo" on Toasts. If we decide to do this, that can be a separate issue.

**Comment by cherrielam** [comment]
This seems to be a new issue that only exists in Staging and not in Production

**Comment by rasmus-storjohann-PG** [comment]
Fixed
