### ISSUE TITLE
Build client UX for Review this service

### ISSUE THREAD

**Issue by tomy-pg** [pg-irc/pathways-frontend#1344]
[Mocks are in Zeplin](https://zpl.io/aMy3Gdo), also available on [Figma (under FOR PRODUCTION - Service Feedback)](https://www.figma.com/file/0Fhv64lm9QeljUKOvaJ128/AA-Feedback-2.0?node-id=529%3A611)

Here is a **[Figma prototype](https://www.figma.com/proto/0Fhv64lm9QeljUKOvaJ128/AA-Feedback-2.0?node-id=529%3A2476&viewport=452%2C476%2C0.2726389169692993&scaling=scale-down)** to see the flow/interaction between the pages

There is **additional copy** added for "Learn more" > Services listed on Arrival Advisor page. "How is PeaceGeeks and bc211 using the information collected?" section is being updated to the following:

> **What happens when I “suggest an update” on the information listed about a service?** 
> 
> When you suggest an update on service information, PeaceGeeks collects and shares with bc211 your suggestions, as well as the name of the service you’re commenting on. We record the date and time that the suggestion was received. If you choose to provide your email address, we collect that so that PeaceGeeks and bc211 may contact you regarding your suggested change. If you work at the service provider organization, you will have the option to share your full name, job title and organization name. It is useful for us to know that the suggestion comes from someone who is familiar with the organization’s work. See also PeaceGeeks’ general [privacy policy](link) and bc211’s [privacy page](link).
> 
> **How does PeaceGeeks use my feedback on services?**
> 
> You can give feedback about a service by selecting the smiley faces at the bottom of a service page and providing an optional comment about your experience. When you submit this feedback, PeaceGeeks collects and reviews it, and then shares your feedback with the service provider organization. We also record the date and time the feedback was received. See also PeaceGeeks’ general [privacy policy](link).

### Acceptance Criteria 
- [x] `How was your experience with [this service]` (smileys) can be seen in the service detail screen
- [x] After clicking on one of the smileys, the user is navigated to a new screen where they can optionally leave a comment
- [x] When clicking on the nth smiley (n=0..3), after navigating to the new screen, the smiley is selected, i.e. the app remembers which smiley was clicked in the first screen
- [x] Clicking on the 'X' returns the user back to their previous page
- [x] Their rating is not sent to the database if they click on the 'X'
- [x] `How was your experience with [this service]` no longer appears in any service' service detail screen that they have previously reviewed.

### Steps for QA: 
1. Open up any service detail page and click on one of the smileys
- [x] Notice that you are navigated to a service review screen
- [x] You are immediately prompted to leave an optional comment
2. Click submit, this is not wired up yet.
3. Click on the X button on the top right corner
- [x] Notice a modal pop up giving you the option to continue editing or discard changes
4. Click discard
- [x] Notice you are navigated back to the same service review screen
- [x] Notice that you no longer see the smiley face ratings
5. Refresh the app on your phone
6. Go back to the same service detail page you were on previously
- [x] Notice that you do not see the smiley face ratings

**Comment by ian-lin-PG** [comment]
PASSED staging 1.59.0
