### ISSUE TITLE
Adjust release process and environment variables for two Airtables

### ISSUE THREAD

**Issue by tomy-pg** [pg-irc/pathways-frontend#1346]
The variable AIRTABLE_TABLE_ID will need to be renamed as we will be using two different tables in Airtable for Feedback and Feedback 2.0

### Acceptance Criteria 
- [x]  variables in app `env` are adjusted for use of two different tables for Feedback and Feedback 2.0
- [x] These changes are reflected in [pathways-deploy](https://github.com/PeaceGeeksSociety/pathways-deploy) and [.env.example](https://github.com/pg-irc/pathways-frontend/blob/develop/.env.example)

### Steps for QA: 
1.

**Comment by ian-lin-PG** [comment]
PASS QA 1.60.0
