### ISSUE TITLE
Regression: Clicking Related Topics keeps the Scroll Position

### ISSUE THREAD

**Issue by cherrielam** [pg-irc/pathways-frontend#1350]
When you go into a Topic and click Related Topics, opening the new Topic should bring the user back to the top. Currently on **Staging**, the keeps the scroll position for the user, which is confusing as it is unclear to the user that the page has changed.

This is a new issue that exists in **Staging**, the correct behaviour is currently in **Production**

### Acceptance Criteria 
- [ ]  Clicking a Related Topic brings the user to the New Topic at the top of the page (does not keep scroll position)

### Steps for QA: 
1.  On the home page scroll down the page and stop at a random point.
2. Navigate to another screen using the footer.
3. Navigate back to the home page
- [x] See that you are brought back to the same position in the homescreen you were on previously. 
4. Select any topic on the home page. 
5. Once of the topic detail page, scroll down as far as you can and select a new topic from the `Related Topics` list
- [x] See that you are brought to the very top of the screen as soon as you navigated to the new topic detail page.
6. Bookmark at least 10 topics
7. Navigate to the topics bookmarks page
8. Scroll up and down
9. Unbookmark any topic
- [x] Ensure that the topic you unbookmarked is removed from the screen
- [x] Ensure that you stay somewhat in the same area of the screen you were on before unbookmarking (this varies a bit since the size of the list changes which affects the offset a little bit)

**Comment by ian-lin-PG** [comment]
PASS QA 1.62.0
