### ISSUE TITLE
Add google analytics to review functionality

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1355]
Describe the issue and expected behaviours. 

### Acceptance Criteria 
- [x]  We know when someone clicks a smiley face even if they don't hit Submit
- [x] We know how many users hit smiley face without hitting Submit

### Steps for QA
1. Navigate to any service detail page. Click on any smiley face.
2. Go to GA Staging > Behaviour > Events > Overview and search for `Event Category: Rating` or `Event Action: RatingChosen`.
- [x] See that the service and rating has been tracked as part of this event. _1 for frownie, 2 for neutral and 3 for smiley_
3. For the same service or a different service, submit the review on the `Service Review Screen`
4. Go back to GA Staging > Behaviour > Events > Overview and search for `Event Category: Review` or `Event Action: SubmitReview`.
- [x] Notice that the service you were on has been tracked by this event.

**Comment by tomy-pg** [comment]
By the acceptance criteria 

> We know how many users hit smiley face without hitting Submit

It seems like I will need to track submit events so we can do a calculation based around unique events to get this figure for reporting.

`Unique Rating Chosen events - Unique Submit Review Events`

**Comment by ian-lin-PG** [comment]
PASS QA 1.62.0
