### ISSUE TITLE
UX inconsistency: Button disabled when it should be enabled

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1356]
Open any service on the app. Click "Suggest an update".  Click "This service no longer exists". Observe that ux says "Provide any additional information (optional)". Also observe that the Submit button is disabled until additional information field is not empty, implying that the additional feedback is required.

### Acceptance Criteria 
- [x]  The submit button is always enabled

**Comment by ian-lin-PG** [comment]
PASS QA 1.62.0
