### ISSUE TITLE
Translation issue: Onboarding text in English when French is expected

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1366]
Tested on iOs:

### Acceptance Criteria 
- [x]  clear all memory from the app, so it will launch the onboarding on start
- [x] Select French as language on splash screen
- [x] Click next
- [x] Observe that some of the text appears in English
- [x] Expected is that all of the text is in French

### Steps for QA: 
1.  
![Screen Shot 2021-02-08 at 11 43 06 AM](https://user-images.githubusercontent.com/32307781/107272713-f6524e00-6a02-11eb-95d2-c124d2a0c9e6.png)

**Comment by tomy-pg** [comment]
I will put up a fix to address this. Our `messages.js` are way behind on `develop`.

**Comment by tomy-pg** [comment]
This is not complete until we add updating messages.js as part of our weekly staging release process.

**Comment by ian-lin-PG** [comment]
QA PASS 1.62.0
![Screenshot_20210219-112001](https://user-images.githubusercontent.com/52009863/108551432-cded0e00-72a4-11eb-84ff-3882500baf73.jpg)
![Screenshot_20210219-112024](https://user-images.githubusercontent.com/52009863/108551435-cf1e3b00-72a4-11eb-960a-e511b8365de6.jpg)
![Screenshot_20210219-112029](https://user-images.githubusercontent.com/52009863/108551444-d0e7fe80-72a4-11eb-94b7-ef54e5d98a3b.jpg)
![Screenshot_20210219-112034](https://user-images.githubusercontent.com/52009863/108551454-d3e2ef00-72a4-11eb-906d-4671356969a0.jpg)
