### ISSUE TITLE
flatlistRef in service list is crashing app

### ISSUE THREAD

**Issue by tomy-pg** [pg-irc/pathways-frontend#1373]
- open up any topic service detail page
- change the location
- you will see an error about `flatlistRef.current.scrollToOffset` being null.

I believe we need to clean-up this ref in our useEffects to fix this.

### Acceptance Criteria 
- [x]  App no longer crashes when changing location

### Steps for QA: 
1.

**Comment by ian-lin-PG** [comment]
PASS QA 1.62.0
