### ISSUE TITLE
Search input bars do not clear in expanded input state

### ISSUE THREAD

**Issue by tomy-pg** [pg-irc/pathways-frontend#1379]
1. Enter a search term and search location in search
2. Expand the input bars
3. Clear both inputs
4. Navigate to another screen
5. Go back to the search screen
You will see the previously cleared inputs again.

### Acceptance Criteria 
- [x]  Cleared inputs stay cleared.

### Steps for QA: 
1.

**Comment by ian-lin-PG** [comment]
PASS QA 1.62.0
