### ISSUE TITLE
Show name of the algolia index used in about Arrival Advisor screen

### ISSUE THREAD

**Issue by ian-lin-PG** [pg-irc/pathways-frontend#1382]
Algolia is paramount for our search experience. We need to keep in mind which index are being used and by which version of the app. One way to do this is to show the algolia index in about arrival advisor.

### Acceptance Criteria 
- [ ]  Open the app, open the about page, observe that the name of the algolia index the app is using appears in the page.

**Comment by rasmus-storjohann-PG** [comment]
A better way might be to compute the name of the algolia index to use from the version string. Does that cause a bad interdependence between these two things? Probably..

**Comment by ian-lin-PG** [comment]
Algolia index is added.
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-05-28 at 11 37 05](https://user-images.githubusercontent.com/52009863/120028096-18b7a980-bfa9-11eb-8bd4-2fbeb016fe52.png)

**Comment by brandon-PG** [comment]
Change index descriptor.
![Screenshot_20210531-104449_Expo Go](https://user-images.githubusercontent.com/84804716/120227304-c58a6480-c1fd-11eb-8e53-7792700b40a4.jpg)

**Comment by rasmus-storjohann-PG** [comment]
String appears correctly in the staging app, closing this as done
