### ISSUE TITLE
iOS Distribution Certificate will no longer be valid in 30 days

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1383]
Dear Rasmus Storjohann,

Your iOS Distribution Certificate will no longer be valid in 30 days. To generate a new certificate, sign in and visit Certificates, Identifiers & Profiles.

Certificate: iOS Distribution
Team ID: FFJ6MN3GTK

To learn more about expired certificates, visit the certificates support page.

Best regards,
Apple Developer Program Support

**Comment by tomy-pg** [comment]
Production release successfully used the new certificate. Closing.
