### ISSUE TITLE
Text Disappears Once "Learn More" is clicked

### ISSUE THREAD

**Issue by Melanie-PG** [pg-irc/pathways-frontend#1385]
When user is on the Leave Feedback page and types something in the textfield under "Tell us more about your experience:", the text disappears once the user clicks on "Learn more" on the bottom.

Issue found on iPhone XS.

1.  User has typed something in the text field.
![IMG_1137](https://user-images.githubusercontent.com/76975404/108548727-1a364f00-72a1-11eb-9278-1fcc8335db07.PNG)

2.  User goes to click on Learn More.
![IMG_1138](https://user-images.githubusercontent.com/76975404/108548876-4356df80-72a1-11eb-9504-d4ba46ff7ecf.PNG)

3.  User exits out of Learn More, and then the text is gone. 
![IMG_1139](https://user-images.githubusercontent.com/76975404/108548935-5bc6fa00-72a1-11eb-84c7-0314626963d2.PNG)

### Acceptance Criteria 
- [x] Learn more content appears in a modal dialog.

**Comment by ian-lin-PG** [comment]
I am proposing we have the discard modal to show up if the comment is filled and they try to click on the learn more button.

**Comment by ian-lin-PG** [comment]
@Melanie-PG @cherrielam I tested this change. Tomy did not change the UI to a modal but the expected behaviour of text remaining is there. This issue can be merged or more discussion is needed?

**Comment by cherrielam** [comment]
Issue can be merged! @ian-lin-PG

**Comment by alysha-PG** [comment]
Expected behavior of text remaining is there in staging app. Please merge @ian-lin-PG
