### ISSUE TITLE
No bottom nav on Submit Feedback screen

### ISSUE THREAD

**Issue by cherrielam** [pg-irc/pathways-frontend#1386]
There should be no bottom nav shown on the Submit Feedback screen:

(Staging 1.62.0 on iPhone XS)
![IMG_7332.PNG](https://images.zenhubusercontent.com/5823860ee40e5714b1700133/fee5f0b4-0b63-441c-a008-becbefbced54)

(Figma mock)
![Screen Shot 2021-02-19 at 10.54.58 AM.png](https://images.zenhubusercontent.com/5823860ee40e5714b1700133/91649dc7-1730-44b5-b4a4-8942717a23f0)

### Acceptance Criteria 
- [ ] There is no bottom nav on Submit Feedback page

### Steps for QA: 
1.

**Comment by tomy-pg** [comment]
Staging 1.63.0: PASS
