### ISSUE TITLE
Submit button floats 

### ISSUE THREAD

**Issue by Melanie-PG** [pg-irc/pathways-frontend#1387]
The "Submit" button on the Feedbacks page has different positioning depending on how the page was accessed.

When the user clicks on "Was this service helpful?" button on the service card, the submit button on the following Leave Feedback page is significantly closer to the bottom. When the user clicks into the Service Details page, then scrolls to the bottom to access "How was your experience with XYZ Org", the button is higher up. 

Found on iPhone XS.

Click on "Was this service helpful"
![IMG_1148.PNG](https://images.zenhubusercontent.com/5ff3960df5b0401a97dc20f1/039f3196-9c31-4e3c-9dd0-a6e8472267de)

Notice how the Submit button is closer to the bottom.
![IMG_1149.PNG](https://images.zenhubusercontent.com/5ff3960df5b0401a97dc20f1/16ace440-d3e0-42b0-b3e1-bf1ee9e994ac)

Now, access the feedbacks page via the Service Details Page.
![IMG_1150.PNG](https://images.zenhubusercontent.com/5ff3960df5b0401a97dc20f1/9f54551e-3be6-41fb-8acf-7a7298132a59)

Notice how the Submit button is now higher up from the bottom. 
![IMG_1151.PNG](https://images.zenhubusercontent.com/5ff3960df5b0401a97dc20f1/a9190a4f-7aa4-4e86-a297-8a528099c5c6)

Spacing under the "Submit" button should be consistent with the spacing under "Submit" in "Suggest edits":

![IMG_7340.PNG](https://images.zenhubusercontent.com/5823860ee40e5714b1700133/eb18c846-51f0-456c-ac8b-eb4be5e445ac)
![IMG_7339.PNG](https://images.zenhubusercontent.com/5823860ee40e5714b1700133/c7716e4f-8520-4cf8-8d7c-99f8be3031aa)

### Acceptance Criteria 
- [ ] Keep the position of the Submit button consistent. Keep the button lower/closer to the bottom, like when accessed by clicking on "Was this service useful?" button.

### Steps for QA: 
1.

**Comment by tomy-pg** [comment]
This seems to be fixed by #1386

**Comment by Melanie-PG** [comment]
Looks good on my iPhone XS
