### ISSUE TITLE
UX Polish: Font weight too light for "Suggest an Update"

### ISSUE THREAD

**Issue by Melanie-PG** [pg-irc/pathways-frontend#1389]
On Service Details page, font weight is not Black. 

Found on iPhone XS.

![IMG_1154.PNG](https://images.zenhubusercontent.com/5ff3960df5b0401a97dc20f1/d20fc554-df5b-4689-98a8-64b7df314b9f)

### Acceptance Criteria 
- [ ] Change font weight to Black to keep it consistent with button text style.  

### Steps for QA: 
1.

**Comment by rasmus-storjohann-PG** [comment]
Hey @Melanie-PG @cherrielam and @ian-lin-PG Acceptance criteria are ambiguous in this bug. Do you want to change the font colour, font weight or both? There is no such weight as "Black".

**Comment by Melanie-PG** [comment]
Looks better, but is there an extra bold font weight available? If there isn't, this looks fine.

**Comment by cherrielam** [comment]
Agree with @Melanie-PG can we make it the same font-weight as the other links (equivalent to the label "Address", etc.)

**Comment by rasmus-storjohann-PG** [comment]
Done

**Comment by rasmus-storjohann-PG** [comment]
Reopening issue to address font change

**Comment by brandon-PG** [comment]
'Suggest an update' text is only less bold on iOS devices

**Comment by cherrielam** [comment]
Looks good
