### ISSUE TITLE
Increase spacing under "Suggest an update" when Feedback component is gone

### ISSUE THREAD

**Issue by cherrielam** [pg-irc/pathways-frontend#1391]
When the feedback (smiley faces) component is gone, "Suggest an update" is too close to the bottom, making the click target not easily accessible. 
![IMG_7343.PNG](https://images.zenhubusercontent.com/5823860ee40e5714b1700133/bc36be2a-35b2-4e81-9b08-a28dede03445)

Increase the spacing - it should look like this: https://zpl.io/Vqd4wMG - there is a line under "Suggest an update" and additional spacing under that.

### Acceptance Criteria 
- [ ] When the feedback component is gone, the spacing under "Suggest an update" should reflect what is shown here: https://zpl.io/Vqd4wMG
- [ ] Last item of the services details has a line under it

### Steps for QA: 
1.

**Comment by tomy-pg** [comment]
Staging 1.63.0: PASS
