### ISSUE TITLE
Title of Organization should not be in all caps

### ISSUE THREAD

**Issue by cherrielam** [pg-irc/pathways-frontend#1392]
The title of the organization should not be in all caps - just regular case. This is probably a confusion that was caused because the design was mocked for MOSAIC which is an Org name that is in All Caps regularly. Organization names should just reflect what is in the BC211 data.

Eg. below: it should read: Economic Development Society of BC (EDSBC) rather than ECONOMIC DEVELOPMENT SOCIETY OF BC (EDSBC)
![IMG_7345.PNG](https://images.zenhubusercontent.com/5823860ee40e5714b1700133/069005a9-981a-41cc-b639-30d4ef33224a)

See examples of BC211 Org titles:
![Screen Shot 2021-02-19 at 11.58.17 AM.png](https://images.zenhubusercontent.com/5823860ee40e5714b1700133/2b319a86-62d6-4c5a-bf8a-dae761c21978)
![Screen Shot 2021-02-19 at 11.58.38 AM.png](https://images.zenhubusercontent.com/5823860ee40e5714b1700133/0c0aba9f-e327-4307-9f24-c2519c54dfcd)

### Acceptance Criteria 
- [ ]  Organization titles display in regular case

### Steps for QA: 
1.

**Comment by tomy-pg** [comment]
Staging 1.63.0: PASS
