### ISSUE TITLE
Bottom line or border added under tabs

### ISSUE THREAD

**Issue by cherrielam** [pg-irc/pathways-frontend#1393]
There should be a bottom border under tabs (used in Bookmarks and Organization pages) to create better differentiation between the sections.

Currently there is no line under the tabs
![IMG_7331.PNG](https://images.zenhubusercontent.com/5823860ee40e5714b1700133/6490682a-7446-4937-8be7-9d75f85667c1)
![IMG_7345.PNG](https://images.zenhubusercontent.com/5823860ee40e5714b1700133/daa9b1e0-c950-404c-be67-8a6650c3b485)

It should look like:
https://zpl.io/2G13xKd - Orgs Detail
https://zpl.io/2jWK16x - Orgs Services
https://zpl.io/bJXwRgJ - Bookmarks w/ feedback banner (updated)
There is a grey line under the tabs. This should be applied across all tabs in the app

### Acceptance Criteria 
- [ ]  

### Steps for QA: 
1.

**Comment by ian-lin-PG** [comment]
@cherrielam I please review these screenshots for accuracy. The line under organization services exists just a bit harder to tell apart.
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-02-23 at 11 51 58](https://user-images.githubusercontent.com/52009863/108899754-a318f780-75cd-11eb-9b4b-cb8355df1567.png)
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-02-23 at 11 51 53](https://user-images.githubusercontent.com/52009863/108899759-a4e2bb00-75cd-11eb-8f39-69a06d661d05.png)
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-02-23 at 11 51 42](https://user-images.githubusercontent.com/52009863/108899762-a4e2bb00-75cd-11eb-8ca8-798b6de305b2.png)

**Comment by cherrielam** [comment]
@ian-lin-PG this looks great, thanks!

**Comment by tomy-pg** [comment]
Staging 1.63.0: PASS
