### ISSUE TITLE
Scroll position sticks when you open a new organization

### ISSUE THREAD

**Issue by cherrielam** [pg-irc/pathways-frontend#1394]
Whenever a user opens a new organization, the scroll position should return to the top, and the Org Detail should open on the "About" tab.

There are two issues: MOVED TO https://github.com/pg-irc/pathways-frontend/issues/1438
**A) New organizations open in the "Services" tab, which is incorrect. They should open in the "About" tab.**
Steps to recreate issue:
1. Run a Search
2. Open a Service
3. Click the Organization
4. Go to the Organization's "Services" tab
4. Return to the Search (Back or press Search icon)
5. Click a new Service
6. Click the Organization
7. **Organization will open on the "Services" tab** <- this should be the "About" tab.

**B) Scroll position sticks within the Services list when you open a new organization** - [See video](https://drive.google.com/file/d/15WDeCw9jtkL2s5vfuTxq6Cx1kos8qs9R/view?usp=sharing)
Steps to recreate the issue:
1. Run a Search
2. Open a Service
3. Click the Organization
4. Go to the Organization's "Services" tab
5. Scroll down.
6. Click another Service
7. Click that service's Organization
8. **Organization will open on the "Services" tab at the Scroll position from when you Scrolled down earlier.** <- even though this returns the User to the same Organization, because the User has opened the Organization anew (instead of clicking Back), the Organization should open on the "About tab" and the Scroll Position is not saved.
9. Run any kind of Service search (either from topic-services or Search)
10. Click any Service
11. Click their Organization
12. **Organization will always open on the "Services" tab at the saved Scroll position.** <- this should not happen, again, open new Organizations on the "About" tab and do not save the Scroll position

On Staging 1.62.0, iPhone XS

### Acceptance Criteria 
- ~~Whenever a user is opening a new Organization (the user is not returning to the Org Detail page from a Back button), the Org Detail should open on the "About" tab, and the previous scroll position is not saved.~~ <- this is being addressed by #1438

### Steps for QA: 
On topic lists and services list do the following:
1. Scroll down a list
2. Click on a card item that will navigate you away from the screen
3. Click back
- [x] Notice that you return to the previous part of the list you were on.

**Comment by rasmus-storjohann-PG** [comment]
https://reactrouter.com/web/guides/scroll-restoration

**Comment by deniza-pg** [comment]
This is still not behaving as described.

**Comment by cherrielam** [comment]
The scroll position issue is fixed, but there is a minor behaviour thing:

Once you open an organization and go to the "Services" tab, any future organizations you open will only open on the "Services" tab, and you will have to manually switch back to the "About" tab. Then when you open a new organization, it will open on the "About" tab (until you switch to the "Services" tab).

(Steps to reproduce: 
1. Search for and open a service
2. Click Organization
3. Click Services tab
4. Hit the back button (top left) until you get to the Service list
5. Open a different service
6. Click the organization
7. Notice that it opens on "Services" tab <-- **this is not the ideal behaviour. Ideally it should open on "About" tab every time you open a new organization**

Ideally, every time you open a new organization, it opens on the **"About"** tab. However, if this is super complicated, it's not a big issue.

**Comment by cherrielam** [comment]
Oh JK sorry I just noticed that the issue I described above is being addressed by #1438

**Comment by cherrielam** [comment]
Closing this because the scroll issue is fixed :)
