### ISSUE TITLE
Search results stay when clearing the search

### ISSUE THREAD

**Issue by cherrielam** [pg-irc/pathways-frontend#1397]
Currently, the Search results stay when the user presses "X" on the Search bar keyword field (clearing the search). This is a weird experience because when the user returns to the Search page (eg. after browsing Learn, Home, etc.) they will still see the previous search results, but there is no indication in the Search bar of what they were searching in the first place. This causes confusion for the user.

This exists both in Staging and Production

### Acceptance Criteria 
- [ ]  When a user clicks "X" in the Search keyword field, the search clears and the results disappear.

### Steps for QA: 
1.

**Comment by tomy-pg** [comment]
Staging 1.63.0: PASS
