### ISSUE TITLE
Feedback banner should scroll with the results, not sticky

### ISSUE THREAD

**Issue by cherrielam** [pg-irc/pathways-frontend#1398]
The Feedback banner on the Bookmarks page should scroll with the Bookmarked items (like the Search Beta banner on the Search results page), not be sticky.

As seen here in Staging 1.62.0 it is sticky, but it should actually scroll along with the Bookmarked items
![IMG_7391.PNG](https://images.zenhubusercontent.com/5823860ee40e5714b1700133/7d1cd99b-b5e0-44e3-ae9f-66ca8d784d97) 

### Acceptance Criteria 
- [x] Feedback banner on the Bookmarks page is not sticky/does not overlay the Bookmarked items

### Steps for QA: 
1.

**Comment by ian-lin-PG** [comment]
@cherrielam I turned the banner into a Header for the list so now it looks as follows. The beige divider between the banner and the first item of the list is gone, let me know if this is a big deal.
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-02-24 at 14 38 06](https://user-images.githubusercontent.com/52009863/109075459-024e3900-76ae-11eb-9bf0-0dd74f7e6c2a.png)
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-02-24 at 14 38 14](https://user-images.githubusercontent.com/52009863/109075453-00847580-76ae-11eb-8f62-02ae7ccbeaa5.png)

**Comment by Melanie-PG** [comment]
Scrolls for me now. Can we have the beige divider between the service card and top header moved so it's between the service card and banner? Right now the banner and card looks like one at a glance.

**Comment by cherrielam** [comment]
+1 on what @Melanie-PG suggested, moving the beige divider to below the banner (none above the banner)

**Comment by rasmus-storjohann-PG** [comment]
@cherrielam to create a new issue for the last UX tweak request
