### ISSUE TITLE
Spacing for Descriptions in Topics Details vs Service Details 

### ISSUE THREAD

**Issue by Melanie-PG** [pg-irc/pathways-frontend#1400]
The spacing on the Topics Details page for the description does not have a gap between 'Read More' button. 
![IMG_1190](https://user-images.githubusercontent.com/76975404/108781141-49a5bf80-751e-11eb-8fa7-4848708e8e76.PNG)

The Service Details page, however, has a gap between the description and 'Read More' button. Additionally, it looks like the last word of the description (in this example, the word 'assistance') is cut off vertically. 
![IMG_1191](https://user-images.githubusercontent.com/76975404/108781145-4ad6ec80-751e-11eb-96d6-1216171a55e6.PNG)

Found on iPhone XS

### Acceptance Criteria 
- [ ]  Remove gap between description and 'Read More' on Service Details page, so the spacing is the same as Topics Detail page. If the paragraph does not, should be cut horizontally rather than vertically. 

### Steps for QA: 
1.

**Comment by rasmus-storjohann-PG** [comment]
Time box, don't spend a lot of time on it

**Comment by tomy-pg** [comment]
Timeboxed for 2 hours. Will need to revisit another time.
