### ISSUE TITLE
When using "My Location" in Topic-Services, does not complete search

### ISSUE THREAD

**Issue by Melanie-PG** [pg-irc/pathways-frontend#1401]
When you go to Topic-Services, then click "My Location" on search page, the search does not actually run, and goes back to the homepage. It works fine when using "My Location" on the Search page. 

[See here for video](https://images.zenhubusercontent.com/99282566/77a7c833-f127-4300-9515-15ebf37f9c7e/rpreplay_final1614035432.mp4)

Steps taken:
1) Go to Topics page
2) Click on any topic (tested on Education, Money & Banking, Health Care, Employment)
3) In this example, go to Education topic page, then click on topic "Adults completing secondary school"
4) Click "Find Services Near Me"
5) On Topics-Service page, click "My Location"
6) Press "Search"

Found on iPhone XS. Location Services permission setting on iPhone is set to "While Using" for Staging app. 

### Acceptance Criteria 
- [ ] Complete search when using 'My Location' on Topic-Services rather than jumping to homepage.

### Steps for QA: 
1.

**Comment by tomy-pg** [comment]
This has been fixed in 1.62.0. Confirmed this with Melanie.
