### ISSUE TITLE
Running "My location" with location services off in Topic-Services shows user "Invalid location" instead of prompting them to enable location services

### ISSUE THREAD

**Issue by cherrielam** [pg-irc/pathways-frontend#1403]
When a user goes to Topic Services (Find related services near me) and do not allow Location Services, they first see the "Enable location services - You need to turn on Location Services" page, but they are still able to press "My location" in the search. If they run the search with "My location" they get an "invalid location" error page, which is confusing to the user because their location is not, in fact, invalid, but that their Location Services is not turned on.

[See video here](https://images.zenhubusercontent.com/99282566/b186426e-9491-4eec-b78f-5c1b84c80403/rpreplay_final1614035962.mp4)

Steps to recreate:
1. Disallow location services for Arrival Advisor
2. Go to a topic
3. Click "Find related services near me"
4. It shows "Enable location services" error screen
5. User can still click My location & run the search
6. **User sees "Invalid location" error screen** - this is incorrect

[As you will see in this video](https://images.zenhubusercontent.com/99282566/c05322dc-9312-4354-80ef-a334a071fc44/rpreplay_final1614036279.mp4), the UX in the Search page is different if Location Services is off. On Search:

1. Disallow location services for Arrival Advisor
2. Go to Search, and run a Search term
3. User can click "My location"
4. **Clicking "My location" takes them to the Location settings page on their device**

**Recommendation for Topic-Services UX behaviour if Location Services is off:**

- **Option A:** Same behaviour as Search. Clicking "My location" when Location Services is off in Topic-Services takes the user to their device location settings
- **Option B:** Instead of showing the user the "Invalid location" error screen, show the user the "Enable location services" error screen if they try to run the search with "My location" while their location services is off.

Staging 1.62.0, iPhone XS
### Acceptance Criteria 
- [x]  Either Option A or Option B implemented (see above). User gets the right feedback if they try to run the search with "My location" while their Location Services are off - the feedback should either direct them to their device location settings or show them a message that tells them to go to their device location settings. 

### Steps for QA: 
1.

**Comment by alysha-PG** [comment]
Issue is halfway fixed. It no longer says "invalid location" which is good, but it is not doing Option A (taking me to location settings) NOR Option B (showing 'enable location services' screen.

Rather, on iOS when I turn off location and then press "my location" button, nothing happens.

**Comment by brandon-PG** [comment]
> Issue is halfway fixed. It no longer says "invalid location" which is good, but it is not doing Option A (taking me to location settings) NOR Option B (showing 'enable location services' screen.
> 
> Rather, on iOS when I turn off location and then press "my location" button, nothing happens.

This looks to be caused by #1570

**Comment by brandon-PG** [comment]
@alysha-PG Should be testable with the new release of the staging app

**Comment by alysha-PG** [comment]
behavior is working as Option A states. "Enable Location Services" screen does not show, but clicking 'my location' when location services are off takes user to device settings automatically.
