### ISSUE TITLE
Submit button too low on "Suggest An Update"

### ISSUE THREAD

**Issue by Melanie-PG** [pg-irc/pathways-frontend#1406]
When we click on Submit An Update button on Service Details page, the submit buttons for the following screens are too close to the bottom. This persists on "Change name or other details," "This service no longer available," and "Other suggestions."

Found on Staging App v. 1.62.0 on iPhone XS

![IMG_1204.PNG](https://images.zenhubusercontent.com/5ff3960df5b0401a97dc20f1/7c09805a-affe-47b7-9197-cc03e08bdeb5)
![IMG_1205](https://user-images.githubusercontent.com/76975404/108916583-56d8b200-75e3-11eb-8179-34352a5d004b.PNG)

### Acceptance Criteria 
- [x]  Add more space below the submit button so that it is not too close to the Home Bar Indicator on new iPhones

### Steps for QA: 
1.

**Comment by rasmus-storjohann-PG** [comment]
Solve with #1387 maybe?

**Comment by ian-lin-PG** [comment]
PASS QA 1.63.0
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-02-26 at 15 44 58](https://user-images.githubusercontent.com/52009863/109366970-a6b8b280-7849-11eb-8f01-63557fa326e9.png)
