### ISSUE TITLE
UX Polish: Modal overlaps with the system bar

### ISSUE THREAD

**Issue by cherrielam** [pg-irc/pathways-frontend#1409]
The modals for Disclaimer, About Arrival Advisor, are too close to the system bar on iPhone XS and similar iPhones (with notch)

On Staging 1.62.0

![IMG_7413.PNG](https://images.zenhubusercontent.com/5823860ee40e5714b1700133/55db0ed0-5b4d-42a6-bea6-7cb211216704)

Recommendation: Either make sure the modal is under the system bar and doesn't overlap, or replace the modals with pages - eg. page used for Learn More -> Services listed in Arrival Advisor (see below) - and ensure that the page does not overlap the system bar

![IMG_7414.PNG](https://images.zenhubusercontent.com/5823860ee40e5714b1700133/79dc5757-b674-4459-82f7-d3e794d3c613)

### Acceptance Criteria 
- [ ]  Modal is made less tall so that it does not overlap the system bar on iPhone XS and similar iPhones

### Steps for QA: 
1.

**Comment by ian-lin-PG** [comment]
No longer touching notch.
<img width="319" alt="Screen Shot 2021-07-02 at 2 09 29 PM" src="https://user-images.githubusercontent.com/52009863/124328849-3a272a80-db3f-11eb-8f74-e79fab4c26b0.png">
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-07-02 at 14 08 29](https://user-images.githubusercontent.com/52009863/124328856-3d221b00-db3f-11eb-8c6a-a7367c2eccf7.png)

**Comment by brandon-PG** [comment]
Conflicts with #1490. About us/Disclaimer will no longer be a modal

**Comment by brandon-PG** [comment]
Reopening because #1490 will still be a modal.

**Comment by ian-lin-PG** [comment]
@cherrielam could you decide whether this current modal height is good?

**Comment by ian-lin-PG** [comment]
@cherrielam this is a notchless screenshot on ipod touch 7th generation 
![Simulator Screen Shot - iPod touch (7th generation) - 2021-07-08 at 10 51 57](https://user-images.githubusercontent.com/52009863/124968728-b35ccc80-dfda-11eb-8504-bb3cbb5025c6.png)

**Comment by cherrielam** [comment]
I think it looks OK

**Comment by ian-lin-PG** [comment]
@cherrielam I think this can close?

**Comment by cherrielam** [comment]
Looks good!
