### ISSUE TITLE
Remove bottom nav bar on the "Services listed on Arrival Advisor" page

### ISSUE THREAD

**Issue by cherrielam** [pg-irc/pathways-frontend#1410]
There should be no bottom bar or nav on the "Services listed on Arrival Advisor" page, as the key user action on this page is to read/close it.

Samsung Galaxy S5 - there is a bottom nav - does not need to be there
![Screenshot_2021-02-23-17-29-30.png](https://images.zenhubusercontent.com/5823860ee40e5714b1700133/5f3ff792-6842-4927-9128-458c3a57d59c)

iPhone XS - there is a teal bar at the bottom, this does not need to be there and may confuse the user that there is something to pull up.
![IMG_7414.PNG](https://images.zenhubusercontent.com/5823860ee40e5714b1700133/d711ed39-f9f0-4159-aa11-1229d933e5a1)

### Acceptance Criteria 
- [x]  No bottom bar or nav on the "Services listed on Arrival Advisor" information page

### Steps for QA: 
1.

**Comment by rasmus-storjohann-PG** [comment]
Solve with #1386 if it's easy

**Comment by tomy-pg** [comment]
Staging 1.63.0: PASS
