### ISSUE TITLE
UX bug: Accented/special characters not showing in Avenir on Android

### ISSUE THREAD

**Issue by cherrielam** [pg-irc/pathways-frontend#1411]
There is missing accent/symbol support in Avenir on Android (see library name below). The library name seems to render on iPhone XS without an issue (although I'm not entirely sure if it's actually the right symbols).

![Screenshot_2021-02-22-12-18-06.png](https://images.zenhubusercontent.com/5823860ee40e5714b1700133/a28115f9-810f-404b-acdc-08dea76d4191)

On Staging 1.62.0, Samsung Galaxy S5

### Acceptance Criteria 
- [ ]  Accents/symbols render on Android properly — this may require rendering it in the system font if not supported by Avenir

### Steps for QA: 
1.

**Comment by cherrielam** [comment]
The symbols seem to render in iPhone XS (at least there are no question marks) 

![IMG_7418](https://user-images.githubusercontent.com/21990736/109067850-ecd41180-76a3-11eb-84ee-df36f50645f6.PNG)

**Comment by brandon-PG** [comment]
Looks like bad data from Algolia. The empty spaces are not rendered in iOS but are rendered as question marks in Android. I don't see this service in the most recent BC211 Data csv.
![Screen Shot 2021-07-19 at 8 58 46 AM (2)](https://user-images.githubusercontent.com/84804716/126208766-7919afb6-fa82-4fce-827a-5e24395b928f.jpeg)
