### ISSUE TITLE
UX Polish: System font shows instead of Avenir on Android

### ISSUE THREAD

**Issue by cherrielam** [pg-irc/pathways-frontend#1412]
On Android, there are some instances where the system font is shown,= instead of Avenir:

1. Selected language, which is bolded, shows in the system font. Should be in Avenir Black:
![Screenshot_2021-02-22-12-19-12.png](https://images.zenhubusercontent.com/5823860ee40e5714b1700133/9bd69ed6-164f-4618-9f6b-531939746999)

2. Italicized body text in Topic Detail shows in system font. Should be in Avenir
![Screenshot_2021-02-22-12-14-49.png](https://images.zenhubusercontent.com/5823860ee40e5714b1700133/e5c30192-dd8d-4cb5-b678-79af4bb09d13)

On Staging 1.62.0, Samsung Galaxy S5

### Acceptance Criteria 
- [ ] Bolded font in language selection is in Avenir
- [ ] Italicized font in topic detail is in Avenir

### Steps for QA: 
1.

**Comment by rasmus-storjohann-PG** [comment]
See also #1411 , solve both together if possible

**Comment by rasmus-storjohann-PG** [comment]
Broke out issue 2 to #1557

**Comment by rasmus-storjohann-PG** [comment]
Assigning this to @cherrielam since she has the eagle eyes needed to distinguish different fonts.

**Comment by cherrielam** [comment]
Issue #1 is addressed now thanks!
