### ISSUE TITLE
Questionnaire close button too near edge on iPhone XS

### ISSUE THREAD

**Issue by cherrielam** [pg-irc/pathways-frontend#1413]
The close button in the questionnaire screens is too close to the top and right edge of the phone screen on iPhone XS - it is nearly impossible for user to click
![IMG_7411.jpg](https://images.zenhubusercontent.com/5823860ee40e5714b1700133/9f1ca835-19c0-4c72-b64b-5fbe119602df)

Placement of close button in the questionnaire screens is where the hamburger icon is on the Home screen

### Acceptance Criteria 
- [ ]   Move button down and to the left so that there is enough spacing above and to the right for it to be clickable for the user

### Steps for QA: 
1.

**Comment by tomy-pg** [comment]
Staging 1.63.0: PASS
