### ISSUE TITLE
UX Bug: Changing languages in Search keeps "My location" input in the previous language

### ISSUE THREAD

**Issue by cherrie-pg** [pg-irc/pathways-frontend#1414]
Not entirely sure if this is an issue... On Search, if the user is searching from "My location", when they change languages, the "My location" input stays in the previous language. It seems like it should be in the current language?

Eg. Current state: 
If searching in French: types in Health a proximité de Mon emplacement --> Switch to English --> shows Health near Mon emplacement
Not sure if "Mon emplacement" should change to "My location" given the person has changed language?

[See video](https://images.zenhubusercontent.com/99282566/0db002c6-1a34-44e1-abcc-553a4fb54842/rpreplay_final1614129149.mp4)

### Acceptance Criteria 
- [ ]  Decision made as to whether, when the user changes languages, "My location" input in search should be in the current language - and then implemented as such

### Steps for QA: 
1.

**Comment by rasmus-storjohann-PG** [comment]
This is an edge case, low priority. We assume users don't tend to change their language very often, so the likilyhood they will see this problem is quite low.

**Comment by rasmus-storjohann-PG** [comment]
This problem has been fixed already, cannot reproduce
