### ISSUE TITLE
Improvements to Google Analytics

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1447]
Describe the issue and expected behaviours. If this is a bug, describe the steps to reproduce the problem, what you observe, and what you expected to observe.

### Acceptance Criteria 
- [ ]  Define a small set of questions that we want to use GA data to answer
- [ ] Define user activities that can be measured in order to answer these questions
- [ ] Define proxy actions in the app that can be used as events to represent the completion of these activities
- [ ] Add GA hooks to those actions
- [ ] Ensure that no PII is included in the data collected by those hooks
- [ ] Wire up the necessary third party infrastructure to collect and analyze this data 
- [ ] Establish processes for routinely monitoring, analyzing and acting on the data collected
- [ ] Establish QA processes to ensure that this functionality is all working correctly

**Comment by alysha-PG** [comment]
@alysha-PG put in road map
