### ISSUE TITLE
Update topics in the help screen to point to MB topics when appropriate

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1462]
![image](https://user-images.githubusercontent.com/32307781/113351489-d008aa80-92ef-11eb-9e80-cbf5b2b8e8e9.png)

### Acceptance Criteria 
- [ ]  All topics in the help screen refer to MB topics when in MB and BC topics when in BC

**Comment by cherrielam** [comment]
In the interim, we can link these in Manitoba (with the caveat that we should consider linking to topics and/or review with MB Start):

Copy changes are **_bolded and italicized_**

Information on emergency services (9-1-1) - https://www.winnipeg.ca/interhom/guide/All/Emergency.stm
Information on **_Health Links - Info Santé_** - https://misericordia.mb.ca/programs/phcc/health-links-info-sante/
Information on **_211 Manitoba_** - https://mb.211.ca/
Information on helplines - https://mb.211.ca/quick-reference-guide-helplines/

**Comment by rasmus-storjohann-PG** [comment]
There are more changes coming in this area following review by MBStart. The plan is to close this issue once it passes QA and create a new issue to track subsequent changes.
