### ISSUE TITLE
Clean up locale code

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1470]
The locale code is old and poorly structured, with too much data stored both in redux and in a singleton, with imprecise types used in many places, etc.

### Acceptance Criteria 
- [x]  The locale functionality in the app still works

### Steps for QA: 
1.  Try all the flows relating to changing the locale in the app

**Comment by alysha-PG** [comment]
Flows are all working correctly. However, in all locales, in the menu, the currently selected locale does not show up - only a check mark with a blank space next to it.
![File (1)](https://user-images.githubusercontent.com/85197659/123873627-a01b7400-d8eb-11eb-9bfd-920d1fe4ca3d.jpg)

**Comment by rasmus-storjohann-PG** [comment]
Issue from an earlier version of the app, closing this as fixed
