### ISSUE TITLE
Build new splash screen

### ISSUE THREAD

**Issue by cherrielam** [pg-irc/pathways-frontend#1483]
We would like to implement a new [splash screen](https://docs.expo.io/guides/splash-screens/) for Arrival Advisor. 

**Designs:** [**On Zeplin**](https://zpl.io/am3X7Qv)

~~There are 3 versions of the splash screen — if they first load the app and haven't selected a province yet, they get the [Splash - PG](https://zpl.io/am3X7Qv) screen. If they are in the Manitoba version, they should get the [Splash - MB](https://zpl.io/aMokj63) screen. If they are in the BC version, they should get the [Splash - BC](https://zpl.io/bPEzD66) screen.~~

There is only one Splash screen: https://zpl.io/am3X7Qv

Ideally the splash screen should have some form of animation to indicate to the user that it is loading (this is considered for V2) Some animation options are:
- Fade in ([prototype link](https://www.figma.com/proto/n5XxNxT01SHDfUfvxN5VWO/WIP-Partner-branding?page-id=485%3A1369&node-id=485%3A1372&viewport=544%2C294%2C0.5882670283317566&scaling=scale-down))

![ezgif.com-gif-maker (4).gif](https://images.zenhubusercontent.com/5823860ee40e5714b1700133/b4553155-4419-4bbf-94cb-29dc1b18e520)

- Swirly loading gif ([prototype link](https://www.figma.com/proto/n5XxNxT01SHDfUfvxN5VWO/WIP-Partner-branding?page-id=429%3A2842&node-id=485%3A1408&viewport=-1632%2C103%2C0.4137962758541107&scaling=scale-down)) - @cherrielam has the lottie JSON file and the GIF for the swirly if desired

![ezgif.com-gif-maker (2).gif](https://images.zenhubusercontent.com/5823860ee40e5714b1700133/38b44886-469a-4d1e-b3dc-1c128554c83d)

- Fancy rotate + fade in ([prototype link](https://www.figma.com/proto/n5XxNxT01SHDfUfvxN5VWO/WIP-Partner-branding?page-id=485%3A1328&node-id=485%3A1332&viewport=472%2C246%2C0.2951677143573761&scaling=scale-down))

![ezgif.com-gif-maker (3).gif](https://images.zenhubusercontent.com/5823860ee40e5714b1700133/822b78bd-0599-4230-ab84-9cdc252b86ec)

### Acceptance Criteria 
- [ ] When the user launches the app, the splash screen matches the design (https://zpl.io/am3X7Qv)
- [ ] Stretch goal: add animation to the screen using any of the proposed designs.

### Steps for QA: 
1.

**Comment by brandon-PG** [comment]
Having different splash screens for different app states does not seem possible with expo as they are defined in 'app.json'. See https://docs.expo.io/guides/splash-screens/ for more information. I could implement the first screen in the Zeplin mocks but not the others. @cherrielam @rasmus-storjohann-PG

**Comment by cherrielam** [comment]
hmm sure, I would love to hear @rasmus-storjohann-PG feedback on whether it would be valuable to do a version of the screen with all 4 logos

**Comment by rasmus-storjohann-PG** [comment]
@cherrielam that was my first thought too, I think it could be cool. It would demonstrate our geographical and network reach and all users would be reminded each time they launch the app that we're in multiple provinces

**Comment by deniza-pg** [comment]
I can not see the fade-in in iOS, it moves too fast.

**Comment by brandon-PG** [comment]
@deniza-pg Expo does not support fade-in for this splash screen. There is no animation.
