### ISSUE TITLE
Update hamburger menu with logos + Creators page

### ISSUE THREAD

**Issue by cherrielam** [pg-irc/pathways-frontend#1489]
We would like to add logos onto the hamburger right side menu. The logos should link to a "Creators" page.

See also #1521 

Mocks:

- [Right menu drawer - MB](https://zpl.io/a3rx4Nl), clicking the logos takes you to [MB version of the "Creators" page](https://zpl.io/aRRon3z)
- [Right menu drawer - BC](https://zpl.io/29Gl7BW), clicking the logos takes you to [BC version of "Creators" page](https://zpl.io/VY5WqwJ)

Note: In the app, we currently have a few kinds of pages: the pop-up modal for "About Arrival Advisor" or "Disclaimer" (accessed via right hamburger menu) and the page for "Services listed on Arrival Advisor" (accessed when you click "Suggest an Update" on a Service and then click "Learn more"). All of those pages should be updated to match the 'Creators' page style.

### Acceptance Criteria 
- [ ]  Right menu drawer shows the correct logos per province, and links to the correct province's "Creators" page
- [ ] The pop-up modal pages (eg. About Arrival Advisor and Disclaimer) are updated to match the design of the "Creators" page
- [ ] The text pages with close button (eg. "Services listed on Arrival Advisor") are updated to match the design of the "Creators" page 

### Steps for QA: 
1.

**Comment by deniza-pg** [comment]
The disclaimer is still BC.

The right menu drawer shows the correct logos per province, and links to the correct province's "Creators" page: There is link to Manitoba 211 but not Manitoba start

**Comment by brandon-PG** [comment]
Changing locales to Arabic will not restart the app with right to left reading. Instead the layout of the app remains the same as the previous language.

**Comment by rasmus-storjohann-PG** [comment]
This may be iOS specific...

**Comment by brandon-PG** [comment]
Is an iOS restart issue https://forums.expo.io/t/updates-reloadasync-doesnt-work-on-standalone-ios-sdk-41/52349

**Comment by deniza-pg** [comment]
The logos don't go to creator's page.

**Comment by brandon-PG** [comment]
The creators page was made a modal for ease of development

**Comment by ian-lin-PG** [comment]
Screenshots of creator's page:
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-08-13 at 11 00 08](https://user-images.githubusercontent.com/52009863/129400692-8e29c54b-63fe-4bcd-90ce-1e2d8f2ddddb.png)
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-08-13 at 11 01 04](https://user-images.githubusercontent.com/52009863/129400696-4e4f59bf-4804-46c4-a85b-16df3e347b96.png)
