### ISSUE TITLE
About Arrival Advisor page updated per province

### ISSUE THREAD

**Issue by cherrielam** [pg-irc/pathways-frontend#1490]
We would like to update the "About Arrival Advisor" page copy and show a slightly different version in each province.

See mocks:
- [About Arrival Advisor page in BC](https://zpl.io/aXjG7Wx)
- [About Arrival Advisor page in MB](https://zpl.io/2pRx8LJ)

~~NOTE: The "About Arrival Advisor" modal page should no longer be a modal; same with "Disclaimer" - all of these pages should be updated to reflect the page design in the mocks above. See related note in #1489~~ per conversation with @brandon-PG we decided not to change the page style to modal since it seems more complicated than it's worth.

### Acceptance Criteria 
- [x] On the "About Arrival Advisor", copy is updated and logos are added. Changing the province shows the correct province's content.
~~- [ ] The "About Arrival Advisor" modal page, and other similar modal pages (eg. "Disclaimer") are updated to match the page design of the mock (no longer a modal).~~
- [ ] The text for Arrival Advisor version number, Service version number, and AAStagingVersion number current shows in the system font. It should show up in Avenir.

### Steps for QA: 
1.

**Comment by cherrielam** [comment]
It's updated! Only issue is the font - can we make sure the circled text below shows up in Avenir?

![IMG_8702](https://user-images.githubusercontent.com/21990736/124329565-7e66fa80-db40-11eb-99a3-2438e45c5cb2.PNG)

**Comment by ian-lin-PG** [comment]
Screenshot after change
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-07-07 at 14 13 28](https://user-images.githubusercontent.com/52009863/124829678-bf3e8500-df2d-11eb-8eed-7143a8722128.png)

**Comment by cherrielam** [comment]
@ian-lin-PG @brandon-PG can you also send an Android screenshot? Just to check that it's behaving in Android as well

**Comment by brandon-PG** [comment]
![Screenshot_1625765996](https://user-images.githubusercontent.com/84804716/124967154-f1f18780-dfd8-11eb-9ea3-041b2099f403.png)
on Android

**Comment by cherrielam** [comment]
Looks great! Thanks

**Comment by rasmus-storjohann-PG** [comment]
Waiting for OK from MBStart on copy, do not QA until they've gotten back to us

**Comment by alysha-PG** [comment]
MB Start has approved copy, font looks good.
![File (2)](https://user-images.githubusercontent.com/85197659/126524176-46bb5707-57ce-4b56-8a9d-d26a75a55612.jpg)
