### ISSUE TITLE
Upgrade ajv

### ISSUE THREAD

**Issue by ian-lin-PG** [pg-irc/pathways-frontend#1498]
The ajv API for validation and errors have changed, which means we need to change all the calls referencing the library. The error is now an object instead of a string, and all tests relying on the error message will now fail. Even after fixing all the library calls, user data tests all fails on unknown field `address` even though this field is not present in the user data schema or persisted data builder.

### Acceptance Criteria 
- [ ]  ajv package upgrade passes all tests

### Steps for QA: 
1.

**Comment by rasmus-storjohann-PG** [comment]
Unit tests pass, no further QA needed
