### ISSUE TITLE
Installation issues for the front-end

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#15]
Tried the yarn command, got this
```
$ yarn install
ERROR: [Errno 2] No such file or directory: 'install'
```
Using `npm install` instead. Rerunning the yarn command after the npm install still gives the same error. The readme should be improved to give better directions on this.

What does `open config/development.js` do? This command also does not work.
```
$ yarn run start
ERROR: [Errno 2] No such file or directory: 'run'
```
I am guessing that there are a lot of unstated assumptions in the readme about the environment on the machine.

**Comment by dylanmccall** [comment]
This is a bug in Yarn, not in pathways-frontend. Please check what version of Yarn you are running using `yarn --version`. It should be 1.3.2. There was an [issue with their packaging in Ubuntu 17.04](https://github.com/yarnpkg/yarn/issues/3189) that you may be seeing here.

Note that NPM and Yarn are mutually exclusive. If `npm install` works, that's fine. Just bear in mind that our lock file is (currently) for Yarn so you might not have *exactly* the same version of each dependency.

**Comment by rasmus-storjohann-PG** [comment]
Ensure that the readme correctly specifies the required yarn version and contains installation instructions.

**Comment by rasmus-storjohann-PG** [comment]
Got the API server running and the webpack server, when I hit the website to load the locations, the API server has this error
```
"OPTIONS /locations HTTP/1.1" 200 0
Not Found: /locations
"GET /locations HTTP/1.1" 404 2286
```
the get response ought to go to /v1/locations

**Comment by dylanmccall** [comment]
That is happening because we haven't merged PR #14 into master. It still thinks it is talking to the old (NodeJS) API.

**Comment by dylanmccall** [comment]
There is no required Yarn version here. As I explained, the issue you had is that Yarn is packed incorrectly in Ubuntu 17.04. That isn't our problem, and will likely be fixed at some point. With that said, it's probably okay to switch to an NPM lock file and use NPM for the readme at this point. It is slightly less of a problem now that there are fewer old versions of NPM floating around.

**Comment by rasmus-storjohann-PG** [comment]
I'd be happy see one less tool in the tool chain, if npm can do everything yarn does.
