### ISSUE TITLE
Different questionnaires in different regions

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1505]
Figure out the information architecture for multiple questionnaires with shared questions:

*  Questionnaire for a given region, with some questions appearing only in one region, or with the question showing up everywhere, but some answers only showing up in one (or some) region(s)
* When people switch region, all answers to the questions are deleted? Or are they all kept?
* When they switch back again, the answers reappear?
* Maybe: mark each question with what regions it should appear in, would make the switch between regions less confusing
* How do we handle BC/MB drivers license: One answer for BC, a second answer for MB, each retains the answer

### This is the plan

- [ ] Taxonomy terms used to connect answers to topics may get a regional prefix, this will be used for those terms that apply to specific regions only
- [ ] Questions as defined in `/pathways-frontend/src/fixtures/types/questionnaire.ts` will get an attribute that indicates what region they apply to. This attribute may be undefined, in which case it applies to all regions
- [ ] Answers as defined in the same file are not changed, but the BC and MB questionnaires will have separate questions and likely we will want to use answer id strings that contain the region. However, this can be done without changing the Answer *type* at all.
- [ ] When showing the questionnaire on the screen, only those questions are shown that have either region === current region or region undefined.
- [ ] When choosing answers, the isChosen flag is updated on the answer that belongs to a question that may be specific to a region
- [ ] When switching regions, different questions and corresponding answers will appear in the app.
- [ ] When switching regions, all isChosen flags (i.e. the user's answers) remain unchanged, so the app will remember the answers from one region, even after switching to a different region. Switching back to the original region will make those answers appear again
- [ ] When computing recommended topics, we pull the relevant taxonomy terms from the questions of the current region only, see `getTaxonomyTermsForRelevantAnswers()`.

### Steps for QA: 
1.

**Comment by alysha-PG** [comment]
re: Checkbox 1 - My understanding is Taxonomy terms used to connect answers to topics **will** get a regional prefix, this will be used for **all taxonomy terms since MB wants only their topic content to show up from their sources**

**Comment by rasmus-storjohann-PG** [comment]
Design:
- [ ] Questions have a new property, region, of type `RegionCode | undefined`
- [ ] Current question (to show in the UX) uses the question id, not index
- [ ] Next and Previous questions also use the question ids, not the index
- [ ]

**Comment by ian-lin-PG** [comment]
Completing the mb questionnaire or completing bc questionnaire then switch to mb causes the same crash.
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-07-15 at 11 06 10](https://user-images.githubusercontent.com/52009863/125836305-3ea316d3-05d8-42dd-900c-0a018b972170.png)

**Comment by deniza-pg** [comment]
I filled the questionnaire in BC with these options:
More than 1 year
I have a social insurance number
Pre-natal
I want to rent a place to live
No English
Permanent resident
I am looking for work
General health care...
Adult education and training.

I switched to Manitoba:

How long have you been living in Canada? (as expected)

**Do you have any of the following important Canadian Documents?
I was expecting to see Social Insurance Number, but it was not selected in the questionnaire.**

What age group do you want resources for?
Pre-natal ( as expected)

Housing situation. (as expected)

Current Level of English (as expected)

What is your status in Canada (as expected)

What is your current work situation? (as expected)

Others (as expected)


----
(I changed things in MB and go back to BC. The changes were there as expected.)

**Comment by alysha-PG** [comment]
adding my comment from #1553 here for visibility:
 @rasmus-storjohann-PG questionnaire should read exactly as is in the first tab here:
https://docs.google.com/spreadsheets/d/1gn4KH_qlVcosFIDiYENVw4uGMWpcvrJwy4zU9gMpPXE/edit?usp=sharing

**Specific changes to make:**
Q. 3. When I go to the questionnaire, expected behavior is there is a Q3. Instead now, it skips from Q2 to Q4. This question is expected to be the one about current immigration status, instead nothing is there and that question is currently Q9.

- [ ] make Q3 immigration status Q

Q. 6. housing (NOTE: please change to both MB and BC):

- [ ] Change order of questions and content. Answers should read (in this order)-

    I want to rent a place to live
    I already rent a place to live
    I want to buy a home
    I already own a home

Q. 7. current level of English:
- [ ] Remove Canadian Language Benchmark mention and levels. Should only read None, Beginner, Intermediate, Fluent.

Q. 10 work

- [ ] add "Select all that apply"
- [ ] remove "None of the above"

Q. 11 Health care

- [ ] Remove BC-specific "Prescription medication" and "Eye doctors"
