### ISSUE TITLE
Review all new MB UX changes in Arabic locale

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1506]
### Acceptance Criteria 
- [ ]  All new UX elements related to the Manitoba project appears correct in RTL in Arabic

**Comment by brandon-PG** [comment]
- Welcome screens
![Screenshot_1624309825](https://user-images.githubusercontent.com/84804716/122832583-708fba80-d2a0-11eb-9179-f8cc6bb3be87.png)
![Screenshot_1624309838](https://user-images.githubusercontent.com/84804716/122832585-71c0e780-d2a0-11eb-8f1c-8cb21553b353.png)
- Onboarding screens
![Screenshot_1624309665](https://user-images.githubusercontent.com/84804716/122832614-7a192280-d2a0-11eb-864a-d31fd81e1cc0.png)
![Screenshot_1624311671](https://user-images.githubusercontent.com/84804716/122832631-81d8c700-d2a0-11eb-8a88-9209e92d430b.png)
- Hamburger menu
![Screenshot_1624311687](https://user-images.githubusercontent.com/84804716/122832668-8d2bf280-d2a0-11eb-9a44-dff016ecc098.png)
![Screenshot_1624309774](https://user-images.githubusercontent.com/84804716/122832687-93ba6a00-d2a0-11eb-8b5a-21f9c54e4dc1.png)
- About us screens
![Screenshot_1624309792](https://user-images.githubusercontent.com/84804716/122832851-d67c4200-d2a0-11eb-8dc4-7ad55a00845b.png)
![Screenshot_1624309797](https://user-images.githubusercontent.com/84804716/122832855-d8460580-d2a0-11eb-916e-dc892c0ee540.png)
![Screenshot_1624311696](https://user-images.githubusercontent.com/84804716/122832866-da0fc900-d2a0-11eb-8379-73bdcab0bb98.png)
![Screenshot_1624311699](https://user-images.githubusercontent.com/84804716/122832871-dc722300-d2a0-11eb-8d3b-62a031083917.png)
- Manitoba start tab
![Screenshot_1624309763](https://user-images.githubusercontent.com/84804716/122832917-f14eb680-d2a0-11eb-9219-09956e14526e.png)

**Comment by brandon-PG** [comment]
Everything looks as it should

**Comment by rasmus-storjohann-PG** [comment]
QA of this issue cannot happen until we have the translations

**Comment by Farouk-PG** [comment]
All looks good and QA is done. Closing!
