### ISSUE TITLE
IOS notification crashes app upon cold start

### ISSUE THREAD

**Issue by brandon-PG** [pg-irc/pathways-frontend#1508]
When an IOS user clicks on a notification with the app not in the background, the app with crash on start.

### Acceptance Criteria 
- [ ] The app should open when the notification is clicked  

### Steps for QA: 
0. Ensure that the app is not currently running on the phone
1. Send a notification to an IOS phone
2. Click on the notification when it appears
3. Verify the app opens correctly

**Comment by ian-lin-PG** [comment]
PASS QA 1.74.0
