### ISSUE TITLE
Use string interpolation for this localized string

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1514]
The component `LanguageAvailabilityDisclaimer` contains the same string for two different provinces. Change the component to use a single string with a placeholder for the name of the region. Note that both the string and the region name will be localized. This will remove needless duplication of the string and simplify translation work going forward.

This is a little tricky because of how the lingui <Trans> component works, see https://lingui.js.org/ref/react.html#trans

Also, make a slight change to the alert string. It should say "Information about {newRegion} is not available in {currentLanguage}, do you want to access information about {newRegion} in English?" With this wording, the user will be more likely to understand what "Cancel" and "Continue" buttons on the alert will actually do.

### Acceptance Criteria 
- [ ]  There is only one string for the alert, containing a placeholder for the particular region.
- [ ] The alert string is made clearer.

**Comment by cherrielam** [comment]
@rasmus-storjohann-PG Thanks!

My proposal for the component:

Header: Continue in English?
Body: "Information about {newRegion} is not available in {currentLanguage}. Do you want to see information about {newRegion} in English?" 

Buttons: Cancel / Continue

**Comment by rasmus-storjohann-PG** [comment]
This has been completed under #1595
