### ISSUE TITLE
Under help, delete "Go to Welcome screen" button

### ISSUE THREAD

**Issue by alysha-PG** [pg-irc/pathways-frontend#1518]
No longer necessary and also ugly / running into 'Delete all user data' button

### Acceptance Criteria 
[  ] the go to welcome screen button is gone!   

### Steps for QA: 
1.  open app
2. go to help (Question mark button)
3. check if 'go to welcome screen' button is still there

**Comment by rasmus-storjohann-PG** [comment]
fixed
