### ISSUE TITLE
Deleting user data in Manitoba switches content to BC

### ISSUE THREAD

**Issue by cherrielam** [pg-irc/pathways-frontend#1520]
Deleting user data in MB switches the content to BC, but the headers still show "Start settling in Manitoba".

Tested on Staging V 1.70.0 on iPhone XS

https://images.zenhubusercontent.com/99282566/b3388cf6-25d7-4614-bc91-24b9398e8d9c/rpreplay_final1625259217.mp4

### Steps to reproduce:
1. Open the app in Manitoba.
2. Open Help page
3. Click "Delete user data"
4. Notice that the links in the Help page are now for BC211 and BC services
5. Close the Help page -> go back to Home, the title says "Start settling in Manitoba" but the content is all BC content.

### Acceptance Criteria 
- [ ]  Clicking "Delete user data" clears user questionnaire and bookmarks,  takes the user to the Welcome screen.

### Steps for QA: 
1.

**Comment by cherrielam** [comment]
Note that also the language selection and province selection menus go awry after deleting user data and being in MB:


https://user-images.githubusercontent.com/21990736/124330785-f9311500-db42-11eb-8d1f-5298d80d3484.MP4

**Comment by rasmus-storjohann-PG** [comment]
Province reverts to BC on deleting all data: this is as designed, BC is the default province, and when we delete all data from the app, it reverts to the default for all settings, including region.

**Comment by cherrielam** [comment]
Except for the fact that the title still says Manitoba. But I would disagree that this is "as designed". Deleting all user data does not equate to a user realizing they will switch provinces. I would do a force exit back to the Welcome screen in that case.
