### ISSUE TITLE
Clicking outside the drawer should close it

### ISSUE THREAD

**Issue by cherrielam** [pg-irc/pathways-frontend#1522]
Clicking outside the language/province selection drawer should close it but it doesn't. 

The first layer drawer does close if you click outside of it (The drawer that shows "About Arrival Advisor"). The second layer drawer (the one that lists the provinces/languages) does not close if you click outside of it. The conflicting behaviour is confusing to the user.

![IMG_8705.PNG](https://images.zenhubusercontent.com/5823860ee40e5714b1700133/359026a5-2a33-402a-a825-63582cf81d9d)

### Acceptance Criteria 
- [ ]  Clicking outside the language list/province list drawers close them. It can either close that layer and return the user to the previous layer OR close all layers entirely (whichever is easier to implement).

### Steps for QA: 
1.

**Comment by brandon-PG** [comment]
This only occurs on the region drawer and happens because the child drawer of the region drawer is the main header menu. This can be fixed by adding an empty drawer between the two but I was unable to find a better solution.
