### ISSUE TITLE
App crashes when switching provinces with bookmarks

### ISSUE THREAD

**Issue by cherrielam** [pg-irc/pathways-frontend#1523]
Currently if a user saves a bookmark in one province, then switches to a different province, when they land on the Bookmarks page, it crashes. A design is needed for what is supposed to happen here

### Acceptance Criteria 
- [x] The topics visible in the app are the topics belonging to the currently selected region. Switching region in the app causes the set of visible topics to update to the set appropriate for the newly selected region
- [x]  A user who has one or more topics and/or services bookmarked in one region, switches region, they will see no bookmarks
- [x]  A user who has one or more topics and/or services bookmarked in one region, switches region, and then switches back to the first region, they will see the bookmarks they had

### Steps for QA: 
1.

**Comment by alysha-PG** [comment]
All acceptance criteria has been met!
