### ISSUE TITLE
Problematic Manitoba services

### ISSUE THREAD

**Issue by ian-lin-PG** [pg-irc/pathways-frontend#1525]
There are 52 services without an address, 107 services without taxonomies out of 159 total possible manitoba services. It's possible for a service to be lacking both a proper address or any taxonomies. I also noticed some addresses without latlong.

[services with no address](https://drive.google.com/file/d/1_fl6OEqXYpnnqfjFKMyJHUt6XH9tbylT/view?usp=sharing)
[services with no taxonomy](https://drive.google.com/file/d/15BVGOnIkiCvihZ2q43AOMrBC8FisRvMW/view?usp=sharing)

### Acceptance Criteria 
- [ ]  

### Steps for QA: 
1.

**Comment by alysha-PG** [comment]
we aren't using their taxonomies so its now irrelevant, and we cut services that dont have addresses.
