### ISSUE TITLE
Android back button does not close region/locale drawers

### ISSUE THREAD

**Issue by brandon-PG** [pg-irc/pathways-frontend#1527]
Tapping the physical back button will not close the region/locale drawer.

### Acceptance Criteria 
- [ ] Tapping  the physical back button once should exit the drawer

### Steps for QA: 
1.  Open the region drawer in the hamburger menu
2. Tap the physical back button on an android device
3. Verify the drawer closes
4. Repeat for the language drawer

**Comment by rasmus-storjohann-PG** [comment]
This passes QA
