### ISSUE TITLE
MVP polish: Completed tasks in My Plan page

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#153]
ACs:
* Implement a Completed Tasks section, similar to Tasks I plan to do and Recommended tasks, located below the Recommended tasks section. The Completed Tasks section is closed by default.
* Clicking the Completed Tasks counter at the top of the page goes to Completed Tasks list and expands the section.

**Comment by bensinjin** [comment]
AC added: Ensure correct icon on saved tasks, square unchecked box as apposed to +
