### ISSUE TITLE
Clicking Done on questionnaire should set active question to the first question

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1535]
Open the questionnaire
Answer every question, clicking Next for each
On the last question, answer and click Done to finish the questionnaire
Observe the "you have new recommendations" alert
Observe that you're taking to the home screen
Click to open the questionnaire again
Observe that you're taken to the last question in the questionnaire
Expected is that you're taken to the *first* question, since you completed it before.

### Acceptance Criteria 
- [x]  Change behaviour on clicking "Done" on the questionnare, so that next time, the questionnaire opens on the first question

**Comment by rasmus-storjohann-PG** [comment]
The action to close the questionnaire needs to take the current region as part of its payload, so that the questionnaire reducer can set active question to the first question for the given region.

**Comment by rasmus-storjohann-PG** [comment]
Alternatively, closing the questionnaire could set the active question to `undefined`. `buildDefaultStore()` should then also set active question to `undefined`. The selector pulling out the questionnaire will then need to get test for active question being undefined, pull the region from the store and initialize the active question to the first question for the region.

**Comment by alysha-PG** [comment]
questionnaire opens on first question
