### ISSUE TITLE
Update UX strings for translation

### ISSUE THREAD

**Issue by alysha-PG** [pg-irc/pathways-frontend#1539]
We would like to update certain strings in the app, which will need to be translated. 

Please review https://www.figma.com/file/br8IthdXBkiMCATBW7KNE4/Main-Mobile-Screens?node-id=701%3A160 middle column and right column to verify the copy that needs to be changed - yellow sticky notes specify what copy needs to be changed. 

The Zeplin screens are also linked below:

Screens to change:
- [x]  [HOME/Full - BC Card](https://zpl.io/aBPqZ3L)
- [x]  [ONBOARDING/1-BC](https://zpl.io/aMwBogJ)
- [x]  [ONBOARDING/2-BC](https://zpl.io/VQy91gm)
- [x]  [ONBOARDING/3-BC](https://zpl.io/25jwx3e)
- [x]  [ONBOARDING/4-BC](https://zpl.io/bzx1LDA)
- [x] [HOME/Questionnaire collapsed](https://zpl.io/VkwQ5rv)
- [ ] [LEARN/Full-BC](https://zpl.io/a7pJeYp)
- [x] [SEARCH/Feedback2.0 with button](https://zpl.io/VOym1zr)
- [x] [HELP/Full-BC](https://zpl.io/bJLZ1Yn)
- [x] [SERVICEFEEDBACK/Discard modal](https://zpl.io/VKX10EP)
- [x] [HOME/Full - MB Start Card](https://zpl.io/a3QK5n1)
- [x] [HOME/Questionnaire collapse - MB](https://zpl.io/brGl5wX)
- [ ] [LEARN/Full-MB](https://zpl.io/boAZqrE)
- [x] [SEARCH/Feedback 2.0 with button - MB](https://zpl.io/bJLZmzx)
- [x] [HELP/Full-MB Option 1](https://zpl.io/brGl5D3) or [Option 2](https://zpl.io/2Z3kQZw) - see issue https://github.com/pg-irc/pathways-frontend/issues/1544

**Comment by rasmus-storjohann-PG** [comment]
review:
- [ ] Onboarding pages 2 and 3 are switched around
- [ ]

**Comment by cherrielam** [comment]
Onboarding pages in current order is fine!

**Comment by ian-lin-PG** [comment]
This change is related to issue #1545, otherwise @rasmus-storjohann-PG  @brandon-PG, new updates to the PR have been pushed.
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-07-22 at 14 27 49](https://user-images.githubusercontent.com/52009863/126712548-103fd2af-278b-4a4f-8a0c-82b622527ce0.png)

**Comment by cherrielam** [comment]
copy for LEARN/Full-MB and LEARN/Full-BC are blocked/have this issue: https://github.com/pg-irc/pathways-frontend/issues/1565. Everything else is good.

**Comment by cherrielam** [comment]
Closing this issue as everything outstanding is captured in #1565
