### ISSUE TITLE
MVP polish: Fix the back button

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#154]
ACs:
* Fix the back button, this probably involves just using the `history` library correctly.
* When the back button works, we can make this change without making the app unusable: Hide the footer in task detail and article detail pages.

**Comment by bensinjin** [comment]
See https://github.com/pg-irc/pathways-frontend/issues/130 & https://github.com/pg-irc/pathways-frontend/issues/102

**Comment by bensinjin** [comment]
I have confirmed the issues outlined in the two aforementioned issues.  It appears, when observing location state in redux, that there is a "previous path" or something along those lines that does appear to have accurate path values for the previous page although the back() call appears to take from the history stack which works as outlined in #130.
