### ISSUE TITLE
UX Polish: Replace MB Start Logo with non-tagline version of logo

### ISSUE THREAD

**Issue by alysha-PG** [pg-irc/pathways-frontend#1542]
Current version has MB Start Logos which include tagline Where Futures Begin, which are illegible. Replace with MB Start logo which does not contain said tagline.

View updated logo here: https://zpl.io/bzdk3oG

Screens where this logo appears:
- [x]  Loading screen/MB
- [x]  HOME/full - Manitoba Card
- [x]  ONBOARDING/1-MB
- [x]  Right menu drawer/MB
- [ ]  MB START PAGE (does not exist yet, see issue #1543 

Nice to have: Consider making these logos responsive to size adjustments if possible for consideration of large phones.

### Steps for QA: 
1.  Check to make sure all above pages have updated logo

**Comment by rasmus-storjohann-PG** [comment]
Logo without tagline appears in all locations
