### ISSUE TITLE
UX Polish: Update Back to Questionnaire on questionnaire collapsed

### ISSUE THREAD

**Issue by alysha-PG** [pg-irc/pathways-frontend#1545]
**This is a nice-to-have issue**

Currently this page reads "UPDATE MY RECOMMENDATIONS - Go back to questions" with a right-facing arrow. Ideally we would simplify this and write "Back to questionnaire" with a left-facing arrow on both the BC and MB Questionnaire Collapsed pages.

BC Page: https://zpl.io/VkwQ5rv
MB Page: https://zpl.io/brGl5wX

**Comment by rasmus-storjohann-PG** [comment]
Solved as part of #1539
