### ISSUE TITLE
Implement UX theming for MB colour scheme

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1554]
Build theme support and use it to implement the colour scheme for the Manitoba region as shown in mocks.

I have a small PR up with the stubbed out design for how this code will be organized, see https://github.com/pg-irc/pathways-frontend/pull/1555.

Theming changes/specs:
- [ ] All Teal (#00838F) becomes MB Green (#447D20) in the Manitoba version - [see mocks for Manitoba theme](https://zpl.io/blekWWk). In particular this means: all buttons, links, bookmark icon, header nav icons, and top background in the menu drawer becomes MB Green. 
- [ ] Change the side drawer colour in BC. The background for the header (behind the logo) is now the theme colour (Teal instead of Light Teal). See [mock](https://zpl.io/29Gl7BW)
- [ ] Change Bottom Nav Bar design across BOTH provinces. The background is now white, the inactive icons are grey, and the active icon is the theme colour (Teal or MB Green). See these mocks for example: [MB Homepage](https://zpl.io/aRw9jZK), [BC Homepage](https://app.zeplin.io/project/5bc7bfa42e72260acb03aa86/screen/60f70fe55ab8d81192335c22/)
- [ ] Change Search page design across BOTH provinces. The background of the search container is now beige, the Search button is now the theme colour (Teal or MB Green). See these mocks: [MB Search](https://zpl.io/bJLZmzx), [BC Search](https://zpl.io/VOym1zr)
- [ ] New image variations for MB vs. BC. There are MB specific Onboarding images [here](https://zpl.io/adyYqOK), [here](https://zpl.io/b65xPLm), and [here](https://zpl.io/aNY5AW9). Questionnaire card girl image also has an MB variant [here](https://zpl.io/aRw9jZK) and [flipped variant for Arabic here](https://zpl.io/beyONPW)
- [ ] New illustrations WILL be added to topics, there are also BC and MB variants - a separate issue will be created for this.

Acceptance criteria:
- [x] When changing regions between BC and MB, the colour scheme of the app changes
- [ ] The colour scheme for BC is the same as what is currently the colour scheme of the app, except for the updates mentioned above (Bottom Nav bar, Search page)
- [ ] The colour scheme for MB is as shown in the mocks linked above.
- [ ] The colour scheme is consistent on Android and iOS

**Comment by alysha-PG** [comment]
@brandon-PG 

QA: I expect to see all screens in MB with MB green theme, Instead I found 1 screen that got left in teal. This is the search screen, found from 
topics > Find related services near me button > search screen 

![Image from iOS (5)](https://user-images.githubusercontent.com/85197659/128548171-4cd4caf6-0394-445b-84ef-14e8928323f3.png)

**Comment by ian-lin-PG** [comment]
BC pages still look teal.
MB topic services page:
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-08-09 at 11 04 41](https://user-images.githubusercontent.com/52009863/128752683-3315279f-6d99-4918-b836-8b552a1b6474.png)
MB search page:
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-08-09 at 11 01 56](https://user-images.githubusercontent.com/52009863/128752711-540b6917-f768-4f62-8063-9e8a47597c11.png)
