### ISSUE TITLE
Modify MB topic import script to remove URL tags in square brackets

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1559]
### Acceptance Criteria 
- [ ]  MB Start topics have links that don't have tags

### Instructions for QA
- [ ] Import the MB Start content with command similar to `./manage.py convert_win_data ../mbstart/FINAL\ Arrival\ Advisor\ Manitoba\ Content_fromMB_7_20.21.txt out/`
- [ ] Check the output for URLs, check that the [TAGS] on the urls are absent in the output.

**Comment by deniza-pg** [comment]
Staging app test:  Tags are in the text.

**Comment by rasmus-storjohann-PG** [comment]
This issue in not resolved in the current staging app, version 1.77.0.

**Comment by rasmus-storjohann-PG** [comment]
Ignore commits already showing on this issue, those are for work done in the old django system.

The plan is to fix this in the Mongo backed. There is a [$replaceAll](https://docs.mongodb.com/manual/reference/operator/aggregation/replaceAll/) command that can be used. It doesn't handle regular expressions, so we have to do a replace for each possible square bracket tag, but there aren't that many so it's OK.

**Comment by rasmus-storjohann-PG** [comment]
This work is now being done manually as part of the MB content review. Closing the issue
