### ISSUE TITLE
Fix name and teaser text for section Welcome to Manitoba

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1565]
The name of the learn section in the top right on the screen shows up in BC as "Welcome to Manitoba" and in MB as "settling in MB", neither of which is correct

### Acceptance Criteria 
- [x]  In BC, the section has name "Welcome to B.C." and description "Social customs and getting around your community". 
- [x]  In MB, the section has name "Welcome to Manitoba" and description "Social customs and getting around your community". 
- [x] @cherrielam to confirm the copy above

See also https://github.com/pg-irc/pathways-frontend/issues/1562

### Steps for QA: 
1.

**Comment by deniza-pg** [comment]
In BC, the section has the name "Welcome to B.C." and the description "Social customs and getting around your community"

I expect to see "Welcome to BC" but instead I see Welcome to Manitoba.

In Manitoba version:
I expect to see "Welcome to Manitoba" but instead I see settling in MB with s not capital.

**Comment by rasmus-storjohann-PG** [comment]
See also #1601 , related issue, not a dupe

**Comment by alysha-PG** [comment]
yep english is right anyways
