### ISSUE TITLE
Missing teaser text on MB topics in iOS

### ISSUE THREAD

**Issue by cherrielam** [pg-irc/pathways-frontend#1567]
It appears that Manitoba topics are missing the teaser text on iOS. See examples below:

![IMG_9016.PNG](https://images.zenhubusercontent.com/5823860ee40e5714b1700133/b99bb15c-97f0-422d-910b-4d9c83b14bb8)
![IMG_9017.PNG](https://images.zenhubusercontent.com/5823860ee40e5714b1700133/c39457af-0c23-4a66-a711-7a92563d2a56)

### Acceptance Criteria 
- [ ]  Teaser text shows on Manitoba topics

### Steps for QA: 
1.

**Comment by deniza-pg** [comment]
Fixed.
