### ISSUE TITLE
MVP polish: Replace hard-coded data in Find services page

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#157]
In the Find Services tab on a task details page, replace hard-coded address and opening hours with live data from the service response. Limit scope to what can be done without any server side work and without adding `O(n)` calls to the server.

**Comment by bensinjin** [comment]
In my opinion this issue is blocked on the approval and implementation of the aforementioned spec. Once the data we require from services_at_location endpoint is further defined we can make the necessary adjustments in the app to pull in the correct fields.
