### ISSUE TITLE
"My Location" no longer works

### ISSUE THREAD

**Issue by cherrielam** [pg-irc/pathways-frontend#1570]
When I go to the search screen, enter a search term and click "My Location", I expect to see "My Location" in the search location input field, and I expect to see results sorted by distance from my location. Instead, I see that the search location input field remains empty, when I hit Search, the input field shows just the search term, not "near my location" as I expect.

https://images.zenhubusercontent.com/99282566/26a1526f-0e7b-414b-abe6-22da3fb65a4e/rpreplay_final1628033341.mp4

Staging 1.73 on iPhone XS

### Acceptance Criteria 
- [ ]  

### Steps for QA: 
1.

**Comment by rasmus-storjohann-PG** [comment]
Heyyy, @cherrielam , your video comes with sound! Nice music!

**Comment by ian-lin-PG** [comment]
@cherrielam This should be fixed in 1.74.0, or at least there was a change in to fix the issue.

**Comment by cherrielam** [comment]
Looks fixed now! I see this is assigned to @alysha-PG so will leave it to you to do any additional QA
