### ISSUE TITLE
UI Polish for MB Release

### ISSUE THREAD

**Issue by cherrielam** [pg-irc/pathways-frontend#1581]
We would like to make the following UI tweaks to give the app some polish ahead of the MB release:

- [x] Topic Card: Recommendation Icon overlaps the text on smaller devices (eg. ipod touch), and the text does not stretch to fill out all the space on larger devices (eg. iPad). The layout should be updated so the text fills all available space but the recommendation icon does not overlap the text.
- [x] Topic Card: Vertically center align the bookmark icon
- [x] Bottom Nav: Remove the shadow and increase the top border weight
- [x] Home screen: Update topic headings to be horizontal (icon is to the left of the text) instead of stacking. Reduce space above each heading
- [x] Home screen: Recommended for you description - remove Recommendation Bubble image and extend the text horizontally
- [x] Right menu drawer: Increase spacing between menu items (locales/regions)
- [x] Welcome screen: Make locale picker down arrow teal
- [x] Welcome screen: I can see a little bit of the blue background peeking out from the header image, which creates a light blue line above the "Settling in Canada is now easier" part. Hide the blue line.
- [x] Topic detail collapsed (read more): Add white gradient to the end of the collapsed text. Increase collapsed topic detail height. The white gradient should show when the text is collapsed and not when it is expanded
- [x] Help screen: Increase spacing around "For additional assistance". Align link items margins with the same margins of the text above (Title and "If you need support settling..." text)
- [x] Help screen: Update button width of buttons to extend the full width
- [x] Entire app: Increase padding around all the text that sits on the background (not text in cards) from 15 to 20
- [x] Bookmarks banner: There is currently a 8px space above and none below. We would like to remove the 8px space above and add the 8px space below.
- [x] Bookmarks page: Remove the marginHorizontal on the bookmark tab bar
- [x] Learn page: Chapter buttons - increase spacing under the Chapter title and increase top and bottom padding around the text
- [x] Questionnaire Card: Improve the collapsed questionnaire card layout so the left arrow aligns with the title text above
- [x] Search page: There is an instance where the pale colour shows up as a background colour — remove and replace with lightGrey
- [x] Shadow (used on questionnaire CTA and learn buttons): reduce the shadow darkness a touch

### Acceptance Criteria 
- [ ]  Changes above are reflected in the app!

### Steps for QA: 
1.

**Comment by deniza-pg** [comment]
Who can test these issues? @cherrielam @brandon-PG @rasmus-storjohann-PG
