### ISSUE TITLE
Content: Links not clickable

### ISSUE THREAD

**Issue by deniza-pg** [pg-irc/pathways-frontend#1588]
Some of the links in the Manitoba content are not clickable because they don't start with https://

Content should address this.

### Acceptance Criteria 
- All the links should be clickable

### Steps for QA: 
1.  Check the topics for links.

**Comment by deniza-pg** [comment]
Adding the images in the app.
Look for the yellow circle or underline.

![IMG_2682.jpg](https://images.zenhubusercontent.com/5e8b55a209056155d2dc47b1/7c9f1df6-8157-4f4a-9222-50c1a9059041)

**Comment by deniza-pg** [comment]
Cont...

![IMG_2628.PNG](https://images.zenhubusercontent.com/5e8b55a209056155d2dc47b1/987e9c95-5edc-416e-a35c-513c7cc9ddb4)

**Comment by deniza-pg** [comment]
![IMG_2630.jpg](https://images.zenhubusercontent.com/5e8b55a209056155d2dc47b1/e7f2a4ff-f74a-4faf-8f1e-971d34bde519)![IMG_2631.jpg](https://images.zenhubusercontent.com/5e8b55a209056155d2dc47b1/567445d3-8582-4536-932b-99ac650ee34e)

**Comment by deniza-pg** [comment]
![IMG_2632.PNG](https://images.zenhubusercontent.com/5e8b55a209056155d2dc47b1/9fa7e4d7-339e-44e8-a3a3-c79fd1f567d2)
![IMG_2633.jpg](https://images.zenhubusercontent.com/5e8b55a209056155d2dc47b1/8ab9f1ec-33f2-4f68-9a06-a716ac7ba95b)

![IMG_2634.PNG](https://images.zenhubusercontent.com/5e8b55a209056155d2dc47b1/a0ec71a9-edd3-4e64-a8b0-fe3c2e291090)![IMG_2635.jpg](https://images.zenhubusercontent.com/5e8b55a209056155d2dc47b1/8bf760f6-68b9-4a72-b7e4-5381f33b2600)

![IMG_2636.jpg](https://images.zenhubusercontent.com/5e8b55a209056155d2dc47b1/76c36e53-a71c-46a7-b252-11ca162be5bd)

**Comment by deniza-pg** [comment]
![IMG_2639.jpg](https://images.zenhubusercontent.com/5e8b55a209056155d2dc47b1/47370690-4ec3-4bda-abf3-2cca64ed8678)

**Comment by deniza-pg** [comment]
![IMG_2640.jpg](https://images.zenhubusercontent.com/5e8b55a209056155d2dc47b1/ec081e07-5c45-46d2-a571-b98a7cc425af)![IMG_2642.jpg](https://images.zenhubusercontent.com/5e8b55a209056155d2dc47b1/5db25407-887e-43c3-83cd-7f4a1fa73180)

![IMG_2643.jpg](https://images.zenhubusercontent.com/5e8b55a209056155d2dc47b1/f47abb8c-4494-4e57-b8a8-bfe03ca330f7)
![IMG_2645.jpg](https://images.zenhubusercontent.com/5e8b55a209056155d2dc47b1/d103a909-af67-414a-a016-534bda4a4601)

![IMG_2646.jpg](https://images.zenhubusercontent.com/5e8b55a209056155d2dc47b1/dd253104-bbc5-4711-900f-d69d25aecc40)

![IMG_2647.jpg](https://images.zenhubusercontent.com/5e8b55a209056155d2dc47b1/aa6de497-8ab9-41a7-a70c-48ac6afe98ae)

![IMG_2648.PNG](https://images.zenhubusercontent.com/5e8b55a209056155d2dc47b1/5f0888f3-cef6-491c-b727-449de285255f)

![IMG_2649.jpg](https://images.zenhubusercontent.com/5e8b55a209056155d2dc47b1/49f6aa09-0d23-4ff0-952a-f0c699a99c4a)

![IMG_2650.jpg](https://images.zenhubusercontent.com/5e8b55a209056155d2dc47b1/2d7ab041-63fd-4f3d-b1ed-551fc81aa63a)

![IMG_2651.PNG](https://images.zenhubusercontent.com/5e8b55a209056155d2dc47b1/27d9b804-221c-47c6-bd08-9b8a65723f8c)

![IMG_2652.jpg](https://images.zenhubusercontent.com/5e8b55a209056155d2dc47b1/ba90cbe4-c14e-4622-82dd-df8d1adc7916)

![IMG_2653.jpg](https://images.zenhubusercontent.com/5e8b55a209056155d2dc47b1/5a4eeddf-9d30-4515-89bb-8937154386fe)

![IMG_2654.jpg](https://images.zenhubusercontent.com/5e8b55a209056155d2dc47b1/e23b97b5-8969-4ecc-befd-8a8900a114a7)

![IMG_2655.jpg](https://images.zenhubusercontent.com/5e8b55a209056155d2dc47b1/2dabe0c5-bc9d-410b-af96-0c9e7586029e)

![IMG_2656.PNG](https://images.zenhubusercontent.com/5e8b55a209056155d2dc47b1/1db8893a-894a-4a06-b249-7041dd102749)

![IMG_2658.jpg](https://images.zenhubusercontent.com/5e8b55a209056155d2dc47b1/e967bd1e-e7a3-44c1-ac37-4cc7dc44aa63)

![IMG_2659.jpg](https://images.zenhubusercontent.com/5e8b55a209056155d2dc47b1/6c7c1887-8c0c-4d38-a7d3-0568aa93e630)

![IMG_2660.PNG](https://images.zenhubusercontent.com/5e8b55a209056155d2dc47b1/de6b76d1-16c3-497a-ba49-dcf7f048fb4d)

![IMG_2661.jpg](https://images.zenhubusercontent.com/5e8b55a209056155d2dc47b1/cc3ca684-5294-467c-a878-15759aa369b4)

![IMG_2662.PNG](https://images.zenhubusercontent.com/5e8b55a209056155d2dc47b1/d84e9bb7-3cc4-4ca8-9d2a-cfeb3f24ca4d)

![IMG_2664.PNG](https://images.zenhubusercontent.com/5e8b55a209056155d2dc47b1/83459f88-cdf8-43cb-9aaa-0ff66dbea87a)

![IMG_2665.PNG](https://images.zenhubusercontent.com/5e8b55a209056155d2dc47b1/2614104d-a86d-4a41-aa7f-baed4f84fcbd)

**Comment by deniza-pg** [comment]
![IMG_2667.PNG](https://images.zenhubusercontent.com/5e8b55a209056155d2dc47b1/6fc451ad-47ff-42e6-a328-0e5be0da310d)![IMG_2671.PNG](https://images.zenhubusercontent.com/5e8b55a209056155d2dc47b1/efbae067-7b6b-457a-94c8-bdc4839f18e5)![IMG_2672.jpg](https://images.zenhubusercontent.com/5e8b55a209056155d2dc47b1/76d3379c-0d2e-4f2a-a95f-ccf4dd4dabab)![IMG_2673.jpg](https://images.zenhubusercontent.com/5e8b55a209056155d2dc47b1/2b1043a7-41de-479a-a4c6-73e94a47b5ba)![IMG_2674.PNG](https://images.zenhubusercontent.com/5e8b55a209056155d2dc47b1/f416fd17-5cef-442c-97e8-1c954b43b7ee)![IMG_2675.jpg](https://images.zenhubusercontent.com/5e8b55a209056155d2dc47b1/fc715f21-9334-4d62-8e60-693e4c32936f)
![IMG_2676.PNG](https://images.zenhubusercontent.com/5e8b55a209056155d2dc47b1/9b6f6c6f-6f12-44dd-8f88-51ed5f5ef0be)

![IMG_2677.jpg](https://images.zenhubusercontent.com/5e8b55a209056155d2dc47b1/6de142c8-a8be-451c-a9a0-94e29da71e54)

![IMG_2678.PNG](https://images.zenhubusercontent.com/5e8b55a209056155d2dc47b1/321dd4a7-ab45-474b-abc1-97415dbbe011)

![IMG_2679.jpg](https://images.zenhubusercontent.com/5e8b55a209056155d2dc47b1/6fd1a746-b89a-45f9-b725-cb1f8145819b)

![IMG_2680.jpg](https://images.zenhubusercontent.com/5e8b55a209056155d2dc47b1/b0804bbc-7a33-422d-a171-596ac07f7bdd)

![IMG_2681.PNG](https://images.zenhubusercontent.com/5e8b55a209056155d2dc47b1/04da0c17-84c1-4f0c-857d-156b08a744ef)

![IMG_2682.jpg](https://images.zenhubusercontent.com/5e8b55a209056155d2dc47b1/ae3dd3c0-3949-4cc0-a078-d1b8b8d9e9da)

![IMG_2641.PNG](https://images.zenhubusercontent.com/5e8b55a209056155d2dc47b1/6f2fa76e-8d90-4ad6-82b6-ef26867a25af)

**Comment by alysha-PG** [comment]
all English MB links are clickable!
