### ISSUE TITLE
Integrate translated UX strings back into app

### ISSUE THREAD

**Issue by alysha-PG** [pg-irc/pathways-frontend#1590]
Translated UX strings can be found here:

https://drive.google.com/drive/u/2/folders/1d1ZDMh3SIsV8QUN9onvbcwPcKV0pzvsY

- [x] BC UX strings (multilingual)

- [x] MB UX strings (French)

**Comment by rasmus-storjohann-PG** [comment]
![image](https://user-images.githubusercontent.com/32307781/131388325-0959ebbb-975d-476c-929d-5d7a479a5ce9.png)

**Comment by rasmus-storjohann-PG** [comment]
![image](https://user-images.githubusercontent.com/32307781/131397798-5f87e7c9-b8d8-403b-bc3c-13830e994260.png)

**Comment by deniza-pg** [comment]
![IMG_2156](https://user-images.githubusercontent.com/63252138/131402009-9a2f1103-e267-4512-afa2-3745e66b8e6f.PNG)
![IMG_2155](https://user-images.githubusercontent.com/63252138/131402013-c8d96cb1-75be-45fc-acbe-d6fd89bbde79.PNG)
![IMG_2154](https://user-images.githubusercontent.com/63252138/131402018-a9f9cf64-c8bc-48d4-8856-4a1b92ea7a76.PNG)
![IMG_2153](https://user-images.githubusercontent.com/63252138/131402019-ce514521-5e54-4dbf-8c60-5d80b3f99329.PNG)
![IMG_2150](https://user-images.githubusercontent.com/63252138/131402022-6743b2d4-cece-4a41-8503-cdeb4faa95c8.PNG)
![IMG_2149](https://user-images.githubusercontent.com/63252138/131402025-6b9d03ba-2368-43a8-83bb-7627438a7767.PNG)
![IMG_2148](https://user-images.githubusercontent.com/63252138/131402026-b4c78109-6ed1-4013-9aee-edf7c9e239a2.PNG)

![IMG_2157](https://user-images.githubusercontent.com/63252138/131402000-18c7d678-1ffd-48a4-8909-9be0ffb7b120.PNG)

**Comment by rasmus-storjohann-PG** [comment]
![image](https://user-images.githubusercontent.com/32307781/133337535-4931349b-5430-4549-a704-a70b4a2d7ffa.png)
