### ISSUE TITLE
Update copy of AA website to reflect BC+MB availability, w/translation

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1597]
### Acceptance Criteria 
- [x]  We have updated copy
- [x] Updated copy is translated into French
- [ ] QA has checked the website translations

See doc with copy here https://docs.google.com/document/d/1PAgBvCOsch8qfzqrab2EOqpkV6kloYuxsMP7yGXkXPI/edit

**Comment by alysha-PG** [comment]
French QA not super thorough as none of us are native speakers but good enough for now.
