### ISSUE TITLE
MVP polish: Support RTL on all text fields

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#162]
ACs:
* Mark all Text elements with textAlign left to make RTL work, see comment from @tnightingale on https://github.com/pg-irc/pathways-frontend/issues/56: 

*Explicitly setting the text-align style on the <Text> components to "left" solved the wrapping problem. We will need to be vigilant in being explicit about alignment so that I18nManager.forceRTL() can do its job.*

**Comment by bensinjin** [comment]
Are we sure this needs to be done everywhere? Doesn't this already work correctly in most places?

**Comment by tnightingale** [comment]
It's likely that the `text-align` property is inherited so that it only needs to be set on a parent for children to benefit. Now that `native-base` components are being used for most page's structure, I suspect alignment is being set implicitly in a lot of cases.

**Comment by trisapeace** [comment]
Unfortunately it doesn't look like it inherits. I tried changing 
```
        <View style={{ padding: 20 }}>
            <Text><Trans>No related services found.</Trans></Text>
        </View>
```
to
```
        <View style={[
            { padding: 20 },
            {textAlign: 'left' },
        ]}>
            <Text><Trans>No related services found.</Trans></Text>
        </View>
```
but that didn't work.

Whereas, changing it to
```
        <View style={{ padding: 20 }}>
            <Text style={[ {textAlign: 'left' }]}><Trans>No related services found.</Trans></Text>
        </View>
```
did work.
