### ISSUE TITLE
Some chapter titles missing translations on Learn page (BC only)

### ISSUE THREAD

**Issue by alysha-PG** [pg-irc/pathways-frontend#1625]
on Learn page, I expect to see chapter titles "Welcome to Manitoba"/"Welcome to BC" and "Family & Specialized Support" show up in the translated language. Instead, I see them appear in English in both MB and BC.

![Image from iOS (7)](https://user-images.githubusercontent.com/85197659/134596114-8c7008b6-0bc9-494d-9a6c-baf5457b538f.png)
![Image from iOS (6)](https://user-images.githubusercontent.com/85197659/134596120-1cd634de-afd5-48d5-917a-b8a9f702c97e.png)
![Image from iOS (8)](https://user-images.githubusercontent.com/85197659/134596126-4937b2d4-3f47-447f-aee6-979893be5430.png)
![Image from iOS (9)](https://user-images.githubusercontent.com/85197659/134596166-a761b184-fe75-4901-ab9c-990bebac65be.png)

### Acceptance Criteria 
- [ ]  all text on Learn page appears in correct translated language, namely "Welcome to ____" and "Family & Specialized Support"

### Steps for QA: 
1.  navigate to learn page
2. view all of the topics being in the correct translated language in all languages, including mb and bc

**Comment by alysha-PG** [comment]
1 small error to fix -
In Korean the text for "Support for disabilities, youth, seniors, income" is accidentally written in Tagalog. Change to this in Korean: 저소득층, 장애우, 청소년 지원

![Image from iOS (22)](https://user-images.githubusercontent.com/85197659/141201506-3342489a-bd8a-4895-befc-afcb9f3f0225.png)

**Comment by Farouk-PG** [comment]
Fixed and moved to In review

**Comment by Farouk-PG** [comment]
Closed with comment accidentally :)

**Comment by rasmus-storjohann-PG** [comment]
QA: When building locally, the string falls back from Korean to English (rather than Tagalog). Need to check this in the staging app.

**Comment by alysha-PG** [comment]
Korean topics now have all Korean titles and content!
