### ISSUE TITLE
UI/UX Design Polish

### ISSUE THREAD

**Issue by cherrie-pg** [pg-irc/pathways-frontend#1633]
**INSTRUCTIONS: This issue is used to collect requested UX/UI tweaks intended to improve the visual interface and address minor usability issues. If you find a major usability issue, please file a separate issue. You can edit this issue or write a comment.** 

### Issues

- [x] **Service detail - Add margin/padding to the left of "Email" component**: Email is misaligned with the other items on the page

![IMG_9977](https://user-images.githubusercontent.com/21990736/136092286-e0cba7e9-16bc-43e4-97fe-8b1c1c7c4f24.PNG)

- [x] **Add shadow under the Topic-Services search header to match the Search page**: On the Search page, there is a shadow underneath the header section which holds the search bars. I expect to see this shadow also under the header that contains the location search bar on the Topic-Services page

![IMG_9975](https://user-images.githubusercontent.com/21990736/136092351-48a82a1a-f125-4110-80cc-5933a26d59ba.PNG)

- [x] ** ALREADY DONE - Move the Bookmark toast higher on iPhone X models**: The Bookmark toast current covers the bottom nav on iPhone X models and should be above the bottom Nav

![IMG_9976](https://user-images.githubusercontent.com/21990736/136092609-6c5b2622-da3b-450e-bd21-40d8e61f5d71.PNG)

- [x] ALREADY DONE, IGNORE **Improve header styling on Topic Detail markdown**: The headers within the markdown are hard to read. Could we add a margin-bottom to the header and make it bold?

![IMG_9978](https://user-images.githubusercontent.com/21990736/136092727-cb2ca986-c596-4a9f-acf0-f1e77e3cddd8.PNG)

### Acceptance Criteria 
- [ ]  

### Steps for QA: 
1.

**Comment by brandon-PG** [comment]
The shadow under the topic services search header should be tested on both android and iOS because they behave differently

**Comment by Kaylee-PG** [comment]
I can confirm that all of these changes have been successfully made after looking at all 4 individually in the staging app.
