### ISSUE TITLE
Slight lag in the Topic Detail image loading 

### ISSUE THREAD

**Issue by cherrie-pg** [pg-irc/pathways-frontend#1635]
There is a slight lag in loading of the image on the Topic Detail page when opening related topics, you can see the image of the prev. topic for a second before it switches. 

Expected behaviour: Does not show the previous topic's image before it loads the correct Topic image (either blank until it loads or ideally load straight away)

https://images.zenhubusercontent.com/99282566/62847b68-5475-4d83-a035-a317b0f2dec5/rpreplay_final1633462777.mp4

### Acceptance Criteria 
- [ ] Topic Detail does not show the previous topic's image before it loads the correct Topic image (the image is either blank until it loads or ideally loads straight away)

### Steps for QA: 
1.

**Comment by Farouk-PG** [comment]
Issue looks ok and couldn’t be reproduced! Closing
