### ISSUE TITLE
Organization page does not load for Manitoba topics

### ISSUE THREAD

**Issue by brandon-PG** [pg-irc/pathways-frontend#1651]
Clicking on the organization name should bring up the organization page with a description and child services.

See video: https://drive.google.com/file/d/1ezhRQojkcSyWLlDuIBSXA3lY0wKaphSm/view?usp=sharing

### Acceptance Criteria 
- [ ] Organization page loads with correct data

### Steps for QA: 
1.  Find a manitoba service page
2. Click on the organization name
3. Verify the page loads with description and services

**Comment by alysha-PG** [comment]
org page now loads!
