### ISSUE TITLE
BC Questionnaire Issues

### ISSUE THREAD

**Issue by deniza-pg** [pg-irc/pathways-frontend#1656]
**IN BC MULTIPLE LANGUAGES**:
- Q3 age groups in every language except English, French, and Arabic: numbers listed are wrong; should be Under 5, 5-12, 13-18, 18-64, 65+
Fix in:
- [x] Tagalog
- [x] Chinese (S)
- [x] Chinese (T)
- [x] Korean
- [x] Punjabi
- Q4 current housing in every language except English: the first 2 options are the same; should be "I want to rent a place to live" and "I already rent a place to live".
Fix in:
- [x] Tagalog
- [x] Chinese (S)
- [x] Chinese (T)
- [x] Korean
- [x] Punjabi
- [x] French
- [x] Arabic

### Low Priority
**FROM BC ARABIC TO MB ENGLISH**:

- "Weird bug happens when I run the app in BC in AR, switch provinces to MB, and when I open the questionnaire in MB, suddenly the questionnaire starts on Q2. I expect the questionnaire to start on Q1 since I haven't ever completed it yet.
- See video: https://drive.google.com/file/d/1o_EcNCSR_MNnWWJ5Bk0qg03Gj2OJSn2a/view?usp=sharing"
    - Rasmus: Fixed

**IN BC MULTIPLE**:

Q3 Age groups has correct age categories in:
- [x] Tagalog
- [x] Chinese (S)
- [x] Chinese (T)
- [x] Korean
- [x] Punjabi

Q4 has different first 2 options in
- [x] Tagalog
- [x] Chinese (S)
- [x] Chinese (T)
- [x] Korean
- [x] Punjabi
- [x] French
- [x] Arabic

- [x] switching from BC arabic to MB english starts on Q1

**Comment by Farouk-PG** [comment]
Just a friendly request to include the string in future update requests to make it easier to allocate the string and update the needed changes for all languages. For example: main string is “under age of 5”, but in language “insert language”, it’s “under age of 8”.

**Comment by rasmus-storjohann-PG** [comment]
The Q3 issues have been resolved, the Q4 issues have not, will dig into this
