### ISSUE TITLE
Missing teaser text

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1666]
When I look at a topic list screen, I expect to see, for each topic. the topic title and the first line of the topic content, aka the "teaser". I observe that for MB content, many topics do not have a topic teaser line.

On topic card: "Applying for a driver's licence of Manitoba Identification Card", "Renting a car", "Safe driving resources", "Finding child care", "Housing for seniors", "Languages of instruction", "Public schools", I expect to see the teaser text, but I see a blank space

**Comment by alysha-PG** [comment]
teaser text now shows in MB/EN and MB/FR
