### ISSUE TITLE
Stretch: Make Welcome screen even better with instant localization

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1678]
Follow up to https://github.com/pg-irc/pathways-frontend/issues/1673

In that issue, all localization was taken out of the welcome screen. Reasoning: It will always be in English because it’s shown when people run the app for the first time, and after all memory has been cleared for the app, in both cases the user’s preferred locale is unknown and we should fall back to En.

However, even better would be to make the welcome screen update immediately on the user changing the value in the Select Language drop down. 

This would need to *not* involve setting the locale on the app, since that is slow and complicated. Instead, we would need to do our own manual localization within the component. The component contains five strings. Make five lookup tables populated with the localized strings using the `i18n._()` function, holding all the localizations for the five strings. When the drop down value changes, pull the strings from the selected locale to display for the five strings. 

### Acceptance Criteria 
- [ ]  When the user changes the selected language in the welcome screeen, all five strings in the screen immediately update to the selected language.

**Comment by brandon-PG** [comment]
Strings from another language cannot be accessed unless that language is activated
