### ISSUE TITLE
“Brought to you by” section links appear on the left side in Arabic

### ISSUE THREAD

**Issue by Farouk-PG** [pg-irc/pathways-frontend#1684]
clicking on “Brought to you by” section in Arabic, links for PeaceGeeks, welcomebc, and bc211 appear on the left side. Expected to have them under the texts on the right side.

### Acceptance Criteria 
- [ ]  links are from right side under text

![IMG_5303](https://user-images.githubusercontent.com/89798867/137547670-6f894aee-f498-47de-a83d-90b81aebcbaa.PNG)

**Comment by alysha-PG** [comment]
links are now right-aligning!
