### ISSUE TITLE
Questionare in Manitoba recommended topics not expected : Case 2

### ISSUE THREAD

**Issue by deniza-pg** [pg-irc/pathways-frontend#1690]
When I test the questionnaire I follow the following steps:

Clear all data from the app (go to ? Help, Clear all Data). Go to the questionnaire. 
On Question 2, Select the answer "Less than 1 year". 
On Question 4, mark that you have all documents.  

I expect to see that recommended topics that show up are, since these are "recommended to all": 
1.1 Manitoba Start & Settlement agencies, 
1.2 General information, 
1.5 Weather in Manitoba, 
1.7 Buying food, 
1.8 In your community: Recreation centres, Public libraries, Canada Post, 
2.1 Types of housing, 
2.7 Household waste management, 
3.1 Canadian money and banking, 
4.7 Vaccinations, 
7.5 Public transportation

But instead, I see:
Social Insurance Number,
Opening a bank account
Credit and credit history
Canadian money and banking

### Acceptance Criteria 
- [ ]  

### Steps for QA: 
1.

**Comment by rasmus-storjohann-PG** [comment]
Closing this issue, it will be solved as part of https://github.com/pg-irc/pathways-frontend/issues/1689
