### ISSUE TITLE
MB UX Polish - BC teal shows up in MB

### ISSUE THREAD

**Issue by alysha-PG** [pg-irc/pathways-frontend#1693]
In MB side, I expected to see only MB green colour scheme, but there are a few places where BC teal pokes through. Change all instances to MB green.

- [x]  Invalid location page circular arrows and "Try again"
<img src="https://images.zenhubusercontent.com/60b823128e6f424e93549168/a9dab9bc-4e8f-4330-bd84-651d5b108891" width=300 align=centre><br>
<br>
- [x]  All links within topics should be green
<img src="https://images.zenhubusercontent.com/60b823128e6f424e93549168/b9cf079b-3434-4500-a30b-ec9371c61e98" width=300 align=centre><br>
<br>
- [ ] Topic-services find related services near me banner - content will be updated to read "call MB211", but teal must also be changed to green
<img src="https://images.zenhubusercontent.com/60b823128e6f424e93549168/7e19b99d-dd62-42d6-bce2-3fb0a96f4e1c" width=300 align=centre><br>
<br>

- [x] Link on Manitoba Start page - greenify (and bold, can you do that too plz?)
<img src="https://images.zenhubusercontent.com/60b823128e6f424e93549168/cf8763f8-5d96-4171-ac97-e09bf5ea57c9" width=300 align=centre><br>
<br>
- [ ] Bookmarks topics and services icon shows teal colour scheme but should have no illustration 
**Zeplin source file with correct bookmarks page [here](zpl.io/VKBQ1JP)**
<img src="https://images.zenhubusercontent.com/60b823128e6f424e93549168/c6660d6e-cdb4-44ca-a160-14b1ff543f58" width=300 align=centre><br>
<br>
- [ ] Server error page "try again" (This may be the same as invalid search page)
<img src="https://images.zenhubusercontent.com/60b823128e6f424e93549168/73453e85-de9a-4268-b03c-352c3b10bc96" width=300 align=centre><br>
<br>
- [ ] When loading services - spinning circle (android) and star thingie (iphone) is teal - see video [here](https://drive.google.com/file/d/1FJmmnxWVRbz47ScKHggZKK4uJUtOjvCP/view?usp=sharing)
<br>

### Acceptance Criteria 
- [x]  Go to search and search for any service, enter crap in the location field. Ensure page that comes up has green arrows and "Try again".

- [x] Check all MB topics and ensure all links are green

- [x] Go to any topic, click "find services near me" and ensure the banner says MB211 and is green

- [x] Go to MB Start page and ensure link to their website is bolded and green

- [x] Go to bookmarks and ensure no illustration is there

- [x] Search for a service and observe the loading spinning thing is green.

- [x] Ask dev to take server down for a second. Go to search, confirm it's green,

**Comment by rasmus-storjohann-PG** [comment]
Only outstanding issue: URL colour in the dynamic content alert box
