### ISSUE TITLE
Bookmarking services causes screen jump on android in production

### ISSUE THREAD

**Issue by alysha-PG** [pg-irc/pathways-frontend#1695]
In production, In both BC and MB, when I bookmark services on android, I expect it to stay steady. Instead, after scrolling down, the top bar  "Find a Service" or in French "Trouver a Service" re-appears when a service is bookmarked. It disappears when a service is unbookmarked.

See extremely high-tech video of a phone screen [here](https://drive.google.com/file/d/1SAoqoJP-s6X1CCAn6eZ1366O7F9oC5Yv/view?usp=sharing).

### Acceptance Criteria 
- [ ]  Top bar does not appear/reappear, or never disappears - either way, there isn't an awkward jump when I bookmark or unbookmark services.

**Comment by Farouk-PG** [comment]
this issue seems to be gone in the last release. can someone confirm?

**Comment by Farouk-PG** [comment]
Closing this as it’s fixed already in staging. Let’s just keep an eye out to see if it comes back. Sometimes updating a third party library can resolve issues like this (or make them appear).
