### ISSUE TITLE
Push notification for product-market fit research

### ISSUE THREAD

**Issue by alysha-PG** [pg-irc/pathways-frontend#1696]
We want to establish AA's product-market fit - in other words, what is the most valuable part of the app, and for whom? We will do that by sending a push notification to users which sends them to a survey.

Logic: users who have had the app downloaded longer than 5 days
Language: Send in English to all users (future rounds we will look at other languages).
**Timing**: it should be sent out on Tuesday at 7pm.

Push notification-
Title: **:compass emoji:** Using Arrival Advisor 
Text: We want to hear how you use Arrival Advisor. Answer 5 quick questions to help us improve!

In-app dynamic content:
Title: We want to hear from you! :compass emoji:
Text: Tell us how you would feel if you could no longer use Arrival Advisor by answering these [5 questions](https://tally.so/r/n0vEP3).

**Comment by brandon-PG** [comment]
All notifications sent on Monday, Nov 15th
