### ISSUE TITLE
Unicode Problems in BC Service data

### ISSUE THREAD

**Issue by alysha-PG** [pg-irc/pathways-frontend#1698]
When I'm in Search in BC, I expect to see flawless text. Instead, I see Unicode problems such as this character > � in place of special characters from accented characters in French and in other random spots. Note: for the English 'random spots', it appears to be happening with spaces, especially spaces right after a period, but happens between random words as well.

French Example:
<img src="https://images.zenhubusercontent.com/60b823128e6f424e93549168/30111b18-05a5-4990-8eb2-8e7aaab68959" width=300 align=centre><br>

BC/English/Housing/Homelessness examples:
� appears in description of The Vancouver Recovery Club - Homeless Outreach Program
� appears in description of The Bloom Group - Powell Place Emergency Shelter for Women
� appears in description of Fraser Region Aboriginal Friendship Centre Association - Aboriginal Homeless Outreach/Homelessness Prevention Program
� appear in description of Progressive Housing Society - Burnaby Housing and Outreach Hub

BC/English/Housing/Finding a place to rent example:
� appears in description of BC Housing - BC Housing Storefront Office

### Acceptance Criteria 
- [ ] Service data does not have html markup or unicode errors.

**Comment by rasmus-storjohann-PG** [comment]
@rasmus-storjohann-PG to communicate with BC211 about this. The data we received from them contains "this is an invalid unicode character" characters that we can't convert to anything valid.

**Comment by rasmus-storjohann-PG** [comment]
The cause of this problem is actually in our Mongo system. The unicode characters look right in the data we received from BC211, but is wrong in the data we upload to Algolia.

**Comment by rasmus-storjohann-PG** [comment]
The problem is there in Mongo DB before the data is exported

**Comment by Kaylee-PG** [comment]
This issue is still NOT RESOLVED. In the search, the same unicode. issues arrise for the searches Alysha has indicated.
