### ISSUE TITLE
BC/FR topic detail - some accents don't render in correct font

### ISSUE THREAD

**Issue by alysha-PG** [pg-irc/pathways-frontend#1699]
When I go to BC/FR, I expect accents to render in the same font as the rest of the text (as they correctly do in MB/FR). Instead, sometimes they render in a different font. Note - this issue shows up inconsistently in BC/FR, and even certain topics have correct accents for the first half of the topic, and incorrect accents in the second half.

<img src="https://images.zenhubusercontent.com/60b823128e6f424e93549168/7134a428-0d4f-4cae-84d4-ffb77074448e" width=300 align=centre><br>

### Acceptance Criteria 
- [x]  French topics in BC render with correct font on accents

**Comment by brandon-PG** [comment]
Caused by the font family not having a character for `U+0301 : COMBINING ACUTE ACCENT` which is sometimes used
