### ISSUE TITLE
BC Arabic layout on Learn page is misaligned

### ISSUE THREAD

**Issue by cherrielam** [pg-irc/pathways-frontend#1700]
When I switch to Arabic in BC, the learn tiles are slightly more to the right and not centered: 

I expect them to be centered: 
![IMG_0241.PNG](https://images.zenhubusercontent.com/5823860ee40e5714b1700133/31cf82a8-d6e3-4965-9c9c-ba57c45dad27)

### Acceptance Criteria 
- [ ]  The Arabic Learn page is centered

### Steps for QA: 
1.

**Comment by Farouk-PG** [comment]
This looks like it’s solved now. Can someone else also confirm please?
