### ISSUE TITLE
Client crashes when loading data with old schema from persistent storage

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1704]
We have recently made a schema change so that service descriptions that used to be a string (for EN only) now is a map from any number of locale identifiers to description in that locale. When the old kind of data sits in client persistent storage, and the client tries to load that into its store, data validation fails and the app crashes.

### Acceptance Criteria 
- [ ]  The app loads successfully with old or new service data in memory

### Steps for QA: 
1.  Install an old version of the app on the device
2. Search for some services to populate the device cache
3. Upgrade to the new version of the app
4. Start the app and observe that it does not crash

**Comment by Farouk-PG** [comment]
this is working. closing
