### ISSUE TITLE
UX glitch in language selector component

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1719]
![image](https://user-images.githubusercontent.com/32307781/142044156-1282b818-5969-4677-a5ce-f886fbbf02d3.png)

Expected is that the language selector is a rounded rectangle. Observed is that part of the rectangle is not visible on my android device.

### Acceptance Criteria 
- [x]  Language selector looks correct on the device

**Comment by rasmus-storjohann-PG** [comment]
Observed on my Android phone

**Comment by rasmus-storjohann-PG** [comment]
Improved dialog for @cherrielam  to review 
<img width="406" alt="image" src="https://user-images.githubusercontent.com/32307781/144331448-981465d3-6e94-4d49-bbef-99535792714a.png">

**Comment by cherrielam** [comment]
Looks good to me
