### ISSUE TITLE
Weblate and ui-strings build process improvement

### ISSUE THREAD

**Issue by Farouk-PG** [pg-irc/pathways-frontend#1724]
Currently, to build strings from Weblate and pull them into the app, we have been relying on dispersed information in different places and set of commands that’s not solidified. This Issue aims to enhance and organize the process in a way that makes it timely and reliable.
  
### Acceptance Criteria 
- [x]  README files have clear and accessible information that directs developers to do the process seamlessly
- [x] Strings build commands are tested and located in applicable README files instead of a google doc.
- [x] Ideally all applicable details are located in one place/section

**Comment by rasmus-storjohann-PG** [comment]
Documentation for the localized string management updated and located at https://github.com/pg-irc/pathways-frontend/tree/develop/locale
