### ISSUE TITLE
In production, Arabic word rolled back to the old one that has a typo

### ISSUE THREAD

**Issue by Farouk-PG** [pg-irc/pathways-frontend#1729]
Try to select Arabic from the language bar, you will see it rolled back to the old word which has a typo. Word should be “عربي” instead of “عربى”.

### Acceptance Criteria 
- [ ]  Change word from “عربى” to “عربي”

### Steps for QA: 
1.  

![IMG_5589.PNG](https://images.zenhubusercontent.com/6143da2a0fad6548c933b051/3547c9f4-8e97-48aa-af08-2504ef80ec7c)

**Comment by rasmus-storjohann-PG** [comment]
We need to know why this happened

**Comment by rasmus-storjohann-PG** [comment]
In the staging app v.1.85.0, this has been fixed. As of Wednesday night in develop, this problem has been fixed. Let's keep a close eye on it.

**Comment by rasmus-storjohann-PG** [comment]
Make sure to check this in 1.87.0

**Comment by alysha-PG** [comment]
in 1.87.0 language selector is showing correct “عربي"
