### ISSUE TITLE
Production app home page has inconsistent text boxes spacing

### ISSUE THREAD

**Issue by Farouk-PG** [pg-irc/pathways-frontend#1730]
On production app, go to home page in any language, it shows an inconsistent spacing on the sides of text boxes as shown below. 

### Acceptance Criteria 
- [ ]  boxes are well aligned from tope to bottom

### Steps for QA: 
1.  
![IMG_5590](https://user-images.githubusercontent.com/89798867/142709032-ba639894-ebf1-4272-9973-3673e4c88d96.PNG)

**Comment by rasmus-storjohann-PG** [comment]
This is not about different width boxes, it's the background colour being white at the top and beige(?) further down. @cherrielam can you review this design to consider any adjustments?

**Comment by Farouk-PG** [comment]
Looks like it’s not a bug but rather a design where it covers topics starting from under the questionnaire box . Closing
