### ISSUE TITLE
Production app takes longer when moving from bookmark to home icons

### ISSUE THREAD

**Issue by Farouk-PG** [pg-irc/pathways-frontend#1731]
In production app, use the icons bar at the bottom to switch from search icon to home icon. It shows that only when moving from bookmark icon to home icon that the app takes a bit longer.
### Acceptance Criteria 
- [ ]  moving through the icons take the same amount of time.

https://user-images.githubusercontent.com/89798867/142709196-61c05a87-5c14-4f33-b76d-0bb7e667566c.MP4

### Steps for QA: 
1.

**Comment by rasmus-storjohann-PG** [comment]
There is a small delay due to the complexity of the home page, but it's minor and not high priority to optimize at this time
