### ISSUE TITLE
Implement Algolia search suggestions

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1736]
This is an algolia feature, see 5 minute "course" on how to do this: https://academy.algolia.com/guides/83ba478c-e7ab-11ea-aeed-067360dfb065/tasks/0ce69ffa-19fd-11eb-884d-067360dfb065

### Acceptance Criteria 
- [ ]  When the user types in a keyword search, suggested queries appear below the search bar, based on previously executed searches as stored and processed by Algolia

**Comment by rasmus-storjohann-PG** [comment]
Hold off on investing in building this feature until we know that we will keep using Algolia for a good long while into the future.

**Comment by alysha-PG** [comment]
dupe of #1175
