### ISSUE TITLE
Paragraph about BC211 missing from Chinese translation of relevant topic

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1742]
Opened the content repo. Navigated to Chapter 1 - How to use directories and the internet. Opened the two Chinese translations. Observed that the first paragraph containing information about BC211 is missing from both Chinese translations. Expected is that the Chinese translations will match the English text.

This could well have been a mistake made when copying this data out of the old PDF sources we had back in the day.

Discovered this as part of the QA for #1716

### Acceptance Criteria 
- [x]  The two Chinese translations for this topic is complete.

**Comment by rasmus-storjohann-PG** [comment]
Pull the correct Chinese texts from the original BC newcomers' guide in Chinese traditional and simplified

**Comment by alysha-PG** [comment]
Fun fact, the newcomers guide actually doesn't include the blurb about bc211 in that location, it's just been added in the app in all the languages except for Chinese. So, here's the translation, which can be added to the beginning of the topic.

**EN for your reference (already in topics)**
BC211
BC211 helps people find all kinds of
community, government, and social
services. People in Metro Vancouver,
Squamish-Lillooet, Fraser Valley, and the
Sunshine Coast can dial 2-1-1 for free,
confidential service in several languages.
Visit the website for information and
resources. There is also an online chat
service that you can use to ask questions.
www.bc211.ca 

**CN (simplified)**
BC211 
BC211讓你尋找各式各樣的社區，政府和  社會服務。大溫地區，Squamish-Lillooet，菲莎河谷和陽光海岸可免費直撥2-1-1查問。具備多種語言提供保密服務。你亦可瀏覽其網站獲取信息和資源。網站還設有在線聊天服務，讓你直接提問。
www.bc211.ca

**CN (traditional)**
BC211 
BC211讓你尋找各式各樣的社區，政府和  社會服務。大溫地區，Squamish-Lillooet，菲莎河谷和陽光海岸可免費直撥2-1-1查問。具備多種語言提供保密服務。你亦可瀏覽其網站獲取信息和資源。網站還設有在線聊天服務，讓你直接提問。

**Comment by rasmus-storjohann-PG** [comment]
@alysha-PG to confirm that the translations are correct

**Comment by alysha-PG** [comment]
I hereby confirm translations are correct - use above plz.

**Comment by Kaylee-PG** [comment]
I can confirm that after matching up areas of text in both simplified and traditional Chinese, the update has been made and the app now has the correct information for the BC 211 information in these languages.
