### ISSUE TITLE
Tab headings missing in the bookmarks page

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1743]
Go to the bookmarks page. Observe the Topics and Services tabs at the top do not have the "Topics" and "Services" heading. Tapping the headings and swiping between the tabs works on my device (Rasmus) but only swiping works on Alysha's device. This problem appears in either BC and MB regions, and in different languages. Expected is that the tab headings "Topics" and "Services" appear.

**Comment by rasmus-storjohann-PG** [comment]
QA: Make sure to test on Android and iOS

**Comment by alysha-PG** [comment]
working on iphone, still need to test on android

**Comment by alysha-PG** [comment]
working on android
