### ISSUE TITLE
MB "General Information" topic 1.2 content change

### ISSUE THREAD

**Issue by alysha-PG** [pg-irc/pathways-frontend#1749]
The content from the WIN guide in MB topic "General Information" under "311 City Service" is wrong and we need to adjust it.

Now it reads:

- Dial 311 on your phone to get information and referrals to community and social services in the Winnipeg area. This service is available 24 hours a day, 365 days a year in more than 150 languages. 311 is free and completely confidential.

- Composez le 311 sur votre téléphone pour obtenir des informations et des références aux services communautaires et soxiaux de la région de Winnipeg. Ce service est disponible 24 heures sur 24, 365 jours par an dans plus de 150 langues. 311 est gratuit et totalement confidentiel.

**Change it to:**
- Dial 311 on your phone to get information and referrals to city services in the Winnipeg area. This service is available 24 hours a day, 365 days a year in English and French. 311 is free and completely confidential.

- Composez le 311 sur votre téléphone pour obtenir des informations et des références aux services municipaux de la région de Winnipeg. Ce service est disponible 24 heures sur 24, 365 jours par an dans anglais et en français. 311 est gratuit et totalement confidentiel.

**Comment by Kaylee-PG** [comment]
I can confirm that both the English and French text has been updated to the new text for the 311 information.
