### ISSUE TITLE
Custom lat long breaks mb search

### ISSUE THREAD

**Issue by brandon-PG** [pg-irc/pathways-frontend#1754]
Using the custom lat long search feature then switching to mb search does not allow for any searching functionality.

### Acceptance Criteria 
- [ ]  Mb search should function after custom lat long is set

### Steps for QA: 
1.  Make a search in bc with the location set to 'Custom 49.16, -123.11'
2. Switch to Manitoba
3. Make a generic search such as 'health' in 'winnipeg'
4. Verify search results appear

**Comment by alysha-PG** [comment]
This is not a feature that users would notice is off, but should still be fixed.

**Comment by rasmus-storjohann-PG** [comment]
Search for string `alert(`Custom LatLong enabled,` to find relevant code, I think...

**Comment by alysha-PG** [comment]
have done QA steps above and search results do appear
