### ISSUE TITLE
Website does not appear in service detail page

### ISSUE THREAD

**Issue by brandon-PG** [pg-irc/pathways-frontend#1755]
The website section is missing from all service detail pages

### Acceptance Criteria 
- [x]  When a service has a website associated to it, it should be visible and clickable

### Steps for QA: 
1.  Navigate to the service 'West Kootenay Child Care Resource and Referral' in 'Nelson', BC
2.  Verify a website is visible and clickable

**Comment by alysha-PG** [comment]
website in steps for QA is clickable
