### ISSUE TITLE
Missing Translation in BC and MB - "Welcome to ____" topic detail

### ISSUE THREAD

**Issue by alysha-PG** [pg-irc/pathways-frontend#1757]
In both BC and MB, when I go to topics > Welcome to BC/MB > click on a topic, I expect the text below the image and above the large title to read "Welcome to BC/MB" **in the respective language**. Instead, I see it in English.

Example from MB/French
<img src="https://images.zenhubusercontent.com/60b823128e6f424e93549168/55561cfb-03ce-4100-bee0-39283aa1d5fc" width=300 align=centre><br>

Example from BC/Punjabi
<img src="https://images.zenhubusercontent.com/60b823128e6f424e93549168/1a3f4ebe-e766-46e5-9613-a65c3c84208a" width=300 align=centre><br>

### Acceptance Criteria 
- [x]  Change all of these subheaders to read "Welcome to BC/MB" in their respective languages.

### Steps for QA: 
1.  Go to BC side / English
2. Go to topics
3. Open "Welcome to BC" topic
4. click on any of the topics
5. change language to all languages
6. Observe that the small text below the image is not in English but rather in the respective language
7. repeat above with MB side and check in French.

**Comment by alysha-PG** [comment]
If the problem has to do with capitalization (in cases where that language uses the English alphabet), here are the translated titles in capital French:

**Comment by rasmus-storjohann-PG** [comment]
Also seen in MB > French > Soutien familial et specialise > any topic shows "Family and specialized support"

**Comment by Kaylee-PG** [comment]
I can confirm that the issue has been resolved. I was expecting to see the change that the "Welcome to BC" tagline under the image header was in the correct languages for both BC and Manitoba and I confirm it is.
