### ISSUE TITLE
MB/BC: Learn more page after Review service is not translated

### ISSUE THREAD

**Issue by alysha-PG** [pg-irc/pathways-frontend#1758]
When I go to a both MB/BC in any language except English > bookmarks > Services tab > :) Review this service > Learn more, the 3rd paragraph is not translated.

Possible reason is because bc211 links were updated from bc211.ca to bc.211.ca/

### Acceptance Criteria 
- [ ]  

### Steps for QA: 
1.  navigate to above in all languages and make sure it is translated.

**Comment by alysha-PG** [comment]
MB > French is correctly updated

BUT none of the BC languages are updated - still needs to be fixed.

**Comment by Farouk-PG** [comment]
Closing as fixed
