### ISSUE TITLE
Press to call asking about external link

### ISSUE THREAD

**Issue by alysha-PG** [pg-irc/pathways-frontend#1762]
When I press call 311, I expect it to trigger a prompt on my phone which asks if I want to call. Instead, the prompt that comes up is asking if I want to open an external link, and when I press yes, then the prompt to call comes up. 

### Acceptance Criteria 
- [ ]  when I press to call 311 or 211 or any number, the prompt to call comes up, not the external link question.

### Steps for QA: 
1.

**Comment by Farouk-PG** [comment]
Closing as fixed
