### ISSUE TITLE
MB/Housing 311 not clickable

### ISSUE THREAD

**Issue by alysha-PG** [pg-irc/pathways-frontend#1763]
I expect that all places where it says "Call 311" that it will be clickable. Instead, in MB in both English and French, at Housing > Emergency Housing and Shelters > the bottom of the page "Call 311 (in Winnipeg only)" is not clickable.

### Acceptance Criteria 
- [ ]  able to click and call 311 on this page.

### Steps for QA: 
1.

**Comment by Farouk-PG** [comment]
Still not clickable on iOS. See attached video. 
https://user-images.githubusercontent.com/89798867/150585594-e5ae1db6-5d2d-4ef9-b0de-ce82498794a5.mov

**Comment by Farouk-PG** [comment]
Still not clickable on iOS. See attached video. 
https://user-images.githubusercontent.com/89798867/150585594-e5ae1db6-5d2d-4ef9-b0de-ce82498794a5.mov

**Comment by Farouk-PG** [comment]
Still not clickable on iOS. See attached video. 
https://user-images.githubusercontent.com/89798867/150585594-e5ae1db6-5d2d-4ef9-b0de-ce82498794a5.mov

**Comment by Farouk-PG** [comment]
Closing as fixed
