### ISSUE TITLE
BC Teal in MB

### ISSUE THREAD

**Issue by alysha-PG** [pg-irc/pathways-frontend#1765]
I expect all of MB to have green colour scheme, instead there's 1 place where it's still teal - topics > find services near me> , when location is off, the button to 'turn on location'.

<img src="https://images.zenhubusercontent.com/60b823128e6f424e93549168/6a7de14f-2c11-4ad4-97dc-1010f118271c" width=300 align=centre><br>

### Steps for QA: 
1.  Turn off location
2. Go to any topic
3. Click 'Search for services near me"
4. Observe that the button to turn on location is Green.

**Comment by Farouk-PG** [comment]
Closing as fixed!
