### ISSUE TITLE
Change taxonomy id to "questionnaire" for all taxonomy terms used in the questionnaire

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1773]
Currently, if a topic is tagged with `timeInCanada:under1Year` and `immigrant_type:refugee_claimant`, and in the questionnaire you select an answer with `immigrant_type:refugee_claimant`, the topic does not get recommended, due to the boolean logic implied by the taxonomy system. Because these terms belong to different taxonomies, boolean AND is applied between them. 

Expected is that if *either* `timeInCanada:under1Year` or `immigrant_type:refugee_claimant` is selected in the questionnaire, the topic should be recommended. 

The solution is to use `questionnaire:under1Year` and `questionnaire:refugee_claimant` as the taxonomy terms for all topics and all answers in the questionnaire. With this change, the terms will both belong to the same taxonomy, and boolean OR will be applied, fixing the usability issue.

- [ ] For the duration of working on this bug, copy the content files for MB and BC into the frontend repo so that changes to the questionnaire code and the content can be made at the same time
- [ ] Work in small commits to make the review process easier. Make corresponding changes to the questionnaire code and the content together and commit them together.
- [ ] When this issue has been completed and merged, the content files can be moved back to their proper location in the content repo.

**Comment by Farouk-PG** [comment]
Duplicate taxonomy fixtures:

"french_level": {
    		"fluent": {},
    		"intermediate": {}
    	},

with:

 	"english_level": {
    		"none": {},
    		"beginner": {},
    		"intermediate": {},
    		"fluent": {}
    	},
-
  	"timeInCanada": {
    		"under1Year": {},
    		"notYet": {},
    		"over1Year": {}
    	},

with:

	"timeinCanada": {
    		"notYet": {}
    	},
-

 	"healthcare": {
    		"needDentist": {}
    	},

with:

	"healthCare": {
    		"disability": {},
    		"needDentist": {},
    		"needEyeExam": {},
    		"information": {},
    		"emergency": {},
    		"bc_services_card": {},
    		"needMedication": {},
    		"costs": {},
    		"MSP": {},
    		"MBHealth": {},
    		"MBHealthCard": {}

**Comment by Farouk-PG** [comment]
Note: There appears to not be taxonomies for “french_level” tag
