### ISSUE TITLE
Failure to find services when specifying postal code

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1780]
Bug from Renee who at the time was located in Florida:

I was just trying out AA found that when I try to enter an address to find nearby services, it always tells me that there are no services to show

![image](https://user-images.githubusercontent.com/32307781/151226635-3a0c62d5-6ed0-4446-9fd1-a0f67f4236ec.png)

I tried address, city and postal code with no success. Trying now in Community and recreation centres. Its trying to force me to turn on location services which defeats the purpose of allowing me enter an address

![image](https://user-images.githubusercontent.com/32307781/151226690-21d4c178-3f6a-4c29-8d73-a7f86d9c69d6.png)

Expected behaviour is that no matter where you are in terms of lat/long, e.g. in Florida in this case, you can enter a Canadian postal code and the search will be made relative to the postal code, not the lat/long. Trick to solve this: There is a hack to make the app think the lat long is an arbitrary position, you can dig into the code to find how to do that... look for `getDeviceLocation()` and specifically the `manualUserLocation` argument.

**Comment by brandon-PG** [comment]
Works as intended
