### ISSUE TITLE
App crash on bc -> mb region change with unsupported language

### ISSUE THREAD

**Issue by brandon-PG** [pg-irc/pathways-frontend#1783]
Switching from bc to mb with any language other than en/fr while viewing a bc topic will cause a crash. This crash can also be triggered by using the android back button to navigate back to a bc topic after switching to mb on the home screen.

This is caused by the onContinue in regionDrawerComponent.ts not clearing to RouteHistory.

### Acceptance Criteria 
- [x]  App should not crash upon switching regions when viewing a topic

### Steps for QA: 
1.  Set region to BC
2. Set language to Tagalog
3. Navigate to any topic detail page
4. Switch region to MB
5. Verify app continues to function

**Comment by alysha-PG** [comment]
app does not crash, QA'd from tagalog and arabic on iphone.

**Comment by alysha-PG** [comment]
app does not crash, QA'd from tagalog and arabic on iphone.
