### ISSUE TITLE
Arabic issue: Text direction not switching unless app is restarted (in iOS), crash on Android!

### ISSUE THREAD

**Issue by alysha-PG** [pg-irc/pathways-frontend#1784]
This is a crash bug on Android and a possibly related bug (not crash) on iOs.

When I open the app in English and then switch to Arabic, I expect to see the text go right to left. Instead, the text direction remains left to right. Then I restart the app, and when I re-open it, the text is correctly in Arabic going right to left. However, when I try to switch in-app back to English, the text remains incorrectly right to left. It requires another app re-start in order to get the correct text direction.

See video from my iphone: https://drive.google.com/file/d/1qtnnPmKeibM6A0yv2Fi4D_YiB3IAxP5L/view?usp=sharing

**NOTE:** I also checked this from my Android and there is different behavior. When I switch languages in-app, it auto restarts the app (which is correct), shows the text in the correct direction, and then immediately crashes (which it should not).

iOs: Bug is reproducible in staging and prod, but not in development build on Expo

### Acceptance Criteria 
- [ ]  text direction should switch from right to left in-app without having to restart

### Steps for QA: 
1.  switch languages in the app and see if the direction is correct

**Comment by brandon-PG** [comment]
https://forums.expo.dev/t/updates-reloadasync-doesnt-work-on-standalone-ios-sdk-41/52349 Is a user with the same issue. I did not see an alternative to restarting the app other than Updates.reloadAsync() which does not work on iOS production.

**Comment by rasmus-storjohann-PG** [comment]
This crash from Sentry might be related https://sentry.io/organizations/peacegeeks/issues/2951395145/?project=256284&query=is%3Aunresolved

**Comment by Kaylee-PG** [comment]
I can confirm this has been fixed! Go team :)
