### ISSUE TITLE
Updates to Onboarding-->Questionnaire Flow

### ISSUE THREAD

**Issue by Kaylee-PG** [pg-irc/pathways-frontend#1789]

**Comment by Kaylee-PG** [comment]
There are currently 3 things happening that we want to fix. 
1) The onboarding screens allow the user to click 'SKIP' 
2) The questionnaire allows users to click 'X' to immediately exit 
3) The last onboarding page prompting the user to click 'START' does not actually take the user to the questionnaire. 

To fix these issues, the below outlines what needs changing so that we can work to increase the % of users who complete the questionnaire. 

**Proposed changes:**

1. Remove the 'SKIP' button on the upper right hand screens for all four of the onboarding pages (Figma > Page: Updated Questionnaire flow > ONBOARDING screen frames) 

2. Re-route the app flow so that the last onboarding page that has the START button, be directed to the first question for the questionnaire, NOT to the app home page (Figma > Page: Updated Questionnaire flow > ONBOARDING/4-MB/BC screen frame) 

3. Remove the 'X' button on the upper right hand screens for all questionnaire pages (1-9) so that the user is forced to press 'SKIP' instead of X-ing off (Figma > Page: Updated Questionnaire flow > QUESTIONNAIRE screen frames) 

For more details, [open this Figma file to see the screens referred to](https://www.figma.com/file/br8IthdXBkiMCATBW7KNE4/Main-Mobile-Screens-%26-Flow?node-id=1459%3A10541)

**Comment by Kaylee-PG** [comment]
<img width="297" alt="Screen Shot 2022-01-26 at 3 07 58 PM" src="https://user-images.githubusercontent.com/95312461/151262336-5f9c8c24-affe-4840-8cac-cde27644e00e.png">
<img width="644" alt="Screen Shot 2022-01-26 at 3 08 17 PM" src="https://user-images.githubusercontent.com/95312461/151262339-05b5c5c7-c363-4baa-8e88-19ee5f92cf67.png">
<img width="215" alt="Screen Shot 2022-01-26 at 3 08 29 PM" src="https://user-images.githubusercontent.com/95312461/151262340-700215cd-0313-4fc7-9a73-da823702e1b7.png">

**Comment by rasmus-storjohann-PG** [comment]
Last page of onboarding copy: "Take our optional questionnaire to see recommended topics for your needs". The questionnaire is no longer optional. @alysha-PG , thoughts? CTA button on the last onboarding page is "Start", is that the best label for that button?

And also, the questionnaire in French still doesn't look good with the two CTA buttons stacking one above the other. En English it's fine because the text on the buttons is shorter, so they both fit side by side.

**Comment by alysha-PG** [comment]
GREAT SUCCESS!
