### ISSUE TITLE
Add more SPO attributes to service review payload to AirTable

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1791]
Service reviews (smiley faces) received from the app are stored in AirTable, from where we want to pass the reviews on to the relevant SPO to give them feedback on their performance from their users.

Currently this process is hampered by the fact that the data stored in AirTable contains only the SPO id. This means we have to look up the service record to find additional needed information.

Expected behaviour is that the AirTable records created when a review is submitted also contains the service organization name, and contact email address so that is becomes easier to pass on the information to somebody at the organization. 

### Acceptance Criteria 
- [ ]  AirTable records of service reviews contain service provider organization name (PublicName)
- [ ]  AirTable records of service reviews contain contact email address (MainContactEmailAddress)
- [ ] Stretch goal: Also the name of the person the contact email address belongs to (MainContactName)

**Comment by alysha-PG** [comment]
instead of slack, I want a gmail message that has an attachment with a record

**Comment by alysha-PG** [comment]
i am waiting for someone to give feedback in the app 
to QA this issue
