### ISSUE TITLE
Bug in bump version string script

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1796]
There is a bug in the script, and also we are getting very close to version 1.100.0, so might as well up the format to support three digits.

With version 1.90.1, expected versionCode in app.json is `10900010`, observed is `190100`.

The reason this is the expected value is to have three digits for each part of the version, so 001 + 090 + 001, with an extra 0 at the end in case we ever need to bump the versionCode without bumping the version string (that would be weird, but we will have that option). So this gives 0010900010, but it's an integer so we drop the leading zero to give 10900010.

### Acceptance Criteria 
- [ ] Fix the math in the bump version string script to produce the correct version code
- [ ] Fix unit tests to match the new scheme for the version code

**Comment by rasmus-storjohann-PG** [comment]
TODO modify scheme to work for 1.100.1 etc

**Comment by alysha-PG** [comment]
MUST HAPPEN IN NEXT 10 WEEKS approx
