### ISSUE TITLE
Add algolia search analytics capabilities

### ISSUE THREAD

**Issue by alysha-PG** [pg-irc/pathways-frontend#1799]
Currently, we are not tracking some [key analytics in algolia](https://www.algolia.com/apps/MMYH1Z0D3O/analytics/overview/AAProductionVersion1.90?from=2022-01-27&to=2022-02-02) which will help us better understand how users are utilizing the search function. Analytics such as:

- Click-through rate (percentage of tracked services where at least 1 result was clicked on by user) - straightforward rite?

- conversion rate (percentage of tracked searches that have led to a a conversion). In our case, a conversion would be when people open the service and then click any info on that, such as open in maps, calling a service, clicking on email.

- No Clicks Rate (percentage of searches that retrieved results but didn't generate clicks) - this is a huge one which will give us an indication about the relevance of search results for our users.

We need to implement these analytics.
Instructions to do that here: https://www.algolia.com/doc/guides/getting-analytics/search-analytics/advanced-analytics/

**Comment by rasmus-storjohann-PG** [comment]
From a click on the search button, in the next 10 events, at least one should be a search result detail page. If not, cont the search as "failed" and emit a "failed search" event to GA.

**Comment by rasmus-storjohann-PG** [comment]
Conversion rate seems like it;s not too hard, just need to make an event when a map is opened or whatever. We need to know whether the service was discovered through keyword search or topic search.
