### ISSUE TITLE
BC Questionnaire missed translation string - "I don't speak English"

### ISSUE THREAD

**Issue by alysha-PG** [pg-irc/pathways-frontend#1826]
I expect the BC questionnaire to be in each respective languages. Instead, in some languages, very ironically on Question 5 "What is your current level of English", the first response is written in English "I don't speak English" rather than the user's native language.

Please fix the strings for:
Chinese traditional
Chinese simplified
Tagalog
Korean
Arabic
Punjabi

The only language that is ok in is French. It is ok in MB as well.

In the following languages,
### Acceptance Criteria 
- [ ]  

### Steps for QA: 
1.  Go through questionnaire and look at question 5 for each language, ensure that the first response is written in the user's language rather than seeing the first answer read in English "I don't speak English".

**Comment by brandon-PG** [comment]
The original translation was done as part of https://github.com/pg-irc/pathways-backend/issues/661 . I don't see any translations for the other languages.

**Comment by alysha-PG** [comment]
Realizing this is because the old questionnaire answer used to be "none" for level of English. See translations below:
 
Chinese traditional: 我不會說英語
Chinese simplified: 我不会说英语
Tagalog: Hindi ako nagsasalita ng Ingles
Korean: 나는 영어를 못한다
Arabic: أنا لا أتحدث الإنجليزية
Punjabi: ਮੈਨੂੰ ਅੰਗਰੇਜ਼ੀ ਨਹੀਂ ਆਉਂਦੀ

**Comment by alysha-PG** [comment]
"I don't speak French" in Arabic:
أنا لا أتحدث الفرنسية

**Comment by alysha-PG** [comment]
FYI another missed translation in the questionnaire is #1843
