### ISSUE TITLE
Add Manitoba content in Arabic to the app

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1830]
Describe the issue and expected behaviours. If this is a bug, describe the steps to reproduce the problem, what you observe, and what you expected to observe.

### Acceptance Criteria 
- [ ]  

### Steps for QA: 
1.

**Comment by rasmus-storjohann-PG** [comment]
Chapter 9 looks good, 8 is good. Chapter 7 is missing "Renting a car", Chapter 6 is missing "Spousal abuse and domestic violence"

**Comment by alysha-PG** [comment]
Generally good, individual issues have been written out elsewhere.
