### ISSUE TITLE
Names of regions are not localized

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1834]
Repro steps:
* Start the app
* Set the language to French and the region to BC
* Open the hamburger menu
* Observe that the region appears as "British Columbia"
* Expected that the region appears as "Colombie Britanique"

Same issue for other regions and other locales.

### Acceptance Criteria 
- [ ]  Regional names are localized correctly

**Comment by brandon-PG** [comment]
Not fixed because we do not have the translated versions of the strings in weblate

**Comment by rasmus-storjohann-PG** [comment]
@alysha-PG to google translate "British Columbia" into all the languages

**Comment by alysha-PG** [comment]
### "British Columbia"

Arabic: برتش كولومبيا 
Chinese (Simplified): 卑诗省
Chinese (Traditional): 卑詩省
Farsi: بریتیش کلمبیا
French: Colombie-Britannique
Korean: 브리티시컬럼비아주
Punjabi: ਬ੍ਰਿਟਿਸ਼ ਕੋਲੰ ਬੀਆ
Tagalog: British Columbia
Ukrainian: Британська Колумбія

### "Manitoba"

Arabic: مانيتوبا
Chinese (Simplified): 马尼托巴
Chinese (Traditional): 馬尼托巴
Farsi: مانیتوبا
French: Manitoba
Korean: 매니토바
Punjabi: ਮੈਨੀਟੋਬਾ
Tagalog: Manitoba
Ukrainian: Манітоба
