### ISSUE TITLE
MB Arabic hyperlinks broken

### ISSUE THREAD

**Issue by alysha-PG** [pg-irc/pathways-frontend#1836]
See also #1838 

I expect that the hyperlinks will work, but instead they do not. It appears there is a space between the bracket and parentheses which contains links. Happens on every page, here is an example from the 211 topic:

![WhatsApp Image 2022-03-28 at 9.56.23 AM.jpeg](https://images.zenhubusercontent.com/60b823128e6f424e93549168/3063f52e-1a88-45c1-8882-011671b4fc4b)

### Acceptance Criteria 
- [ ]  hyperlinks in MB Arabic are clickable

### Steps for QA: 
1.

**Comment by rasmus-storjohann-PG** [comment]
sed command to fix links with an extra space in them:
```bash
sed s/\\]\ \(/\\]\(/
```

**Comment by Meaad-PG** [comment]
I see this issue in Mental Heath Centres
For Mental Health resources for Winnipeg the hyperlink is broken and phone number unclickable 
![IMG_880723D604C1-1](https://user-images.githubusercontent.com/102553427/161642125-b931fc4b-c6e6-4dc6-928d-7c2d646ae621.jpeg)

**Comment by Meaad-PG** [comment]
Same in **Hosing for seniors** 
![IMG_0704171E59B4-1](https://user-images.githubusercontent.com/102553427/161644569-08d4dcf0-318d-4791-8c3e-d7ee6e926515.jpeg)
