### ISSUE TITLE
Reversed content- "Manitoba Start & Settlement agencies"

### ISSUE THREAD

**Issue by Meaad-PG** [pg-irc/pathways-frontend#1844]
In the Arabic version, it's written as "And settlement agencies Manitoba start &)

Because the sentence has Arabic and English wording, the order of the sentences is reversed. To resolve this, it's better to write the whole sentence in Arabic like this "مانيتوبا ستارت ووكالات الاستقرار"

![IMG_3977](https://user-images.githubusercontent.com/102553427/160927510-b22dde6e-2cf5-4961-9e68-b544c331981b.PNG)

**Comment by rasmus-storjohann-PG** [comment]
Proposed solution: Insert newline between "Manitoba Start" and the remainder of the text, so the appearance in the app will be
```
Manitoba Start
<and settlement services>
```

**Comment by alysha-PG** [comment]
fixed!
