### ISSUE TITLE
MB Arabic Newline needs fixing

### ISSUE THREAD

**Issue by alysha-PG** [pg-irc/pathways-frontend#1865]
In the MB Start topic, I expect to see the English "Manitoba Start" written on a different line from the Arabic. Instead, I see English "Manitoba Start\n".

![File.jpg](https://images.zenhubusercontent.com/60b823128e6f424e93549168/a5871f52-0f8e-43e0-8cd8-151e7fd0b0fe)

### Acceptance Criteria 
- [ ]  Manitoba Start is on the first line instead of on the same line, and no \n appears

**Comment by alysha-PG** [comment]
@rasmus-storjohann-PG after typing this up im thinking perhaps you already fixed it - plz put in the appropriate column of doneness.

**Comment by rasmus-storjohann-PG** [comment]
Not fixed on staging

**Comment by rasmus-storjohann-PG** [comment]
For now I suggest we fix this manually, it's just really messy to come up with a scheme that lets a properly escaped newline character move through our whole content management line.

**Comment by rasmus-storjohann-PG** [comment]
If we do want to automate it, we need to work backwards: Figure out what it needs to look like in clientFixtureTopics.json, then figure out what it needs to look like inside Mongo, then what it needs to look like in content/topics/mb/markdown/CHAPTER 1 - Welcome to Manitoba/topics/Manitoba Start & Settlement agencies/ar.Manitoba Start\n ووكالات الاستقرار.md, then what it needs to look like in content/topics/mb/WinnipegIntroductionForNewcomers/

**Comment by Meaad-PG** [comment]
Fixed
![IMG_4074](https://user-images.githubusercontent.com/102553427/168686517-cb031ee1-6bc0-4fdc-bc4e-d206b5d8356e.jpg)
