### ISSUE TITLE
MB Arabic header tag on wrong side

### ISSUE THREAD

**Issue by alysha-PG** [pg-irc/pathways-frontend#1870]
When I go to MB Arabic > Employment > Learn About your Rights as a Worker, I expect the heading "Employment Standards Act" (Arabic: قانون معايير التوظيف) to be bolded. Instead, it appears as a # with the text to the right and not bolded.

![Image from iOS (1).png](https://images.zenhubusercontent.com/60b823128e6f424e93549168/fcbf5e90-a274-47bc-a885-9798fb11ab3d)

![IMG_7047.PNG](https://images.zenhubusercontent.com/60b823128e6f424e93549168/430ef93d-27c9-45b5-811a-97215bf338fc)

### Acceptance Criteria 
- [ ]  markdown has قانون معايير التوظيف with # to the right of it instead of left

### Steps for QA: 
1.

**Comment by rasmus-storjohann-PG** [comment]
Maybe there is some white space before the `#`? I think the heading markdown expects the `#` to be at the start of the line

**Comment by Meaad-PG** [comment]
Fixed
