### ISSUE TITLE
BC Ukrainian content: Get your BC Services Card

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1900]
Expected to see bullet list. Observe 'code' style due to leading spaces before bullet points.

![image](https://user-images.githubusercontent.com/32307781/169107587-a7104ef1-3326-4687-9615-cd12b1962f37.png)

**Comment by alysha-PG** [comment]
not fixed

**Comment by rasmus-storjohann-PG** [comment]
Closing as duplicate of #1920. What a tragedy that such a round issue number ends up being a nothing issue!
