### ISSUE TITLE
BC Ukrainian content: Services for refugees and refugee claimants

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1903]
URL looks funny, 'canada.ca/en/...' split over three lines. Expected is to see just the clickable url.

![image](https://user-images.githubusercontent.com/32307781/169116416-4c8574f8-1e40-49f6-ac18-0e974a7dfeef.png)

**Comment by Meaad-PG** [comment]
There is also this issue in the same topic. 
![IMG_4159](https://user-images.githubusercontent.com/102553427/169349113-ed0c7bf4-cecf-4580-b8b7-3f7f6f5a6468.jpg)
