### ISSUE TITLE
BC Ukrainian content: Emergencies

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1904]
Expect to see a bullet list. Observe a code block. Fix by removing leading spaces before bullets.

![image](https://user-images.githubusercontent.com/32307781/169118793-ba5e376e-8b94-4c57-b9be-627555f59cb8.png)

**Comment by alysha-PG** [comment]
@rasmus-storjohann-PG  - I am checking "Medical Emergencies" topic in both UK and EN and can't find this text - is it in another topic?

**Comment by rasmus-storjohann-PG** [comment]
It's topic 1.10-emergencies, it shows up in EN and UK, and it is not quite fixed...
