### ISSUE TITLE
BC Ukrainian content: Volunteering

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1909]
Expect a clickable link to email address info@volunteerbc.bc.ca, observe that it is non-clickable text:

![image](https://user-images.githubusercontent.com/32307781/169131768-927c81fe-b9b8-4008-805a-9469b396cc06.png)

**Comment by alysha-PG** [comment]
There is also a 2nd mistake on this screenshot - At the very bottom, it reads
Email: info@govolunteer.ca .

Right now, both the word 'Email:' and the actual email 'info@govolunteer.ca' are clickable - should be just the email, not the word 'Email:"
