### ISSUE TITLE
MB Arabic content: Search tab not working 

### ISSUE THREAD

**Issue by Meaad-PG** [pg-irc/pathways-frontend#1916]
When I searched for Arabic keywords such as "education, health and housing" and chose the Winnipeg site, I got no result.

![IMG_4100](https://user-images.githubusercontent.com/102553427/169151625-9910fc6f-c83d-4290-a30e-084a9c148a06.PNG)
![IMG_4101](https://user-images.githubusercontent.com/102553427/169151632-6ea72a6e-f7c0-4ffc-a062-db85496fc8e0.PNG)
![IMG_4102](https://user-images.githubusercontent.com/102553427/169151637-f4e7ba99-6097-4354-a6a5-5d70610b1c0b.PNG)

**Comment by brandon-PG** [comment]
We only support english and french for searching right now
