### ISSUE TITLE
BC Ukrainian content: Get your BC Services Card

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1920]
Bullet lists have too many leading spaces

![image](https://user-images.githubusercontent.com/32307781/169173977-4c0a647c-15d1-463b-9260-8ff178c64f06.png)

**Comment by alysha-PG** [comment]
not fixed

**Comment by rasmus-storjohann-PG** [comment]
Fixed it, leaving two spaces in front of bullets to make the bullets nested under the numbered items. In EN and probably other languages, there are no leading spaced, so the bullets appear at the same horizontal alignment as the numbered items. Let's see which way works better, I think both are acceptable but nested is better.
