### ISSUE TITLE
BC Ukrainian content: Know your rights as a tenant

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1923]
- [x] Topic title is in English, expected that the topic title appears in UK
- [x] Also there are email links with `mailto:` in front, should not be there, check the URLs in the topic

![image](https://user-images.githubusercontent.com/32307781/169174907-5065d3e8-d668-44ca-9a47-15cbbdd652ca.png)

**Comment by alysha-PG** [comment]
not fixed
