### ISSUE TITLE
BC Ukrainian Content: Family-Violence 

### ISSUE THREAD

**Issue by Meaad-PG** [pg-irc/pathways-frontend#1940]
In Family> the topics of violence, abuse and neglect, this unnecessary text can be removed.  
![IMG_4138](https://user-images.githubusercontent.com/102553427/169223385-726c44e0-81e2-4349-8280-78b312635e14.jpg)

**Comment by alysha-PG** [comment]
not fixed

**Comment by alysha-PG** [comment]
Link is fixed but opening bracket before the be3k-ish word needs to be removed

![File (1).jpg](https://images.zenhubusercontent.com/60b823128e6f424e93549168/13835632-4542-4a64-b663-e68c83938412)

**Comment by alysha-PG** [comment]
Not fixed
