### ISSUE TITLE
BC Ukrainian Content: Legel- Using a lawyer 

### ISSUE THREAD

**Issue by Meaad-PG** [pg-irc/pathways-frontend#1942]
This paragraph seems missing in the Ukrainian content.

![IMG_4156](https://user-images.githubusercontent.com/102553427/169345313-95a39569-0424-4b09-9641-4caaa658a036.jpg)
![IMG_4157](https://user-images.githubusercontent.com/102553427/169345318-17ba3215-c26e-4535-9405-093b90cc88e2.PNG)

**Comment by alysha-PG** [comment]
Wow, it's like @Meaad-PG can read Ukrainian!!!!!!

@rasmus-storjohann-PG I made an error in pasting. The missing content is accidentally pasted at the bottom of topic 9.11, The Office of the Ombudsperson. It should be moved up to this topic, 9.10 Using a Lawyer.

Search in content for
"# Допомога у випадку неможливості найняти адвоката"

And move all of that info up. Delete from Ombudsperson topic.

See visual here:
![Screen Shot 2022-05-19 at 11 58 04 AM](https://user-images.githubusercontent.com/85197659/169380827-31840f2f-3298-4997-9364-d70a4ef3ff7c.png)
