### ISSUE TITLE
BC English Content: Driving-Driver's licence (3 broken URL)

### ISSUE THREAD

**Issue by Meaad-PG** [pg-irc/pathways-frontend#1945]
## Edit - 1. NOT FIXED
![IMG_4167](https://user-images.githubusercontent.com/102553427/169357109-7525c1d0-8b2e-46a3-bc3d-81b729f379b3.jpg)

## 2. FIXED
![IMG_4168](https://user-images.githubusercontent.com/102553427/169357114-12f87d5d-d058-48be-bdba-bcb35bfae53c.jpg)

## 3. FIXED
![IMG_4169](https://user-images.githubusercontent.com/102553427/169357119-a41b8ce8-866e-4889-8c1c-f546081eef30.jpg)

**Comment by alysha-PG** [comment]
The first link is still broken (#1 - not fixed) while #2 and #3 are correctly fixed.
