### ISSUE TITLE
BC Ukrainian Content: Welcome to B.C-Personal Safety (Missing text)

### ISSUE THREAD

**Issue by Meaad-PG** [pg-irc/pathways-frontend#1953]
This text seems missing in the Ukrainian content. 

![IMG_4194](https://user-images.githubusercontent.com/102553427/169409820-239996fa-2c2e-4949-9d28-352298aac93f.PNG)
![IMG_4195](https://user-images.githubusercontent.com/102553427/169409828-5a7679e4-db4a-4ba2-aebe-e2937c9bb5fb.jpg)

**Comment by brandon-PG** [comment]
That section is missing in the Ukrainian pdf of the newcomers guide
