### ISSUE TITLE
BC Ukrainian Content: Welcome to B.C-Service for refugees (Separate Text)

### ISSUE THREAD

**Issue by Meaad-PG** [pg-irc/pathways-frontend#1954]
The sentence is part of the paragraph above. It should not be in a separate line.

Sentence in Ukrainian "Що стосуються забезпечення житлом, медичним обслуговуванням та доходом."
In English translation" housing, health care and income."

![IMG_4196](https://user-images.githubusercontent.com/102553427/169411602-039e783c-9851-44d5-97d8-4a010bd59b44.PNG)
![IMG_4199](https://user-images.githubusercontent.com/102553427/169411609-d3c03f01-8994-46c6-8a5e-76dcb10a5d98.jpg)

**Comment by alysha-PG** [comment]
Not fixed. Find text "Що стосуються" and backspace so it is directly after the word before that looks like "notpe6,"
