### ISSUE TITLE
BC Ukrainian Content: Family Support-Seniors' programs

### ISSUE THREAD

**Issue by Meaad-PG** [pg-irc/pathways-frontend#1956]
The text is listed as a bullet point which is not the case in EN content. 

![IMG_4205](https://user-images.githubusercontent.com/102553427/169422013-379a2247-f8a8-4c99-9bdb-4deec2c41aea.PNG)
![IMG_4207](https://user-images.githubusercontent.com/102553427/169422024-dc06143b-3630-4a4e-af99-44d567312db0.jpg)

**Comment by alysha-PG** [comment]
Not fixed. Update on instructions:

-remove the "ca" after the Healthlinkbc.ca link.
-remove the period before the word that looks like "Wykante"
-backspace so "Wykante" appears directly after the healthlinkbc.ca link.
