### ISSUE TITLE
Modal dialog for confirming discarding information is not usable in Ukrainian

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1960]
Open the app. Set the language to Ukrainian. Search for a service. Upen dialog for suggesting updated information. Enter some information in one or more fields. Hit the back button. Observe modal dialog appear to let the user confirm to discard the information entered. The text on the buttons in the dialog is so long that the UX is not usable. Expected is that the modal is usable.

Design needed, or updated translated strings

![image](https://user-images.githubusercontent.com/32307781/170094790-c773a2fa-fd7a-48af-a0ac-13b1de6f7e0d.png)

### Acceptance Criteria 
- [ ]  The modal is usable

**Comment by alysha-PG** [comment]
Going with translate solution - shorten to just
"Продовжуйте" (aka "Continue").
