### ISSUE TITLE
BC Ukrainian Welcome to BC > Personal Safety

### ISSUE THREAD

**Issue by alysha-PG** [pg-irc/pathways-frontend#1966]
Remove line break after the first paragraph - it is cutting in the middle of a sentence. Backspace before the word that looks like "HamaratncR"

![File.jpg](https://images.zenhubusercontent.com/60b823128e6f424e93549168/79c495ef-8e2a-4371-87f1-e21ab5252d40)

**Comment by rasmus-storjohann-PG** [comment]
Ran into pretty tricky git merge conflicts with this change, please QA extra carefully
