### ISSUE TITLE
Alert users of new languages via push notification

### ISSUE THREAD

**Issue by alysha-PG** [pg-irc/pathways-frontend#1983]
Push notification-

Title: New languages available! :tada:
Text: In BC, you can now read information in Farsi (فارسی) and Ukrainian (українська)! In Manitoba, read information in Arabic (العربية)! 
And, read updated English content! Update your Arrival Advisor app to view.

**Comment by brandon-PG** [comment]
When is the best time? @alysha-PG

**Comment by brandon-PG** [comment]
Notifications sent out
