### ISSUE TITLE
BC Ukrainian Content: Employment -Starting your own business 

### ISSUE THREAD

**Issue by Meaad-PG** [pg-irc/pathways-frontend#1987]
In Uk content, all points are listed as main points without sub-points. This is not the case in En content. 
There are five main points( point 2 has four sub-points, and point  3 has four sub-points). 
The fourth main point is not listed as a bullet point but as a paragraph.

Here is the point # 2 
![IMG_4279 2](https://user-images.githubusercontent.com/102553427/170589847-445aed26-b108-4849-aa8b-e781efee2085.jpg)

And this point # 3
![IMG_4279](https://user-images.githubusercontent.com/102553427/170589943-2476bb59-2d85-407d-8b6d-a6c8eb900c9f.jpg)

This the fourth point.
![IMG_4281 2](https://user-images.githubusercontent.com/102553427/170589769-e19a50d7-2934-4e7f-acab-cc28712c1949.jpg)

**Comment by rasmus-storjohann-PG** [comment]
All bullets are on the same level. To fix this, review carefully how this is done in the EN content and match in UK and FA, which has the same issue
