### ISSUE TITLE
BC UK Questionnaire missing translation strings

### ISSUE THREAD

**Issue by alysha-PG** [pg-irc/pathways-frontend#1997]
The problem is that we have a few changes to the Questionnaire in English, and those are the strings I got translated into UK and Farsi. However, we don't want to mess with the English questionnaire at this time. So, I am providing some strings in this and the Farsi issue to match the current questionnaire format, and we shall fix all of it next round.

- Q1 time in Canada: 
"Less than 1 year" not translated	
Менше 1 року

- Q2 - Which of the following neither question nor any answers are translated (NOTE: the UK strings do match the question on this one, so i don't know why it's not showing up)

Which of the following important Canadian documents do you still need?	
Які з перерахованих нижче необхідних канадських документів вам ще потрібні?

I need a Social Insurance Number	
Мені потрібен номер соціального страхування

I need a Canadian bank account	
Мені потрібен рахунок в канадському банку

I need a Permanent Resident Card	
Мені потрібна картка постійного резидента

I need to register for MSP (Medical Services Plan)	
Мені потрібно оформити MSP (план медичного обслуговування)

I need a BC Services Card (health card)	
Мені потрібна картка BC Services Card (картка здоров'я)

I need a BC Driver’s License	
Мені потрібні водійські права Британської Колумбії

I am not sure what I need	
Я не впевнений, що мені потрібно

- Q5 - Beginner/Intermediate/Fluent not translated (Just paste in the full ukrainian that includes english canadian language benchmark levels)

Beginner
Початковий рівень (Canadian Language Benchmark 1-4)

Intermediate 
Середній рівень (Canadian Language Benchmarks 5-8)

Fluent
Вільне володіння (Canadian Language Benchmarks 9-12)

- Q9 "Resources to deal with abuse/violence" missing - should be:
Ресурси для протидії жорстокому поводженню/насильству

- Q9
"Places of worship" should only show up in MB - delete for all of BC, or if that's too complicated, add in ukrainian:
Богослужіння

**Comment by rasmus-storjohann-PG** [comment]
@alysha-PG do we have an issue for the "and we shall fix this the next time around" part?

**Comment by alysha-PG** [comment]
No not yet because there are additional overhauls that need to be done between BC and MB, I have it on a list to write up after this release.
