### ISSUE TITLE
BC/UK Driving - quotation mark consistency

### ISSUE THREAD

**Issue by alysha-PG** [pg-irc/pathways-frontend#2003]
driving definitions - << >> symbols around licence and licensed, should be changed to " " to match the quotation marks below

![Image from iOS.png](https://images.zenhubusercontent.com/60b823128e6f424e93549168/7d273fac-6501-4874-9b20-86457ec7c9b5)

**Comment by rasmus-storjohann-PG** [comment]
I think the " should instead be changed to <<>>, as this is Ukrainian convention for quotation marks.

**Comment by alysha-PG** [comment]
The way it is in the rest of the text mostly is that if it's around an English word it's ", and if it's around a Ukrainian word it's <<. This is inconsistent throughout the text and not worth going through and changing everywhere but for this 1 issue where they are right next to each other i think it's worth making it consistent.
