### ISSUE TITLE
BC Farsi and Arabic most phone numbers in content not clickable

### ISSUE THREAD

**Issue by alysha-PG** [pg-irc/pathways-frontend#2061]
Some odd ones out are clickable but most aren't due to spacing. In Farsi, it looks like many phone numbers are formatted with `1 800 999 - 9999`, the extra space/dash combo will throw our script off, this is fixable.

**Comment by rasmus-storjohann-PG** [comment]
FA > Employment > Starting your own business > two phone numbers are not clickable. AR > Health > Healthlink BC > 8-1-1 is not clickable.

**Comment by rasmus-storjohann-PG** [comment]
Phone numbers in FA and AR have digits in scrambled order to make them appear in the correct order in the text, we cannot unscramble them to make them have the correct order to actually call the number. Closing this issue as Won't Fix. Very sad.
