### ISSUE TITLE
BC Farsi:Family and Specialized Support-People with disabilities 

### ISSUE THREAD

**Issue by Meaad-PG** [pg-irc/pathways-frontend#2078]
The phrase should be "Disability Alliance BC" but now it's reading as "Disability Alliance (words in farsi) BC". Erase "BC" from the 2nd line and just add it to the line above so it reads "Disability Alliance BC".

<img width="406" alt="Screenshot 2022-05-30 at 2 01 42 PM" src="https://user-images.githubusercontent.com/102553427/171058839-07e407b5-b3f5-4263-9e59-57199ec1eb33.png">

![IMG_4399](https://user-images.githubusercontent.com/102553427/171059060-e0888847-28cd-4f65-ba6d-1533bcdec9d2.jpg)

**Comment by rasmus-storjohann-PG** [comment]
This is as correct as we can make it. Closing this as won't fix.
