### ISSUE TITLE
BC Farsi: Legal system and Immigration-Hate crimes and help for victims...

### ISSUE THREAD

**Issue by Meaad-PG** [pg-irc/pathways-frontend#2085]
There are four issues in this topic. 

![IMG_4425](https://user-images.githubusercontent.com/102553427/171524113-41ebe5da-f3db-4eb4-8464-43401200a239.jpg)

1. **Red arrow** highlights a missing letter at the beginning of the word **"گر "** it should be **"اگر "** The missing letter is **" ا "**
See screenshot below from the guide.
<img width="379" alt="Screenshot 2022-06-01 at 5 38 47 PM" src="https://user-images.githubusercontent.com/102553427/171523818-440de366-dc01-4f76-9f19-31d558572b6f.png">

2. **Yellow arrow** refers to mixed up order of words. The words in english should be at the beginning of the sentence.
See screenshot below from the guide.  

<img width="407" alt="Screenshot 2022-06-01 at 5 41 13 PM" src="https://user-images.githubusercontent.com/102553427/171524042-3d9549eb-9c6c-49d9-bf70-8774883fcce1.png">

3. **Blue arrow** refers to the word **" mailto"** that should be removed. 

**Issue # 4:** There is a missing second link here. In the guide and english version there are two links.  Attached a screenshot from English content. 

![IMG_4427](https://user-images.githubusercontent.com/102553427/171524306-74d4255c-91cb-48fa-8f10-bcd99c1d7079.jpg)

![IMG_4426](https://user-images.githubusercontent.com/102553427/171524297-cc13b814-b88d-43de-95fd-c646927d8855.jpg)

**Comment by brandon-PG** [comment]
The second link is not clickable in the ncg. It appears to be a dead link when I type it in manually. I am going to leave it out of the content
