### ISSUE TITLE
BC Farsi: Legal system and Immigration-For more legal information

### ISSUE THREAD

**Issue by Meaad-PG** [pg-irc/pathways-frontend#2087]
There are 8 issues in this topic. 

1.  Blue arrow points out to the word **"mailto"** that should be removed. 
2. Red and yellow arrows point out to the mixed up order of words. The english words should be at the beginning of the sentences. 
3. Green arrow points out to the word **" نجمن "**  which should be **" انجمن "** it missed the letter **" ا "**
![IMG_4429](https://user-images.githubusercontent.com/102553427/171526693-b2f43180-badc-426e-9c7f-cd0ec7df87cc.jpg)

4. The word **"mailto"** should be removed. 
5. Red arrow points out to the mixed up order of words. The english words should be at the beginning of the sentences. 

![IMG_4430](https://user-images.githubusercontent.com/102553427/171526730-19c505f2-13c5-4463-a43a-6504177277bd.jpg)

6. Blue arrow points out to a small space needed here to separate between the two paragraphs.
7. Red arrow points out to the mixed up order of words. The english words should be at the beginning of the sentences. 

![IMG_4431](https://user-images.githubusercontent.com/102553427/171526734-6594900d-f02a-4b5b-b32e-2a5cfffc7b39.jpg)

See screenshot from the guide. 

<img width="811" alt="Screenshot 2022-06-01 at 6 12 19 PM" src="https://user-images.githubusercontent.com/102553427/171526509-b5c772bf-fc04-494c-9a7a-896b1a1c739a.png">

**Comment by brandon-PG** [comment]
My solution puts the bolded phrases on their own line. Otherwise the english words will always be in the wrong spot described above

**Comment by rasmus-storjohann-PG** [comment]
A few comments:
* Not sure I'm a fan of bringing the EN text on to its own line, but maybe it's the least bad solution for when an RTL paragraph starts with an EN word.
* All fixes seem to be right, just waiting for Meaad to confirm one thing, then I can close this

**Comment by rasmus-storjohann-PG** [comment]
Item number 3 above, see green arrow, has not been fixed.
