### ISSUE TITLE
Support single newline characters in Newcomer's Guide importer and markup

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#209]
ACs: There is a way to specify single newline without paragraph break in the Newcomer's Guide content.

Perhaps a good enough work around is to use bullet lists in these situations?

**Comment by trisapeace** [comment]
I like the idea to just add `\n` directly in the `.md` file.

**Comment by rasmus-storjohann-PG** [comment]
Figured out that the way to do this is to use a single newline, but to make sure that there is at least two trailing space characters on the line before the newline.

**Comment by trisapeace** [comment]
Ah, so does that work automatically with our parser? Or is that something that you needed to add?

**Comment by rasmus-storjohann-PG** [comment]
The parser leaves this unchanged, and the markdown component interprets it to be a linebreak. I just needed to make sure that our import tool leaves the trailing spaces and newline unchanged.
