### ISSUE TITLE
Crash bug: undefined is not an object, evaluating o.taxonomyTerms

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#2092]
Useful information from Sentry:

https://sentry.io/organizations/peacegeeks/issues/3307728546/?project=256284&referrer=weekly-email

* TypeError findExploreSectionBy(lib/selectors/explore/find_explore_section_by)
* Line of code, where `needle` is probably passed in with value `undefined`:
```
export function findExploreSectionBy(needle, haystack) {
    const needleTerms = filterExploreTaxonomyTerms(needle.taxonomyTerms); // <===
```

### Acceptance Criteria 
- [ ]  Use defensive programming to ensure that when this happens again, the app does not crash, e.g. it could instead navigate to the home page or something
- [ ] Figure out the root cause of the issue and fix that.

### Steps for QA: 
1.  

![image](https://user-images.githubusercontent.com/32307781/172203783-48c8ad4f-514e-45bd-87ca-2d01e23ea119.png)

**Comment by alysha-PG** [comment]
no crashes detected this round
