### ISSUE TITLE
BC/EN Legal > For more legal information 

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#2093]
Links in bullet list appear as their own list items, when the should be part of the item above each link.

In BC EN, topic "For more legal information". Each bullet point has one or more links/phone numbers below it. Expected is that each link is part of the bullet point above. Observed is that each link appears as its own list item

 :

![image](https://user-images.githubusercontent.com/32307781/172203452-d9bdd17c-2785-4bf1-8579-85b18ba197ae.png)

**Comment by shivangi-PG** [comment]
Closed with dupe
