### ISSUE TITLE
Create Jobs Stories for the Goals+Tasks

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#21]
@rasmus-storjohann-PG commented on [Wed Feb 14 2018](https://github.com/pg-irc/pathways-backend/issues/190)

**Comment by cherrielam** [comment]
Update on progress as of today (21 FEB)
@rasmus-storjohann-PG and Michael working on consolidating the job stories into this doc to then turn into a survey to put forward to newcomers to discover priorities: https://docs.google.com/document/d/16VDjiQFavl5UpK-kAG40ciy3Q99LFldUVqcqR2R6EA0/edit?ts=5a8dc1b3

@rasmus-storjohann-PG and I worked on new job stories after @amyngai 's feedback (see bottom of doc): https://docs.google.com/document/d/12Gdmv7BgzhHgmWFK1HU7Wx6OebTE4PcsLyGFjVX2G0g/edit?usp=sharing

@rasmus-storjohann-PG and I worked on Experience Map based on @amyngai 's recommendation:
https://docs.google.com/spreadsheets/d/1LUFXUVVuonMzTqAdlZoLLVHfl2Rd8CCc6053GlExvCg/edit?usp=sharing
