### ISSUE TITLE
Investigate react-js as client platform as progressive app

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#24]
AC: Have an understanding of the trade-offs with using react-js to build an a progressive app in light of the Tides Toronto report on how our users tends to use their devices, particularly phones versus computers, and websites vs apps.
* Can share something with a contact, preferably over WhatsApp
* Can use local storage
* Can open google maps

**Comment by bensinjin** [comment]
WIP:

PWA: Pretty useless without service worker support as service workers are in charge of caching data so the app can be used offline.  I think that's a no go considering this functionality does not exist across all browsers. Storage on PWAs is done in a browser database see https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API.

Hybrid app: TODO

Creating share links is pretty straight forward regardless of platform - some references: https://developers.google.com/maps/documentation/urls/guide, https://faq.whatsapp.com/iphone/23559013

**Comment by mackh** [comment]
Tom pointed out that service worker support is going into webkit beta
https://webkit.org/blog/8090/workers-at-your-service/

**Comment by bensinjin** [comment]
It seems Apples implementation of service worker support may actually purge cached data after a period of two weeks. If that’s the case I’m not sure we care to wait for it. Thanks for the post though I’ll take a closer look next week.

**Comment by bensinjin** [comment]
I think we may be leaning towards a react native app but it’s too soon to say. The pwa stuff is pretty awesome but it may be a bit too early days...

**Comment by mackh** [comment]
One thing to consider is that we may want to be careful to avoid forcing
users to download from the app store.

In previous conversations, we wanted to avoid this to keep barriers to
adoption low and not force people to tie their use of the app to an email
address if they want to remain anon

**Comment by bensinjin** [comment]
Oh right, good point. I think we’re talking Wednesday you should join us if you’re around?

**Comment by mackh** [comment]
Sure, that would be great, let me know what time

**Comment by bensinjin** [comment]
Yeah will do
