### ISSUE TITLE
Rework the home page

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#241]
Rework the home page to show: 
* Explain what the app does
* Buttons CTA to go do things in the app
* Include Need Help button moved from top bar
* *optional* What the current state is: Has the user answered questions, are there any tasks in the My Plan
* Keep the button on the nav bar
* Ideally make the whole home page fit on the screen without scrolling;

**Comment by bensinjin** [comment]
This was addressed under #275.

**Comment by rasmus-storjohann-PG** [comment]
Mock needed, moving back to ToDo

**Comment by rasmus-storjohann-PG** [comment]
On closer inspection, this work is done as Ben commented and this story can be closed out.
