### ISSUE TITLE
For discussion: MyPlan as email inbox

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#267]
Ideas for My Plan as email inbox:
* When a task becomes recommended it's just like an email that was just received: Make it bold, make it go to the top of the list. 
* Sort order of the list is the order in which they were added, most recent at the top. We may want to have this just be the default sort order, and allow users to change the ordering using dragging.
* When a task is read, it's just like an email being read: It's no longer bold, stays in the same place in the list
* When a task is starred, it's like an email being starred: Star shows up in the list, and there is a way to see just the starred ones. Also, in the future, starred tasks are stored for offline access. (It would also make sense to have a similar list of all recommended tasks)
* When a task is completed, it's like an email being deleted: It disappears from the list, but it can be found by looking through the archive

**Comment by ArtiBPG** [comment]
@cherrielam to review need when working on designs for V2
