### ISSUE TITLE
Finish styling the app

### ISSUE THREAD

**Issue by bensinjin** [pg-irc/pathways-frontend#294]
New designs have been created and there a couple of outstanding styling tasks left.

https://drive.google.com/open?id=1rm_NKpOr-hL0L4UP7_hlS5yzEf5tzBu2 Current Mockups as of 20181107

ACs: 
- Style Task Detail screen
- Style Explore Detail screen
- Style Help screen: (Need designs)
- Style Privacy screen: (Need designs)
- Style notifications: 'Task Added', 'Questionnaire advertisement after 3 min',  'Questionnaire newly recommended tasks': (Need designs)
- Finish off style related stories under this one

**Comment by robinpuga** [comment]
https://drive.google.com/open?id=1rm_NKpOr-hL0L4UP7_hlS5yzEf5tzBu2 Current Mockups as of 20181107
