### ISSUE TITLE
Onboarding: Simple 1 page with text

### ISSUE THREAD

**Issue by ArtiBPG** [pg-irc/pathways-frontend#323]
Create a simple onboarding page with text. The onboarding screen should inform the user about:
- what the app does
- what they can expect from the app
- heads up about the questionnaire

- get strings ready for translation ASAP, can do this before we write any code

**Comment by cherrielam** [comment]
![1 1x](https://user-images.githubusercontent.com/21990736/49903706-f2bfde00-fe1c-11e8-967a-327d69df4838.png)
Note: image at the top is a placeholder. Thoughts? Ready to dev?
Back button should go back to the start page (select language), only way to go forward is to "Start personalization" or "Skip personalization"

**Comment by cherrielam** [comment]
If ready to dev, the Zeplin is here: https://app.zeplin.io/project/5bc7bfa42e72260acb03aa86/screen/5c1191cc1c6890243d39d5f7

**Comment by rasmus-storjohann-PG** [comment]
@cherrielam is this mock ready to go or are you making a new one?

**Comment by rasmus-storjohann-PG** [comment]
@cherrielam can you add the text to the translation spreadsheet? This will go in early in V2
