### ISSUE TITLE
Help page content: Find numbers for services

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#335]
Figure out which phone numbers should go into our help page

**Comment by ArtiBPG** [comment]
@cherrielam Review and sign off on [Help Page content](https://docs.google.com/spreadsheets/d/1nVVWTH8SfptnEQ6On82UFF_82fcp8FeqKHpeNWgSS4c/edit?usp=sharing)
Tab: Help, columns: Suggested Text and Service detail/click
