### ISSUE TITLE
Newly recommended tasks dialog: Change button

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#360]
ACs:
* Newly recommended tasks dialog: Change button from "add bookmarks" to just "OK", 
* When clicking the button, the dialog is closed and nothing else happens, i.e. bookmarks are not created. 
* The navigation behaviour following the click on OK remains unchanged from how it is now. 
* Keep the selectors in place for now, we will likely want to surface this information in some form.

**Comment by rasmus-storjohann-PG** [comment]
@cherrielam can you confirm that this is what we want to do?

**Comment by robinpuga** [comment]
We discussed changing the button "Bookmark these topics" to just read "OK"... it should not create any Bookmarks... user ends up on the Recommended Topics page.
