### ISSUE TITLE
Document app release and deployment process

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#364]
## Server side
Staging/release

## Client side
App Stores
Channels

## Versioning

**Comment by bensinjin** [comment]
This outlines our notes regarding release process: https://docs.google.com/document/d/1D9qAX1k3RFpRgMDDABKSS5g3A7CypBZ6MAq2CzumHnM/edit?ts=5c141a4f#heading=h.xo4vi3hg5h4f

**Comment by rasmus-storjohann-PG** [comment]
Good link for Apple store process 
https://www.raywenderlich.com/120-how-to-submit-an-app-to-apple-from-no-account-to-app-store-part-1

**Comment by rasmus-storjohann-PG** [comment]
@ArtiBPG  to come up with freeze dates

**Comment by rasmus-storjohann-PG** [comment]
Steps to script and/or document:
- [ ] Tag the content
- [ ] Tag the client code base
- [ ] Make a script releasing the app
- [ ] Bump version, android versionCode
- [ ] Build with bi + ba
- [ ] Check the flag to not debug google analytics
- [ ] Expo whoami
- [ ] Capture the hash of HEAD of content
- [ ] Filter out unsupported languages from content

**Comment by rasmus-storjohann-PG** [comment]
Things to remember next time we release to the Apple store (they only allow changes to the store presence as part of a release, annoying):
- [ ] Update urls from https://peacegeeks.org/arrival-advisor to https://arrivaladvisor.ca/

Cherrie should probably be involved in the next release for the App store to review copy

**Comment by rasmus-storjohann-PG** [comment]
Updates for the release script (client):
- [ ] Execute the expo bi ba build steps after user confirmation
- [ ] Add command line option staging or release, hard-code the two urls in the script
- [ ] git tags should include whether it's staging or release
- [ ] staging and release builds cannot have the same version string, meaning ideally all odd builds will be staging and all even ones release. Real world that is unlikely to be the case, which is no big deal.

**Comment by rasmus-storjohann-PG** [comment]
Release issues now tracked in #502
