### ISSUE TITLE
Topics: Newcomers' Guide import: Take topic sort order from a file

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#365]
ACs:
* The topic (task) data model is modified to contain a new field "index" which is a zero-based counter representing the ordering of the topics within a chapter.
* Topic sort order within a given chapter can be specified using a file with path `content/NewcomersGuide/<chapter>/order.txt`
* If the file does not exist, topics in that chapter are sorted alphabetically by their ids (current behaviour)
* If the file exists, it should contain the topic ids as they appear in the content directory structure (i.e. not slugified), one id per line. The ordering of the ids should be the ordering of the topics within the chapter.
* If the file contains a duplicate id, a missing id (a topic exists in the content directory structure but it does not appear in the file), or an invalid id (an id appears in the file that does not appear in the directory structure), import of the data fails. 
* Carry the index number through the import to the exported tasks.ts fixture file and use it to sort topics in lists in the client.

**Comment by ArtiBPG** [comment]
If we add a new content resource then it will not make sense. Do we still need this now that we have categories?

**Comment by cherrielam** [comment]
IF it is not a costly task, I recommend that we still do this now, it makes the organization of our topics sorting much more sensible in the short term. 

Adding more resources is a longer term project which we can deal with the order as that happens.

**Comment by cherrielam** [comment]
Also can the order.txt eventually be responsive to our analytics, eg. which topics are being opened most often will rise to the top?

**Comment by ArtiBPG** [comment]
> @ArtiBPG @rasmus-storjohann-PG IF it is not a costly task, I recommend that we still do this now, it makes the organization of our topics much more sensible in the short term. Adding more resources is a longer term project which we can deal with the order as that happens.

lets do this first, I will create a new issue.
