### ISSUE TITLE
Set up translation support system for app strings

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#366]
ACs:
* Recommendation for a platform for manage strings so translators can work on the platform, not spreadsheets
* Nice to have: The platform has translation memory, handle updates to strings, to have translators review translations of strings that have changed in English
* Nice to have: Glossary
* Connects with Git repository: dev can push strings for translations and pull translated strings back into repo.

[Previous research](https://gist.github.com/tnightingale/10301e58e96cbd53e22c2d337a07dee4)
Another platform to consider: [Weblate](https://weblate.org/en/) - open source and free
[What the translator interface looks like](https://www.youtube.com/watch?v=J7I-EOK1UME)

**Comment by rasmus-storjohann-PG** [comment]
@ArtiBPG can you complete this issue with some acceptance criteria, some idea of what should be in place for us to say that this task is "done".

**Comment by tomy-pg** [comment]
Weblate AWS Setup: https://docs.google.com/document/d/1fsKZvG4u9QyVs0ov9ZQi65NcIq2JI-j7lqiw3yRuEPc/edit
Weblate Workflow and Features: https://docs.google.com/document/d/1IasGRezuUeiSDGBud5C9tIWWhz--5zFvAupo9M-hNEo/edit

**Comment by tomy-pg** [comment]
Having some issues with the Translation Status being really inconsistent. Digging into the issue.

**Comment by tomy-pg** [comment]
Can confirm that Translation Status being inconsistent is a caching issue. Weblate creators highly recommend caching with Weblate (although I haven't found out all of the reasons why). I currently have Redis running on the server but I will probably need to use a caching service such as [ElastiCache](https://aws.amazon.com/elasticache/).

**Comment by tomy-pg** [comment]
TODO: 
Translation Memory
Add Google Translate / other translation tools (I need a credit card for Google translate) 
Glossary

**Comment by tomy-pg** [comment]
Be more aware of duplicate strings across .po files. 
For example, because there as some strings that are duplicates of each other in FR, 
Weblate flags the strings as needing editing and this affects how the strings look in the app until this is resolved. 

![Screenshot_20190626-093235_Arrival Advisor](https://user-images.githubusercontent.com/47794846/60199251-58dbe380-97f8-11e9-8750-02103a5308db.jpg)

**Comment by rasmus-storjohann-PG** [comment]
Closing as complete, no QA needed
