### ISSUE TITLE
Section headings in topic lists

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#368]
ACs:
* Topic in topic lists are sorted by their sections
* Each section has a heading with section name and icon 
* Needs mocks

**Comment by cherrielam** [comment]
See bottom section of this mock: https://zpl.io/beLgK1W

**Comment by cherrielam** [comment]
Pls discuss who is responsible for this! @rasmus-storjohann-PG @DarwishMenna @bensinjin
