### ISSUE TITLE
Update the ReadMore component

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#369]
See mock: [https://zpl.io/2pnXkR8](https://zpl.io/2pnXkR8) or in app zpl://screen?pid=5bc7bfa42e72260acb03aa86&sid=5c363c1a0b5f05bdc987351c

ACs:
* Read more button looks good
* The read more component is never smaller when expanded than collapsed
* Mocks needed
* "Read more" is 16 px below the text and 24 px above the grey line; when text is expanded the arrow will point upwards and text will say "Read Less", position with stay the same (still be 16px below the bottom of the text and 24 px above the grey line.)

More spacing reference on top of Zeplin, if need

![topic detail 1x](https://user-images.githubusercontent.com/21990736/50922359-2a5f7d00-13ff-11e9-91c9-450b5e190292.png)

**Comment by cherrielam** [comment]
@bensinjin this should be ready to go! Small issue, I will create a separate issue for the other Topic Detail stuff

**Comment by bensinjin** [comment]
This will include #383 as this is a small story

**Comment by bensinjin** [comment]
Bug: This has been merged but we need to look into how to deal with the new bookmark button triggering the "reset" ie. re closing the readmore.
