### ISSUE TITLE
Font: Avenir for Android

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#371]

**Comment by cherrielam** [comment]
Reopening this if there's time to fix the way the Avenir Black renders in Android. I think it's a different font file and that's why it's loading as the default Android font not Avenir.

**Comment by bensinjin** [comment]
Cherrie and I sat down, here's what we're doing: Any style that uses a 900 weight swap font family for AvenirBlack on Android. Font family download here: https://github.com/potyt/fonts/blob/master/macfonts/Avenir/Avenir-Black.ttf
