### ISSUE TITLE
Reorganize bottom nav and top nav

### ISSUE THREAD

**Issue by cherrielam** [pg-irc/pathways-frontend#374]
See mock: [Open in Web - zpl.io/beLgK1W](https://zpl.io/beLgK1W) or zpl://screen?pid=5bc7bfa42e72260acb03aa86&sid=5bc7c591c5588f18fa4caaae to open in app

**Bottom nav** should have three icons: Recommended, Learn, Bookmarks -- **EDITED JAN 8, 4:52 PM**
_Recommeded (left) is your landing/active page, Learn (middle) - should have higher importance and hierarchy than Bookmarks, Bookmarks is on the right - least priority. Onboarding should take you directly to the Recommended page if they complete the questionnaire._

**Top nav** should have a right hamburger menu icon and a left "help" icon. Left "help" icon opens to the Help page, Right menu icon opens to a menu with language and other items. 

New mock for the Right Menu to come, see: #376

**Comment by bensinjin** [comment]
This will include: https://github.com/pg-irc/pathways-frontend/issues/376
