### ISSUE TITLE
Ensure we can translate strings with JS Lingui

### ISSUE THREAD

**Issue by bensinjin** [pg-irc/pathways-frontend#375]
Js Lingui has changed since our initial implementation. The `<Trans>` component looks to keep working as expected but strings passed to `props.i18n.t` as done previously (see https://github.com/pg-irc/pathways-frontend/commit/e6843b6bfec3eb9b38211a891854917b306790ed#diff-7765904c0fb44044594e919a5dd53488R55) don't appear to be picked up by `yarn extract`. Here's some useful links:

- This outlines what `withI18n` should look like now: https://lingui.js.org/ref/react.html#withi18n
- This covers TS support: https://lingui.js.org/guides/typescript.html, and should be reviewed to see if we need to bring in any new type definitions, I think we'll likely want at least `withI18nProps` from `lingui__react` as we're currently using our custom `i18nProps` type.

AC:
- Develop a standardized way to translate strings in cases where we cannot use the `<Trans>` component.
- Be sure to check `yarn extract` properly extracts these strings and they should show up in `messages.js` files in the `/local/[language-code]/.` directories.

**Comment by ArtiBPG** [comment]
@rasmus-storjohann-PG review today and close or update or assign to someone

**Comment by rasmus-storjohann-PG** [comment]
Currently we are not using the `props.i18n.t` in the welcome component or anywhere else that I can find. Closing this issue, we'll deal with this problem if and when we run across it in the future.
