### ISSUE TITLE
Update Right Drawer Menu with About the App info

### ISSUE THREAD

**Issue by cherrielam** [pg-irc/pathways-frontend#376]
See mock: [https://zpl.io/adrwJGe](https://zpl.io/adrwJGe) or open in app: zpl://screen?pid=5bc7bfa42e72260acb03aa86&sid=5c35398881e80429857c679a **Happy to review this as a team before it goes into development**

The right drawer has been split into two sections: Top being the language selection section and Bottom being the About the App section. 

Specs if you need:
![right menu drawer](https://user-images.githubusercontent.com/21990736/50868430-60035800-1364-11e9-8b9b-7b1c347e7bd3.png)

**Comment by bensinjin** [comment]
Included under: https://github.com/pg-irc/pathways-frontend/issues/374
