### ISSUE TITLE
App content: About, Privacy, Disclaimer, Help, ToS

### ISSUE THREAD

**Issue by ArtiBPG** [pg-irc/pathways-frontend#378]
Final EN content needed for:
About page - done
Disclaimer - done
Help - done
Privacy - done
Logos of funding agencies- done
[TOS](https://docs.google.com/document/d/1ctsj7YzHENK7YO6BoA0AZm0i7SjiOuw1w_Ok8dkiuDk/edit?usp=sharing) - done. Use the content in the doc.

Content is in a spreadsheet now, needs a final resting place: https://docs.google.com/spreadsheets/d/1nVVWTH8SfptnEQ6On82UFF_82fcp8FeqKHpeNWgSS4c/edit?usp=sharing

Need to determine where the ToS will be surfaced, in the app or on the website

Todo:

- [x] Update Privacy Policy on PG website- @cherrielam 

- [x] Figure out where TOS should go @rasmus-storjohann-PG . On the About page, link to existing page at https://arrivaladvisor.ca/terms-conditions/ (Note that a TOS is important for apps that "That are part of a SaaS app, That have user-generated content, That are part of an ecommerce store" ([source](https://www.termsfeed.com/blog/terms-conditions-mobile-apps/)), so it's not urgent yet.)

- [x] Review [TOS](https://docs.google.com/document/d/1ctsj7YzHENK7YO6BoA0AZm0i7SjiOuw1w_Ok8dkiuDk/edit?usp=sharing) @rasmus-storjohann-PG 

- [x] ~Add TOS to App store/Play Store @rasmus-storjohann-PG.~

- [ ] Add logos of funding agencies @cherrielam 

Note that the terms of service link was not implemented as part of this issue, see #646 for that work.

**Comment by ArtiBPG** [comment]
@rasmus-storjohann-PG add to content Repo
Assign to Lauren to update About page and shorten sentences.

**Comment by rasmus-storjohann-PG** [comment]
Created stub files here https://github.com/PeaceGeeksSociety/content/tree/master/ArrivalAdvisor, please edit these files to fill in the actual content, and create translated files alongside them with language code prefix on the file names.

**Comment by ArtiBPG** [comment]
[Privacy policy should link to the PG policy](https://peacegeeks.org/privacy)
[Draft privacy policy](https://docs.google.com/document/d/1t74LDFwMZigSrDNLy3Bu1oCf7GIfDTPpEzLgLEBXWek/edit?ts=5c35ad0a) @rasmus-storjohann-PG to comment on accurate of section about app privacy.

**Comment by ArtiBPG** [comment]
@cherrielam @rasmus-storjohann-PG 
[Privacy policy approved](https://docs.google.com/document/d/1t74LDFwMZigSrDNLy3Bu1oCf7GIfDTPpEzLgLEBXWek/edit?usp=sharing) by MacCarthy

@cherrielam to update it on the PG website

**Comment by ArtiBPG** [comment]
@rasmus-storjohann-PG TOS is ready for you to review: https://docs.google.com/document/d/1ctsj7YzHENK7YO6BoA0AZm0i7SjiOuw1w_Ok8dkiuDk/edit?usp=sharing

**Comment by cherrielam** [comment]
@ArtiBPG This has now been updated on the PeaceGeeks website. You can review: peacegeeks.org/privacy-policy

**Comment by cherrielam** [comment]
@ArtiBPG Where would you like logos of funders to be added?

**Comment by ArtiBPG** [comment]
@cherrielam The about section makes most sense.  The about section still has placeholders for links in the text is that something we can fix now?

**Comment by rasmus-storjohann-PG** [comment]
Tried to QA, seems like this is all done, although this issue is a bit of a mess so it's hard to tell. Closing.
