### ISSUE TITLE
Clean up questionnaire content

### ISSUE THREAD

**Issue by ArtiBPG** [pg-irc/pathways-frontend#381]
Questionnaire and NCG content is in a [spreadsheet](https://docs.google.com/spreadsheets/d/1e_5bqB6h8r68mWMRohvNPBfn2Fr9MnADpAqvohKMTLo/edit?usp=sharing)

Todo:
- Review questionnaire language
- Use the taxonomy terms in content for review tab to look up articles based on answers to questions.
- Finalize questionnaire language

**Comment by rasmus-storjohann-PG** [comment]
As part of this task, the nomenclature as used in the content was changed from tasks and articles to topics. Task is still widely used in the source code, for future fix.
