### ISSUE TITLE
Update topic detail page

### ISSUE THREAD

**Issue by cherrielam** [pg-irc/pathways-frontend#383]
See mock: [https://zpl.io/2pnXkR8](https://zpl.io/2pnXkR8) or in app zpl://screen?pid=5bc7bfa42e72260acb03aa86&sid=5c363c1a0b5f05bdc987351c

In this issue:
1. Update Top nav for topic detail. Left is a left arrow (to go back), Right is the hamburger button (opens right drawer) and to the left of the hamburger button is the bookmark button. Bookmark becomes solid when bookmarked and unsolid when not. 
2. Update look of tags for Topic Detail. Category tag (eg. education, etc.) now sits above the Topic title in H5 style and the Recommended tag now sits below the Topic title in a new Caption style (it's basically paragraph style but in Book Oblique)
3. Updating grey lines for sectioning and remove the titles (About, Who can help)
4. Change the find services function to a button
5. Bottom Nav Menu appears and is sticky to bottom of the Topic Detail screen (see: https://zpl.io/aByGdBm) so that people can navigate back to the main screens if they go down a rabbit hole of topics.
6. Clicking on a related topic should bring user to the TOP of the related topic screen, so the user can see the image and the title of the new topic they are reading. (Currently it does not scroll the screen back to the top when clicking on a related topic, the scroll position stays the same as the previous page. User does not notice that they are reading a new topic) 
7. Clicking back (breadcrumb) **needs discussion** I noticed that some apps will take the user to the screen position that you were in when you clicked to that related topic, but it might be good to take the user back to the top since all our "related topic" sections look identical.

You can see spacing in zeplin, but also providing this for additional reference:

![topic detail 1x](https://user-images.githubusercontent.com/21990736/50922359-2a5f7d00-13ff-11e9-91c9-450b5e190292.png)

**Comment by bensinjin** [comment]
This will be done under #369
