### ISSUE TITLE
Topics: Reduce number of related topics on Topic Detail

### ISSUE THREAD

**Issue by cherrielam** [pg-irc/pathways-frontend#384]
**NEEDS DISCUSSION**

Number of related topics/threshold needs to be decided.

**Comment by ArtiBPG** [comment]
@cherrielam can you write instructions for what needs to be done in FR and AR?

**Comment by cherrielam** [comment]
Has this not already been resolved? Looks like there are 3 related topics right now? For FR and AR @ArtiBPG 

Looks good to me...
