### ISSUE TITLE
Put "Personalize recommended topics CTA" component on Recommendations page

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#399]
ACs:
* Personalize recommended topics CTA appears on the top of Recommendations page
* The page currently holding that component is removed from the code base

**Comment by ArtiBPG** [comment]
@cherrielam review the request. Is it necessary?

**Comment by cherrielam** [comment]
Yep. Here is a mock [https://zpl.io/VkwQ5rv](https://zpl.io/VkwQ5rv) - for what the questionnaire CTA looks like collapsed, and what the questionnaire looks like expanded is covered by issue #410 

Questionnaire collapsed UI to show when the user has answered (at least 1) questions. 
Questionnaire expanded UI (Home screen issue #410) to show when the user has not answered any questions.

**Comment by cherrielam** [comment]
Can't seem to assign @bensinjin so I'm doing it here
