### ISSUE TITLE
Markdown component needs better style control

### ISSUE THREAD

**Issue by robinpuga** [pg-irc/pathways-frontend#400]
The markdown component in the app is displaying heading styles that are very large and the font in the component isn't matching the rest of the app. This needs improvement. 

Headings on Android also look like a different font (could be separate ticket).

**Comment by cherrielam** [comment]
See #371 for headings on Android (I made a comment)

**Comment by cherrielam** [comment]
Minimum AC:

- headers can be made into smaller headers, eg. from # to ### ? and ## to #### ?
- nice-to-have is better styling overall for the markdown component
