### ISSUE TITLE
Write "short description" and "full description" copy about the app

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#402]
We need this for the app stores. It is quite possible that we will want it translated to our languages.

Also add the English copy to app.json so it shows up in Expo.

### Apple and google stores
As seen in the screen shot below from the google store, promo text is up to 80 characters and full description is up to 4000. In the apple store the corresponding limits are 170 and 4000 characters respectively. We can use almost the same text for both.

Apple rule: Don't mention the android app in the copy.

**Comment by rasmus-storjohann-PG** [comment]
![screenshot from 2019-01-16 17-07-03](https://user-images.githubusercontent.com/32307781/51288621-da118d80-19b1-11e9-8394-22f3040636fd.png)

**Comment by ArtiBPG** [comment]
@rasmus-storjohann-PG add link to content repo and assign to Lauren

**Comment by rasmus-storjohann-PG** [comment]
Created stub files here https://github.com/PeaceGeeksSociety/content/tree/master/AppStores, please edit these files to fill in the actual content, and create translated files alongside them with language code prefix on the file names.

**Comment by rasmus-storjohann-PG** [comment]
@rasmus-storjohann-PG is the copy needed for the apple store similar or the same???

**Comment by laurenrenehyde** [comment]
_Short/Promo Descriptions_

**168** Characters: Arrival Advisor is a free mobile app that helps refugees and immigrants across British Columbia navigate their settlement journey and connect with their new community.

**75** Characters: Directory of services for newcomers to British Columbia navigate settlement

**Comment by cherrielam** [comment]
@rasmus-storjohann-PG FYI for submission the Title should be Arrival Advisor (with space :) ) 

The content in Lauren's PR is now good to go. @ArtiBPG I also added the descriptions here (https://docs.google.com/document/d/1PAgBvCOsch8qfzqrab2EOqpkV6kloYuxsMP7yGXkXPI/edit?usp=sharing) See bottom of document.
