### ISSUE TITLE
Questionnaire component

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#41]
Show a list of questions with various multiple-choice components for answers, see wireframes. Anchor on each question to allow for deep-link to a given question, validate that anchors is really what we need here. Top of questionnaire contains user introduction popup that can be dismissed, see wireframes.

Acceptance criteria:
* Questionnaire component takes an array of questions as props.
* Questions reducer updates the isSelected property on each answer.
* Hard-code mock questions (at least two) and answer data in the reducer.
* Of course: reducer and action generators are unit tested.
* Only minimal styling to make components match wireframes.

**Comment by rasmus-storjohann-PG** [comment]
Data model as set up in the reducer as default content of the store:
```ts
const buildDefaultStore = () => ({
    questions: [
        {
            text: 'Which age group(s) do you and your family\nmembers belong to?',
            canSelectMultiple: true,
            answers: [
                {
                    text: 'Under 5\nyears old',
                    isSelected: false,
                },
                {
                    text: '5-12\nyears old',
                    isSelected: false,
                },
                {
                    text: '13-18\nyears old',
                    isSelected: false,
                },
                {
                    text: '18-64\nyears old',
                    isSelected: false,
                },
                {
                    text: '65+\nyears old',
                    isSelected: false,
                },
            ],
        },
        {
            text: 'Which immigrant type do you identify as?',
            canSelectMultiple: false,
            answers: [
                {
                    text: 'Refugee or refugee claimant',
                    isSelected: false,
                },
                {
                    text: 'Temporary resident',
                    isSelected: false,
                },
                {
                    text: 'Other immigrant or permanent resident',
                    isSelected: false,
                },
                {
                    text: 'None of the above, or I’m not sure',
                    isSelected: false,
                },
            ],
        },
    ],
});
```

**Comment by tnightingale** [comment]
Couple of thoughts:

I'm unsure about having presentational/layout parameters alongside what is essentially content. Specifically the `showInTwoColumns` property. I think this is likely up to the renderer to determine what's best. Presentation & layout will be impacted by a variety of things, for example: 

- device screen size; two columns might not be acceptable for narrow screens / portrait layout
- the number of items in the `sections` list (also brings up the question whether this parameter is tied to the `sections` property or just a general parameter?)

In my experience it's better to encode those decisions as heuristics in the renderer as it tends to scale better as we add more items (& new properties).

We talked about answers being "tagged" with categories for matching later with tasks. How is this applied? I suspect `sections` isn't flexible enough for this (I assume your use of sections is actually just for presentation and not for driving tagging/categorization?). `sections` makes for a useful "hint" to the renderer but for the sake of consistency I'd suggest normalizing it (remove nesting) and make it an optional property. Something like:

```javascript
const buildDefaultStore = () => ({
    questions: [
        {
            text: 'Which age group(s) do you and your family\nmembers belong to?',
            canSelectMultiple: true,
            showInTwoColumns: true,
            sections: [
                {name: 'c&y', text: 'Children & Youth'}
                {name: 'a&s', text: 'Adults & Seniors'}
            ],
            answers: [
                    text: 'Children & Youth',
                    answers: [
                        {
                            text: 'Under 5\nyears old',
                            isSelected: false,
                            section: 'c&y'
                        },
                        {
                            text: '5-12\nyears old',
                            isSelected: false,
                            section: 'c&y'
                        },
                        // ...
                        {
                            text: '18-64\nyears old',
                            isSelected: false,
                            section: 'a&s'
                        },
                        // ...
                    ],
                },
            ],
        },
        {
            text: 'Which immigrant type do you identify as?',
            canSelectMultiple: false,
            showInTwoColumns: false,
            answers: [
                {
                    text: 'Refugee or refugee claimant',
                    isSelected: false,
                },
                // ...
            ],
        },
        // ...
    ],
});
```

This does feel very similar to what we build for another of our projects where we have dynamic surveys defined using a slightly-modified version of [JSONSchema](http://json-schema.org/). We built our own renderer but it was very similar to [json-editor](https://github.com/json-editor/json-editor) ([interactive example here](https://json-editor.github.io/json-editor/)). Might be worth checking out and seeing if any existing schema/standards might fit our needs here.

**Comment by rasmus-storjohann-PG** [comment]
Very good points, @tnightingale. I'll take them into account.
