### ISSUE TITLE
Break About / Privacy / Disclaimer into three pages 

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#414]
ACs:
* About / Privacy / Disclaimer appear each on their own page, linked from the Right-side menu

**Comment by bensinjin** [comment]
About: https://docs.google.com/spreadsheets/d/1nVVWTH8SfptnEQ6On82UFF_82fcp8FeqKHpeNWgSS4c/edit?ts=5c53681e#gid=1736399270 (About tab) also Add copyright blurb to bottom of this page

Privacy: Url to peacegeeks.org/privacy-policy

Disclaimer: https://docs.google.com/spreadsheets/d/1nVVWTH8SfptnEQ6On82UFF_82fcp8FeqKHpeNWgSS4c/edit?ts=5c53681e#gid=1006308193 (Disclaimer tab)

Remove Send Feedback
