### ISSUE TITLE
Recommendations: QA and find the best recommendation algorithm

### ISSUE THREAD

**Issue by ArtiBPG** [pg-irc/pathways-frontend#432]
Recommendation algorithms:
https://arr-adv-bm25.herokuapp.com/swagger/
https://arr-adv-lucene-bm25.herokuapp.com/swagger/
https://arr-adv-lucene-tf-idf.herokuapp.com/swagger/
https://arr-adv-tf-idf.herokuapp.com/swagger/

Round 1 with 10 task ids:
https://docs.google.com/spreadsheets/d/147nMAf6Sax2zJb2nddTp4SpG7BEI53S-Luy87XxJuCc/edit#gid=0
Results in the spreadsheet are from service recommendations based on original content structure- before combining topics.

Nest Step: Analyze similarity score and find patterns

**Comment by rasmus-storjohann-PG** [comment]
@tomy-pg 's findings are written up here https://docs.google.com/document/d/1xrDHzWW1Oqd16neFM8XVWsUjyqBWoddUSmu-wjEUMK4/edit
