### ISSUE TITLE
Task detail component

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#44]
This is the one-task-fills-the-whole-screen view of a task. 

AC: 
* When clicking on the ">" button of a given task in the task list, open the detail page of that task.
* Style the detail page as follows:

![image](https://user-images.githubusercontent.com/32307781/40735542-48b1fe5a-63f0-11e8-8740-31a04948f081.png)

Out of scope to keep the PR small: The Find Services sub-screen. The Learn More section. Any new functionality, including marking a task as completed, share and "..." button. So all tasks will show the COMPLETED TASK label for now.

For context, this is the whole screen:

![screenshot from 2018-05-30 10-01-09](https://user-images.githubusercontent.com/32307781/40735828-103ec246-63f1-11e8-9277-6fa150b1574f.png)

**Comment by rasmus-storjohann-PG** [comment]
Suggested shape for the Task entity:
```
interface Task {
    id: string;
    title: string; // localized
    description: string; // localized
    category: string; // i.e. taxonomy: education, health, etc.
    importance: number; // on enum, values 1-5 or something
    starred: boolean; // this is likely to be tweaked
    completed: boolean;
    isFree: boolean; // this is likely to be tweaked
    lastUpdated: date; // don't know what we'll use to represent dates
}
```
This would be the form of the data for the consumption in the component, a normalized structure should be used in the store, and a selector function should be tasked with converting from one to the other. At least that is my current thinking on normalization. @tnightingale does that sound right to you?

**Comment by rasmus-storjohann-PG** [comment]
@bensinjin we may have had a miscommunication, I took this story to mean the one-task-fills-the-whole-screen component. Did you take it to mean the one-task-in-a-list-of-tasks component? If so, it makes sense that you wanted to do this story at the same time as #42, but as I see it, I think your PR only covers #42.

**Comment by bensinjin** [comment]
Yeah looks that way. The issue number referenced in the commits on the PR have been updated.
