### ISSUE TITLE
Create app store screenshots

### ISSUE THREAD

**Issue by cherrielam** [pg-irc/pathways-frontend#446]
@rasmus-storjohann-PG @ArtiBPG when are these due? and can you provide specs?

**Comment by rasmus-storjohann-PG** [comment]
This is the graphics needed for the Android store

![image](https://user-images.githubusercontent.com/32307781/52364405-f8d7d280-29f9-11e9-97f5-88b4450d2fda.png)

**Comment by rasmus-storjohann-PG** [comment]
### For the Play store (Android): 

* Hi-res icon: 512 x 512 32-bit PNG with alpha
* Feature graphic: 1024 w x 500 h 24 bit JPG or PNG, no alpha
* Promo graphic: 180 w x 120 h 24-bit JPG or PNG, no alpha
* Optional promo video (youtube link)
* Up to 8 screenshots for phone and 8 screenshots for tablet

**Comment by cherrielam** [comment]
Product icons are here: https://drive.google.com/open?id=1qVY0CqXn-IK8zOM_dcPbsCLcuYr3xiFU @rasmus-storjohann-PG

**Comment by cherrielam** [comment]
Here are the screenshots: https://drive.google.com/open?id=1ggzNuBS_kyQW-sW-X_GCCLErSL-QXGdL @rasmus-storjohann-PG

**Comment by rasmus-storjohann-PG** [comment]
So @cherrielam I should ignore the files from 14 days ago and use the ones from 16 hours ago?

**Comment by rasmus-storjohann-PG** [comment]
Still need screenshots for Android
