### ISSUE TITLE
Don't breadcrumb about and disclaimer

### ISSUE THREAD

**Issue by bensinjin** [pg-irc/pathways-frontend#455]
AC: About, disclaimer: Don't breadcrumb these, they have an X button which takes you back to the
most recent non-about non-disclaimer page

This involves messing around with our router's history (in theory, there may be a better way). I'm going to see if there are good ways to do this last but it won't be a priority.

This comes from #450.

**Comment by rasmus-storjohann-PG** [comment]
How about making about and disclaimer pages into modals? End-run around the router

**Comment by cherrielam** [comment]
Can we remove the right-arrows in the menu? Thanks!

![Screenshot_20190719-134226](https://user-images.githubusercontent.com/21990736/61564464-5cdfd780-aa2b-11e9-9ad0-3d18fddea247.png)

**Comment by ian-lin-PG** [comment]
@cherrielam Does this looks like what you were thinking?

![image](https://user-images.githubusercontent.com/52009863/61566106-e85b6780-aa2f-11e9-9cea-0e88d868b087.png)

**Comment by tomy-pg** [comment]
Client: 1.1.0 / Server: 1.3.5 

Arrows have been removed on iOS and Android.

**Comment by jparlina** [comment]
Tested on Staging V1.4.0, Server V1.3.9 on iOS:
no back button on About page and Disclaimer page, have an X button which takes you back to the most recent non-about non-disclaimer page
