### ISSUE TITLE
Simple fix to the recommendation/bookmark confusion + add PG logo

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#458]
Suggestion: Change the icons for either or both these concepts. (see Cherrie's comment below)

Also, Add PeaceGeeks logo to the landing screen. See zeplin: https://zpl.io/adPzkPR

**Comment by cherrielam** [comment]
Use the user-check FontAwesome5 icon. See zeplin: https://zpl.io/beLgK1W (ignore the stars at the bottom)
