### ISSUE TITLE
Bug? Map defaults to Apple Maps in iPhone and does not option in other even though it claims to?

### ISSUE THREAD

**Issue by cherrielam** [pg-irc/pathways-frontend#463]
Gordon from our Marketing Agency mentioned that clicking the button "Open in Maps" always defaults to Apple Maps for him even though the copy claims to give him the option to open in other maps. He keeps getting redirected to the app store to download Apple Maps I think. Can someone look into this?

**Comment by robinpuga** [comment]
Based on old build; now fixed.
