### ISSUE TITLE
Answer option needs to be added

### ISSUE THREAD

**Issue by ArtiBPG** [pg-irc/pathways-frontend#505]
The question " Do you need financial assistance or low income support?" has only 2 options- Yes and No. People who have already applied for and received financial assistance will reply No. However, they should see articles and services for low income.
Suggestion: Add an option that says " I have low income assistance" This will bring up the same topics and services as "Yes".
This came up during a user testing session.

![screenshot_20190227-170938_arrival advisor](https://user-images.githubusercontent.com/44411551/53534407-967f6880-3ab3-11e9-8f09-8d254ca6ba26.jpg)

**Comment by rasmus-storjohann-PG** [comment]
@cherrielam can you sign off on the string for this story, the question in the questionnaire is "Do you need financial assistance or low-income support?", the new answer is "I have low income assistance", it will have the same meaning as "Yes". @ArtiBPG how do you want to manage the translation of this string?
