### ISSUE TITLE
App store description needs to be updated

### ISSUE THREAD

**Issue by cherrielam** [pg-irc/pathways-frontend#512]
App Store description (in English) needs to be updated to include acknowledgment of LEAP | Pecaut Centre for Social Impact, and also to point people to the domain: arrivaladvisor.ca

What's the best way to do this? In the content repo? LMK @rasmus-storjohann-PG @bensinjin

**Comment by ArtiBPG** [comment]
@cherrielam can you tell me if:
1) A string currently available in the Content Translation sheet needs to be updated? If yes, give me:
Current text:
New text:
2)  A brand new string needs to be added. If yes, give me:
Text for new string:

Also, let me know:
3) Which content tabs does it need to be added to? All or some of these?
C1 - UI Strings
C3 - About (in the app)
C4- Disclaimer
C7 - Long and short description for App Store

**Comment by cherrielam** [comment]
@ArtiBPG @rasmus-storjohann-PG 
In your Content For Translation Spreadsheet
**old**: The Arrival Advisor app is created by PeaceGeeks in partnership with settlement organizations in Metro Vancouver, as well as immigrants and refugees like you. This project is possible thanks to funding by the Province of British Columbia and the Google.org Impact Challenge Canada.

**new**: The Arrival Advisor app is created by PeaceGeeks in partnership with settlement organizations in Metro Vancouver, as well as immigrants and refugees like you. This project is possible thanks to funding by the Province of British Columbia and the Google.org Canada in partnership with LEAP | Pecaut Centre for Social Impact.

**note** this string: Settling in British Columbia is now easier, with Arrival Advisor. Learn more at https://arrival-advisor.ca used to be https://peacegeeks.org/arrival-advisor. This is already changed in the spreadsheet but I noticed that the French column still has the old URL

**Comment by rasmus-storjohann-PG** [comment]
The English string "The Arrival Advisor app is created by PeaceGeeks..." was updated as part of https://github.com/pg-irc/pathways-frontend/pull/531/files under the issue #529.

**Comment by cherrielam** [comment]
@rasmus-storjohann-PG @ArtiBPG The website URL in some of the final translations of the app description say https://arrival-advisor.ca when it should say https://arrivaladvisor.ca. Specifically the Korean (ready) and Chinese Simplified (ready) translations both have the wrong URL.

I see that in the OLD Content for Translation (bulk) spreadsheet the arrival-advisor.ca URL was used so it must've been incorporated as a mistake. Can we make sure this is updated?

@robinpuga it might also be a good idea to also purchase arrival-advisor.ca domain and redirect to ours.

**Comment by rasmus-storjohann-PG** [comment]
This is done for English, still need to check the other languages include the LEAP reference.

**Comment by rasmus-storjohann-PG** [comment]
From Apple: 
![image](https://user-images.githubusercontent.com/32307781/58918410-03bc1e80-86df-11e9-8e61-a6961fed9f31.png)

From Google:
![image](https://user-images.githubusercontent.com/32307781/58918422-10407700-86df-11e9-9ddd-d1f9ad47aefb.png)
