### ISSUE TITLE
French Arrow Misalignment

### ISSUE THREAD

**Issue by ludivinegh** [pg-irc/pathways-frontend#515]
**Describe the bug**
The first arrow is not aligned with the following ones, because the string that precedes it is long.

**App version**
1.0.7

**To Reproduce**

1. Go to help screen.
2. See error for the first arrow.

**Expected behavior**
The first arrow should ideally be aligned with the following ones. This should be done by reducing the font size or adding a line break.

**Screenshots**
http://glbl.me/n85

ACs:
* Make the affected line (see screenshot) wrap a little earlier so 9-1-1 goes on to the next line and the arrow lines up with the other items
* This is UX polish, not top priority

**Comment by tomy-pg** [comment]
This bug is no longer appearing in the app that is released in both stores as well as the develop branch.

**Comment by rasmus-storjohann-PG** [comment]
The issue has not been resolved, this is in develop:

![image](https://user-images.githubusercontent.com/32307781/58117388-4cd68380-7bb3-11e9-8487-1b0edff31cac.png)

**Comment by ArtiBPG** [comment]
Arrows are still not aligned: https://www.screencast.com/t/MwLkQLH9IcE
Testing Staging 1.0.23 (Android)

**Comment by jparlina** [comment]
Fixed in Staging 1.0.23 (iOS)
