### ISSUE TITLE
Make button accomodate two lines of text

### ISSUE THREAD

**Issue by ludivinegh** [pg-irc/pathways-frontend#516]
**Describe the bug**
The French translation of these two buttons is quite long, and the layout is off. Consider shortening the translations or reducing the font size, to prevent the strings from being so close to the buttons' edges.

**App version**
1.0.7

**To Reproduce**
1. Go to help screen.
2. See error for both buttons.

**Expected behavior**
Shorter buttons or a smaller font would look better

**Screenshots**
http://glbl.me/n83

ACs:
* Update relevant long strings to include `\n` for newline
* Change UX logic to detect the `\n` in the string and make a button that is large enough to acomodate two lines of text

**Comment by rasmus-storjohann-PG** [comment]
So this looks a little better, is this issue considered fixed?

![image](https://user-images.githubusercontent.com/32307781/54044185-30fe3c80-4183-11e9-9014-a64526c2ee35.png)

**Comment by rasmus-storjohann-PG** [comment]
For easier access, this is the screenshot with the broken handling of two lines of text on the button, this is bad:

![image](https://user-images.githubusercontent.com/32307781/54044252-5c812700-4183-11e9-8a2f-0c64bbeb1617.png)

**Comment by rasmus-storjohann-PG** [comment]
Just need to fix one remaining issue with this button
