### ISSUE TITLE
French Misalignment in Menu

### ISSUE THREAD

**Issue by ludivinegh** [pg-irc/pathways-frontend#517]
**Describe the bug**
This is likely because of the checked mark, but French doesn't seem to be aligned with the other languages.

**Version**
1.0.7

**To Reproduce**

1. Go to the main menu
2. Go to language changes
3. See error (the word "Français" is not aligned)

**Expected behavior**
The word "Français" should be aligned

**Screenshots**
http://glbl.me/n7z

**Comment by rasmus-storjohann-PG** [comment]
This is about bringing the UX to a high polish, not top priority to fix
