### ISSUE TITLE
Delete user data function does not work as expected

### ISSUE THREAD

**Issue by ArtiBPG** [pg-irc/pathways-frontend#518]
**Describe the bug**
Delete user data function does not work as expected

**App version**
1.0.6 and server version 1.1.2

**To Reproduce**
1. Go to '? button
2. Click on Delete all user data
3. Goto home page and click on "Answer Questions"
4. Questionnaire goes to the 10th question or the last question answered

**Expected behavior**
I expect the app to basically reset. So in step 4, it should go to the first question.

**Comment by rasmus-storjohann-PG** [comment]
Should be an easy fix, set the current question to 0 as part of the reset in the questionnaire reducer

**Comment by tomy-pg** [comment]
@ArtiBPG  I think this may have been fixed with the latest version of the app (1.0.8). I have tried to reproduce this on both Android and iOS but could not.

**Comment by rasmus-storjohann-PG** [comment]
Closing as Could Not Reproduce
