### ISSUE TITLE
Untranslated text in the About section in the FR version 

### ISSUE THREAD

**Issue by ArtiBPG** [pg-irc/pathways-frontend#521]
There is some English text in the About section of the FR app
Screenshot: https://i.imgur.com/DFzz6y2.png
Version 1.0.6, server version 1.1.2 from Play Store

Update this once the final FR text has been submitted

**Comment by ArtiBPG** [comment]
@tomy-pg get translations from [here](https://github.com/pg-irc/pathways-frontend/issues/529)

**Comment by tomy-pg** [comment]
@ArtiBPG I believe @rasmus-storjohann-PG has completed this issue.
