### ISSUE TITLE
UI Layout breaks when font is larger

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#525]
iOS setting allows for larger fonts for accessibility. 

AA v1.0.7

This breaks some of our layouts. This will be an issue for languages as well, esp French (and Spanish)

![image](https://user-images.githubusercontent.com/32307781/53825133-72e07600-3f2a-11e9-9e80-aa5d11cd1ed3.png)

**Comment by cherrielam** [comment]
Hmmm, I've poked around an done some research on this, some of the info is very techie so I had trouble understanding. But this seems like an informative read (maybe?): https://medium.com/bbc-design-engineering/improving-your-apps-accessibility-with-ios-11-db8bb4ee7c9f

**I imagine there are 3 UI options:**
1) Force the font size to stay the same despite accessibility changes (not 100% sure if we can do this? But it seems possible, like for example, this can be done for the bottom nav bars to prevent scaling — see article linked above.)
2) Scale the entire box when the text scales. Make the box full width when the text gets so large that it needs to wrap around? (This will likely take some programming finagling that I am ill-equipped to measure the cost of)
3) Do nothing — I think that people who are using larger font sizes for accessibility get that the size is making the words break. Obvious it's not pretty but it's still legible.

Thoughts? @bensinjin @rasmus-storjohann-PG @tomy-pg

**Comment by cherrielam** [comment]
OK here's some more substantive ideas from @amyngai and her AxiomZen friends 😄 
>A few early thoughts:
>- you can turn on `hyphenationFactor` in iOS and define your hyphenation
>- if you used collection view, you might be able to set the min-max width of a card and it can dynamically lay the cells out for you (eg: on landscape view, you can have 3 cards per column or make it fit 50% or dynamic padding)

>It would be very easy to go from that 2 column grid layout to a one column grid layout programmatically based on the dynamic text size changes, assuming they did it in a standard way (UICollectionView)

>You can check the `UIApplication.preferredContentSizeCategory` which will tell you which dynamic text size the user is using. You can also subscribe to notifications for when that setting changes. Then you would just change the collection view layout based on that with some pretty simple math calculating the cell size for one column instead of 2

**Comment by ian-lin-PG** [comment]
I am just responding to Cheerie three ideas for pursuing this issue as well as commenting on the suggestions Amy provided.

1. There is a way in react-native to lock the Text components such that they are immune to the Font change from the iOS accessibility options. There should probably be more discussion before pursuing this route.

2. This is probably the preferred approach for resolving this issue. Right now we use expo to compile our application which abstracts many of the iOS specific options that Amy was suggesting. I could find well supported react-native equivalent for hyphenation or UICollectionView, see [under maintained hyphenation library](https://github.com/HyphenateInc/hyphenate-react-native),[UICollectionView inclusion ignored](https://github.com/facebook/react-native/issues/638) and [No longer maintained ReactNative grid library](https://github.com/lucholaf/react-native-grid-view). Currently digging into codebase to search for switch cases and proper styles that may help with the situation.

3. Easiest option 👍

**Comment by ian-lin-PG** [comment]
After talking to Tomy and more digging, there is a few sub bullet points to 2.
a. Set [maxFontSizeMultiplier](https://facebook.github.io/react-native/docs/text#maxfontsizemultiplier) or [adjustsFontSizeToFit](https://facebook.github.io/react-native/docs/text#adjustsfontsizetofit) to force the fonts to stay within a certain size hence prevent breakage. 

b. Using font size or font scale information to dynamically set width of the component such that it becomes single column when a threshold is reached. The main issue is that react-native font retrieval helpers are android specific, see [here](https://facebook.github.io/react-native/docs/pixelratio#getfontscale). Which means we have to use third party libraries to retrieve font information including [react-native-text-size](https://www.npmjs.com/package/react-native-text-size?activeTab=readme) or [react-native-device-info](https://www.npmjs.com/package/react-native-device-info/v/0.9.1).

**Comment by ian-lin-PG** [comment]
a.[maxFontSizeMultiplier] is not an available option to include when I tried it, despite being released in the version of react-native that our current expo is built on. [adjustsFontSizeToFit is apparently bugged](https://github.com/facebook/react-native/issues/20906).

b.Both library requires linking the react-native module which [expo does not support](https://github.com/expo/expo/issues/56).

Back to square 1, quite literally.
1. I have been able to turn off font scaling from accessibility settings, however, whether it is worth it or if it breaks the experience probably requires more discussion. 
![image](https://user-images.githubusercontent.com/52009863/60684325-f5822f00-9e51-11e9-801f-d02df7fe69e0.png)

**Comment by rasmus-storjohann-PG** [comment]
Currently blocked on the upgrade to Expo 33

**Comment by ian-lin-PG** [comment]
Preliminary tests on maxFontSizeMultiplier is successful. The max scaling for this page specifically is 1.4. Currently deciding on whether to apply this prop across all Text components and the best approach to do so.

**Comment by ian-lin-PG** [comment]
First image scaled up to 1.4, second image is default size. The difference is not immediately obvious until compared side by side.

![image](https://user-images.githubusercontent.com/52009863/60842563-3303f680-a189-11e9-9e0a-f622f65fb5a8.png)
![image](https://user-images.githubusercontent.com/52009863/60842569-39926e00-a189-11e9-8b28-1cf104bbb1d8.png)

**Comment by ian-lin-PG** [comment]
Here is a visual comparison between 1x scale, 1.4x scale and the maximum 1.47x scale.
![image](https://user-images.githubusercontent.com/52009863/61011514-b4958900-a32f-11e9-908a-dd0986f37d79.png)

**Comment by ian-lin-PG** [comment]
I created a wrapper class with the maxFontScaleMultiplier preset. I replaced most of the old text components with this new class. This is a lot of changes in a lot of class files. I am open to suggestions for other approaches as well.

The markdown component isn't a Text component, so the detail descriptions did not have the maxFontScale set. I am open to suggestion for this area as well.
