### ISSUE TITLE
Rendering of email and web site urls is unclear

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#526]
![image](https://user-images.githubusercontent.com/32307781/53825211-a0c5ba80-3f2a-11e9-9435-0854dc84120d.png)

ACs:
* Change the import script so that is shows: "Email foo@bar.com Website: www.foo.com/xyz...", i.e.
* Put in prefix "Email" and "Web"
* Show email address and web address instead of "email" and "link"
* If web address is longer than 28 characters, truncate and append "..." so that the resulting web address is 28 characters long, unless that would truncate off the end of the host name, in which case truncate such that the entire host name is included, i.e up to the end of ".com" or ".ca"

@cherrielam for review

**Comment by cherrielam** [comment]
I agree. Sounds good @rasmus-storjohann-PG
