### ISSUE TITLE
French text ready for import

### ISSUE THREAD

**Issue by ArtiBPG** [pg-irc/pathways-frontend#529]
Text in all tabs named "Ready" can be imported into the app.
[French](https://docs.google.com/spreadsheets/d/15GX7p6YL1N3ZfcXe-jRWlbdTMbx0XlaF38zuH61k-e0/edit?usp=sharing)

- Use the translations in the column "French" in all tabs labelled "Ready"
- Ignore the text in hidden columns.

C1 - UI Strings
C2 - Questionnaire
C3 - About (in the app)
C4- Disclaimer
C5 - Headings for topics that were combined from the NCG
C7 - Long and short description for App Store
C8 - Text on screenshots for the app store and Play Store
C11- Learn page short descriptions
C12- Keywords for app store and play store

ACs:

All these UI strings are imported into the app, the app store page, etc. These strings are all ready to go now.

**Comment by rasmus-storjohann-PG** [comment]
Apple store text can apparently(?) only be updated as part of a new release. Added a comment to the release story with the text to be entered for iOS.

**Comment by rasmus-storjohann-PG** [comment]
We don't have multilingual screenshots for the app store yet
