### ISSUE TITLE
BC211: Handle letters in BC211 service phone numbers

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#537]
Variety - The Children's Charity has phone number "310-KIDS (5437)". This confuses the app, and the phone number is not clickable.

There are a few different formats in the BC211 database, but the most common pattern is "1-888-4AL-ANON (1-888-425-2666)", i.e. with the entire phone number in brackets after the mnemonic number. A variant is this pattern "1-800-222-TIPS (8477)" where only the mnemonic part of the number is repeated, but it is less common.

ACs:
* Phone numbers of the format "1-888-4AL-ANON (1-888-425-2666)" is clickable in the app and calls the right number
* Phone numbers of the format "1-800-222-TIPS (8477)" are not clickable, this is out of scope for this issue since the pattern is quite rare and not worth the effort. But if it's easy to make it work too, go ahead.
* Phone numbers of the format "1-888-425-2666" are already clickable in the app, keep that in place obviously
* The format "604-436-9449 Local 221" and "604-792-2760 Ext 221" are clickable, this should already be in place. The app does nothing with the "221" part of the numbers.
* Ensure that there are unit tests in place to demonstrate how all of these patterns are handled. Solve this as follows:
   * Make a function that takes in the whole phone number string and returns a valid all-numeric phone number for handled cases, or the empty string for non-handled cases.
   * Write unit tests for this function to verify that it handles all cases and correctly returns the empty string for non-handled cases.
   * Use this function in the client to create the clickable element with the phone number.

**Comment by rasmus-storjohann-PG** [comment]
[PhoneNumbers.txt](https://github.com/pg-irc/pathways-frontend/files/3407850/PhoneNumbers.txt)

@ian-lin-PG here's a list of the phone numbers with more than just numbers in them. Have a scan over it to see if there are any recurring patterns that are not yet covered in this implementation,

**Comment by ian-lin-PG** [comment]
@rasmus-storjohann-PG using the power of regex I cleaned through the phone numbers that you provided me with. There is no area code with mnemonics as previously discussed. There are definitely a few edge cases that seems to entry errors. 

1. Two of mnemonics are 5 letters, being SHOES and MERCY, after cleaning their number will appear as 1-855-55-63729 and 1-844-94-74637 both numbers appear exactly 3 times for a total of 6 appearances.

2. Extra digits. 1-844-11782-7811 appeared twice while 1-877-345-99777 appeared 7 times.

3. There is only 1 number that has missing hyphens,Phone/Fax: 604 485-6006, and it appears 2 times. After processing it looks like /:604485-6006, because I removed all alphabets, spaces and brackets in numbers with any alphabets. There is no '/' or ':' in any other phone numbers.

![image](https://user-images.githubusercontent.com/52009863/61551342-c18a3a80-aa09-11e9-8841-23a5ad5b9b07.png)

**Comment by rasmus-storjohann-PG** [comment]
QA:
* Do not import phone numbers "(none)"
* Correctly import "1-844-START11 (782-7811)"
* Correctly import "1-855-55-MERCY (63729)"
* Correctly import just the 1-800 number for "1-866-235-0350; 613-731-4092"
* Correctly import "1-877-345-9PSS (9777)"
* Correctly import "1-888-tai-chi-1"
* Correctly import "211NS (21167)"
* Correctly import "250-478-WILD (250-478-9453)" and "250-992-PALS (250-992-7257)"
* Correctly import "1-800-678-1129 Local 245"
* Correctly import "250 832-3885 Local 1310"
* Correctly import "250-286-9766 or 1-866-286-9766"
* Correctly import "250-949-6625 / 250-286-8064"

**Comment by ian-lin-PG** [comment]
In the event there are 2 numbers, is there a preference for 1-800 numbers? So far I parse the first phone number whichever that may be.

**Comment by rasmus-storjohann-PG** [comment]
When there are two numbers separated by `;` then I think the preference should be for the number that starts with `1-8`, i.e. 1-800 other other similar numbers. This is motivated by the fact that it'll be cheaper for the user potentially.

**Comment by rasmus-storjohann-PG** [comment]
QA:
- [ ] Phone number is blank: `  11851 |                             | 9489482     | phone1`
- [ ] Phone number is too long : `24883 | 18004342268562257245263265  | 58382702    | phone1`
- [ ] Phone number is too long, is it mnemonic with an extra (few) letters to make it readable? `21889 | 180054335463                | 46512843    | phone1` and `18226 | 1800622623218006226232      | 43781584    | phone1 ` and ` 18224 | 1800622623218006226232      | 43781577    | phone1 `

- [ ]

**Comment by ian-lin-PG** [comment]
<Phone TollFree="false" Confidential="false">
      <PhoneNumber>(none)</PhoneNumber>
      <Type>Phone1</Type>
    </Phone>
This is why some number show up as empty, there is 955 instance of them.

**Comment by ian-lin-PG** [comment]
<Phone TollFree="false" Confidential="false">
        <PhoneNumber>1-800-O-CANADA (1-800-622-6232</PhoneNumber>
        <Type>Phone1</Type>
      </Phone>
There is a consistent type with this particular 1-800 Canada number, my regex matches for both brackets, the phone number here is missing the closing one.

**Comment by ian-lin-PG** [comment]
<Phone TollFree="false" Confidential="false">
      <PhoneNumber>1-800-LIFELINE (1-800-543-3546)</PhoneNumber>
      <Type>Phone1</Type>
    </Phone>
The mnemonic itself contains an extra letter which translates to an extra digit and breaks the number.

**Comment by ian-lin-PG** [comment]
<Phone TollFree="false" Confidential="false">
        <PhoneNumber>25-562-9622</PhoneNumber>
        <Type>Phone1</Type>
      </Phone>
      <Phone TollFree="false" Confidential="false">
        <PhoneNumber>1-800-661-205</PhoneNumber>
        <Type>Phone2</Type>
      </Phone>
Both numbers are missing digits in ID 58371491.

**Comment by ian-lin-PG** [comment]
<Phone TollFree="false" Confidential="false">
          <PhoneNumber>236-333-10090</PhoneNumber>
          <Type>Surrey</Type>
        </Phone>
Phone number has extra digit.

**Comment by ian-lin-PG** [comment]
<Phone TollFree="false" Confidential="false">
        <PhoneNumber>250-562–2900</PhoneNumber>
        <Type>Phone1</Type>
      </Phone>

**Comment by ian-lin-PG** [comment]
<Phone TollFree="false" Confidential="false">
          <PhoneNumber>250-785-6021 ext. 232</PhoneNumber>
          <Type>Phone1</Type>
        </Phone>
Something with the extensions, ID: 54925067.

**Comment by ian-lin-PG** [comment]
<Phone TollFree="false" Confidential="false">
      <PhoneNumber>men@saavancouver.org</PhoneNumber>
      <Type>Email (men)</Type>
    </Phone>
      <Phone TollFree="false" Confidential="false">
        <PhoneNumber>women@saavancouver.org</PhoneNumber>
        <Type>Email (women)</Type>
      </Phone>
    <Phone TollFree="false" Confidential="false">
      <PhoneNumber>tom@setfreecanada.com</PhoneNumber>
      <Type>Email (Tom)</Type>
    </Phone>
    <Phone TollFree="false" Confidential="false">
      <PhoneNumber>paul@setfreecanada.com</PhoneNumber>
      <Type>Email (Paul)</Type>
    </Phone>
Wrong type of data, ID: 9488068, 9490743

**Comment by ian-lin-PG** [comment]
> ```
>   <Phone TollFree="false" Confidential="false">
>     <PhoneNumber>250-562–2900</PhoneNumber>
>     <Type>Phone1</Type>
>   </Phone>
> ```
> 
> Not sure what's wrong, ID: 58630848.

Import was correct on my machine.
![image](https://user-images.githubusercontent.com/52009863/63038518-2fdde380-be76-11e9-864c-eb4ba4d35c8b.png)

**Comment by ian-lin-PG** [comment]
@jparlina There are a lot of under the hood changes all of them have to deal with phone numbers in recommended services.

- [ ] Phone number types should not not have underline between each words, see: https://github.com/pg-irc/pathways-backend/issues/391#issuecomment-520606887
- [ ] 10 digit phone number should all follow xxx-xxx-xxxx
- [ ] 11 digit phone number should all follow 1-xxx-xxx-xxx
- [ ] There is no more mnemonics at all 1-800-O-CANADA should only be numbers now

**Comment by jparlina** [comment]
Tested Staging V1.2.0, server 1.3.8 on iOS 12.4:

- [ ] Phone number types should not not have underline between each words, see: pg-irc/pathways-backend#391 (comment)
- [ ] 10 digit phone number should all follow xxx-xxx-xxxx
- [ ] 11 digit phone number should all follow 1-xxx-xxx-xxx
- [ ] There is no more mnemonics at all 1-800-O-CANADA should only be numbers now

**Comment by jparlina** [comment]
Tested Staging V1.4.0, server 1.3.9 on iOS 12.4.1:

- [x] Phone number types should not not have underline between each words, see: pg-irc/pathways-backend#391 (comment)
- [x] 10 digit phone number should all follow xxx-xxx-xxxx
- [x]  11 digit phone number should all follow 1-xxx-xxx-xxx
- [x] There is no more mnemonics at all 1-800-O-CANADA should only be numbers now (Service Canada's phone number is now all numeric)
