### ISSUE TITLE
Service Listing: Topic about banks shows food banks

### ISSUE THREAD

**Issue by ArtiBPG** [pg-irc/pathways-frontend#540]
The topic about banks (the money type of banks) shows food banks.
![screenshot_20190307-210015_arrival advisor](https://user-images.githubusercontent.com/44411551/54008731-ca463800-411c-11e9-9d7e-3f056f8c25c3.jpg)

**Comment by rasmus-storjohann-PG** [comment]
Fixing this involves tweaking the NLP processing, which is out of scope for v1 unfortunately.

**Comment by Arnie0426** [comment]
@rasmus-storjohann-PG Not sure how much work it would be but something simple that would work for most NLP cases without having to do any NLP at all would be to only match the longest matching term, and ignore the subterms. I haven't looked at what exactly you're doing but I remember from our previous convos that you were simply doing a prefix match and figuring out how many times each term appeared... and scoring them using BM25 with an IDF score for each term.

If this is indeed how it works, the only change that you'd need to do is on the term extraction side assuming there are idf scores for both `food banks` and `banks`. Assuming you _are_ using something like a trie (prefix tree - https://en.wikipedia.org/wiki/Trie), the code could be something as simple as:

```
# Assuming this is your idf 
idfs = {"liverpool": 12, "liver": 8, "united kingdom": 5, "united": 3, "kingdom": 4}
for k, v in idfs.items():
    trie.insert(k, v)

# doc
doc = "Liverpool is a football club in the United Kingdom".lower()

# get all matches using a trie
matches = trie.getAllMatching(s)
print(matches)
`[(0, 5), (0, 9), (36, 42), (36, 50), (43, 50)]`

# this gets you all subwords
for start, end in matches:
    print(s[start:end])

# but if you merge the intervals of the matches, it will just work.
for start, end in merge_intervals(matches):
    print(s[start:end])
```

**Comment by Arnie0426** [comment]
![image](https://user-images.githubusercontent.com/10529313/54053927-ab3bba80-419d-11e9-8af1-068bc656690c.png)

results ^

not sure if this is helpful
