### ISSUE TITLE
Get location never returns on some Android devices

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#548]
App blocks for ever on the call to `Location.getCurrentPositionAsync()` in `src/sagas/services.ts`

This seems to me a know problem, may just need to update expo, see [this issue](https://github.com/expo/expo/issues/946). Except that we did that pretty recently, so I'm not sure if that is the solution.

**Comment by tomy-pg** [comment]
Some notes on this issue: https://docs.google.com/document/d/1emsj507egcqQrHfAA-i4lf_f0Vk_tf7zZ1jwkaFZBGA/edit

**Comment by bensinjin** [comment]
Further AC:
- We should have two location errors: one for no location permissions and one for timeouts
