### ISSUE TITLE
Presentation of links is too generic

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#550]
Showing links as just "link" makes it unclear where the url is pointing to, which makes for poor UI in some situations, see screenshot.

Alternative solutions:
* `github.com`
* `github.com/pg-irc/pa...` (all urls truncated to the same maximum length with ellipsis, this is my preferred solution)
* `https://github.com/pg-irc/pathways-frontend/issues/new`

![image](https://user-images.githubusercontent.com/32307781/54218358-a97a3b80-44aa-11e9-9d25-12c5cd4925c4.png)

**Comment by ArtiBPG** [comment]
duplicate: #526
