### ISSUE TITLE
Service list: Click targets are too small and close together

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#551]
ACs:
* The user can easily click on URL, email address or phone number without worrying that they click the wrong click target near by.
* Make the different click targets more separate by following the pattern from the hamburger menu: About, Disclaimer and Privacy policy links: More vertical space, right arrow on the right side.

This shows the problem:
![image](https://user-images.githubusercontent.com/32307781/54225604-5065d400-44b9-11e9-9a52-75906e92cd13.png)

**Comment by rasmus-storjohann-PG** [comment]
As part of this story, we could also remove the email and web link entries if there is no corresponding data, see 

![image](https://user-images.githubusercontent.com/32307781/54304760-1103ba00-4583-11e9-8e46-882543801ab7.png)

**Comment by cherrielam** [comment]
I agree, Click targets could be made bigger. Thinking better list spacing?
