### ISSUE TITLE
Import translated learn section titles into the app from the translation spreadsheet 

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#554]
All strings for /pathways-frontend/src/fixtures/hard_coded/explore.ts need to be added from the translation spreadsheet. The descriptions are already in, just need the titles

The strings are in the per-language spreadsheets, in the learn description tab, so that tab contains both learn descriptions and learn titles.

ACs:

* All learn section title strings appear in the app in all languages

**Comment by ArtiBPG** [comment]
To do- Things to do right away
