### ISSUE TITLE
Talk taxonomies with BC211

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#555]
Get in touch with BC211 and explore the use of their taxomomy in our recommendation.

- handling feedback received- about accuracy, missing/incorrect data?
- new requests to add data to AA and BC211
- should we create our own forms for intake and feedback? what fields should we include? how do we track progress?
- BC211 used to have a form for updating service data, now they just have an email address. Why?

**Comment by ArtiBPG** [comment]
moved to doc with list of questions for Oct 2019 meeting with BC211
