### ISSUE TITLE
Combine the Chinese Simplified & Traditional translations into 1 translation written with the 2 scripts

### ISSUE THREAD

**Issue by cherrielam** [pg-irc/pathways-frontend#562]
Right now the translations/characters used for Simplified and Traditional Chinese are different. This is a bit strange because the Chinese itself should be the same, Simplified and Traditional are just two different scripts/ways of writing. *Note: this can be a later-on project. Ideally if this is tackled before importing/through Weblate though I imagine that would make the most sense.*

My recommendation is to have one or two Chinese translators compare both the Simplified and Traditional translations against the English original and select the dominant translation (could be a combination of both, doesn't have to be one over other). Then the dominant translation should be used in BOTH the Simplified and Traditional scripts.

(If you are confused, the best way I can explain this is: Chinese Simplified and Traditional are kind of like fonts. For instance a sans-serif "A" and a serif "A" look different visually, but they both inherently mean and say "A". Right now it's a bit strange because essentially two different people did the translations, so imagine two English versions of the app, one in serif and one in sans serif, and one says "Settle in Canada with confidence." whereas the other one says "Have confidence in your settlement in Canada." Not wrong or bad, but just rather weird. What you would want is the translation to be the same, even if the font is different, so there's no discrepancy whether you're a Simplified or Traditional reader. Does that make sense?)

**Comment by cherrielam** [comment]
tagging @rasmus-storjohann-PG for FYI if thinking about importing... it's fine if this is tackled later after the first import for the test flight (probably will need to be)

**Comment by ArtiBPG** [comment]
-I will still need to know which version you want to keep. The current Simplified or Traditional?We will actually have to hire a third translator to do this job. 
-We will ask them to use the newcomers guide as reference. Also can you confirm which newcomers guide we should use for reference?
-Can you confirm which version of the app Simplified or Traditional seems unnatural when reviewed on its own, that is not compared to the other version.
- Is it common for people to switch between the two version? Will a user actually switch between the two to compare translations?

@cherrielam

**Comment by cherrielam** [comment]
@ArtiBPG 
- For which version, as per our convo this morning, my personal (non professional) impression is the Traditional translations feel stronger BUT it would honestly be best if a Chinese QA person can read both translations, compare with the English, and choose the superior one. **Note: This does NOT pertain to the Newcomers Guide content. The Newcomers Guide content is already identical between Traditional and Simplified. Just the UI strings and app description that we manually translated need to be QA'ed for combining into one consistent Chinese version.** Admittedly this is a bit of a project to read everything but nothing should need to be translated anew, just needs to be QA'ed. (Eg. in my example, someone has to pick whether "Settle in Canada with confidence" or "Have confidence in your settlement in Canada" is the preferred translation. They should be making their decision by comparing with the English original.) It is honestly fine if they pick one paragraph from the Simplified version and one paragraph from the Traditional version. Simplified and Traditional are literally like fonts, so someone just needs to put all the prevailing paragraphs together (whether it is all simplified, all traditional or combo) and set it to be all Simplified characters & save, and then set all the characters to be in all Traditional characters & save, and make sure both versions are ready for import. 
- It doesn't matter which Newcomer's Guide. They are identical. As I mentioned, they're like two documents written in two different fonts but the words are the same.
- It's not super common, but I wouldn't say it's uncommon. Being able to read Chinese, I did flip between Chinese Trad and Simplified out of curiosity on the website and was thrown off because the wording was very obviously different. In the app this won't be AS obvious because the Newcomers Guide stuff will be identical, so only UI strings may be different. It's just weird, but not critical or necessarily bad. **Thus why this is a V2 project.**

In the future though actually for Chinese translations, you only really need to translate into Chinese once and get people to QA it. You'd typically pick a Mainland Chinese/Mandarin speaker who can translate into 'formal' Chinese (rather than a Cantonese speaker who might translate into more slang style Chinese... though this won't typically happen even if they're Cantonese, because they'll normally write in 'formal' Chinese). If they translate into Simplified, you can just put the Simplified characters into something that can convert all the characters to Traditional characters. This can be done in Microsoft Word or something of the like by literally highlighting all the characters and changing the font to a Traditional font. And vice versa. That way you only have one Chinese translation to deal with, and both scripts.
