### ISSUE TITLE
Missing Translation: “Things to do right away”

### ISSUE THREAD

**Issue by jparlina** [pg-irc/pathways-frontend#585]
![BB7CBC13-6315-4BF3-8DE8-0215A319BEC5](https://user-images.githubusercontent.com/48343061/55282468-7dabe200-5301-11e9-9fbb-2a034629de1e.jpeg)
![F1C7DD71-2238-4676-AF57-7AC3F105B62B](https://user-images.githubusercontent.com/48343061/55282469-7dabe200-5301-11e9-9e4f-0a8a08c1f5d9.jpeg)
![250A2E86-848D-4578-8E1C-4CA40CC57C77](https://user-images.githubusercontent.com/48343061/55282470-7dabe200-5301-11e9-8c0d-c120f99d7573.jpeg)
![Uploading 91255888-73DC-4E1A-824A-70F77634F7DF.jpeg…]()

Topic Title and Description of “Things to do right away” are not translated in French and Arabic versions of the app

**Comment by rasmus-storjohann-PG** [comment]
Also strings related to the getLocation() call on android, there are 2-3 strings related today.
