### ISSUE TITLE
Service Listing: Surrey Libraries Not Found in Surrey

### ISSUE THREAD

**Issue by jparlina** [pg-irc/pathways-frontend#591]
Having AA booth at the Resource Fair for Refugee Claimants at the Guildford Recreation Centre (same building where the Surrey Libraries - Guildford Library is also located), but Surrey Libraries did not show up on search results although it’s listed on bc211

When searching “Public Libraries” - the results are listed in the following order and most of them are not in Surrey:
1. Fraser Valley Regional Library - Terry Fox Library (Port Coquitlam)
2. Fraser Valley Regional Library - Pitt Meadows Public Library (Pitt Meadows)
3. Fraser Valley Regional Library - George Mackie Library (Delta) 
4. New Westminster Public Library (New westminster)
5. Courthouse Libraries BC - Courthouse Library - Surrey
...see screenshots for the rest of results 

![5D9632B9-6A4A-47F4-A4ED-82021E2D015F](https://user-images.githubusercontent.com/48343061/55676191-29b27780-5884-11e9-9f0a-d86a276c9007.png)

![629E61D8-AC14-456C-8761-3A4780889FFB](https://user-images.githubusercontent.com/48343061/55675892-afcbbf80-587e-11e9-8d7f-81f94984436d.png)
![67312EA3-002C-461F-B037-76C6B9B67DC6](https://user-images.githubusercontent.com/48343061/55675893-afcbbf80-587e-11e9-82c9-9239cf55d144.png)
![188D516D-D34B-48B1-A22F-B39FDD237DF6](https://user-images.githubusercontent.com/48343061/55675894-afcbbf80-587e-11e9-89aa-082d83b3a2b7.png)
![219395D8-DFB3-4EAE-9ED5-4D9094979C85](https://user-images.githubusercontent.com/48343061/55675895-afcbbf80-587e-11e9-8a2a-f15b008f0054.png)
![DF278508-1FFC-480B-AC84-C050195D6261](https://user-images.githubusercontent.com/48343061/55675896-afcbbf80-587e-11e9-8cac-51332993698a.png)
![B2B4346E-C8FD-41DF-8068-6B63EE486490](https://user-images.githubusercontent.com/48343061/55675897-afcbbf80-587e-11e9-976c-f7996359c933.png)
![60E2205C-9DC4-4E6F-83FA-9DA53CCCA3C4](https://user-images.githubusercontent.com/48343061/55675898-afcbbf80-587e-11e9-8353-2f1233d5db1c.png)
![B73AC955-29EA-499B-AF4B-924B2E3AB9A1](https://user-images.githubusercontent.com/48343061/55675899-b0645600-587e-11e9-991c-c70a6dcf208e.png)
![D9DAEF79-56D9-4B75-A5E5-9E143BF8A203](https://user-images.githubusercontent.com/48343061/55675900-b0645600-587e-11e9-9946-28e01b8e8fa2.png)
![22E18121-6CD3-4309-9369-FB9B6495DCD2](https://user-images.githubusercontent.com/48343061/55675901-b0645600-587e-11e9-97fd-d5ca39658587.png)
![7563A42E-9591-418A-AC17-6B4CF2247252](https://user-images.githubusercontent.com/48343061/55675902-b0645600-587e-11e9-9a08-392f627c10b6.png)
![90B5940C-384F-47A1-B8BD-2375EBBFAC34](https://user-images.githubusercontent.com/48343061/55675903-b0645600-587e-11e9-8f0c-47be3c1f8fff.png)
![E1118015-303E-4364-A8DB-9A9B1A0CA988](https://user-images.githubusercontent.com/48343061/55675904-b0645600-587e-11e9-9dc7-50d10cde7537.png)

**Comment by jparlina** [comment]
When searching “Community and Recreation centres” - see results on attached screenshots, and the Guildford Recreation Centre where I was using the app was not listed in search results.
![58B93D1E-646A-4972-898D-EECDD4D45970](https://user-images.githubusercontent.com/48343061/55675915-d7bb2300-587e-11e9-8352-ed5975f3e607.png)
![ACEF09BA-363A-42A5-8C19-190E739FAA29](https://user-images.githubusercontent.com/48343061/55675916-d7bb2300-587e-11e9-9574-a21552efb767.png)
![Uploading 7FECF971-64B9-4D13-956F-92877B12D2E3.png…]()
![Uploading E7606A74-AC07-4E69-BCCF-E1F1EAFE8535.png…]()
![Uploading 8AE88698-0878-4A7D-ACAC-40CE9295F556.png…]()
![Uploading E035AEB9-2415-4602-B041-54223B24BF62.png…]()
![Uploading C7E3A4C2-EB3A-4F99-9C3E-B2E0B8CF79EB.png…]()
![Uploading 3D9604AA-FD48-4FE5-96B3-60E987A51E70.png…]()
![Uploading C46AE0F6-5AE0-4A05-86E2-B8F52F12E984.png…]()
![Uploading ECD96F62-16A7-4CC7-B761-7C6AFF22120D.png…]()
![Uploading 5AE8D70B-95F8-4885-A56F-5FBB94199F8A.png…]()
![Uploading D7EF041D-858F-4875-94CD-8EF81D5B0D2C.png…]()

**Comment by ArtiBPG** [comment]
Next steps: 
- find out if surrey libraries exits in Sept 2018 BC211 dataset. If no, check March 2019 dataset
- if they do not exist in both, direct them to bc211
- If they exist in one or both Sept and March datasets, this is a location/search bug.
- If they do not exist in March/Sept dataset, we are missing some entries from bc211

**Comment by jparlina** [comment]
We received an email about this issue from PG website's contact form (screen shot is attached).
I confirmed that "Surrey Libraries" (service_id 36761355) is in both Sept 2019 and Mar 2019 datasets, so it looks like it's a location/search bug. I just tested it on the "AA Staging" app (red/blue) from the HiVE, "Surrey Libraries" was included in search results under "Public Libraries". Hopefully it'll be resolved once we release the March 2019 dataset.

![Screen Shot 2019-04-17 at 3 30 57 PM](https://user-images.githubusercontent.com/48343061/56325159-fa262980-6125-11e9-9bc8-44e17e95e8d0.png)

**Comment by jparlina** [comment]
Received a follow-up email from Surrey Libraries on Jun 13, 2019.
Issue: [Surrey Libraries](http://redbookonline.bc211.ca/organization/36761355/surrey_libraries?search1=Surrey%20Libraries&search2_basic=V2x%206t4&from=NDkuMjIyNDk1OCwtMTIyLjU3OTUwODY=) does not have any service records listed in bc211 database, unlike [Fraser Valley Regional Library](http://redbookonline.bc211.ca/organization/9487754/fraser_valley_regional_library?search1=Fraser%20Valley%20regional%20library&search2_basic=&) for example.

**Comment by ArtiBPG** [comment]
Surrey Library appears on 1.3.12 with Taxonomy based Service listings
