### ISSUE TITLE
Inconsistent Data with BC211: La Boussole's address

### ISSUE THREAD

**Issue by jparlina** [pg-irc/pathways-frontend#592]
We received an email notification from info@arrivaladvisor.ca that La Boussole's address on the Arrival Advisor is outdated. The current address on bc211 is correct. See screenshots.

![IMG_9767](https://user-images.githubusercontent.com/48343061/55759873-6363b980-5a0f-11e9-8e07-875eb259790b.jpg)
![IMG_9767](https://user-images.githubusercontent.com/48343061/55759934-8c844a00-5a0f-11e9-9e70-0cd9af33c43f.jpg)

**Comment by ArtiBPG** [comment]
Next Steps:
Check if their latest data March 2019 from BC211 has the latest address.

**Comment by ArtiBPG** [comment]
March database has Main street address. Will be updated in the app once we update the app with the March data.

**Comment by rasmus-storjohann-PG** [comment]
@jparlina and @ArtiBPG Note that I was able to look this up from swagger directly, as follows:
* Go to https://fierce-ravine-89308.herokuapp.com/swagger/ or https://pathways-production.herokuapp.com/swagger/
* Scroll down to `GET ​/services_at_location​/`
* Click Try it out
* Enter "Boussole" in the input field named "search"
* Click "Execute"
* You will see the address as part of the response.

**Comment by ArtiBPG** [comment]
test with next staging app which will have June data

**Comment by ArtiBPG** [comment]
Staging 1.0.24 has the right address.
