### ISSUE TITLE
Back button with side menu open should close side menu

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#594]
Repro on Android:
- Start the app
- Navigate through a couple of pages
- Open the hamburger menu
- Hit back button
- Observe that the hamburger menu remains open and the navigation backwards through breadcrumbs happens behind it
- Expected is that back button closes the hamburger menu

**Comment by bensinjin** [comment]
@rasmus-storjohann-PG do you mean the Android back button?

**Comment by bensinjin** [comment]
I see what you mean, when the Android back button is pressed, digging...

**Comment by rasmus-storjohann-PG** [comment]
This issue came back, happens on staging now, 1.38.0

**Comment by rasmus-storjohann-PG** [comment]
Fixed
