### ISSUE TITLE
User should not be asked to select language at every start

### ISSUE THREAD

**Issue by jparlina** [pg-irc/pathways-frontend#606]
One of the feedback from the MOSAIC English Conversation group was that it'd be great if the user doesn't get asked to select the language every time the user launch the AA app (see screen shots). Entering this as an issue based on our discussion at Apr 10 Design Sprint 

![Screen Shot 2019-04-15 at 12 03 30 PM](https://user-images.githubusercontent.com/48343061/56158326-8e518e80-5f76-11e9-9fe0-aa79c59a8ec1.png)

![IMG_9798](https://user-images.githubusercontent.com/48343061/56158466-f1432580-5f76-11e9-8f6c-540c2da0ebe6.jpg)

ACs:
* When opening the app for the first time, see the language selector and onboarding flow
* When opening the app for a subsequent time, opens straight on the Recommended Topics page
* Start the app for the first time, quit the app during the onboarding flow, start the app again, see the language selector and onboarding flow.
* Open the app for the first time, accept English as current locale, open the app a subsequent time, does not show the language selector.

**Comment by jparlina** [comment]
Tested on staging app v 1.0.18:
1. When opening the app for the first time, see the language selector and onboarding flow --> PASSED

2. When opening the app for a subsequent time, opens straight on the Recommended Topics page --> PASSED

3. Start the app for the first time, quit the app during the onboarding flow, start the app again, see the language selector and onboarding flow. --> FAILED (see issue 

4. Open the app for the first time, accept English as current locale, open the app a subsequent time, does not show the language selector. --> PASSED

**Comment by rasmus-storjohann-PG** [comment]
If you want to demonstrate the app including the welcome screen, go into settings on the device, look  up the arrival advisor app, and delete all memory related to the app. This is a more complete delete all data than what is available from within the app help screen.
