### ISSUE TITLE
Service Listing: Incorrect Search Results: “Where to look for a job”

### ISSUE THREAD

**Issue by jparlina** [pg-irc/pathways-frontend#610]
I was doing a presentation at ISS Welcome Centre (2610 Victoria Dr, Vancouver) for Job Quest program staff. When one staff searched “Where to look for a job”, the only result that came out was “Fraser Works Co-op” in New Westminster. 
I tested also in Burnaby and at the HiVE - exact same result (see screen shot)

![7AB566C2-BC14-4A96-A6A2-2867F313F1F0](https://user-images.githubusercontent.com/48343061/56305494-4a38c800-60f5-11e9-9e65-9a86c4c35fa4.jpeg)

**Comment by tomy-pg** [comment]
In our manually review process this topic, the NLP for this topic seemed to be OK. We could possibly add more to this topic manually.

**Comment by ArtiBPG** [comment]
On Staging 1.3.12 with Taxonomy based Service listings, all services are now employment related.
