### ISSUE TITLE
QA and deploy of Arrival Advisor currently in staging

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#617]
ACs:
* When in surrey and looking up Public Libraries, manual recommendations include <insert surrey libraries>
* When in Burnaby and looking up <language schools>, manual recommendations include <insert burnaby libraries>

TODO
* Find new services in BC211.

Then:
* Update recommendation files
* Run the server side prepare deploy script with the correct client and server versions, and recommendation files
* Upload data.json to AWS

* Log into heroku (staging) `$ heroku ps:exec -a fierce-ravine-89308`
* Set environment variables per the server side README: Take the variables from `export DJANGO_SETTINGS_MODULE=co...`, copy into pico, edito the value for DATABASE_URL to the value from the *correct* heroku instance -> Settings -> Reveal config vars -> database url, copy paste into the heroku shell.
heroku$ wget <s3-url-to-data.json>
heroku$ ./manage.py flush
heroku$ ./manage.py loaddata data.json

Test in staging, if all is good
* Make a new client build, publish it to both stores with Ben's help
* When review is passed and we're ready to publish the client:
* On heroku web site, promote staging to production
*  Log into production server and update DB as above, * Log into heroku (production) `$ heroku ps:exec -a pathways-production`, and follow the same steps as above.

**Comment by ArtiBPG** [comment]
why only Surrey and Burnaby?
