### ISSUE TITLE
Set up Google Analytics events tracking 

### ISSUE THREAD

**Issue by cherrielam** [pg-irc/pathways-frontend#618]
Set up the following events to track performance within the app using Google Analytics. 

We would like to track...

#### 1) Which services are accessed the most frequently

**Services Listing:**
- *#* clicks on website URL of a service (we want to see which service's website URL is clicked the most)
- *#* clicks on phone of a service (we want to see which service's phone # is clicked the most)
- *#* clicks on email of a service (we want to see which service's email is clicked the most)
- *#* clicks on service "Open in Maps" button (we want to see which service is opened in Maps the most)
- *#* We should be able to look up a service, any service and see if the phone, email and/or map links were ever clicked

*Q: is there a way to see all of the above in aggregate? (we want to see which services are clicked (any of URL, email, phone, Open in Maps) the most)* 

- *#* visits to the Services Listing page, specific to a topic 
- *#* clicks on a Services Listing page, specific to a topic
(we want to know how the number of page visits of Services Listing page compares with the number of clicks once the user hits that page - eg. when they get to the Services Listing for "Settlement workers" do they access a service or do they leave? If they leave it would indicate that they didn't find the Services Listing useful)
- *#* We should be able to look up a topic, any topic and see if the service listing page was ever visited

**Topic Detail:**

- *#* clicks on the "Find Services" button, specific to a topic (we want to know which topics have the most clicks on "Find Services", eg. which topics are people most interested in accessing services for?)

#### 2) Which topics people find most useful

**Bookmarks:**

- *#* saved bookmarks, specific to a topic (we want to know which topics are being bookmarked the most)
Note: we should separate from the un-saving of bookmarks (eg. if someone clicks the bookmark icon to save and then clicks again to un-save, the saved bookmark event should not be tracked 2 times. Instead, we should track that the "save" event happened 1 time, and the "unsave" event happened 1 time. If possible it might also be nice in the future to track the time between "save" and "unsave" events to remove the ones that were accidental saves (immediate unsaves)
- *#* We want to know how many topics on average have been bookmarked per user. Since we are not tracking IPs, this could just be an average based on total number of active users.

**Topic Detail:**

- time spent on a topic (we want to know which topics people spend the most time on)

#### 3) Overall usefulness of the app 
(many of these are probably already tracked?)

- *#* saved bookmarks per user  
- time spent on the app
- reopens of the app (returning users)
- *#* of topics read per user (might use # of screens per user as a proxy)
- *#* downloads
- uninstall rate
- retention rate
- *#* users (over time)

--------

For reference: this came from the PeaceGeeks team metrics brainstorming: https://docs.google.com/spreadsheets/d/1KrK2OsBi_hllZ7sbEN8l2sPvP1sEosTqm_a1yz_BegA/edit?usp=sharing (see Sheet 1 - "HEART Metrics...")

**Comment by cherrielam** [comment]
Assigning to @ArtiBPG and @rasmus-storjohann-PG to review before assigning to Ben :)

**Comment by rasmus-storjohann-PG** [comment]
QA:
- [x] Bookmarks added is recorded with the topic id, bookmarks removed is not recorded
- [ ] Web links: Not successfully tested yet
