### ISSUE TITLE
AA Website FAQ - still mentions "starred topics" (star has been replaced by check mark)

### ISSUE THREAD

**Issue by jparlina** [pg-irc/pathways-frontend#623]
The last item on FAQs page on AA website mentions "starred" topics (we replaced "star" with "check mark"). Make sure the translated websites are also fixed accordingly. 

![Screen Shot 2019-05-13 at 2 06 25 PM](https://user-images.githubusercontent.com/48343061/57654670-a3c3d380-7589-11e9-8fa1-368dd37b6dc8.png)

**Comment by cherrielam** [comment]
Migrated this issue to the Arrival Advisor website repo: https://github.com/PeaceGeeksSociety/Arrival-Advisor-Website/issues/151
