### ISSUE TITLE
Move questionnaire strings to po files

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#625]
* Update code to retrieve questionnaire strings from po files rather than from the fixture. Will need to use [I18n._()](https://lingui.js.org/ref/core.html#I18n._) probably.
* Move the strings in all languages into po files
* Figure out what keys to use in po files, potentially we'd want structured keys like `id:name` and `id:description`, rather than using the English string as key.
* Make the questionnaire a separate component w.r.t. translation, anticipating how it will be managed in weblate.

The explore section headings need to be moved from json to po files as well, that can be done under this story or broken out into a separate one.

ACs:
* Strings in questionnaire shows up correctly in several languages.

**Comment by tomy-pg** [comment]
TODO:
Update code to retrieve questionnaire strings from po files rather than from the fixture.

**Comment by tomy-pg** [comment]
Pulling ui-strings from https://github.com/tomy-pg/ui-strings
Eventually, the ui-strings will be moved to pg-irc. The reason it is not currently there already is because of a known issue with Weblate v.3.5.1 which is discussed here: https://github.com/WeblateOrg/weblate/issues/2590

**Comment by jparlina** [comment]
Issue in previous staging V1.2.21 in French (iOS):

![IMG_1619.JPG](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/3af340ae-47a2-408a-93c8-a84591e67ef2)

Tested Staging V1.2.23 in French (iOS): fixed 
Arabic - looks ok
Punjabi - looks ok
Korean - looks ok
Chinese Traditional - looks ok
Chinese Simplified - looks ok
Tagalog - looks ok
