### ISSUE TITLE
Update icons for Android app

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#633]
ACs:
* App icons for both staging and production for the Android app adheres to [Google's new guidelines](https://developer.android.com/google-play/resources/icon-design-specifications)

The good news is that Google's new guidelines are similar to Apple's current guidelines, so that should make it easier.

**Comment by tomy-pg** [comment]
The icons adhere to the guidelines. The Staging icon still looks off. I am curious to see if the icon is being affected the word text "Staging" falling outside of the keyline grid. 

![Screen Shot 2019-09-20 at 10 18 48 AM](https://user-images.githubusercontent.com/47794846/65345845-1116ef00-db90-11e9-9350-37f9bb80c445.png)
