### ISSUE TITLE
Fix app bar colour on android

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#634]
![image](https://user-images.githubusercontent.com/32307781/57946531-59946800-7891-11e9-8761-37b422050d87.png)
Screenshot shows that our app's header bar has a default blue colour. Gmail as their brand's red colour, so it can be done. We should make it so that we use our brand colour as well.

The screenshot shows the staging app, but the issue affects the production app as well.

**Comment by ian-lin-PG** [comment]
My phone and Tommy's phone doesn't have the same multi-tasking screen, we should check the android version and decide whether we should support the older version.

**Comment by ArtiBPG** [comment]
@rasmus-storjohann-PG Can you update the issue with the Android version?

**Comment by ArtiBPG** [comment]
So far, based on Android dev console data, Android 7.0 is the oldest version that has our app installed.

**Comment by ian-lin-PG** [comment]
There is a [primaryColor](https://docs.expo.io/versions/v28.0.0/workflow/configuration/#primarycolor) option in app.json that can change the background color. I tested it works, but I might have set the wrong primaryColor.

**Comment by ian-lin-PG** [comment]
These are the two colors I cam up with by using color pick on the app. @cherrielam let me know if either color works.
![Screenshot_20190709-155447](https://user-images.githubusercontent.com/52009863/60928519-9b72d680-a262-11e9-9a1b-17c90dead63d.png)
![Screenshot_20190709-135153](https://user-images.githubusercontent.com/52009863/60928520-9ca40380-a262-11e9-92a4-1708b18aecee.png)

**Comment by tomy-pg** [comment]
Client: 1.0.25, Server 1.3.4: Tested and approved
