### ISSUE TITLE
Icons on Arabic version should be right-aligned

### ISSUE THREAD

**Issue by jparlina** [pg-irc/pathways-frontend#635]
Issues in both versions 1.0.13 and 1.0.17 for both Android and iOS:

**1. Icons on Home Page on Arabic version should be right-aligned** like the rest of the texts:
The icons on Home page for each category (i.e. Things to do right away, Settling in, Employment, Health Care, Money & Banking) should be on the right side (see screen shot): 
![IMG_0643](https://user-images.githubusercontent.com/48343061/58196307-db640700-7c7e-11e9-8062-4fc09c47766b.JPG)

**2. Icons under each "Learn" category on Arabic version should be right-aligned**
When you open each Category from the "Learn" page, the category icon at the top of the page should be right-aligned like the rest of the texts (see screen shot):
![IMG_0650](https://user-images.githubusercontent.com/48343061/58197197-9b9e1f00-7c80-11e9-8577-13d39e6aa836.JPG)

**Comment by ArtiBPG** [comment]
Still not fixed
![Screenshot_20190628-165715_Arrival Advisor](https://user-images.githubusercontent.com/44411551/60376775-f89a9c80-99c5-11e9-994d-727ca3557075.jpg)

**Comment by jparlina** [comment]
Fixe in Staging 1.0.23 - iOS
