### ISSUE TITLE
Text Direction & Alignment Issues when switching from Non-Arabic to Arabic and vice versa

### ISSUE THREAD

**Issue by jparlina** [pg-irc/pathways-frontend#636]
Issues on both versions 1.0.13 and 1.0.17:
- seems to be an issue on iOS but not on Android 
- issue can't be replicated every time (not consistent) when switching between non-Arabic to Arabic, or vice versa 
- happens after a few times switching between Arabic and non-Arabic (use cases: some settlement workers may have to switch between languages a few times to help different clients; some Arabic speakers may switch back and forth - e.g. going to the service location and need to show what the app says to the service provider in English).

You can tell whether the alignment is correct based on the position of the dropdown arrow for language selection on the Start page. Examples:
1. When switching from Arabic to English, if you see the dropdown arrow is in the wrong position (e.g. on the screen shot below the dropdown arrow is on the left side of the word "English")

![IMG_0658](https://user-images.githubusercontent.com/48343061/58200109-d73be780-7c86-11e9-8d21-10d4e3df06f3.JPG)

1a. when you just continue by clicking "Start" button, you'll see the alignment on all pages after that will be incorrect (see screenshots below):

![IMG_0660](https://user-images.githubusercontent.com/48343061/58200147-eb7fe480-7c86-11e9-8358-89a9c1b43d8f.JPG)

![IMG_0662](https://user-images.githubusercontent.com/48343061/58200355-795bcf80-7c87-11e9-8c30-5ff3c14ff47a.JPG)

![IMG_0661](https://user-images.githubusercontent.com/48343061/58200342-73fe8500-7c87-11e9-9b5e-5f067a926405.JPG)

1b. If you see on the Start page the position of the dropdown arrow is incorrect, but instead of just clicking "Start", you click on the dropdown arrow and select the same language again (in this example English, then you'll see the arrow then moves to the correct position and the pages inside will be fine when you click "Start". 

2. Same issues happen sometimes when you switch from non-Arabic to Arabic. If you see the dropdown arrow for the language selection is incorrect (e.g. on the screen shot below the dropdown arrow is on the right side of "Arabic"):

![IMG_0656](https://user-images.githubusercontent.com/48343061/58201256-795ccf00-7c89-11e9-969e-1f9128f062ae.JPG)

2a. Then you just continue by clicking "Start" button, you'll see the alignment on all pages after that will be incorrect (see screenshots below):

![IMG_0663](https://user-images.githubusercontent.com/48343061/58201405-d9537580-7c89-11e9-938b-18dfd6a7fe6f.JPG)

![IMG_0664](https://user-images.githubusercontent.com/48343061/58201406-d9537580-7c89-11e9-83bf-55c338364816.JPG)

![IMG_0665](https://user-images.githubusercontent.com/48343061/58201407-d9537580-7c89-11e9-9dc9-1e0a71f5a01a.JPG)

![IMG_0666](https://user-images.githubusercontent.com/48343061/58201408-d9ec0c00-7c89-11e9-8fc7-0bdf45a9db7f.JPG)

2b. If you see on the Start page the position of the dropdown arrow is incorrect, but instead of just clicking "Start", you click on the dropdown arrow and select the same language again (in this example Arabic, then you'll see the arrow then moves to the correct position and the pages inside will be fine when you click "Start".

**Comment by rasmus-storjohann-PG** [comment]
There are still issues on iOs. Reopening

**Comment by tomy-pg** [comment]
Client: 1.1.0 / Server: 1.3.5
This issue still persists on iOS while testing on Jean's iPhone.

**Comment by jparlina** [comment]
Tested on iOS 12.4 Staging V 1.1.0, server V1.3.5: 
no consistent pattern to replicate the issue

First test:
- Started with English, switched to Arabic - PASSED
- Went back to English - PASSED
- Went back to Arabic - FAILED (alignment and text direction stayed like in English)

Second test:
- Started with English, switched to Arabic - PASSED
- Went back to English - FAILED  (alignment and text direction stayed like in Arabic)
- Went back to Arabic - PASSED
- Went back to English - PASSED

Third test:
- Started with English, switched to Arabic - PASSED
- Went back to English - FAILED (alignment and text direction stayed like in Arabic)

**Comment by tomy-pg** [comment]
The next plan of action for this issue is to side-load a development app to a iOS device as suggested by @bensinjin . This way we can log values to help us debug this issue.

**Comment by ian-lin-PG** [comment]
QA on Kate's iphone (iPhone6 iOS 12.4):
Expo builds: 33 times changing language for 9 minutes, cannot reproduce issue.

**Comment by jparlina** [comment]
Tested on Staging V1.4.0, Server 1.3.9 on iOS 12.4.1:

- Started in EN, changed to AR from Home EN - PASSED
- opened a topic in AR, change to EN from a topic - PASSED
- changed back to EN from AR topic - PASSED

- on service listing page, changed from EN to AR - PASSED
- on service listing page, changed from AR to EN - PASSED
