### ISSUE TITLE
Provide 32 and 64 bit versions of the Android app

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#642]
This issue is blocked until we update Expo to the upcoming version 34.

From Google:

By August 1, 2019, all apps that use native code must provide a 64-bit version in addition to the 32-bit version in order to publish an update. This past January, we reiterated that this is required in order to make way for innovation and in anticipation of future Android devices that only support 64-bit code.
As the deadline approaches, we wanted to remind you that at least one of your apps* uses native code but does not currently offer a 64-bit variant:

From [Expo](https://blog.expo.io/expo-sdk-v33-0-0-is-now-available-52d1c99dfe4c#53d4):

We recommend that all Expo developers with Android apps upgrade to SDK 33 now to front-load most of the work required for creating 64-bit APKs, coming in SDK 34, and necessary to submit to Google Play in August.

ACs:
* Change the build process for Android to produce both 32 and 64 bit builds.
* Publish both builds on the staging app.

**Comment by ArtiBPG** [comment]
Need this my July 19th to be in time for Play Store's Aug 1st deadline.

**Comment by tomy-pg** [comment]
During the staging release for client: 1.0.25 and server 1.3.4 - the warning for 32 - 64 bit requirement did not come up like in previous builds.
