### ISSUE TITLE
Service List on Arabic App should align left

### ISSUE THREAD

**Issue by jparlina** [pg-irc/pathways-frontend#644]
Services on the Arabic version of the app should align left since they are not translated into Arabic. Same issue for both versions 1.0.13 and 1.0.17.

See 1st screenshot below for iOS: all texts and “Open Map” button are incorrectly aligned right.

See screenshot below for Android: all texts and “Open Map” button are incorrectly aligned right, EXCEPT for the last 3 lines (phones and website).

![F35C5016-1D82-4FF5-9AA8-0A0455C30771](https://user-images.githubusercontent.com/48343061/58516067-9c8cf000-815b-11e9-86aa-92ed37bb893c.jpeg)

![5A27C862-432D-4A03-BF1A-624DC33A25C1](https://user-images.githubusercontent.com/48343061/58516033-85e69900-815b-11e9-8f35-de429c4c4655.jpeg)

**Comment by rasmus-storjohann-PG** [comment]
Still outstanding issues on iOs.

**Comment by jparlina** [comment]
Tested V 1.0.22 - still an issue in both iOS and Android

**Comment by jparlina** [comment]
Tested Staging V 1.0.25 on iOS 12.3.1 at the HiVE:
Confirmed on Arabic version's service listing:
- all content and icons are aligned left
- all labels (Address, Phone, Fax, Web, Email) are now in English
