### ISSUE TITLE
Staging V1.0.18 - Missing Language Selection

### ISSUE THREAD

**Issue by jparlina** [pg-irc/pathways-frontend#652]
In staging app v 1.0.18 the language selection only appears when the app was first installed from App Store. If a user doesn't "Delete all user data", the user goes straight to Home screen. If a user clicks "Delete all user data", the next time the user opens the app, it SHOULD start with "Language selection" screen (currently it goes straight to on boarding screen). 

[https://drive.google.com/file/d/15Ztb659YfK4d3PoOf_O9Rit1qP8_Nqds/view?usp=sharing](url)

**Comment by rasmus-storjohann-PG** [comment]
This is expected behaviour. The user can change language through the hamburger menu.

**Comment by rasmus-storjohann-PG** [comment]
If you want to demonstrate the app including the welcome screen, go into settings on the device, look  up the arrival advisor app, and delete all memory related to the app. This is a more complete delete all data than what is available from within the app help screen.
