### ISSUE TITLE
Staging v1.0.19 - UX Issue: Missing "Read More/Less" - all languages

### ISSUE THREAD

**Issue by jparlina** [pg-irc/pathways-frontend#659]
Under each topic description "Read more" or "Read less" shows up as {english Text} for all languages - see screenshot below in Arabic

![IMG_0952](https://user-images.githubusercontent.com/48343061/59137235-9ce77100-893b-11e9-915a-6dc32c5ebd0e.JPG)

**Comment by rasmus-storjohann-PG** [comment]
This issue should already be fixed by this commit https://github.com/pg-irc/pathways-frontend/commit/114df8fc155436345c848b6de8e08fe7e62c4ca4 but the fix is not in staging yet. The problem only appears in a real app (it looks fine in Expo), so we will push this to staging to verify.

**Comment by jparlina** [comment]
Tested in Staging V 1.0.22, iOS: fixed 

![D2249C64-FCBF-478B-9017-DC45D6D392EF.jpeg](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/e05937c7-2bc7-4566-804f-b2e04433189c)

![9738489C-B12D-47B5-9CA2-A589F95E5B2B.jpeg](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/89221406-cd41-4e6f-b109-9e6fc47d401e)

![335E7672-4C50-45CB-9BA3-9A0B7DD5961D.jpeg](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/a004733b-340f-423a-af46-22d02fbce3c0)

![7F809CEC-DCE9-4E7F-BE42-6A23C83B7E82.jpeg](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/378f8945-f7a6-44b2-b9ff-0e65f2f82226)

![9DC5370C-7183-4915-98A7-F7F29747A311.jpeg](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/4e2f6eda-a641-4676-9e12-2f6cfc965076)

![A5AFFE5B-5DFD-49BD-98F2-7398CCB1480B.jpeg](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/2e8aef36-eb67-4f55-93fc-ab6a676afd4d)

![30F65128-C447-4F8C-BF53-916533FFA706.jpeg](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/a62fb92b-22ef-4ad3-bf27-e084bed06f4e)
