### ISSUE TITLE
Create a generic loading HOC to be used as application splash-screen

### ISSUE THREAD

**Issue by tnightingale** [pg-irc/pathways-frontend#66]
**Proposal:**
Generalize the `withFontLoading()` HOC to be a `withLoader()` HOC that takes a `loading: boolean` prop and depending on its value, either renders either a loader/splash screen or the wrapped component.

**Explanation:**
As our application grows there will be async tasks that will need be completed on bootstrap before we can perform our first meaningful (interactive) render.

Currently there is a [`withFontLoading()`](pg-irc/pathways-frontend/blob/master/src/components/helpers/with_font_loading.tsx) HOC that delays rendering its child components (the entire application UI) until it ensures the correct fonts have loaded. It is implemented using React's component lifecycle hooks & component state to track the status of the font loading.

A new bootstrap task is to [fetch the user's current locale/RTL layout preference](#56); we want to prevent the UI from flashing the default locale and instead wait until the user's locale preference has been loaded before rendering any screens.

Initially its input can be simple; just a `loading: boolean` property but functionality could be expanded:
- the 'loading' render output can be configurable; pass a component to be used as splash-screen/loading message
- handle individual failure/error cases
- display individual task loading progress/completion

**Comment by ApolloMuses** [comment]
This is a good idea, using HOC is a great way to generalize loading for repeated screens as well as something like authentication flow. Here's a example of using HOC for authentication written for a React app.

`
```

import React, { Component } from 'react';
import { connect } from 'react-redux';


export default function(ComposedComponent) {
  class Authentication extends Component {
    static contextTypes = {
      router: React.PropTypes.object
    } //to use react-router's context, must declare a context types for each

    componentWillMount() {
      if (!this.props.auth) {
        this.context.router.push('/'); //pushes the user back to main page
      }
    }

    componentWillUpdate(nextProps) {
      //handles when users clicks sign out
      if (!nextProps.auth) {
          this.context.router.push('/');
      }
    }

    render() {
      return <ComposedComponent {...this.props} />
    }
  }

  const mapStateToProps = (state) => {
    return { auth: state.auth }
  }
  return connect(mapStateToProps)(Authentication);
}

/*
in some other file, we want to use this HOC

..in this other file

import Authentication //HOC
import Resources //The component I want to wrap (prevent users from gaining access)

const ComposedComponent = Authentication(Resources);

...in some render method

<ComposedComponent />
 */

```
`

**Comment by tnightingale** [comment]
Thanks @ApolloMuses, that's essentially what I had in mind.

FWIW my implementation is in a branch [here](https://github.com/pg-irc/pathways-frontend/blob/feature/66-loading_hoc/src/components/main/loader.tsx). It's very simple right now but we can expand it as our design clarifies. The main difference is that it doesn't do the redux `connect()` mapping, allowing us to set the `loading: boolean` prop however we want. As it happens in this case I do use redux/`connect()` to wire things up [here](https://github.com/pg-irc/pathways-frontend/blob/feature/66-loading_hoc/src/components/main/index.ts#L24-L25).

One of the challenges was getting TypeScript to be happy with the HOC. I came up with [this helper to resolve TS issues](https://github.com/pg-irc/pathways-frontend/blob/feature/66-loading_hoc/src/%40types/omit.d.ts).

**Comment by tnightingale** [comment]
Interesting, I just discovered that this exists: https://docs.expo.io/versions/latest/sdk/app-loading. IT's nice because it just holds the Expo splash/loading screen up a little bit longer but it assumes you're calling an async function from your application component's lifecycle hooks.

My implementation in for this issue doesn't care about the source of the l loading state, it just switches the child component based on a `loading` prop. In effect, it adds a `loading` prop to whatever component you decide to wrap.
