### ISSUE TITLE
Staging V 1.0.19: Service Description - extra indentation before first word and last word gets cutoff before "Read more"

### ISSUE THREAD

**Issue by jparlina** [pg-irc/pathways-frontend#663]
See Service Description on the screenshot below:
- There's an extra space before the first word in the description
- The last word gets cutoff before "Read more" (see red highlight on the right side of the screen and compare with the green highlight after "Read more" was clicked)

![IMG_0957.JPG](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/98a4338d-a624-4ea3-a657-82e8762f4e82)

![IMG_0959.JPG](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/be4be631-0ea1-436e-bce0-0f03d0481d2c)

**Comment by bensinjin** [comment]
I'm closing this PR as we've decided it runs contrary to designs outlined by Cherrie.
