### ISSUE TITLE
On Arabic version of App, "Read more" under each service listed (in English) should align left

### ISSUE THREAD

**Issue by jparlina** [pg-irc/pathways-frontend#664]
Tested Staging V 1.0.19:
"Read more" on the Arabic version of the app should align left like in the English version of the app - see screen shot below

![IMG_0961.JPG](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/34b23c0e-23f6-4e40-ad16-ea5dab8e2007)

**Comment by jparlina** [comment]
Tested Staging V 1.0.22: 
"Read more" is now aligned left, but the arrow is still on the left of the words "Read more" (see screen shot below)

**Comment by ArtiBPG** [comment]
Testing staging: 1.0.13, Android
Read more is left aligned but title and phone number re right aligned.
Formatting is generally messier than before.

[Screenshot](https://screencast.com/t/Ju6lrj4fO)

**Comment by rasmus-storjohann-PG** [comment]
Outstanding elements still right aligning on service listing in Arabic:
- [ ] service name
- [ ] Read more should have the arrow to the right (?) of the string
- [ ] Phone
- [ ] Web, also string is in Arabic should be English
- [ ] Email, also string is in Arabic should be English
- [ ] Open in Maps button

**Comment by jparlina** [comment]
Tested Staging V 1.0.25 on iOS 12.3.1 at the HiVE:
Confirmed on Arabic version's service listing:
- all content and icons are aligned left
- all labels (Address, Phone, Fax, Web, Email) are now in English
