### ISSUE TITLE
Release notes process

### ISSUE THREAD

**Issue by ArtiBPG** [pg-irc/pathways-frontend#666]
Each release should have:

External change log for App Store and Play Store:
* Brand new shiny features, as written by Cherrie and translated.

Technical change log should be available on github:

List of changes as generated by gren, perhaps with one issue for each release.

Version for Service Listing Feature
Version for Search Feature
Version number for any new features
Client version
Server version
Service recommendation version
Issues that were part of a release
BC211 database version
BC211 data change log
(**Additions and removals:** number of services added, number of services removed, number of orgs added, number of orgs removed
**Updates**: Services/organization names changed, service/org descriptions changed, changes to other fields)

Use gren to automate release note generation: https://github-tools.github.io/github-release-notes/

**Comment by rasmus-storjohann-PG** [comment]
CHANGELOG files created on both front and back end repos, README files updated with instructions on how to use them

**Comment by rasmus-storjohann-PG** [comment]
# Change log from 1.0.15 to next production release
* Added support for Chinese simplified, Chinese traditional, Korean, Punjabi, Tagalog
* Added onboarding flow
* Improved flow at app startup to only prompt for language the first time the app is started
* Service listing page is now in English regardless of the user’s selected language
* About and disclaimer pages are now modal
* Improved markdown styling
* Service listing results ranked by both relevance and proximity to the user
* Added server end point for getting related topics for a given service
* Improved appearance of URLs in Newcomers’ Guide content
* Upgrade to Expo 33, supports 64 bit architecture on Android
* Fix various UX bugs, including RTL bugs
* Improvements to analytics
* Added one integration test
* Improvements to app release process automation

**Comment by rasmus-storjohann-PG** [comment]
@cherrielam and @ArtiBPG according to this story, we want to have an external change log for publication in the Google and Apple stores: "Brand new shiny features, as written by Cherrie and translated.". See change log above for all the things that have changed since the last public release.
