### ISSUE TITLE
Poor service recommendations

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#672]
I’m on skytrain on the way to the office. When I was in Surrey I tested the Staging app and searched “public libraries”, none of the results were related to libraries - eg. homeless shelter, food bank, dental clinic, treatment programs for ppl with addiction.
When I searched “Contact workers at your local settlement agency” in New Westminster (on skytrain), none of the 30 services listed was related to settlement services.
The staging app is actually worse than the live version. I think we need to include manual recommendations until we fix the NLP or use the new taxonomy. The results are so random on the staging app. Ppl will easily abandon the app.

**Comment by rasmus-storjohann-PG** [comment]
Two problems found:
* Client uses the wrong argument name in the URL to the server, with "task" rather than "topic"
* Server returns poor quality matches when the proximity value is included.

**Comment by jparlina** [comment]
Screenshots of results from "Public Libraries" search in Surrey - none of the results were relevant/related to public libraries. Tested using Staging App version 1.0.19; Server version 1.3.1; bc211 dataset Jun 2019

![IMG_0986](https://user-images.githubusercontent.com/48343061/59476075-e46e7100-8e03-11e9-858f-09ac887c82bb.PNG)
![IMG_0987](https://user-images.githubusercontent.com/48343061/59476076-e46e7100-8e03-11e9-87cb-bc617d237a61.PNG)
![IMG_0988](https://user-images.githubusercontent.com/48343061/59476077-e5070780-8e03-11e9-8623-d0fd5d5b29a8.PNG)
![IMG_0989](https://user-images.githubusercontent.com/48343061/59476078-e5070780-8e03-11e9-9986-f8254897eab7.PNG)
![IMG_0990](https://user-images.githubusercontent.com/48343061/59476079-e5070780-8e03-11e9-84d0-cb5a854c09b5.PNG)
![IMG_0991](https://user-images.githubusercontent.com/48343061/59476080-e5070780-8e03-11e9-8a63-1e5e9188d9cf.PNG)
![IMG_0992](https://user-images.githubusercontent.com/48343061/59476081-e5070780-8e03-11e9-925b-e64ceb0ff38e.PNG)
![IMG_0993](https://user-images.githubusercontent.com/48343061/59476082-e5070780-8e03-11e9-8868-cb4bc9cb8c9c.PNG)
![IMG_0994](https://user-images.githubusercontent.com/48343061/59476083-e59f9e00-8e03-11e9-84c9-32da3f3a0b4e.PNG)
![IMG_0995](https://user-images.githubusercontent.com/48343061/59476084-e59f9e00-8e03-11e9-8de6-fe1d518fb946.PNG)
![IMG_0996](https://user-images.githubusercontent.com/48343061/59476085-e59f9e00-8e03-11e9-87a8-fb08f0b1947e.PNG)
![IMG_0997](https://user-images.githubusercontent.com/48343061/59476087-e59f9e00-8e03-11e9-9adb-40e0d648c6b0.PNG)
![IMG_0998](https://user-images.githubusercontent.com/48343061/59476088-e59f9e00-8e03-11e9-9879-6979ad6f8e06.PNG)
![IMG_0999](https://user-images.githubusercontent.com/48343061/59476089-e59f9e00-8e03-11e9-83c4-588dba28e2f4.PNG)
![IMG_1001](https://user-images.githubusercontent.com/48343061/59476090-e59f9e00-8e03-11e9-85d7-8f32c55d53be.PNG)
![IMG_1002](https://user-images.githubusercontent.com/48343061/59476091-e6383480-8e03-11e9-8bf4-a301d55864df.PNG)

**Comment by jparlina** [comment]
Screenshots of results from "Contact workers at your local settlement agency" search in New Westminster - none of the 30 services listed were relevant/related to "settlement services". Tested using Staging App version 1.0.19; Server version 1.3.1; bc211 dataset Jun 2019.

![IMG_0986](https://user-images.githubusercontent.com/48343061/59476187-74141f80-8e04-11e9-8047-082bdd5c0167.PNG)
![IMG_0987](https://user-images.githubusercontent.com/48343061/59476188-74141f80-8e04-11e9-9dd7-15548ea4850a.PNG)
![IMG_0988](https://user-images.githubusercontent.com/48343061/59476189-74141f80-8e04-11e9-9896-d29e1cb33125.PNG)
![IMG_0989](https://user-images.githubusercontent.com/48343061/59476190-74141f80-8e04-11e9-8691-d7e810bbe245.PNG)
![IMG_0990](https://user-images.githubusercontent.com/48343061/59476191-74acb600-8e04-11e9-865a-d91e599fb9ef.PNG)
![IMG_0991](https://user-images.githubusercontent.com/48343061/59476192-74acb600-8e04-11e9-80e1-ef5a8aa04748.PNG)
![IMG_0992](https://user-images.githubusercontent.com/48343061/59476193-74acb600-8e04-11e9-8bc1-cc17bd075d00.PNG)
![IMG_0993](https://user-images.githubusercontent.com/48343061/59476194-74acb600-8e04-11e9-88d0-2fc6e9430745.PNG)
![IMG_0994](https://user-images.githubusercontent.com/48343061/59476196-74acb600-8e04-11e9-9f14-078e67952bd3.PNG)
![IMG_0995](https://user-images.githubusercontent.com/48343061/59476197-74acb600-8e04-11e9-83e3-ae397e341c63.PNG)
![IMG_0996](https://user-images.githubusercontent.com/48343061/59476198-74acb600-8e04-11e9-9ece-40479b0c3ad7.PNG)
![IMG_0997](https://user-images.githubusercontent.com/48343061/59476199-75454c80-8e04-11e9-993d-a70adba57848.PNG)
![IMG_0998](https://user-images.githubusercontent.com/48343061/59476200-75454c80-8e04-11e9-9d1f-ea276490adce.PNG)
![IMG_0999](https://user-images.githubusercontent.com/48343061/59476201-75454c80-8e04-11e9-87f7-266e80d2b70e.PNG)
![IMG_1001](https://user-images.githubusercontent.com/48343061/59476202-75454c80-8e04-11e9-9378-3ae9233ebc31.PNG)
![IMG_1002](https://user-images.githubusercontent.com/48343061/59476203-75454c80-8e04-11e9-9af3-b9b4a66bc6db.PNG)

**Comment by jparlina** [comment]
Screenshots of results from "Contact workers at your local settlement agency" search in New Westminster - none of the 30 services listed were relevant/related to settlement services. Tested using Staging App version 1.0.19; Server version 1.3.1; bc211 dataset Jun 2019.

![IMG_1005](https://user-images.githubusercontent.com/48343061/59476306-03213780-8e05-11e9-8420-755ef2a47eea.PNG)
![IMG_1006](https://user-images.githubusercontent.com/48343061/59476308-03213780-8e05-11e9-8bf2-770700f2e74a.PNG)
![IMG_1007](https://user-images.githubusercontent.com/48343061/59476309-03213780-8e05-11e9-9bbb-4c04d8897f2d.PNG)
![IMG_1008](https://user-images.githubusercontent.com/48343061/59476310-03213780-8e05-11e9-8705-07cefd66f3b9.PNG)
![IMG_1009](https://user-images.githubusercontent.com/48343061/59476311-03213780-8e05-11e9-8de9-af352ce07d78.PNG)
![IMG_1010](https://user-images.githubusercontent.com/48343061/59476312-03b9ce00-8e05-11e9-9bdc-65bc7b6155fd.PNG)
![IMG_1011](https://user-images.githubusercontent.com/48343061/59476313-03b9ce00-8e05-11e9-97e1-dcc6df15dd8e.PNG)
![IMG_1012](https://user-images.githubusercontent.com/48343061/59476314-03b9ce00-8e05-11e9-847a-823fc790d6dd.PNG)
![IMG_1013](https://user-images.githubusercontent.com/48343061/59476315-03b9ce00-8e05-11e9-97a7-cac86d3f8214.PNG)
![IMG_1014](https://user-images.githubusercontent.com/48343061/59476316-03b9ce00-8e05-11e9-985d-c1a9f419516f.PNG)
![IMG_1015](https://user-images.githubusercontent.com/48343061/59476317-03b9ce00-8e05-11e9-8629-fdc16a6a3a4d.PNG)
![IMG_1016](https://user-images.githubusercontent.com/48343061/59476318-03b9ce00-8e05-11e9-832c-3f8de4c1403f.PNG)
![IMG_1017](https://user-images.githubusercontent.com/48343061/59476319-04526480-8e05-11e9-81ed-65e9bbf11ad1.PNG)
![IMG_1018](https://user-images.githubusercontent.com/48343061/59476320-04526480-8e05-11e9-87a9-61993d2ff887.PNG)
![IMG_1019](https://user-images.githubusercontent.com/48343061/59476321-04526480-8e05-11e9-8f83-156fc878ffab.PNG)
![IMG_1020](https://user-images.githubusercontent.com/48343061/59476322-04526480-8e05-11e9-8d0c-e5baef1ef5b7.PNG)

**Comment by jparlina** [comment]
Services listed in Staging V1.0.23 are now consistent with what we have on production V1.0.13. (i.e. includes any services with the word “library”). The differences are due to the differences in bc211 dataset (Production: Sep 2018 dataset; Staging V1.0.23: Jun 2019 dataset). See side by side comparison here: https://docs.google.com/document/d/16tlUR7oQYRLoVgIqfXawWnHglr13RMAFPOGEqpFDjPI/edit

In terms of relevance, it still has the same issue as production (NLP issue). NLP picks up any services with the word “library”, including some “not-so-relevant public libraries” (48% of 27 results):
- PeerNet BC - PeerNet BC
- Decoda Literacy Solutions - Decoda Literacy Library
- Books for Me! Literacy Foundation
- BC Epilepsy Society
- BC Children’s Hospital (BCCH) - Family Support and Resource Centre
- Le Centre Culturel Francophone de Vancouver
- BC Children’s Hospital (BCCH) - Eating Disorder Resource Centre of BC
- Indian Residential School Survivors Society (IRSSS) - East Vancouver Office
- etc.

**Comment by jparlina** [comment]
Tested on Staging 1.0.25 - Server version 1.3.4 on iOS 12.4: 
tested some topics under "Things to do right away" - services recommended in staging app are worse (irrelevant) than those in production (V1.0.13).

See side by side comparison here: https://docs.google.com/document/d/1Vg9ZmxOTi1zVVT9LnJXNLrwM2jaUVHOPQfrNz1NHkU0/edit

**Comment by jparlina** [comment]
@rasmus-storjohann-PG 
Based on our conversation with Arti earlier, here are the fields that will be helpful for manual scanning of recommended services: 
- service_id
- organization_name
- service_name
- service_description
- city
