### ISSUE TITLE
Use Webview instead of Markdown component

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#682]
Currently we're using a mark down component from `react-native-markdown-renderer` that is hard to customize.

# heading
## heading2

ACs:
* Frontend: Replace the Markdown component with the web view from https://github.com/react-native-community/react-native-webview. Note that the webview shows content generated client side.
* Backend: Change the Newcomers Guide import script to convert mark-down to HTML tags. Note that we're using a very small subset of the markdown features, so it's not that complex. See `/pathways-backend/newcomers_guide/clean_data.py`

**Comment by ian-lin-PG** [comment]
Back end files have been converted to produce HTML instead of markdown. Front end react-native-webview component is incompatible with Expo, currently looking for workarounds.

**Comment by ian-lin-PG** [comment]
The current Expo SDK v32.0.0 is based on React Native 0.57 “September 2018”. However, in October there has been an [architecture change](https://www.reddit.com/r/reactnative/comments/9sim5r/any_thoughts_on_the_react_native_slimming_moving/) where the web-view component has been moved to it's own npm module named react-native-webview. This change introduced a (bug)[https://github.com/react-native-community/react-native-webview/issues/140] for using the new react-native-webview module.

The fix in expo can be found [here](https://github.com/expo/expo/issues/3381) and should have been merged in the [newest release](https://blog.expo.io/expo-sdk-v33-0-0-is-now-available-52d1c99dfe4c). The newest release of expo is also based on the [March 2019 version of react-native](https://facebook.github.io/react-native/blog/2019/03/12/releasing-react-native-059)  which should include the architecture change that happened last October.

**Comment by ian-lin-PG** [comment]
Upgraded expo to version 33.0.0 without errors, new warmings requires react-native link which is currently [unsupported] (https://github.com/expo/expo/issues/56) without detaching to expokit.

**Comment by ian-lin-PG** [comment]
Webview is currently enabled but there are a few outstanding issues:
1. Webview component does not currently scale to the screen size with flex, instead need hard coded dimensions to render
2. Webview component does not scroll vertically if the container outside is able to scroll vertically, might be an android issue.
3. Component above the Webview may be hidden until Webview component is interacted with
4. Webview redirects links WITHIN the component with no way to navigate back

**Comment by ian-lin-PG** [comment]
HTML renderer achieved better results than integrating webview. Currently markdown2, the markdown to html converter library, does not accept all ASCII characters. As a result, special characters or majority of certain languages are broken after the conversion, currently looking for alternative libraries.

**Comment by ian-lin-PG** [comment]
Someone, yours truly, did an unicode escape on all the markdown strings before being converted to html. Markdown2 is completely blameless. Language broken crisis averted.
