### ISSUE TITLE
Staging V1.0.21: Missing Translation in About Page - Paragraph 1 for all non-English versions

### ISSUE THREAD

**Issue by jparlina** [pg-irc/pathways-frontend#691]
The first paragraph in the About Page is not translated for all non-English versions of the app

![4C352905-6878-40BF-8265-F19AF927BEAB](https://user-images.githubusercontent.com/48343061/60279064-4bd0fa00-98b5-11e9-8f36-50329eef67b8.jpeg)

![12805942-3536-4F2E-A482-CB3D58DE64DE](https://user-images.githubusercontent.com/48343061/60279298-a407fc00-98b5-11e9-83fb-03e8cccf7bc8.jpeg)

![56F02AC1-29D1-4D7D-B003-394E116B3732](https://user-images.githubusercontent.com/48343061/60279065-4bd0fa00-98b5-11e9-98ce-ea0f42c89ec8.jpeg)

![DF177F3F-178A-4F41-8FB6-6473DDB235ED](https://user-images.githubusercontent.com/48343061/60279066-4bd0fa00-98b5-11e9-80af-a4bca2f56027.jpeg)

![818AF879-0D2A-42E9-9822-F37660FF658D](https://user-images.githubusercontent.com/48343061/60279067-4bd0fa00-98b5-11e9-884d-49f885bd561e.jpeg)

![65C712DA-DA51-43D2-A6E0-3C5B39FFBB15](https://user-images.githubusercontent.com/48343061/60279258-90f52c00-98b5-11e9-9325-bd18db1835d7.jpeg)

![3FEA746B-A8B7-4653-A80B-4EBBECB22073](https://user-images.githubusercontent.com/48343061/60279261-90f52c00-98b5-11e9-90c9-5638b9fced33.jpeg)

**Comment by ArtiBPG** [comment]
@tomy-pg i also see this in production, please fix asap.

**Comment by jparlina** [comment]
@ArtiBPG @tomy-pg 
In production it’s the bottom half that’s not translated 

![9149C8B2-4A60-4658-81BF-AF927997ED1D](https://user-images.githubusercontent.com/48343061/60620603-80025a00-9d90-11e9-865a-ea1f9765f1e3.jpeg)

![A66DD6F0-2820-4229-BA54-E5162C08122E](https://user-images.githubusercontent.com/48343061/60620605-80025a00-9d90-11e9-8313-27128f640992.jpeg)

**Comment by jparlina** [comment]
@tomy-pg Also on “Disclaimer” page - missing translation in first paragraph

![4AD514B8-1367-4133-99FC-EB0F49888818](https://user-images.githubusercontent.com/48343061/60621410-7b3ea580-9d92-11e9-9119-2f36aad3a3fc.jpeg)

![DD6FF720-66F6-417B-88E8-C2E2F842C77B](https://user-images.githubusercontent.com/48343061/60621411-7b3ea580-9d92-11e9-8c7b-b1a5e7939084.jpeg)
