### ISSUE TITLE
Staging V1.0.21: Missing Translation at bottom of About Page - Arabic 

### ISSUE THREAD

**Issue by jparlina** [pg-irc/pathways-frontend#694]
See screenshot below:
(1) “Newcomers Guide to British Columbia” is split into two lines, and since Arabic is written right to left the split looks weird and doesn’t make sense. 

(2) Server version at the bottom of About page is missing. The screenshot below shows “exception” instead of 1.3.3

![53FA3E47-2D8D-4EE1-B4DA-2EB44CD7A50D](https://user-images.githubusercontent.com/48343061/60302528-ebf44680-98e8-11e9-9658-f71e4fe255f7.jpeg)

**Comment by rasmus-storjohann-PG** [comment]
From Abdi: The "Newcomers Guide" string should look like that, not a bug.
