### ISSUE TITLE
Missing Translation: “Category” when clicking a Topic 

### ISSUE THREAD

**Issue by jparlina** [pg-irc/pathways-frontend#698]
Tested Staging V 1.0.22:
Missing Translation in all non-English versions of the app: “Category” at the top of the page when you click a Topic (see screenshots below) 

![4ECC6916-B053-4DF1-8857-E006200B1731](https://user-images.githubusercontent.com/48343061/60367139-561cf200-99a2-11e9-9f1a-b93092ecb8cf.jpeg)

![3A40F442-4988-49DB-9D74-447DD8A661C3](https://user-images.githubusercontent.com/48343061/60367141-561cf200-99a2-11e9-947a-19213b654af1.jpeg)

![375036BA-C1F8-47FC-8956-87208D10BCFF](https://user-images.githubusercontent.com/48343061/60367142-561cf200-99a2-11e9-9656-6e9ccc0c2461.jpeg)

![DF4898A8-93D7-463F-9478-8013EB783571](https://user-images.githubusercontent.com/48343061/60367143-561cf200-99a2-11e9-82ae-864851b699f9.jpeg)

![5B812F68-A66E-44F9-91A7-0962698B9825](https://user-images.githubusercontent.com/48343061/60367144-561cf200-99a2-11e9-8ef5-fe95c2b39c64.jpeg)

![55F1B9F1-4D22-4B16-B51E-F21F35445DAD](https://user-images.githubusercontent.com/48343061/60367145-56b58880-99a2-11e9-861e-d4364cea3693.jpeg)

![46EC5664-231E-4978-AACA-88C7A5025508](https://user-images.githubusercontent.com/48343061/60367146-56b58880-99a2-11e9-8c94-150e7b628c3b.jpeg)

**Comment by ArtiBPG** [comment]
Translation exits but is not showing up on these screens.

**Comment by bensinjin** [comment]
@tomy-pg and I looked at this, we did figure out what was wrong, we need to wrap the `TaxonomyComponent`'s value should be: `<Trans id={props.topic.exploreSection.name.toUpperCase()} />` this appears in the `task_detail_content_component.tsx`. Please take a look @tomy-pg and put some comments down on the PR for this issue, cheers.

**Comment by jparlina** [comment]
Tested Staging V 1.0.25 on iOS 12.3.1 at the HiVE:
"Category" are no longer in English when clicking on a topic (though I can't confirm whether the  translations are accurate).
