### ISSUE TITLE
Mark-down styling issues

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#703]
Issues with the current mark down component:
* Use the same font as the app, should be avenir (this is also wrong for the topic teaser string)
* Have nice headers
* Body text font bigger (text size 16sp from Zepelin)
* Body text font colour dark grey as per Zepelin
* Change the link colour from blue to green (one line change)

Also:
* About page body text font colour should be dark grey as per Zepelin

Reference:
* Zepelin https://zpl.io/aByGdBm

**Comment by bensinjin** [comment]
For Ben: Review these requirements and ensure our Markdown component is sufficient.

**Comment by cherrielam** [comment]
A few remaining UI issues related to the markdown/font styling:
1. The header font used for the category of a topic (eg. "Education" below) should be capitalized. It should be using the same header style is "Related topics"
![IMG_4429](https://user-images.githubusercontent.com/21990736/61565118-f065d800-aa2c-11e9-8751-2266bd603fdb.PNG)

![IMG_4433](https://user-images.githubusercontent.com/21990736/61565326-8bf74880-aa2d-11e9-93cf-c0fe50fc9ebf.PNG)


2. (see image above) The Read More component - "Read more" text needs to be aligned with the Body text above. This may be related to other "Read More" issues... maybe consult @bensinjin to see when this will be tackled.

3. The teaser text is not in Avenir, it is currently using the device default font (on both Apple and Android)
![IMG_4430](https://user-images.githubusercontent.com/21990736/61565214-3753cd80-aa2d-11e9-8c0a-d761f9badea9.PNG)

4. The links are not using Avenir, also using the device default font.
![IMG_4431](https://user-images.githubusercontent.com/21990736/61565251-55213280-aa2d-11e9-9047-6cd14077e5ef.PNG)

**Comment by ian-lin-PG** [comment]
1. This will be more difficult because the explore section names are translated and used throughout the application, it would be hard to keep it capitalized in one place and not in all the other places. Alternatively, the 'RELATED TOPICS' is hard coded and will barely take any time to change to 'Related Topics', just a thought.

2. I applied marginLeft:5 on the 'Read More' and it's more aligned now.

3 and 4 I applied fontFamily: 'AvenirBook' to the components in question.

**Comment by rasmus-storjohann-PG** [comment]
@cherrielam can you QA this story, you're then ones with the sharp eye for subtle font differences.

**Comment by cherrielam** [comment]
@rasmus-storjohann-PG sure thing.

QA-ing below for Staging Version 1.4.0:

- [x] 1. PASSED - The header font used for the category of a topic (eg. "Education" below) should be capitalized.

- [ ] 2. FAILED - The Read More component - "Read more" text needs to be aligned with the Body text in the Topic Detail page. It appears the Read more component has disappeared. See issue #711 

- [x] 3. PASSED - The teaser text is in Avenir, not the device default font (on both Apple and Android)

- [x] 4. PASSED - The links are in Avenir, not the device default font.

**Comment by ian-lin-PG** [comment]
@cherrielam Right now the topic recommendations are all empty so none of the topics have been collapsed. The issue is tracked here pg-irc/pathways-backend/issues/438. I happen to be tagged to this issue having worked on it last.

**Comment by cherrielam** [comment]
Ok gotcha, thanks @ian-lin-PG. I can't currently QA 2. regarding the "Read More" component then until it is published to Staging. Let me know if I should QA a different way @rasmus-storjohann-PG 

I have tried to QA the "Read More" component alignment on the Services Listing page, but it is actually misaligned on Services Listing 😅. I have flagged that as a separate issue in #811 .

**Comment by rasmus-storjohann-PG** [comment]
@cherrielam if this issue is all passed except for a problem that is being tracked in #711, then I suggest you close this issue as done.

**Comment by rasmus-storjohann-PG** [comment]
QA is blocked until next staging release which will have recommended topics.

**Comment by tomy-pg** [comment]
@cherrielam this is ready for QA.

**Comment by cherrielam** [comment]
> @rasmus-storjohann-PG sure thing.
> 
> QA-ing below for Staging Version 1.4.0:
> 
> * [x]  1. PASSED - The header font used for the category of a topic (eg. "Education" below) should be capitalized.
> * [x]  2. PASSED - The Read More component - Works now, and is aligned with the rest of text
> * [x]  3. PASSED - The teaser text is in Avenir, not the device default font (on both Apple and Android)
> * [x]  4. PASSED - The links are in Avenir, not the device default font.
