### ISSUE TITLE
Ensure all steps in Expo update to version 33 were completed

### ISSUE THREAD

**Issue by bensinjin** [pg-irc/pathways-frontend#706]
I think we're missing a few libraries that still need to have their versions bumped and tested. Also double check the import syntax is fixed where is should be.

ACs:

- Review https://blog.expo.io/expo-sdk-v33-0-0-is-now-available-52d1c99dfe4c#c0d2 and test

**Comment by ian-lin-PG** [comment]
Right now the package.json versions are correct but the @types equivalent are outdated. The end result is that we cannot use new functionalities not declared in the @types. Will upgrade the @types declarations starting with the ones directly tied to expo.

**Comment by ian-lin-PG** [comment]
The Upgrade Expo commit has been reverted, and I have moved the original Issue #687 from merged to in progress. I will continue the work back on #687 and close this task.
