### ISSUE TITLE
Investigate rich text solution

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#71]
AC: Have an understanding of the various alternatives libraries we could use to get rich text in the app, i.e. paragraph length text components where some or the text appears as bold, italic, underline, bullets and headings.

**Comment by tnightingale** [comment]
Here are some markdown renderers:
- https://github.com/Benjamin-Dobell/react-native-markdown-view
- https://github.com/mientjan/react-native-markdown-renderer

This one has a warning that it's being rewritten and likely unstable:
- https://github.com/CharlesMangwa/react-native-simple-markdown

Finally, looks like RN's `<Text />` component supports some form of "rich text" support by nesting components (good to know about but less useful to us):
 - https://facebook.github.io/react-native/docs/0.49/text.html#nested-text

My brief attempt at Googling didn't surface any non-markdown solutions for rich text renderers/components in RN.

**Comment by tnightingale** [comment]
PR in #94
