### ISSUE TITLE
Service Listing page - Partially localized

### ISSUE THREAD

**Issue by ArtiBPG** [pg-irc/pathways-frontend#711]
Description:
The services page is partially localized.

AC: 
Website email and all other fields in the service listing should be in English: https://www.screencast.com/t/XoYWFSown8
There should be a visual indicator or message so that users know that this page is intentionally available only in English.
@cherrielam to review and create a mock 

@cherrielam should these strings appear in EN or translated: https://www.screencast.com/t/Z3OUmIarq

**Comment by cherrielam** [comment]
I think the screen should only appear in English and we should have an alert that our services listing will only be available in English (this will translate well for the Search function). I will create a mock for the alert.

**Comment by ArtiBPG** [comment]
@cherrielam which Monday July 29th or Aug 5th?

**Comment by cherrielam** [comment]
## UI change recommendation:
- the header ("Find a Service Near You" & topic title) and warning message should be localized
- the warning message is currently not "dismissable" but scrolls up along with everything else. This gives the user the option to call BC211 always.
- the message ONLY displays in non-English languages. The English version below is only provided for translation purposes... I am open to other wording. @ArtiBPG ideas?

## Mocks:
See mock in Chinese: https://zpl.io/2yWGwpK
See mock in English: https://zpl.io/25Ao06J

![English translation](https://user-images.githubusercontent.com/21990736/62172629-c394a900-b2e7-11e9-8ba4-9565338b09d8.png) ![In other languages](https://user-images.githubusercontent.com/21990736/62172630-c394a900-b2e7-11e9-9f73-02c24c799bdb.png)

**Comment by ArtiBPG** [comment]
@cherrielam 
I suggest simpler language:
Information about services is currently only available in English.
For information in other languages, please call BC211.

Also, this may be a good time to check with BC211 if they are ok with this message.

**Comment by cherrielam** [comment]
@ArtiBPG I have updated the screen to reflect this: https://app.zeplin.io/project/5bc7bfa42e72260acb03aa86/screen/5d40d199bfc64e0d78fd1192 

![English translation](https://user-images.githubusercontent.com/21990736/62902645-15d8bf80-bd15-11e9-9779-98f3279f28b1.png)

@jparlina can you email Louise to ask if we can direct users to call them for multilingual services info?

**Comment by jparlina** [comment]
@ArtiBPG @cherrielam Would this message appear under all topics?

**Comment by cherrielam** [comment]
@jparlina Yes IF the user is in a non-English language version of the app. If they are in English, the message will not appear.

**Comment by cherrielam** [comment]
This issue is currently being put on hold because more testing is needed to discover what kind of partial localization makes sense to non-English speakers. We have received contrary feedback from user testing that the original version of this page was better.

**Comment by cherrielam** [comment]
Based on our testing (see results here: https://docs.google.com/document/d/1oIo3JJtHfEJMWcDtjmKRpC4HPH1vQh7Gi4kclH2S4uc/edit?usp=sharing) - the immediate recommendation is to **revert to the old partially localized version of the services listing page (version that is in production)**, where **as much of the page is translated as possible**. In Arabic, this means having Arabic labels & buttons and it's OK if the English text is right-aligned. We can skip the "warning" thing that asks the user to call BC211.  

In terms of the medium term solution of improvements to the partially localized page, that will be mocked up and tackled in https://github.com/pg-irc/pathways-ux-ui/issues/67

**Comment by jparlina** [comment]
Tested on staging V1.4.0, Server V1.3.9 on iOS 12.4.1:
Confirmed the following are translated (as per Weblate) on service listing for all non-English version of the app:
- Category name
- Topic name 
- Read more
- Address
- Web
- Email
- Open in maps


- [x] Arabic

![IMG_2403.JPG](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/59ee5eea-4aa9-4a07-9704-2481b3a0361d)



- [x] French
![IMG_2402.JPG](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/ebf1979f-7e58-456a-8f70-4137bb3d16f4)



- [x] Korean
![IMG_2395.JPG](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/027669f9-6cc8-4468-b480-63cbf481ee6c)



- [x] Punjabi
![IMG_2396.JPG](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/7f1464e3-5f29-4b64-9625-745e1fac390a)



- [x] Tagalog
![IMG_2398.JPG](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/9a82b389-f7e9-448b-9624-e37caed7d12f)



- [x] Chinese Simplified
![IMG_2399.JPG](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/7944ea64-f979-4a58-908b-2c3a52eaa8bb)



- [x] Chinese Traditional
![IMG_2400.JPG](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/07b7c47f-dced-45de-80cc-4e448d39e11e)

**Comment by jparlina** [comment]
As per team standup this morning, the alignment for the arabic version still needs to be fixed (see https://github.com/pg-irc/pathways-frontend/issues/812)
