### ISSUE TITLE
Traditional Chinese question #4 and #5 are the same

### ISSUE THREAD

**Issue by tomy-pg** [pg-irc/pathways-frontend#718]
![image (1).png](https://images.zenhubusercontent.com/5c6c8cff9d62b128eab447ff/a384c9fc-6620-42a6-87c2-10d3ef894f11)![image (2).png](https://images.zenhubusercontent.com/5c6c8cff9d62b128eab447ff/c97fdd0f-0700-4e46-b13f-1de9ba0e1a01)

**Comment by ArtiBPG** [comment]
Copy paste error since we were using spreadsheets.
Question 5 should be:
What is your current level of English?
您目前的英文程度？

**Comment by tomy-pg** [comment]
The changes will be reflected once we run another staging build.

**Comment by ian-lin-PG** [comment]
The translation has been corrected on staging.

![image](https://user-images.githubusercontent.com/52009863/61563109-ccec5e80-aa27-11e9-97f9-8b53cd0aad42.png)
