### ISSUE TITLE
Newcomers' Guide data model

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#72]
AC: Describe the data model including the entities: Task, Info (find better name), Questionnaire, Question, Answer, TaxonomyTerm, with multilingual support and support for some form of mark-up.

**Comment by rasmus-storjohann-PG** [comment]
This was my first stab at data model, with separate entities for user data and localization data:
![image](https://user-images.githubusercontent.com/32307781/40554869-072d3988-5ffc-11e8-9396-cac1896fa0f5.png)

**Comment by rasmus-storjohann-PG** [comment]
However, I am tending towards a simpler model where the user data is stored in the entities, and the localized strings are also stored in their entities as a lookup table keyed on the locale:
![image](https://user-images.githubusercontent.com/32307781/40554943-490f288e-5ffc-11e8-83da-5bd5eafcf976.png)

**Comment by rasmus-storjohann-PG** [comment]
Recognizing that there is actually a 1:1 relationship between Answer and TaxonomyTerm entities, the model can be simplified quite a bit:

![image](https://user-images.githubusercontent.com/32307781/40567463-4509c9aa-602a-11e8-8b1b-2622e05f2900.png)

Note that this model explicitly assumes that it will be represented in Javascript, translating this to SQL would involve additional tables (see several array and map data types).

**Comment by tnightingale** [comment]
Looks good at first glance.

I'm not sure about embedding/simplifying TaxonomyTerms down to just strings on Answer/Task/Article entities. Do we anticipate our taxonomy terms being user-facing at all? If so then our term names are going to need to be translated, would be best to use foreign-keys in that case.

I assume Article is for the general info content?

**Comment by rasmus-storjohann-PG** [comment]
Robin raised some good points: We need to be able to add tasks that are not associated with answers, otherwise we're ending up with too few tasks or too many questions. So I'm now thinking more along the lines of a few dozen tasks being "featured" by being tied to answers in the questionnaire, plus a much larger number of more specialized tasks that can only be discovered through the ExploreAll deep delve.

With that I end up with something like this:

![screenshot from 2018-05-30 17-13-51](https://user-images.githubusercontent.com/32307781/40754207-f4579a26-642c-11e8-85f7-21ff5ca0f617.png)

The recommendation algorithm is still not quite right, though...

**Comment by rasmus-storjohann-PG** [comment]
## Recommendation algorithm
A task or article is recommended
* if it has `isRecommendToAllUsers` equal to true, or
* if it has one or more associated question, all of those questions have `isSelected` equal to true, or
* if it has no associated questions and it has a taxonomy term with `recommendIfSelected`, and that taxonomy term is associated with a question that has `isSelected` equal to true

**Comment by mdorsey** [comment]
I assume a "power" taxonomy term is one with recommendIfSelected equal to true. If so, looks good. If not, how does a taxonomy term get tagged as a "power" term?

**Comment by bensinjin** [comment]
This is looking good Rasmus.

**Comment by rasmus-storjohann-PG** [comment]
For completeness, this is what the server side data entities would look like
![screenshot from 2018-06-06 10-44-36](https://user-images.githubusercontent.com/32307781/41064662-176881a6-6991-11e8-9f08-008021fc5972.png)

**Comment by rasmus-storjohann-PG** [comment]
Client side entities:

![screenshot from 2018-06-07 08-45-15](https://user-images.githubusercontent.com/32307781/41110807-2260b440-6a2f-11e8-9a6a-c8a28de7a5e9.png)

### Recommendation algorithm
A task or article is recommended:
* if it has `isRecommendedToAllUsers` equal to true, or
* if it has one or more associated answers, all of those answers have `isSelected` equal to true

**Implications of this implementation:**

* We can easily tag a task or article to be recommended to everyone.
* "Featured" tasks and articles that are associated with one or more answers in the questionnaire are recommended only when all the related answers are selected, so we have precise control over how they are recommended.
* Answers corresponding to broad categories such as "between 13 and 18 years old" can be used in combination with one or more other answers, to avoid recommending large number of tasks based on broad categories.
*  Answers corresponding to narrower categories, such as "I'm interested in LGBT issues" can be used by themselves, so that selecting just this one answer leads to the recommendation of tasks.
* Tasks and articles that are not associated with answers will never be recommended, but they can be found through search and explore all.
* In the likely event that we need to represent more complex logic and just AND among selected answers in the recommendation engine, storing the logic in the form of http://jsonlogic.com/ seems a possible solution.

Server side entities:

![screenshot from 2018-06-07 08-46-06](https://user-images.githubusercontent.com/32307781/41110842-3e48ad02-6a2f-11e8-9e07-8154e3f60006.png)

**Comment by rasmus-storjohann-PG** [comment]
Following additional discussion with Robin, and refinement of the scope for the MVP to exclude all server side work, this more general data model (all relationships to taxonomy terms are 0..n rather than the more narrowly defined relationships above) is proposed to be sufficient for the MVP:

![screenshot from 2018-06-08 15-06-15](https://user-images.githubusercontent.com/32307781/41183084-81ac7df4-6b2d-11e8-9523-49adf8b4c0b3.png)

**Comment by rasmus-storjohann-PG** [comment]
Final diagram represent the client data structure we want. Note that the tasks are represented using a different data structure, this is tech debt that we probably want to fix.

**Comment by rasmus-storjohann-PG** [comment]
Here are some thoughts on what the server side data model could look like, @bensinjin, @robinpuga, @trisapeace please have a look.

![screenshot from 2018-07-04 09-36-07](https://user-images.githubusercontent.com/32307781/42288010-e44c848c-7f6d-11e8-8544-04418a02edb5.png)

**Comment by trisapeace** [comment]
Looking good, @rasmus-storjohann-PG .

Is there any time when we would need to get an Article or a Task without it being associated with user? For example, when would we need to get an article without knowing whether it were starred or not? I think you only need one API call that will return the join of Article and UserArticle. You wouldn't want to have to make two separate calls to get it. And the same for one API call that will get the join of Task and UserTask.

Similarly, an API call to answer would need to take a particular user as a parameter so you only get back Answers associated with a particular user. Am I understanding this correctly?

For structure elements not related to users, like ExploreSection, TaxonomyTerm, Task, Article, Question, and (sort of) Answer, do you envisage these being downloaded from the server on initial installation? Or will these be updated at some interval?

The reason that I say "sort of" in front of Answer is that it seems to be playing the role of both a read-only item like Article and also a write-able item like UserArticle. So maybe it needs two endpoints... one that will be readonly like `/answer/:answerid` and also one for read-and-write like `/user/:userid/answer/:answerid` (or `/answer/:answerid/user/:userid`).

Can you please explain what you mean by "localized string"? To do the locale switcher on the front end, it will need to know all the translations for each entity, won't it?

**Comment by bensinjin** [comment]
I think the model looks good although the api piece possibly shouldn't be modelled directly from it.  I think it's going to be better that we build specifically what we need from the api from example: "Heres a list of survey answers get me associated tasks" or "Here's a list of user tasks sync it with the server".

**Comment by rasmus-storjohann-PG** [comment]
Hmmm, good point. This looks like it could be relevant https://savvyapps.com/blog/how-to-build-restful-api-mobile-app
