### ISSUE TITLE
Move Weblate strings from Tomy's github repository to a repo under pg-irc

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#720]
While developing our weblate deployment, Tomy stored translated strings in his own github repo.

AC:
* The translated strings are stored in a repo that is under the github.com/pg-irc
* The client build succeeds using the new repro as source of translated strings

**Comment by ArtiBPG** [comment]
@rasmus-storjohann-PG how do we test if the transfer was successful?

**Comment by ArtiBPG** [comment]
Scheduled for after the production release in Sept
