### ISSUE TITLE
Configure Weblate Project to address needs 

### ISSUE THREAD

**Issue by tomy-pg** [pg-irc/pathways-frontend#725]
Below are a list of things @tomy-pg needs to do for Weblate. 
### Acceptance Criteria
 - [x] Add source string bug report email address
 - [x] Upgrade Weblate from 3.5.1 to 3.7.1  
- [x] Use a repo under github.com/pg-irc
- [x] fix the flow by either making the branching more intuitive or possibly move to the frontend

Right now with our current version, users are only allowed to make 20 translations per 60 second window. 

With an upgrade to 3.7.1 this is bumped to 30 translations per 60 second window. 

This issue is also related to: https://github.com/pg-irc/pathways-frontend/issues/720

**Comment by tomy-pg** [comment]
This will be completed after the next production release.

**Comment by ArtiBPG** [comment]
@tomy-pg we need Weblate to manage the few strings for the next prod release.
can it at least be made usable for: 1)logging in and reviewing strings 2) copy pasting in translations?

**Comment by tomy-pg** [comment]
@ArtiBPG If we are managing a few strings for the next production release, Weblate is ready to go. 

The only concern is about the current rate limiting. Translators can only perform 20 translation actions within a 60 second window until we upgrade Weblate versions where the rate limit is slightly higher (30 actions in 60 seconds). 

The rate limit was put in place to prevent malicious use. The developers of Weblate believe that for _normal use_ IE: translating strings, approving and navigating, the rate limit that is currently in place is not restrictive.  

Discussion on rate limiting can be found here: https://github.com/WeblateOrg/weblate/issues/2208

**Comment by ArtiBPG** [comment]
Our users all need to be logged in. Do we still need rate limiting to protect against malicious use?

**Comment by tomy-pg** [comment]
This will be blocked until the first production release.

**Comment by tomy-pg** [comment]
Upgrade Weblate to version 3.8.1 and is currently under the pg-irc repository.

**Comment by rasmus-storjohann-PG** [comment]
QA:
- [ ] Readme page at https://github.com/pg-irc/ui-strings contains stale content

**Comment by rasmus-storjohann-PG** [comment]
QA: Pass
