### ISSUE TITLE
Adjust the front-end build process 

### ISSUE THREAD

**Issue by tomy-pg** [pg-irc/pathways-frontend#731]
We have a new Google Analytics id for staging that can be added into our .env file during the prepare_deploy script. As well, there are improvements that can be made to how we validate locale strings. 

AC:  
- [x] In pathways-frontend prepare_deploy script - add the staging google analytics id to .env 
- [x] In the expo build script remove `--release-channel release` * from giveExpoCommandsForPublishing in the prepare deploy script. *This AC was completed as part of Issue #502 
- [x] Improve validation of messages.js files generated 

Manual QA:
- [ ] Builds for both iOS and Android are created without error when running a staging and production builds

**Comment by rasmus-storjohann-PG** [comment]
QA: 
* Failure: Script does not complain if --serverVersion is not given on the command line. Ensure that all required command line switches are included in the command line validation step.

**Comment by rasmus-storjohann-PG** [comment]
QA: Passed, now complains when the server version is not given
