### ISSUE TITLE
Newcomers guide content: Traditional Chinese link is not formatted properly

### ISSUE THREAD

**Issue by ian-lin-PG** [pg-irc/pathways-frontend#732]
Some of the data in the Newcomers Guide links in TW_CH does not terminate properly with a space. This is especially apparent in the TW_CH translation for "Applying for a driver's License"

AC: 

- [x] add in a space after .com if there wasn't one there before.

QA:

- [x] Go to  the topics _Have your qualifications and credentials assessed_ and _Applying for a driver's licence_ and ensure that the links in the description are clickable 

![image](https://user-images.githubusercontent.com/52009863/61237106-8d073d80-a6ee-11e9-8e62-341468b9efe2.png)

**Comment by ian-lin-PG** [comment]
Having done a traditional Chinese QA, I notice the issue with malformed url is quite prevalent. There are worse issues such as spaces in between the url, url that doesn't have http:// or www prefix making it extremely hard to match.

My recommendation is to QA through simplified Chinese and consider transposing the simiplified Chines markdowns to traditional Chinese markdowns. The two uses different character sets but the correspondence is 1 to 1.

**Comment by tomy-pg** [comment]
Client: 1.1.0 / Server: 1.3.5

Chinese Simplified links are clickable. Thanks for all your effort manually fixing these, @ian-lin-PG .
