### ISSUE TITLE
Korean_Not clickable links

### ISSUE THREAD

**Issue by rankanglee** [pg-irc/pathways-frontend#739]
**Describe the bug**
Links are not clickable. 

**App version**
1.0.24

**To Reproduce**
1. Go to 'Learn all about B.C.'
2. Click on below topics: (Entered keywords in the full name of the topics for efficiency.)
Settling in - SIN, public transportation
Education - Adults completing, Children extra support, Distributed learning, English language learning for children, French program, Private schools, Post-secondary, English classes, Registering in public schools, Training and certifications
Health care -  All except Eye exam, Healthy kids, Language assistance, Private clinics
Money & Banking - Tax, Employment
Housing - Homelessness, Property tax, Where to go for
Employment - Please check all.
Legal system & immigration - Legal systems, government, immigration, courts, Ombudsperson, police, Lawyer
Driving - Driver's license, new car, accident, car seat, car insurance, safe driving, traffic laws, outside BC
Help for individuals & families - Please check all.
![KakaoTalk_Photo_2019-07-17-01-38-22](https://user-images.githubusercontent.com/47799302/61360594-9948e300-a833-11e9-9e1b-6b1ea64efd8f.jpeg)

3. See error

**Expected behavior**
Links should be hyperlinked.

**Observed behavior**
Some links are not clickable.

**Screenshots**
Please find the attached screenshot as an example.

**Smartphone (please complete the following information):**
 - Device: iPhone7
 - OS: iOS 12.3.1

**Comment by ian-lin-PG** [comment]
This is the exact same issue as #390 just on a different page. Possible approaches includes inserting http:// programatically or manually inside the markdown files.

**Comment by tomy-pg** [comment]
Client: 1.1.0 / Server: 1.3.5

Confirming that the links are clickable.
