### ISSUE TITLE
Staging V 1.0.25 - Bookmarks disappear when switching EN <> AR

### ISSUE THREAD

**Issue by jparlina** [pg-irc/pathways-frontend#740]
Tested on iOS Staging V1.0.25:
Started app in Arabic, bookmarked certain topics, switched to English:
- the English version opens up in home page instead of staying on the same page that I had opened in the Arabic version
- all my bookmarks disappeared even though I didn’t “Delete all user data”

Same when I started in English, then switched to Arabic.

For other languages, bookmarks did not disappear and you didn’t get rerouted to Home page every time you switch language. 

Note: Answers to questionnaires did not disappear when switching between EN <> AR

**Comment by ian-lin-PG** [comment]
The issues exists when changing from any languages to Arabic and vice versa. Preliminary theory is that the alignment utility, I18nManager, doesn't save the state when relaunching app with the correct language orientation. The issue also doesn't exist in production, which means one of the merged changes specifically related to Arabic caused this change.

Currently combing through merged changes for clues.

**Comment by jparlina** [comment]
Tested Staging V1.1.0, server 1.3.5 on iOS 12.4:

Started at language selection screen - selected Arabic - closed onboarding - bookmarked several topics on Home screen - checked My Bookmarks - changed language to English - PASSED:
- language changed in English and stayed on the same screen instead of opening new language on Home screen
- bookmarks did not disappear when language was changed

Deleted all user data on the app - in English version
Bookmarked topics on Home screen in English version 
Changed language to Arabic - Onboarding screen showed up - is this expected? @tomy-pg 
Bookmarks did not disappear - PASSED 

No more issue with bookmarks so moving this to "Ready for Production" 
Onboarding screen issues are separate.
