### ISSUE TITLE
Exclude Demo and testing Phones from Google Analytics 

### ISSUE THREAD

**Issue by jparlina** [pg-irc/pathways-frontend#742]
Exclude Testing phone and employee phones from Google Analytics for production app.
Employee and testing phone can be included in GA for the staging version.

Not posting phone details here for security reasons. 
This issue is a placeholder to complete the task in person.

ACs:
Employee phones should not be counted as part of Google Analytics.

Steps for QA:

1. Navigate to the search page on the app
2. Click on the location input bar
3. Type in 'foobar' and click enter/done
- [ ] ensure you receive a pop-up indicating that 'analytics is disabed'

4. Open Google Analytics and navigate to In Real-time analytics:
- [ ] ensure you do not see your device active. 

To enable analytics on your device again, type in 'barfoo' in the location bar.

**Comment by ArtiBPG** [comment]
related: https://github.com/pg-irc/pathways-frontend/issues/707

**Comment by bensinjin** [comment]
@ArtiBPG It looks like we now have a separate id for staging. We should be able to close this.

**Comment by rasmus-storjohann-PG** [comment]
@ArtiBPG so we are tracking release, staging apps separately using different google analytics ids. Is that good enough, or would you like to exclude our own users for when they use the production app too? That may be difficult to do, haven't looked into it.

**Comment by rasmus-storjohann-PG** [comment]
See https://support.google.com/analytics/answer/1034840?hl=en

**Comment by ArtiBPG** [comment]
@rasmus-storjohann-PG Look into what we can do to exclude specific phones irrespective of IP.
At least come up with a few solutions and time estimate.

**Comment by ArtiBPG** [comment]
works for Android.
@jparlina test on iPhone

**Comment by jparlina** [comment]
Tested on Staging V1.15.0, server 1.3.21 using iPhone - PASSED ("Analytics Disabled")

**Comment by jparlina** [comment]
Tested on Staging V1.16.0 on both Android and iOS with @tomy-pg. Activities are still being tracked after disabling analytics on the device.

**Comment by jparlina** [comment]
Steps for QA:
1. Navigate to the search page on the app
2. Click on the location input bar
3. Type in 'foobar' and click enter/done
- [x] ensure you receive a pop-up indicating that 'analytics is disabed'
![IMG_4012.PNG](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/9a972ff9-af18-4e2b-a45f-9389dd610c8b)

4. Open Google Analytics and navigate to In Real-time analytics:
- [x] ensure you do not see your device active.

5. To enable analytics on your device again, type in 'barfoo' in the location bar.
![IMG_4013.PNG](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/e6b7f3d4-22c8-41c9-8dc3-f7cf0f83cb99)

**Comment by jparlina** [comment]
@ArtiBPG See my comments on #4 above 
Is it acceptable that the device is still shown as "Active" but the events are no longer tracked when the Analytics is disabled on the device?  If yes, then we can close this issue.
