### ISSUE TITLE
App stuck on language selection screen on certain Android phones

### ISSUE THREAD

**Issue by ian-lin-PG** [pg-irc/pathways-frontend#750]
After clearing all the cache and data on Ian's phone, One Plus 5, relaunching the arrival advisor app would cause a constant refresh on the language selection screen and break the flow. The error message are as follows:

![image](https://user-images.githubusercontent.com/52009863/61985869-3b00ca80-afc0-11e9-9f77-eb608c0d8be6.png)

Quitting the app and relaunch the app will arrive at the welcome screen and the bug disappears. However, the language will default to English up until the user either quit, skip or complete the onboarding questionnaire which is not ideal.

ACs:
- [x] Find out the cause of the language refresh bug and how prevalent the issue is
- [ ] Fix the language selection screen.

**Comment by rasmus-storjohann-PG** [comment]
See https://www.robinwieruch.de/react-warning-cant-call-setstate-on-an-unmounted-component/ for possible approach to a solution ... depending on what exactly is causing the problem

**Comment by ian-lin-PG** [comment]
Further investigation into my phone found that it does more redirects than necessary in most routes. In the welcome page in particular it does redirects indefinitely.

**Comment by tomy-pg** [comment]
Client: 1.1.0 / Server: 1.3.5:

Issue no longer occurs on my Samsung s9 and Ian's One Plus.
