### ISSUE TITLE
Ensure localized strings show up in app onboarding flow

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#751]
The strings in the onboarding flow are already translated for use elsewhere in the app and/or the website. Either way they are stored in Weblate. If they are only used in the web site, they will not be available to the app until they are copied from the website part of weblate to the app part of weblate. 

ACs:
- [ ] Onboarding flow text is localized to all languages.

**Comment by rasmus-storjohann-PG** [comment]
Tested in
- [ ] English
- [ ] Arabic
- [ ] French
- [ ] Korean
- [ ] Punjabi
- [ ] Tagalog
- [ ] Chinese trad
- [ ]  Chinese sim

**Comment by jparlina** [comment]
@ArtiBPG Where can I find all the localized strings for onboarding so I can QA this on Staging V1.4.0?

**Comment by jparlina** [comment]
Tested on Staging V1.4.0, Server V1.3.9 on iOS 12.4.1:
Confirmed strings in the correct languages appear as per translations on Weblate:
- [x]  English
- [x]  French
- [x]  Tagalog
- [x]  Chinese Simplified
- [x]  Chinese Traditional

**Comment by jparlina** [comment]
For Korean all good except onboarding page 1 - see https://github.com/pg-irc/pathways-frontend/issues/817
