### ISSUE TITLE
Onboarding in Arabic: Invert swipe direction

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#759]
In Arabic, the onboarding flow swipe direction should be inverted.

ACs:
* Swipe right for next screen
* Swipe left for previous screen

To test: 
* Start the app
* Select Arabic
* Navigate to the help screen, scroll to the bottom of the page, hit the button to delete all data for in the app, this is so that the onboarding flow will come up when the app starts
* Exit the app
* Start the app to see the onboarding flow in Arabic
* Confirm the swipe direction to move through the onboarding pages is correct as per the ACs above

**Comment by jparlina** [comment]
Tested on Staging V1.4.0, server V1.3.9 on iOS:
Confirmed the onboarding in Arabic version: 
- Swipe LEFT for next screen
- Swipe RIGHT for previous screen
