### ISSUE TITLE
strings that need translations 

### ISSUE THREAD

**Issue by tomy-pg** [pg-irc/pathways-frontend#760]
As of staging release 1.2.0 / Server 1.3.6 here is a list of ui-strings that need to be translated for all non-English locales:

### Acceptance Criteria

Help and Support Page: 
- [ ] Do you want to delete all user data from this phone? This includes which answers are chosen in the questionnaire and which topics are bookmarked.
- [ ] Cancel 

![Screenshot_20190807-120712_Arrival Advisor](https://user-images.githubusercontent.com/47794846/62650668-3e734a80-b90c-11e9-821d-8f9140cc8ad8.jpg)

Side Menu:
- [ ] Terms of Use 

Error Messages:
- [ ] Go to Settings
- [ ] Try again
- [ ] Can't reach the internet
- [ ] Enable location services
- [ ] Check location services
- [ ] No related services found
- [ ] An error occured
- [ ] Services are not available offline. Please connect to the internet and try again.
- [ ]  To find services, please turn on Location Services for Arrival Advisor in Settings and try again.
- [ ]  It took too long finding your location. Setting your device's Location Services to “High Accuracy” can sometimes fix this problem.
- [ ] We’re having difficulty connecting to the server. Please try again later.
- [ ] Server error

**Comment by tomy-pg** [comment]
@ArtiBPG with the improvement of error messages  Issue #704, there have been a set of new strings introduced

**Comment by backciro** [comment]
I'm working on Italian Translation if it needed

**Comment by ArtiBPG** [comment]
@tomy-pg see #836 
Can we use this issue as a placeholder to track strings that need to be translated? only strings should all be in weblate. We dont have to list them in this issue.

**Comment by tomy-pg** [comment]
@ArtiBPG I like that idea. Works for me.
