### ISSUE TITLE
Keep font family styling consistent in markdown styles

### ISSUE THREAD

**Issue by bensinjin** [pg-irc/pathways-frontend#762]
AC:
- Call `getNormalFontStylesForOS()` (or the "bold" alternative if need be) in the styles for markdown in places where we need to set font family
- Remove any hardcoded font family style calls in the codebase that exist outside our `src/application/styles.ts` file and contain setting font family to the styles file.

**Comment by jparlina** [comment]
@cherrielam I think this was meant for you to QA? Thx

**Comment by cherrielam** [comment]
Refer to #703 for QA - 3. has passed
