### ISSUE TITLE
Create issue template for pathways-frontend and backend

### ISSUE THREAD

**Issue by tomy-pg** [pg-irc/pathways-frontend#765]
To ensure issues we create are consistent, create an issue template. 

AC: 
- [ ] Create basic template for both pathways-frontend and backend 

QA: 
- [ ]  Click new issue in front and and back end repos, verify that templates are being used for the new issues. Do not click create, no need to actually create eh issues.

**Comment by jparlina** [comment]
Tested: 
- [x] Clicked new issue in front and and back end repos, verified that templates were available to use

![Screen Shot 2019-09-16 at 3.27.02 PM.png](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/c4e746dc-70d9-45a9-b7bc-25b2e34c268f)

![Screen Shot 2019-09-16 at 3.27.30 PM.png](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/5e64022d-2b06-4f8b-b593-6b6a155b7469)
