### ISSUE TITLE
Language QA

### ISSUE THREAD

**Issue by tomy-pg** [pg-irc/pathways-frontend#767]
As of Staging release 1.2.0 / Server 1.3.6 there are some strings that need to be QA'd in all non-English languages. 

### Acceptance Criteria: 

Onboarding: 
- [x] Arrival Advisor is your go-to guide to getting settled in your new community.
- [x] Answer a few optional questions to get tailored recommendations for your needs.
- [x] Find service providers near you that can help you through your settlement journey.
- [x] Bookmark the topics that you find helpful for future use.
- [x] Start 

About page: 
- [x] The Arrival Advisor app is created by PeaceGeeks in partnership with settlement organizations in Metro Vancouver, as well as immigrants and refugees like you. This project is possible thanks to funding by the Province of British Columbia and Google.org Canada in partnership with LEAP | Pecaut Centre for Social Impact. Special thanks also goes to individual donors who make this project possible. Arrival Advisor is an open-source project. You can view it on <0>GitHub</0> and <1>contact us</1> to learn how you can support this project.

This is waiting on Arabic and Tagalog QA: 
- [x] Arrival Advisor is a free, multilingual, mobile app that helps immigrants and refugees in British Columbia, Canada find information and services to navigate their settlement journey. Arrival Advisor is offered in English, Arabic, Chinese Simplified, Chinese Traditional, French (Canadian), Korean, Punjabi, and Tagalog.

**Comment by ArtiBPG** [comment]
done for all languages and updated in weblate
