### ISSUE TITLE
Google Play policy for target audience - Update in Google Play console

### ISSUE THREAD

**Issue by ArtiBPG** [pg-irc/pathways-frontend#772]
Read the instructions on the blog post: https://android-developers.googleblog.com/2019/05/building-safer-google-play-for-kids.html
Follow the instructions and update the relevant section on the Play Console before Sept 1st 2019.
Add a note to do the release checklist to do this every time a new production version is released.

### Acceptance Criteria 
- The current version of AA on the Play Store is compliant with the latest Google Play policy update.

**Comment by rasmus-storjohann-PG** [comment]
I suggest to indicate our target audience as 18+. It's the simplest, and there is nothing in the app that is catering to younger users.

**Comment by rasmus-storjohann-PG** [comment]
Went to the google play console for the production app, then
* Click on Store Presence -> App content -> Target audience and content -> Start
* Selected 18 years and over, app store presence does not appeal to children, not designed for families.
* "App store appeals to children" is described as imagery of animals and you persons, etc., which we don't have. Google warns that if they review our store listing and disagree with our assessment, they will block our app. I don't see any reason why they would do this. These rules are designed to catch malicious apps that are deceptively targeting children.
