### ISSUE TITLE
ALL_Incorrect Categorizing

### ISSUE THREAD

**Issue by rankanglee** [pg-irc/pathways-frontend#773]
**Describe the bug**
Metric and imperial measure are under Money & Banking. 

**App version**
1.0.24

**To Reproduce**

**Expected behavior**
It should be moved to Settling in.

**Smartphone (please complete the following information):**
- Device: iPhone7
- OS: iOS 12.3.1

![KakaoTalk_Photo_2019-07-17-01-46-25](https://user-images.githubusercontent.com/47799302/61361141-c5189880-a834-11e9-89e6-03c4705e9d6d.jpeg)
![KakaoTalk_Photo_2019-07-17-01-46-33](https://user-images.githubusercontent.com/47799302/61361142-c5189880-a834-11e9-8674-9b0d83c52cd3.jpeg)

**Comment by ArtiBPG** [comment]
Its under both categories. closing.
