### ISSUE TITLE
Prompt users to turn on high accuracy mode using new Expo 33 functionalities 

### ISSUE THREAD

**Issue by tomy-pg** [pg-irc/pathways-frontend#774]
As of Expo 33, we can prompt Android user's to turn on High Accuracy Location. 
https://docs.expo.io/versions/latest/sdk/location/#locationwatchpositionasyncoptions-callback
https://github.com/expo/expo/pull/3273

This was not available prior the stable release of Expo 33, therefore we implemented a work around in Issue #548 . 

### Acceptance Criteria 
- [x] When Android users have location services set to "Device Only" or High Accuracy Mode is turned off they are prompted to enable High Accuracy  

### Steps for QA: To be done on **Android device**
1.  Go to settings and search for Location. Depending on the device you should find a setting along the lines of "Improve Accuracy"

![Screenshot_20190812-165500_Settings](https://user-images.githubusercontent.com/47794846/62906129-407d4500-bd22-11e9-98be-5b54052038da.jpg)

2. Turn off all of Improve Accuracy - in my device I turned off Wi-fi Scanning and Bluetooth scanning 
![Screenshot_20190812-165503_Settings](https://user-images.githubusercontent.com/47794846/62906145-4ecb6100-bd22-11e9-81d6-be5e5d0c28fd.jpg)

3. Open app and try to find related services of a topic 
4. You should be prompted to turn on High Accuracy

**Comment by ArtiBPG** [comment]
@tomy-pg how do we prompt user? just my adding a message or does it actually open settings to the page where they can set location to high accuracy?

**Comment by tomy-pg** [comment]
**getCurrentPositionAsync** - which is what we are currently using now automatically asks users to turn on location settings and improve accuracy as part of the Expo 33 upgrade. 

Below is the screenshot of what this looks like on an Android phone when location services are **turned on** but but High Accuracy is **disabled**. 

![Screenshot_20190813-104134](https://user-images.githubusercontent.com/47794846/62964058-16299700-bdb7-11e9-90f4-ed921631bc25.jpg)

**Comment by bensinjin** [comment]
As this is closely related to work I'm doing, I'm picking it up. A note from Tomy:
> the prompt code is already there. It’s now automatically part of getCurrentPostionAsync

**Comment by bensinjin** [comment]
This now happens automatically - I'm closing it as this stuff is now being addressed under #704
