### ISSUE TITLE
Notification to update the app

### ISSUE THREAD

**Issue by cherrielam** [pg-irc/pathways-frontend#779]
We would like to create a push notification and/or in-app notification (pop-up dialog) for users to update their app to the newest version. This notification should for when we have the release of new languages.

The notification should say something like (**sample text, TO BE REVIEWED** by @cherrielam ):

> **New version of Arrival Advisor is available**
> Click to update

Notification should look like: _Status Bar_ 

![image](https://user-images.githubusercontent.com/21990736/63306406-3b2e7600-c29f-11e9-96ec-c44a8f67a90f.png)

and _Dialog_

![image](https://user-images.githubusercontent.com/21990736/63306394-310c7780-c29f-11e9-9076-ff5034070ed6.png)

### Acceptance Criteria for Mid-November
- [ ] Send notifications to all users in 7 languages to get them to update the app.
- [ ] Notification should only show if user does not have the current version of the app.
- [ ] Dialog should have options to _Update_ and _Not Now_. If the user clicks _Not Now_, they should not see the dialog again.

### Acceptance criteria for notification infrastructure
- [ ] Notification infrastructure is set up for pushing other notifications to user.
- [ ] Content writer should able to author, schedule and send notifications 
- [ ] Content writer should be able to send notifications to staging and/or production without having to wait for a production build.

### Examples of types of notifications:
- Update the app
- Notify all users if new content is added
- Notify all users to review saved services (after saving services is implemented)

Out of scope (they will require us to eject from Expo)
- [ ] PM should be able to select users in a specific region to send notifications e.g. users in a specific country, at a specific time of day etc. and track events in google analytics.
- [ ] Should integrate with Google Analaytics for tracking.
- [ ] In-app messaging

This may be a useful thread: https://stackoverflow.com/questions/9849889/how-to-notify-users-about-an-android-app-update

### Steps for QA: 
1.  Test the 2 types of notifications in the staging app

**Comment by rasmus-storjohann-PG** [comment]
This is from an email from customer support at algolia. They have a little feedback thing in the email, we could do something similar?

![image](https://user-images.githubusercontent.com/32307781/63457941-b1012180-c406-11e9-8cc6-2738b1050252.png)
This is using https://www.helpscout.com/

**Comment by bensinjin** [comment]
**Thin thread push notification (PN) implementation process:**

_Preliminary steps:_

For this to work on Android we need to upload a Firebase Cloud Messaging server key to Expo so Expo can send notifications to Arrival Advisor.

_Implementation:_

1. Build a simple server side application responsible for storing PN tokens and sending PNs.
2. From Arrival Advisor POST the user's device push token to our PN server. This token is generated by Expo and unique per device.
3. Using the PN server POST notifications to `https://exp.host/--/api/v2/push/send`. The body of the request would contain the appropriate push token along with the message and other various properties.
4. (Nice to have to but probably necessary eventually) Build out the PN server to have a nice PN editing experience so non technical people can author and send out PNs.

Reference: https://docs.expo.io/versions/latest/guides/push-notifications/

**Comment by rasmus-storjohann-PG** [comment]
Breaking out sub stories:
* POST end point on our server for registering and storing tokens. Eventually tokens may be associated with locale and user accounts, but for now we just have a list of tokens with no associated information.
* client side functionality in the Arrival Advisor app to send the token to the endpoint
* Command line tool for sending notifications: a manage.py command that iterates over the tokens in the DB and calls POST on the expo end point with the content of the notification. POST to https://exp.host/--/api/v2/push/send. The body of the request contains the appropriate push token along with the message. Notifications in all locales are sent to all clients, and clients select which strings to show as per their currently selected locale. This is the simplest, we can make it more efficient later.
* Client side functionality to make the notification show up
* Django admin module for sending notifications through https://pathways-production.herokuapp.com/admin/ the with a more user friendly UX than the command line.

**Comment by bensinjin** [comment]
Also, mentioned in sprint planning, do some research on platforms like Firebase.

**Comment by bensinjin** [comment]
Here is an article discussing a variety of the available platforms for notification authoring: https://www.businessofapps.com/guide/push-notifications/.

**Comment by bensinjin** [comment]
So I've done more digging. It maybe be hard to integrate with third party services for managing notifications because of Expo discussed here: https://forums.expo.io/t/3rd-party-push-notification-service-for-non-detached-app/722. Basically Expo has no supported way for us to gain access to the required token needed for these third party services (we get an "Expo" token instead).

**Comment by rasmus-storjohann-PG** [comment]
Push tokens need to be managed as part of user data, see implications of that change and possible courses of action [here](https://docs.google.com/document/d/1gP_YCqSUTt0RQKpGQPeYfLe5uRnPCosrF8xz2_OK4j0/edit#)

**Comment by ArtiBPG** [comment]
@bensinjin Look into the time and risk involved in ejecting from Expo so we have enough information to decide if its worth doing.

**Comment by rasmus-storjohann-PG** [comment]
@ArtiBPG I think we can close out this issue
