### ISSUE TITLE
Create a debug version of Arrival Advisor on Testflight

### ISSUE THREAD

**Issue by ian-lin-PG** [pg-irc/pathways-frontend#780]
#636 is a bug that is only reproducible in standalone builds of Arrival Advisor. To make headway on this issue, we need to create a debug version of Arrival Advisor so we can make changes without affecting the stability of staging or production app. This debugging version of app could be used as an internal development build to test potentially breaking changes unsuitable for staging or production

### Acceptance Criteria 
- [x]  Have an new debug version of app running on an iPhone

### Steps for QA: 
1. download third app to iphone
2. move between LTR - RTL locales

**Comment by rasmus-storjohann-PG** [comment]
No QA required for this story
