### ISSUE TITLE
First slide of AR onboarding is not RTL 

### ISSUE THREAD

**Issue by tomy-pg** [pg-irc/pathways-frontend#785]
Describe the issue and expected behaviours. If this is a bug, describe the steps to reproduce the problem, what you observe, and what you expected to observe.

On the first slide of onboarding, while the locale is set to AR, the text is left-to-right, as opposed to being right-to-left. The text on the other slides are right-to-left as normal. 
See #790 

### Acceptance Criteria 
- [ ]  While using AR locale, all onboarding slide text are right-to-left

### Steps for QA: 
1. Delete all user data
2. Restart App
3. Select AR locale
4. Go through the onboarding slides and ensure all the text flow right-to-left

**Comment by bensinjin** [comment]
I played with this for a couple hours and could not get it to work properly. From what I can tell it's the fact that we start the sentence with "Arrival Advisor" that seems to throw things off. I've ensured this isn't a bug specific to the onboarding screen by rendering the sentence in a very simply component but we still see the problem. I also tried adding an additional space to the translated string but this doesn't appear to help. I have confirmed however that if we have some Arabic characters before the Arrival Advisor string this works as expected.

Maybe we can rephrase this?

**Comment by ArtiBPG** [comment]
1)Can we add a forced line break:

دليلك المفضل في رحلتك نحو Arrival Advisor

 .الاستقرار في مجتمعك الجديد
or like this in Weblate: https://screencast.com/t/gm1nER7b

2) the period at the send of the sentence seems to be behaving like LTR when selecting text. If that is correct, the sentence has RTL between LTR elements at the beginning and end of the sentence. Could this be causing the problem?

**Comment by bensinjin** [comment]
@ArtiBPG So I played around with newline characters. The best thing I was able to produce was:

<img width="295" alt="Screen Shot 2019-09-09 at 9 05 03 AM" src="https://user-images.githubusercontent.com/3228323/64547186-f4053500-d2e0-11e9-8eae-6c49be0b9c1b.png">

Which was produced using the following string (from jsx_strings.po):

`msgstr "Arrival Advisor \n دليلك المفضل في رحلتك نحو الاستقرار في مجتمعك الجديد."`

I wasn't able to get new line characters to render properly when inserted between the Arabic words as it appears they get ignored.

In terms of you're other updates I'd be interested in seeing how they appear in the app. @tomy-pg how do we get those changes?

**Comment by bensinjin** [comment]
@ArtiBPG this is what your changes look like:
<img width="290" alt="Screen Shot 2019-09-09 at 9 54 21 AM" src="https://user-images.githubusercontent.com/3228323/64550473-d8e9f380-d2e7-11e9-874a-742fce88e982.png">

Which was produced using the following string (from jsx_strings.po):
```
msgstr ""
"‎‎‏Arrival Advisor دليلك المفضل في رحلتك نحو\n"
" الاستقرار في مجتمعك الجديد.‏‏"
```
That was produced from your changes in weblate. It still doesn't seem to like the fact that the sentence begins with "Arrival Advisor".

**Comment by rasmus-storjohann-PG** [comment]
Can we do a slight rephrase so that it starts with something in Arabic. Something like "*The* Arrival Advisor..." or something?

**Comment by bensinjin** [comment]
> Can we do a slight rephrase so that it starts with something in Arabic. Something like "_The_ Arrival Advisor..." or something?

Yep! That was another suggestion that works.

**Comment by tomy-pg** [comment]
@DarwishMenna was kind enough to suggest and translate a version of this string that would work:
![Screenshot_20190909-125347_Expo](https://user-images.githubusercontent.com/47794846/64564181-d39ba180-d305-11e9-9629-b6613203f2ec.jpg)


The English translation to this string is: 
The application Arrival Advisor is your go-to guide to getting settled in your new community

**Comment by jparlina** [comment]
Tested on Staging V1.4.0, Server 1.3.9 on iOS 12.4.1:
Confirmed by cross-checking with weblate all AR onboarding texts are RTL

![IMG_2385.JPG](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/0cdca6d9-6eaa-4862-8e13-e431131e7fd2)

![IMG_2386.JPG](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/37084800-2a07-4be8-8464-710cdfda9997)

![IMG_2387.JPG](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/0861e83c-0912-44a7-9b05-536dfb606e4c)

![IMG_2388.JPG](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/2e1a591e-2893-4682-9675-ad8f0113ec8d)
