### ISSUE TITLE
Fix Recommendations dialog & flow

### ISSUE THREAD

**Issue by cherrielam** [pg-irc/pathways-frontend#789]
### Description of design change:
Fix the Recommendations dialog and flow as follows:
1. When the user closes the questionnaire and their answers give them new/updated recommendations, they should see a confirmation dialog that says: "New topics have been recommended based on your answers" with the Recommendation icon & a button to "See recommendations". (The screen should look as such: https://zpl.io/bLWB8wQ)

![Recommendation Dialog.png](https://images.zenhubusercontent.com/5823860ee40e5714b1700133/34793380-427d-44d6-8491-7c3e9e80af95)

Note: please increase the bottom padding from the existing dialog (should at least match the top padding)
![IMG_4425.PNG](https://images.zenhubusercontent.com/5823860ee40e5714b1700133/2bd6d03b-b153-4510-b6e1-361a7e55304c)

2. When the user closes the questionnaire and their answers have not changed, there should be no dialog. Remove the dialog that says "no new topics recommended based on your answers" ... it seems excessive and should be self evident to the user. 

### Rationale:
- Users are consistently confused by the dialog and want to click the recommended items that are listed within (which doesn't work).
- Showing the number of topics recommended has been shown through our user research to add no value to the user. They are not sure if a bigger or smaller number is good, in general they feel neutral about it.
- Adding "See recommendations" as the button clarifies to the user where they are going next. 
- The language in the dialog overall reinforces to the user what the result of the questionnaire is, without being complicated.

### Difficulty, impact:
|-- Difficulty: should be relatively easy as the dialog already exists and needs just a design change --| -- Impact: medium to high importance to user, since it currently causes confusion -- |

### Possible Roadblocks:
- although the text is similar to what already exists, it'll still need to be translated and QA'ed. We can consider simpler (existing) translations as alternate text, I'm open to your suggestions

**Comment by ArtiBPG** [comment]
I think we should remove the "No new topics recommended dialogue"
@cherrielam make final decision, update the spec or make a new issues.
Also include requirements for tracking in GA so we can answer the questions: 

- How many users click on "Go back to questionnaire"?
- Do people actually go back to the questionnaire and answer more questions?
- How many people actually see the "New topics recommended" dialogue?
- How many users close the questionnaire before completing?

**Comment by cherrielam** [comment]
Recommendations dialog looks great and works properly on iOS and Android. "No new recommended topics" dialog no longer exists/shows.

I have added the following issue to capture Arti's GA questions above:
https://github.com/pg-irc/pathways-frontend/issues/949
