### ISSUE TITLE
Chinese (Traditional) QA: Onboarding & About Page

### ISSUE THREAD

**Issue by jparlina** [pg-irc/pathways-frontend#791]
### **Onboarding 1**
![IMG_2184](https://user-images.githubusercontent.com/48343061/63536590-c474c100-c4c8-11e9-9c77-24fd674ed72c.JPG)

### **Onboarding 2**
![IMG_2185](https://user-images.githubusercontent.com/48343061/63536598-c8a0de80-c4c8-11e9-9c3e-cdc01134e985.JPG)

### **Onboarding 3**
![IMG_2186](https://user-images.githubusercontent.com/48343061/63536604-cb9bcf00-c4c8-11e9-9696-d82365eb2c55.JPG)

### **Onboarding 4**
![IMG_2187](https://user-images.githubusercontent.com/48343061/63536609-cdfe2900-c4c8-11e9-83cc-8f7e8f0cd6fe.JPG)

### **About Page 1**
![IMG_2188](https://user-images.githubusercontent.com/48343061/63536617-d22a4680-c4c8-11e9-8d6e-e0222e54f042.JPG)

### **About Page 2**
![IMG_2189](https://user-images.githubusercontent.com/48343061/63536629-d7879100-c4c8-11e9-9ef6-684514b5ebb9.JPG)

**Comment by ian-lin-PG** [comment]
Confirm new string is in staging.
