### ISSUE TITLE
Chinese (Simplified) QA: Onboarding & About Page

### ISSUE THREAD

**Issue by jparlina** [pg-irc/pathways-frontend#792]
### **Onboarding 1**
![IMG_2170](https://user-images.githubusercontent.com/48343061/63536050-ab1f4500-c4c7-11e9-9af2-61d9bda477e5.JPG)

### **Onboarding 2**
![IMG_2171](https://user-images.githubusercontent.com/48343061/63536051-ab1f4500-c4c7-11e9-86be-9034f627c107.JPG)

### **Onboarding 3**
![IMG_2172](https://user-images.githubusercontent.com/48343061/63536052-ab1f4500-c4c7-11e9-9a7b-8139ebb11a7e.JPG)

### **Onboarding 4**
![IMG_2173](https://user-images.githubusercontent.com/48343061/63536053-ab1f4500-c4c7-11e9-9af1-a34572e67215.JPG)

### **About Page 1**
![IMG_2174](https://user-images.githubusercontent.com/48343061/63536054-ab1f4500-c4c7-11e9-986a-53444e4d2a5d.JPG)

### **About Page 2**
![IMG_2175](https://user-images.githubusercontent.com/48343061/63536055-ab1f4500-c4c7-11e9-88b0-a7f28d19c99b.JPG)

**Comment by ian-lin-PG** [comment]
New string are present in staging.
