### ISSUE TITLE
Missing app strings from August 2019 and Partial Localization

### ISSUE THREAD

**Issue by tomy-pg** [pg-irc/pathways-frontend#805]
There are some missing app strings that need to be added to Weblate / pathways-frontend s that are needed prior to our production release:

All locales need to include: 
- [x] Do you want to delete all user data from this phone? This includes which answers are chosen in the questionnaire and which topics are bookmarked.
- [x] CANCEL
- [x] Delete user data
- [x] Delete all user data 

@ArtiBPG The string "No services to show" needs to be translated as well. 

### Acceptance Criteria 
- [x] Each locale has all of the above strings translated

**Comment by ArtiBPG** [comment]
"No services to show" will be translated for Oct release along with any other new/updated strings.

**Comment by ArtiBPG** [comment]
@jparlina we should QA the localized screens internally once translations have been added to staging.

**Comment by jparlina** [comment]
@ian-lin-PG Please confirm the translations in the screenshots below for: 
- [ ] Chinese Simplified
- [ ] Chinese Traditional

![IMG_2457.jpg](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/7b7960e9-d453-4b75-9a94-c1fbae6b04a2)

![IMG_2462.jpg](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/a242a2b9-60af-404c-9ae2-06428f4d3abd)

![IMG_2463.jpg](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/cb678352-c3d7-4cc4-a3ba-3fa7000bee5d)

**Comment by ian-lin-PG** [comment]
@jparlina can confirm the translation are correct.

**Comment by ArtiBPG** [comment]
reviewed other languages. Arabic had an alignment issue that can we fixed for the October release.
