### ISSUE TITLE
Copy for Each Release

### ISSUE THREAD

**Issue by tomy-pg** [pg-irc/pathways-frontend#807]
This issue is used to keep track of the release notes/_what's new_ copy we are providing users when we release an update to our production build. 

@cherrielam - each store has the following character limit for the _What's New Section:_
Apple Store: 4000
Google Play Store: 500

This is how our workflow looks like:

Step 1:  Cherrie creates and adds _What's New_ copy to [Release Notes report]( https://github.com/pg-irc/pathways-frontend/projects#workspaces/arrival-advisor-5977956f40fbe90e67bb4155/reports/release?release=5d24f9d79c24773a1026b351)
Step 2: Arti green lights the copy or asks Cherrie for revision
Step 3: Tomy adds Release notes to `.pot` for Release Notes component on Weblate. 
Step 4. Arti has the strings translated.
Step 5: During the end of the release process, Tomy adds the copy to each store. 

## For the September release
There should be two different versions of the _What New Section_ as we are releasing 5 languages that were not a part of the March 2019 production release 

### Acceptance Criteria for Cherrie: 
- [ ] En, Fr and AR _What's New_ notes contain description of major changes from March release
- [ ] KO, PA, TL, zh_CN and zh_TW _What's New_ notes are written as an introduction to the app

## Acceptance Criteria for Arti: 
- [ ] Arti QA's the _What's New_ copy for each locale. 

### Acceptance Criteria for Tomy 
- [ ] _What's New_ copy is placed in Weblate
- [ ] Each sentence should be an individual msgid in PO file
- [ ] Document process in Release process document

**Comment by cherrielam** [comment]
Release notes copy has now been added to the bottom of: 
https://github.com/pg-irc/pathways-frontend/issues#workspaces/arrival-advisor-5977956f40fbe90e67bb4155/reports/release?release=5d24f9d79c24773a1026b351

Tagging @ArtiBPG for review & feedback.

**Comment by ArtiBPG** [comment]
strings in release_notes component in weblate translated and committed

**Comment by tomy-pg** [comment]
Verifying that the release notes are translated. Only thing left is to add these translations to the app stores when the release is made.
