### ISSUE TITLE
Styling polish on Services Listing 

### ISSUE THREAD

**Issue by cherrielam** [pg-irc/pathways-frontend#811]
There are a few remaining styling issues, primarily regarding the Services Listing page.

#### 1. Alignment of text on services listing page
All of the text (header of Services Listing page, Title of the service, Description of the service, and Read More text) should be aligned on the left side (and vice versa right side for RTL). Currently there is a weird indentation at the start of the Description and the Read More text is more right indented than the rest of the text. Refer to Figure 1 below.

#### 2a. Space needed between "Web:" and the website URL.
There needs to be a space after the colon after "Web" for English, French, Arabic, Korean, Punjabi, Tagalog. Refer to Figure 1a-f.

#### 2b. Remove extra space(s) before website URL or email address.
- Remove one space before website URL for Chinese Simplified (see Figure 1g) and Chinese Traditional (Figure 1h)
- Remove 2 spaces before email address for Chinese Simplified (see Figure 1g)

#### 3. Space between "Read More" and down arrow should be reduced.
Looks like the space between the words "Read More" and the down arrow in the component got expanded between the different app versions. Can we reduce it to match the old version of the app? Refer to Figure 1 vs. Figure 2.

#### 4. Empty state "No related services" and "No topics to show" text should be in Avenir font.
Currently shows in the default device font. Refer to Figure 3.

#### 6. Links on Topic Detail page should be entirely in #00858F "teal".
There is an underlined space between the URL and the icon that is black instead of teal.

#### FIGURE 1a: 
<img width="250" src="https://user-images.githubusercontent.com/21990736/64996372-9f3e5d00-d892-11e9-9256-b0c08c1dacfc.PNG">

#### FIGURE 1b: 
![Screen Shot 2019-10-02 at 5.22.08 PM.png](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/78af933b-78a0-4d20-9892-809ecc545562)

#### FIGURE 1c: 
![Screen Shot 2019-10-02 at 4.40.59 PM.png](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/34f0bcf2-0ddd-4d3f-a9a3-d6f2c3b8b38d)

#### FIGURE 1d: 
![Screen Shot 2019-10-02 at 4.43.31 PM.png](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/3ca1ddff-91b5-445b-8efa-1921a28dbbaf)

#### FIGURE 1e: 
![Screen Shot 2019-10-02 at 5.01.39 PM.png](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/501fe2b7-0384-4a1e-a853-e8f5dc25eb4c)

#### FIGURE 1f: 
![Screen Shot 2019-10-02 at 5.00.59 PM.png](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/a41db0dd-bb83-4702-97d0-82bcb49ddfd7)

#### FIGURE 1g: 
![Screen Shot 2019-10-02 at 5.05.33 PM.png](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/7332b621-ddac-497e-b9e6-c4de50a256aa)

#### FIGURE 1h: 
![Screen Shot 2019-10-02 at 5.12.45 PM.png](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/a2542286-b2fa-43d3-8525-630430aa5d1c)

#### FIGURE 2:
<img width="250" src="https://user-images.githubusercontent.com/21990736/65000331-09a9ca00-d8a0-11e9-8071-6a651492ccf7.PNG">

#### FIGURE 3:
<img width="250" src="https://user-images.githubusercontent.com/21990736/65000419-61483580-d8a0-11e9-86f1-1e1c3d92ae29.PNG">

### Acceptance Criteria 
- [ ]  Services listing text is all aligned on the left side
- [ ]  There is a space between "Web:" and the URL for all languages
- [ ]  There is one space between "Email:" and the email address for Chinese Simplified
- [ ]  There is no space between the "Web" label and colon (:) for French
- [ ]  There is no space between the "Email" label and colon (:) for French
- [ ]  The space between "Read More" and the down arrow in the _Read More component_ is reduced to match the old app version.
- [ ]  Empty state "No related services" and "No topics to show" text should be in Avenir font.
- [ ]  Links on Services Listing page are in teal #00858F
- [ ]  Links on topic detail: Underlined space between URL and the icon is in teal, not black

### Steps for QA: 
1.

**Comment by cherrielam** [comment]
Assigning to @ArtiBPG to assign to someone appropriately and add deadline. The dev can add steps for QA. Thanks!

**Comment by tomy-pg** [comment]
I think this issue could either be closed or updated because we are working off of different services listing mocks. What do you think @cherrielam and @ArtiBPG ?

**Comment by cherrielam** [comment]
IMO probably closed because this is being replaced by a smaller Services card and the Services detail, right?

**Comment by tomy-pg** [comment]
Agreed. Closing this issue.
