### ISSUE TITLE
Left align service name and service description in Arabic service listings

### ISSUE THREAD

**Issue by ian-lin-PG** [pg-irc/pathways-frontend#812]
Describe the issue and expected behaviours. 

### Acceptance Criteria 
- [x]  The non-localized service name and service description is left aligned in Arabic service listing

### Steps for QA: 
1. Switch to Arabic
2. Click on the first topic relating to SIN cards
3. Click on find related services with the map icon
4. Service Canada the service name is left aligned
5. Service Canada description is also left aligned

**Comment by ian-lin-PG** [comment]
![image](https://user-images.githubusercontent.com/52009863/65066503-52619180-d939-11e9-8e59-446d81b3193e.png)

**Comment by ian-lin-PG** [comment]
@ArtiBPG @cherrielam New partial localization:
![image](https://user-images.githubusercontent.com/52009863/65082845-cd3ba400-d95b-11e9-84c2-a1dfaf34afac.png)

**Comment by ian-lin-PG** [comment]
Got blessing from @ArtiBPG  and @cherrielam.

**Comment by jparlina** [comment]
Tested on Staging V1.5.0 server V1.3.10 on iOS 13 (iPhone 7 plus):

Completed steps for QA:
- [x] Switch to Arabic
- [x] Click on the first topic relating to SIN cards
- [x] Click on find related services with the map icon
- [x] Service Canada the service name is left aligned
- [x] Service Canada description is also left aligned

![IMG_2454](https://user-images.githubusercontent.com/48343061/65349951-7b805d00-db99-11e9-8189-04de062ea5f9.jpg)


![IMG_2455](https://user-images.githubusercontent.com/48343061/65349978-86d38880-db99-11e9-96d9-1ef82ad16236.jpg)
