### ISSUE TITLE
The client sends notification token to server

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#813]
### Acceptance Criteria 
- [x]  As part of the app boot process, and subject to the user giving the necessary permissions to the app, the app sends the push notification token to the server. See pg-irc/pathways-backend/issues/441 for details on the end point to use.

### Steps for QA: 
1.  Start the app, verify that the token is saved to the database.

**Comment by ian-lin-PG** [comment]
To close this issue, please sending a notification to Android devices and see that it uses the new notification icons:
![image](https://user-images.githubusercontent.com/52009863/69827053-a5be4e80-11ca-11ea-91a8-d68770415659.png)

**Comment by rasmus-storjohann-PG** [comment]
This has been confirmed to be working
