### ISSUE TITLE
Notifications UX

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#814]
### Acceptance Criteria 
- [ ]  Notifications appear in the app as per mocks below.
- [ ]  Notifications contains a call to action to upgrade the app to the next version, should open the app store on the app's page.
- [ ] Details of flow from the lock screen TBD, how will this work with the user unlocking the phone...

![image](https://user-images.githubusercontent.com/32307781/65072178-319f3900-d945-11e9-93e6-84436a310e5e.png)
![image](https://user-images.githubusercontent.com/32307781/65072192-3c59ce00-d945-11e9-9963-7f980873c011.png)

**Comment by jparlina** [comment]
Tested on Android and iPhone:
1. User closed the app > user opened the app > notification was sent > user received notification (PASSED)
2. User changed language > closed the app > opened the app > notification was sent > user received notification (PASSED)

Note: If user set Notifications setting on iPhone to "Show Previews - Never", then when user clicks on the notification (without preview of the content), it just opens the app, but user won't know the content of the notification. - see issue #932
