### ISSUE TITLE
Style list of tasks in my plan

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#82]
AC: Style My Plan header and tasks in My Plan as follows:

![image](https://user-images.githubusercontent.com/32307781/40735198-6c854022-63ef-11e8-85fa-cd93ea56904b.png)

Out of scope: Do not build any new functionality, such as event handling, as part of this story.

Heads up for future changes, all of this is out of scope for this task and for your information only: The TASKS I PLAN TO DO string will be replaced with a different string for tasks in different states. The star icon (which is not a button) represents tasks that are recommended, it will not appear on tasks that are not recommended. The eight dots will be used as a handle for dragging tasks to reorder them.

From page 13 of our current mocks, for context this is the whole screen:

![image](https://user-images.githubusercontent.com/32307781/40735240-86457932-63ef-11e8-971e-3d99e4698dbb.png)

**Comment by bensinjin** [comment]
Ticket #83 is now included in this work.

**Comment by rasmus-storjohann-PG** [comment]
BUG
* In the task detail page, in RTL, the Information and Find Services tabs are shown in the same order as in LTR.

**Comment by bensinjin** [comment]
https://github.com/GeekyAnts/NativeBase/issues/518 discusses this

**Comment by rasmus-storjohann-PG** [comment]
Can we make this manually, i.e. in RTL create the Services tab first so it ends up on the left, and open the Task tab explicitly?

**Comment by bensinjin** [comment]
Unfortunately it's not that simple it's actually the RTL setting that breaks how the tabs work.  The ability to explicitly open a tab doesn't work properly in RTL and we get other funny issues like tabs rendering completely empty.

**Comment by rasmus-storjohann-PG** [comment]
Closing this story, tracking bug in #135
