### ISSUE TITLE
Start button on Onboarding screen does not work

### ISSUE THREAD

**Issue by ArtiBPG** [pg-irc/pathways-frontend#822]
Start button on Onboarding screen does not work. Does not advance to the next screen, app home screen on clicking.
Happens only on Android (8.0.0 and 6.0.1 were tested) , works as expected on iPhone.
The button works if you click repeatedly really fast more than 7-10 times.

### Acceptance Criteria 
- [x]  Start button, when clicked should take the user to the app home screen.

### Steps for QA: 
1.  click start button once. It should take you to the home screen.

![Screenshot_20190919-112459_Arrival Advisor.jpg](https://images.zenhubusercontent.com/5c0b0754be31d617e4c1dea1/e30d0882-69ff-4f89-b82a-8fcaa08d8e0c)

**Comment by tomy-pg** [comment]
Staging version: Client 1.6.0, Server 1.3.11

PASS.

Device: Samsung S9.
