### ISSUE TITLE
Remaining strings need translation

### ISSUE THREAD

**Issue by tomy-pg** [pg-irc/pathways-frontend#825]
Here are the remaining strings that need to be translated for all locales for the release:
- [ ] An error occurred
- [ ] Can’t reach the internet
- [ ] Check location services
- [ ] Enable location services
- [ ] Go to Settings
- [ ] It took too long finding your location.
- [ ] It took too long finding your location. Setting your device’s Location Services to “High Accuracy” can sometimes fix this problem.
- [ ] Server error
- [ ] Services are not available offline. Please connect to the internet and try again.
- [ ] To find services, please turn on Location Services for Arrival Advisor in Settings and try again.
- [ ] Try again
- [ ] We’re having difficulty connecting to the server. Please try again later.
- [ ] No services to show

These strings are already on Weblate in the jsx_strings component. All translators need to do is go into a locale and click on:
![Screen Shot 2019-09-20 at 12 24 08 PM](https://user-images.githubusercontent.com/47794846/65353274-90f98500-dba1-11e9-8621-813e48a1b3cd.png)

@ArtiBPG will have these strings translated
@tomy-pg will add these strings to the client
 
### Acceptance Criteria 
- [ ]  No services to show is translated in all locales

### Steps for QA: 
1.  Switch between locales and click on a topic that does not have recommended services, IE: Opening a bank account
2. See to it that No services to show is translated.

**Comment by ArtiBPG** [comment]
All strings in jsx_strings and release_notes in Weblate translated and committed.

**Comment by tomy-pg** [comment]
The localized string was added to Weblate 5 days prior to the release and merged into _master_. The tag 1.6.0 seems to be off-sync which is why we currently do not see this change. This also affects Issue #826
