### ISSUE TITLE
Arabic QA: "Delete All Users Data"

### ISSUE THREAD

**Issue by jparlina** [pg-irc/pathways-frontend#829]
Confirm the following texts are correctly translated into Arabic (see screenshots in English and Arabic below):
- [ ] Do you want to delete all user data from this phone? This includes which answers are chosen in the questionnaire and which topics are bookmarked.
- [ ] Delete all user data
- [ ] CANCEL

Also confirm whether
- [ ] the line breaks make sense

If not, make your suggestions in the comment.

![IMG_2457](https://user-images.githubusercontent.com/48343061/65353781-d23e6480-dba2-11e9-8e5b-c0b0dc4123b4.jpg)

![IMG_2456](https://user-images.githubusercontent.com/48343061/65353785-d66a8200-dba2-11e9-90b3-4ab34cfba202.jpg)

**Comment by ArtiBPG** [comment]
During staging QA, check if updated translation appears in the app

**Comment by ArtiBPG** [comment]
Translation is fine but layout is different in 1.3.1.1.
Not a deal breaker for production but it should be fixed for the next release.
![Screenshot_20190927-132240_Arrival Advisor](https://user-images.githubusercontent.com/44411551/65799945-28268580-e12a-11e9-895b-12fba80f65f3.jpg)

**Comment by tomy-pg** [comment]
We might need to hack this with adding spaces prior to the string because React Native Alert component headings cannot be moved using CSS.

**Comment by rasmus-storjohann-PG** [comment]
Closing this as won't fix, we can't change the style specifically in Ar.
