### ISSUE TITLE
Style list of recommended tasks

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#83]
ACs: Style recommended tasks as follows:

![image](https://user-images.githubusercontent.com/32307781/40736609-5ad618a2-63f3-11e8-9daf-dc48235816c4.png)

In scope: Hook up the "+" button to adding the task to My Plan.

Out of scope: the "Important for all newcomers to BC" string and the (i) button. Any logic related to recommendation, so all tasks will show the star icon for now. Any functionality hooked up to the ">" button.

Heads up for future changes, all of this is out of scope for this task and for your information only: The star icon (which is not a button) indicates that the tasks are recommended, which for the recommended list will always be true for all the items in the list. However, I would like the task list item components to be the same no matter what list they are on, so the star icon should be backed by the state on the task that it is recommended rather than by the task being in the recommended task list. If that makes no sense, ask me.

For context, this is the whole screen:

![screenshot from 2018-05-30 10-22-46](https://user-images.githubusercontent.com/32307781/40736651-726825aa-63f3-11e8-9ccb-8670b9e633af.png)

**Comment by bensinjin** [comment]
Merged into #82.
