### ISSUE TITLE
Korean QA: "Delete All User Data"

### ISSUE THREAD

**Issue by jparlina** [pg-irc/pathways-frontend#830]
Confirm the following texts are correctly translated into Korean (see screenshots in English and Korean below):
- [ ] Do you want to delete all user data from this phone? This includes which answers are chosen in the questionnaire and which topics are bookmarked.
- [ ] Delete all user data
- [ ] CANCEL

Also confirm whether
- [ ] the line breaks make sense
If not, make your suggestions in the comment. 

![IMG_2457](https://user-images.githubusercontent.com/48343061/65353621-74118180-dba2-11e9-853e-bafe670af74e.jpg)

![IMG_2459](https://user-images.githubusercontent.com/48343061/65353647-8095da00-dba2-11e9-9839-34729c22baef.jpg)

**Comment by ian-lin-PG** [comment]
Steps for staging QA:
1. Go to categories
2. Got to Education
3. Go to Costs and financial help for post-secondary school
4. Change to Korean
5. Check the last paragraph matches the next image.

**Comment by ian-lin-PG** [comment]
Steps for staging QA:
1. Go to categories
2. Got to Health Care
3. Go to Family doctors, walk-in clinics, and public health units
4. Change to Korean
5. Check the last paragraph matches the next image.
