### ISSUE TITLE
No Error Message on iOS when in Airplane Mode or Offline

### ISSUE THREAD

**Issue by jparlina** [pg-irc/pathways-frontend#832]
Tested on Staging V1.4.0, Server V1.3.9 on iOS 12.4.1, iPhone 7 plus:

When phone is in airplane mode or offline - FAILED on iPhone (no error message - see screenshot below); no issue on Android

![IMG2434.png](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/598e238e-e32c-45e6-8838-063863a13b27)

### Acceptance Criteria 
- [ ]  When phone is offline or airplane mode, you should see this message: 
![Offline](https://user-images.githubusercontent.com/21990736/62093043-92a36e00-b22c-11e9-9b40-7dcd04d2c63c.png)
- https://zpl.io/bJW1A7r 

### Steps for QA: 
1.  Turn off your cellular data or set your phone in airplane mode
2. Select a topic
3. Click "Find related services near me"
4. You should see the error message as shown in screenshot above

**Comment by tomy-pg** [comment]
Staging version 1.21.0:
PASSES QA.
