### ISSUE TITLE
App store screen shots in more languages

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#835]
Currently we have screenshots in English and French only. These screenshots appear in the google and apple stores. They are stored [here](https://drive.google.com/drive/folders/1_WXmFw4dtCcwrky3hXkJlKAySBuSRAPc). It would be nice to have them in more languages.

### Acceptance Criteria 
- [ ]  When seeing the app's listing in the google and apple stores, see screenshots of the app in most/all supported locales.

**Comment by aron-chen-pg** [comment]
I have made all the screenshots in different languages. I also created the updated screens in English and French where the multiple languages are shown in the hamburger menu. 
I used Google Translate to make the language change, so we will have to have people review the copy before uploading them on to the app store.

**Comment by ArtiBPG** [comment]
@aron-chen-pg Please use these translations
[AA screenshot translations.xlsx](https://github.com/pg-irc/pathways-frontend/files/3849224/AA.screenshot.translations.xlsx)

**Comment by aron-chen-pg** [comment]
@ArtiBPG I have updated all the screenshots :) https://drive.google.com/drive/folders/1o1pYvZMOATjemsK-IBsU2XLUjbnGtLKr?usp=sharing

**Comment by rasmus-storjohann-PG** [comment]
@ArtiBPG  Do we have a way to track this so we don't forget to update the store next time we do a public release?

**Comment by ArtiBPG** [comment]
@rasmus-storjohann-PG can you track it in your release checklist?

**Comment by tomy-pg** [comment]
This is what we did last time: https://github.com/PeaceGeeksSociety/content/issues/717

**Comment by tomy-pg** [comment]
References this issue in https://github.com/PeaceGeeksSociety/content/issues/733 so we do not forget.
