### ISSUE TITLE
Localize app subtitle in Apple store

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#836]
The subtitle is currently only in English. Note that the upper length limit on the string is pretty short.

ACs:
- [ ] The app subtitle appears localized in the apple store

![image](https://user-images.githubusercontent.com/32307781/65903655-a45eda00-e371-11e9-9eee-71bbea6e0156.png)

**Comment by ArtiBPG** [comment]
closed as it has been combined with #760
