### ISSUE TITLE
Render search results

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#839]
[User Stories](https://github.com/pg-irc/pathways-frontend/issues/841)

ACs:
- [x] Service list with search results, [mocks here](https://app.zeplin.io/project/5bc7bfa42e72260acb03aa86/screen/5d929aa5bb3cda171b4e0de9), but with simplifications: 
- [x] Use existing `ServiceListComponent` but populated with data from Algolia. This means that the details of how the services appear in the list will match the current service listing in the app, not the service listing in the mock. 
- [x] Build plumbing to make data from our REST end point and from Algolia into the same client side data format Service in `/pathways-frontend/src/stores/services/types.ts`.

**Comment by ian-lin-PG** [comment]
Adding a screen of current Search UI for comparison
![Screenshot_20191004-101824](https://user-images.githubusercontent.com/52009863/66226836-a33eed00-e690-11e9-9c0c-06b3dbf7711a.jpg)

**Comment by ian-lin-PG** [comment]
Deviation from the mocks:
1. Remove the 'Service only in English' component as it's not yet tested.
2. Remove Organization from the services for now

**Comment by ian-lin-PG** [comment]
Adding android then iOS screenshots for @cherrie to compare old and new UI:
android:
![image](https://user-images.githubusercontent.com/52009863/67246883-981be900-f414-11e9-8f1a-0f4d5f416372.png)
iOS:
![image](https://user-images.githubusercontent.com/52009863/67246894-a2d67e00-f414-11e9-8f32-cfd2bca1053b.png)

**Comment by ArtiBPG** [comment]
@cherrielam test on Android and iOS

**Comment by tomy-pg** [comment]
@ArtiBPG I don't think @cherrielam needs to QA this issue since the service listing from search has deviated from the mocks. It would make more sense for her to QA once the service listing from search has been developed to match the mocks.

**Comment by tomy-pg** [comment]
QA'd on Staging version 1.14.0:

PASS.
- Services from search match topic services listing. 
- Plumbing also exists to turn Algolia data into same data type on client.
