### ISSUE TITLE
Search for BC211 service from the client

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#84]
AC: A button in the Explore pane issues a hard-coded REST request to the server for some services using the search API, and displays a simple list of the resulting records. The point of this story is to get the infrastructure for REST calls in place.

**Comment by tnightingale** [comment]
Mock of how services should look (not AC):
![task detail-window-map 3](https://user-images.githubusercontent.com/169635/42001550-293b9ac4-7a19-11e8-9b93-5120e50b9302.jpg)
