### ISSUE TITLE
Bookmark services

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#840]
As a user who has found a relevant service via the search feature, I want to be able to save the service information so that I can contact or visit the service at a later time.

ACs:
- [x] Build plumbing to persist a service to permanent storage on the client. Follow existing pattern for persistence of chosen answers in `selectUserDataForLocalPersistence()`. Services will be stored in their entirety (not just the ids), so that will be different from the current patterns. Bookmarked services will also be loaded from local memory at app startup, see `UserDataPersistence.loadSuccess()` and how `LOAD_USER_DATA_SUCCESS` is used in several reducers to take data from persistent storage and place it in their respective stores.
- [x] Bookmark button appears on service list item component. Button is filled if the service is currently bookmarked, outline if not, consistent with topic bookmarks. Clicking the button causes the service to be added to or removed from local persistent storage. This is done in a saga that is watching for the action to change the bookmarked state of any service, see `watchUserStateChangesToSaveUserData()`.

Steps for QA:
Services can be bookmarked from topic service list and search service list: 
1. Generate a list of services by topic
2. Click on the bookmark icon
3. Navigate to the bookmarks page and click on the Services tab
- [x] Ensure the service(s) you bookmarked are there

Bookmarked services are available in the app even while the device is offline:
1.  Set the phone to airplane mode
2. Shut down the app 
3. Restart the app
4. Go to the bookmarks page and click on the Services tab
- [x] Ensure that the bookmarked service appears with all its data.

Scope:
* Bookmarking of organizations is OUT OF SCOPE. (Some of the mocks imply that this is a thing.)

**Comment by ArtiBPG** [comment]
@jparlina - tested on Android, please test on iPhone

**Comment by jparlina** [comment]
Tested on Staging V 1.15.0, Server V1.3.21 on iPhone 7s from the HiVE - PASSED

Services can be bookmarked from topic service list and search service list:
1. - Generate a list of services by topic
2. - Click on the bookmark icon
3. - Navigate to the bookmarks page and click on the Services tab
- [x] Ensure the service(s) you bookmarked are there

Bookmarked services are available in the app even while the device is offline:
1. Set the phone to airplane mode
2. Shut down the app
3. Restart the app
4. Go to the bookmarks page and click on the Services tab
- [x] Ensure that the bookmarked service appears with all its data.
