### ISSUE TITLE
Fix "Web" prefix on URLs in NCG content

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#853]
Having all URLs prefixed with "Web: " in the app looks weird. See https://github.com/pg-irc/pathways-frontend/issues/526 for the issue that introduced this. Engage with the design department to figure out a solution.

### Acceptance Criteria 
- [x]  Remove "Web:" prefix on all web addresses in the NCG content
- [x]  Remove "Email:" prefix on all email addresses in the NCG content

**Comment by jparlina** [comment]
Tested on Staging V1.8.0, Server V1.3.14 using iPhone 7 Plus iOS 13.2 at the HiVE:

Acceptance Criteria:
- [x] Remove "Web:" prefix on all web addresses in the NCG content
- [x] Remove "Email:" prefix on all email addresses in the NCG content

Tested topics:
- [x] Contact workers at your local settlement agency - prefix on all web addresses were removed
- [x] Community: Volunteering - prefix on all web addresses and email were removed

Screenshots below for topic "Where to go for help about housing":

Figure 1 (BEFORE): 
![Production V1.7.0.jpg](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/294bca6b-84a1-4aad-a568-b1302e8dba13)

Figure 2 (AFTER):
![Staging V1.8.0.jpg](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/7850d097-7d8e-4d9d-95c8-a21ee8660448)
