### ISSUE TITLE
"No services to show" behaviour should accurately reflect the page state

### ISSUE THREAD

**Issue by cherrielam** [pg-irc/pathways-frontend#860]
We would like better differentiation between loading and empty state for services listing page:

1. **Loading State** - We'd like to add a Loading State to the services page for when the user is initially loading the page and no services are shown *yet*. In the loading state, the page should be **empty**, with the spinning indication that it is loading. It should not display "No services to show".
In the future, it may be nice to add a loading state page: see https://github.com/pg-irc/pathways-frontend/issues/704#issuecomment-520976207
![IMG_5466.jpg](https://images.zenhubusercontent.com/5823860ee40e5714b1700133/ea757727-a890-46b2-b46e-a506a44b9e7f)

2. **Empty State** - When the service actually has no services to show, the Empty State should be more obvious. We could either use the empty state (already designed) or make the current text visually more prominent (eg. black font colour).

### Rationale:
1. When loading services, users shouldn't see the tag "no services to show" as **it is sending a false message to them**. Especially when there are instances of slow load speed, it causes users to immediately leave the page thinking that there are no services for this topic, when in fact they are just loading.

2. Users should be properly informed instead of having to look closely for the information.

### Difficulty, impact:
|--(technical difficulty = ??)--| -- high user importance (must have) -- |

### Possible Roadblocks:
Technical difficulty - see https://github.com/pg-irc/pathways-frontend/issues/704#issuecomment-520976207 - @bensinjin had started to look into whether this is possible

### More Visual Reference:
https://drive.google.com/open?id=1mwsjFbQZE6A8clfhkMumwT3WoE32KM3s

### Acceptance Criteria
- [ ] The loading state page exists and shows up when services listing is loading 
- [ ] The empty state page shows up when there are no services available, and is prominent so the user can tell

### Steps for QA
1. Go to topics and press Find related services near me
When loading services: 
- [ ] Ensure when services are loading that the loading screen state is shown on screen
If there are no related services for the topic: 
- [ ] Ensure that when a service is not populated that the empty screen state is shown
If there are related services for the topic:
- [ ] Ensure that you see the services listed

**Comment by tomy-pg** [comment]
Issue #864 was also addressed as part of this issue.

**Comment by cherrielam** [comment]
Did a quick QA. The loading state page needs an added indicator to tell the user that the page is still loading, otherwise the app looks broken.

### Problem
In a poor wi-fi situation, the services page will remain on the loading state for an extended period of time, but the user can't tell if it is still loading or just broken. **See [video of the behaviour here](https://drive.google.com/file/d/1r59uz0vtLWiQeCT943r3VRsYdKm1Nb_n/view?usp=sharing)**

- Because there is no loading animation, it appears to the user that this page is supposed to be this way... which just looks broken.
- Is this page supposed to time out at some point and just tell the user to check their network connection? (Not sure if this is necessary.)

### Recommendation
Add some kind of loading animation back to the loading state page. Perhaps a loading spinner, **see example of [LinkedIn](https://drive.google.com/open?id=19DqmNuupmZpeHL0AVf068jhh7GnSnSel))**. @tomy-pg had a question about two spinners: in the LinkedIn situation, when you drag down, you see [two spinners](https://drive.google.com/open?id=1T0LDbNwo-YBVHKHRCkWPKEUUV02IockJ). You will also see that LinkedIn and [Facebook](https://drive.google.com/open?id=1T0LDbNwo-YBVHKHRCkWPKEUUV02IockJ) both have a subtle screen animation that scrolls from left to right... not sure that this is necessary/possible but it is an alternative to the loading spinner and create a nice "loading" effect.

### Additional nice-to-have fixes:
- [There's a weird beige bar](https://drive.google.com/open?id=1hXlXWv2skVG3BSqMhm8jHCa_cSKLC0Lp) that shows up when dragging down for the spinner. Can that be removed, so the whole block is teal?

**Comment by tomy-pg** [comment]
In my PR for Issue #940 addresses this.
