### ISSUE TITLE
Remove arrow on Home page

### ISSUE THREAD

**Issue by cherrielam** [pg-irc/pathways-frontend#862]
Remove arrow on Home page (see image below)

![IMG_5411.jpg](https://images.zenhubusercontent.com/5823860ee40e5714b1700133/b1818040-8f4f-4584-96b9-e5287f098363)

### Rationale
The arrow doesn’t currently do anything

### Difficulty, impact:
|--(technical difficulty = easy?)--| -- high user importance (SHOULD have) -- |

### Acceptance Criteria:

- [ ]  Arrow on home page is removed

### Steps for QA

**Comment by ian-lin-PG** [comment]
Here is the iOS and android screenshots in that order:
![image](https://user-images.githubusercontent.com/52009863/69681079-c61ec980-1061-11ea-9cf8-25d126deeecc.png)
![image](https://user-images.githubusercontent.com/52009863/69681092-d636a900-1061-11ea-92b0-f2a4895f71ae.png)

**Comment by jparlina** [comment]
Tested on iPhone 7 Plus (iOS 13.2.3) - AA Staging V1.12.0, server V1.3.18:
confirmed Arrow on Home Page was removed 
![IMG_3706](https://user-images.githubusercontent.com/48343061/70285132-4a1c3400-177b-11ea-93d2-b3c495436ce6.PNG)

Tested on Nexus 5 (Android 6.0.1) - AA Staging V1.12.0, server V1.3.18:
confirmed Arrow on Home Page was removed 
![Screen Shot 2019-12-05 at 4 16 52 PM](https://user-images.githubusercontent.com/48343061/70285073-1214f100-177b-11ea-9e53-12d22879d19e.png)
