### ISSUE TITLE
Avenir font on Help page & Services Listing page

### ISSUE THREAD

**Issue by cherrielam** [pg-irc/pathways-frontend#863]
Some text is not styled in Avenir and is currently in device default font. This includes:
- The grey "note" text on the Help & Support page.
![IMG_5414.jpg](https://images.zenhubusercontent.com/5823860ee40e5714b1700133/0e509529-35d0-4fd3-848b-278d86f0ec78)
- The tag text that shows "no services to show" 
![IMG_5415 copy](https://user-images.githubusercontent.com/21990736/66418950-05ad2b80-e9b8-11e9-8304-8d028dae397d.jpg)

### Rationale
Visual consistency

### Difficulty, impact:
|--(technical difficulty = easy?)--| -- high user importance (SHOULD have) -- |

### Acceptance Criteria
- [x] The grey "note" text is in Avenir on the Help & Support page, on both iOS and Android.
- [x] The tag text that shows "no services to show" is in Avenir, on both iOS and Android

### Steps for QA
-

**Comment by ian-lin-PG** [comment]
@cherrie The following are screenshots for the Avenir fonts on Android
![image](https://user-images.githubusercontent.com/52009863/69673666-ab435980-104f-11ea-8556-273b8ae49bab.png)
![image](https://user-images.githubusercontent.com/52009863/69673674-af6f7700-104f-11ea-9ad9-554f201332c7.png)

**Comment by ian-lin-PG** [comment]
@cherrielam  Here are the screenshots for iOS
![image](https://user-images.githubusercontent.com/52009863/69673893-3cb2cb80-1050-11ea-8c28-01a561dfde63.png)
![image](https://user-images.githubusercontent.com/52009863/69673906-44727000-1050-11ea-86a1-77679f2863e8.png)

**Comment by rasmus-storjohann-PG** [comment]
@cherrielam to QA this since she has the eye for fonts

**Comment by cherrielam** [comment]
@rasmus-storjohann-PG et al, the font is now correct in Staging in both iOS and Android.

Just a minor typo on the "Help & Support" page:
> Mutlilingual health information services 

should be corrected to "Multilingual"

![Screenshot_20191220-160505_Arrival Advisor](https://user-images.githubusercontent.com/21990736/71377510-df8c3600-2579-11ea-8129-94ff210422d9.jpg)

**Comment by tomy-pg** [comment]
Steps for QA after bug fix: 

- [ ] Ensure multilingual is spelt correctly in the Help page.
