### ISSUE TITLE
Loader breaks the teal header on Services Listing

### ISSUE THREAD

**Issue by cherrielam** [pg-irc/pathways-frontend#864]
On iOS, the loader breaks the teal header in the Services Listing page when the page is loading. The loader should be **just below the header block** because it is the services that are loading and not the whole page.
![IMG_5467.jpg](https://images.zenhubusercontent.com/5823860ee40e5714b1700133/7caa62da-2250-42d7-8d38-a0374ac2ce7d)

### Rationale:
Visual cohesion and also to indicate to the user that it is the services that are loading and not the entire page

### Difficulty, impact:
|--(technical difficulty)--| -- SHOULD do -- |

> ### Acceptance Criteria:
> - [ ] Loader is below the teal header block on the Services Listing and no longer breaks the header block when services are loading
> 

*** Comments from @tomy-pg :
I could not stop the spinner from breaking the header on iOS.
After discussion with @cherrielam she requested to make the background of the spinner teal and have the colour of the spinner be white.

### Acceptance Criteria: 
On iOS
- [ ] spinner is coloured white 
- [ ] background for spinner is teal

### Steps for QA:
On IOS: 
1. Go to topics and press `Find related services near me`
- [ ] Ensure that the spinner is coloured white and its  background colour is teal.

**Comment by tomy-pg** [comment]
Addressed as part of Issue #860

**Comment by tomy-pg** [comment]
I could not stop the spinner from breaking the header on iOS. 
After discussion with @cherrielam she requested to make the background of the spinner teal and have the colour of the spinner be white.

**Comment by cherrielam** [comment]
See my comment in #860

**Comment by tomy-pg** [comment]
Issue #940 addresses this.
