### ISSUE TITLE
Sort Recommended first in Related Topics

### ISSUE THREAD

**Issue by cherrielam** [pg-irc/pathways-frontend#865]
In Related Topics, we would like to see the Recommended topics sorted above the non-recommended. (Currently it appears to be sorting alphabetically without regarding for recommended or not).

![IMG_5422.jpg](https://images.zenhubusercontent.com/5823860ee40e5714b1700133/b03c6788-9346-454d-9ae0-8834cd08714b)

### Rationale:
Recommended topics should have higher importance to the user by nature of being "recommended". The fact that they are sorted higher also helps to educate the user that the Recommended star means it is more important to me

### Difficulty, impact:
This is not hard

### Acceptance Criteria:
- [x] Related Topics are sorted such that the Recommended ones appear at the top.

### Steps for QA:
1. Select a topic from the home screen or the explore screen.
2. Scroll down to where it says 'Related Topics'
- [ ] Ensure that recommended topics are listed first.

**Comment by jparlina** [comment]
Tested on Staging V1.17.0, Server V1.3.23 on iPhone 7s (iOS 13.3) and Android 6.0.1:
- [x] Related Topics are sorted such that the Recommended ones appear at the top.

**iOS:**
![iOS_SortRecommendedFirst_RelatedTopics](https://user-images.githubusercontent.com/48343061/73213948-0a802180-4106-11ea-9d20-f956863b66f9.png)

**Android:**
![Android_SortRecommendedFirst_RelatedTopics](https://user-images.githubusercontent.com/48343061/73213974-153ab680-4106-11ea-85b1-bfdc9e2378de.png)
