### ISSUE TITLE
Service Address and lat/long on bc211 is not where the service is actually offered - won't show up based on lat/long

### ISSUE THREAD

**Issue by jparlina** [pg-irc/pathways-frontend#868]
For some service records, the physical address (and lat long) is not where the service is actually offered, so the service record won't show up accurately on Arrival Advisor. We'll need to discuss with bc211 to clarify why the data is structured the way they are and if any revisions need to be made on the bc211 data, then figure out our solutions for AA as appropriate. 

Examples:
A service record that has multiple addresses as part of the service description: SUCCESS offers the BC Settlement and Integration Services (service ID 9509135) at multiple locations (Surrey, Richmond, Vancouver, Coquitlam, Fort St. John). The various locations are included as part of service description (see Figure 1a). The service record's address is the head office's  address in Vancouver (see Figure 1b). Users in Fort St. John won't be able to find this service since AA searches by lat long within 25 km radius of the geo location of the phone. 

**FIGURE 1a:** 
![Screen Shot 2019-10-10 at 5 48 10 PM](https://user-images.githubusercontent.com/48343061/66617475-22995880-eb8a-11e9-84e9-5a89f54dc7c1.png)

**FIGURE 1b:** 
![Screen Shot 2019-10-10 at 5 49 00 PM](https://user-images.githubusercontent.com/48343061/66617481-2af19380-eb8a-11e9-98f6-e0b7ab88941a.png)

### Acceptance Criteria 
- [ ]  

### Steps for QA: 
1.

**Comment by ArtiBPG** [comment]
Fixed by BC211, check with next iCarol export

**Comment by jparlina** [comment]
As per email dated Nov 8, 2019, bc211 has corrected this by creating a service record for each location that used to be in the org description (compare screenshot below with figure 1a above). Will need to test on the app after next iCarol export.

![Screen Shot 2019-12-05 at 5 04 20 PM](https://user-images.githubusercontent.com/48343061/70286886-c44fb700-1781-11ea-8bb3-608aa5a5f8ed.png)

**Comment by rasmus-storjohann-PG** [comment]
@jparlina let's confirm that this has been fixed in the next staging app.

**Comment by jparlina** [comment]
Tested on Staging V1.31.0 Server 1.3.30:
Now those services under BC Settlement & Integration Services provided by S.U.C.C.E.S.S. have its own service record for each location.  

![Screen Shot 2020-05-01 at 2 35 56 PM](https://user-images.githubusercontent.com/48343061/80843477-491bf100-8bb9-11ea-9c17-3f4f044b05bc.png)

![Screen Shot 2020-05-01 at 2 36 07 PM](https://user-images.githubusercontent.com/48343061/80843486-4d480e80-8bb9-11ea-82a5-97bb2ea37911.png)

![Screen Shot 2020-05-01 at 2 36 23 PM](https://user-images.githubusercontent.com/48343061/80843494-5042ff00-8bb9-11ea-84d8-926254f9568f.png)

![Screen Shot 2020-05-01 at 2 36 49 PM](https://user-images.githubusercontent.com/48343061/80843497-55a04980-8bb9-11ea-8d18-19e7e2e5ecab.png)
![Screen Shot 2020-05-01 at 2 37 17 PM](https://user-images.githubusercontent.com/48343061/80843530-651f9280-8bb9-11ea-9500-532bf05acb54.png)
