### ISSUE TITLE
Bookmark pop up doesn't show up on Android phones 

### ISSUE THREAD

**Issue by ian-lin-PG** [pg-irc/pathways-frontend#878]
There used to be a pop up that says a topic has been bookmarked as follows:
![image](https://user-images.githubusercontent.com/52009863/67046136-8240b800-f0e4-11e9-9508-8e13b9ca5409.png)

### Acceptance Criteria 
- [ ]  Bookmark pop up shows up on Android devices
### Steps for QA: 
1.  Open the App
2. Click on bookmark icon beside 'Apply for a Social Insurance Number(SIN)'
3. See a pop up at the bottom of the screen revealing the topic has been bookmarked

**Comment by ArtiBPG** [comment]
addressed in https://github.com/pg-irc/pathways-frontend/issues/892
