### ISSUE TITLE
Search feature testing

### ISSUE THREAD

**Issue by ArtiBPG** [pg-irc/pathways-frontend#889]
This issues will hold links to all the tests done for the search feature

Test round 1:
Test cases [here.](https://docs.google.com/spreadsheets/d/1ndHTUapYrGx5glqd0GhHBI6cXURXNws1WNmclGgiv4I/edit#gid=0)
Next steps: 
- Fix issue #919 
- QA with round 1 test cases again

**Comment by jparlina** [comment]
See issue[ #919 ](https://app.zenhub.com/workspace/o/pg-irc/pathways-frontend/issues/919)

**Comment by jparlina** [comment]
Closing this since we have moved this to issue [#919](https://app.zenhub.com/workspaces/arrival-advisor-5977956f40fbe90e67bb4155/issues/pg-irc/pathways-frontend/889).
