### ISSUE TITLE
Search bars collapse to show search term only

### ISSUE THREAD

**Issue by cherrielam** [pg-irc/pathways-frontend#890]
We would like to revise search UI so that it doesn't take as much space on the user's screen as they are scrolling the page, but the user is still informed about what keyword they have searched. The idea here is that the teal search block collapses, and the top nav still shows to the user what their search is of. (See animation below)

### Mocks
- Zeplin: see [screen 1](https://zpl.io/agWEZ09) and [screen 2 - scrolled up](https://zpl.io/aN58Y3d)
- GIF of scrolling/collapsing animation for reference:

![AA-Search-v1 1-Collapse](https://user-images.githubusercontent.com/21990736/67794651-37a33200-fa3a-11e9-8dab-997deb31f8cf.gif)

### Acceptance Criteria 
- [ ]  

### Steps for QA: 
1.

**Comment by ArtiBPG** [comment]
closing as we have an updated design #918
