### ISSUE TITLE
Improve Search Modal performance

### ISSUE THREAD

**Issue by ian-lin-PG** [pg-irc/pathways-frontend#893]
Right now the search components renders three sub components all at once resulting in unnecessary rendering that contributes to slower responses. Use branching logic as appropriate and render the three sub components as needed.

### Acceptance Criteria 
- [ ]  Search component only renders one of `SearchInputModal` or `LocationInputModal` or the Search screen component

### Steps for QA: 
1.  Open the Search screen
2. Click on one of the search input modal, the modal should open faster than before.

**Comment by rasmus-storjohann-PG** [comment]
We tried a fix to this problem, which improved the speed of the app but broke the functionality. Putting it back in triage for now.

**Comment by ArtiBPG** [comment]
closing as we have an updated design #918
