### ISSUE TITLE
Keyword Bug in Search

### ISSUE THREAD

**Issue by aron-chen-pg** [pg-irc/pathways-frontend#896]
When typing "Canada" into the service input field, the app automatically refreshes. Attempted to type the same word again then causes a page that is filled with strings.

Staging version
Arrival Advisor version: 1.9.0
Server version: 1.3.15
Tested device: Samsung 8

Update: Jean tested it on her iPhone and it turned out fine, so it might be an Android issue?

### Acceptance Criteria 
- [ ]  When typing "Canada" or "United States," the app should proceed normally without any refreshes

### Steps for QA: 
1. Open the staging app.
2. Click on to search tab
3. Type in country names: "Canada" or "United States" in the service text input box

**Comment by rasmus-storjohann-PG** [comment]
This is probably related to this crash from Sentry:
```
Error: Error: data[3]._geoloc.lng should be number

This error is located at:
    in Unknown
    in AlgoliaInfiniteHits(UnknownComponent)
    in RCTView
    in n
    in u
    in RCTView
```
See the lat/long data in this record:
![image](https://user-images.githubusercontent.com/32307781/68889109-1ea0af00-06d1-11ea-87f9-6f4084cd30ef.png)
