### ISSUE TITLE
Android back button should close search modals

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#898]
* Launch the app
* Click on the search icon
* Click on either search input field to open either modal screen
* Click the Android back button
* Expected is that the modal closes so we go back to the main search screen
* Observed is that the back button either just closes the keyboard or does nothing at all

### Acceptance Criteria 
- [ ]  Expected behaviour is implemented.

**Comment by ArtiBPG** [comment]
closing, not needed as we have #918
