### ISSUE TITLE
`yarn test` should run all the tests

### ISSUE THREAD

**Issue by trisapeace** [pg-irc/pathways-frontend#90]
Right now, when I run `yarn test` or `yarn run jest`, it says that there are 0 matching file names for the `testRegex` string:
`testRegex: \\__tests__\\[\\w]+\.(test|spec)\.tsx?$ - 0 matches`

**Comment by rasmus-storjohann-PG** [comment]
@trisapeace can you confirm that this issue has been fixed so we can close this story?

**Comment by trisapeace** [comment]
Yes, this works. Thanks!
