### ISSUE TITLE
Create analytics event for click on "Read more..."

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#903]
We suspect that users are clicking "Read more" every time they look at a topic. If this is true, we should consider modifying the UX so that all the text is there without an extra click.

### Acceptance Criteria 
- [x]  Analytics event is sent when the user opens the Read More part of the UX. 
- [x]  Separate analytics event is sent when the user closes the Read More part of the UX. 

### Steps for QA: 
1.  Monitor the event under "read time" in google analytics

**Comment by ArtiBPG** [comment]
UX modification will be a separate issue if we decide to do it. For is issue all we need to do is create the analytics event.

**Comment by tomy-pg** [comment]
QA'd on Staging version 1.14.0: 

I was able to see a DetailExpanded Action each time I clicked on Read more on a Topic page while using GA Real Time Events. 

Pass.
