### ISSUE TITLE
Upgrade packages to fix iOS warning regarding UIWebView

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#906]
Dear Developer,

We identified one or more issues with a recent delivery for your app, "Arrival Advisor Staging" 1.10.0 (1). Your delivery was successful, but you may wish to correct the following issues in your next delivery:

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

After you’ve corrected the issues, you can upload a new binary to App Store Connect.

Best regards,

The App Store Team

https://github.com/expo/expo/issues/5497
https://github.com/react-native-community/react-native-webview/issues/819

**Comment by rasmus-storjohann-PG** [comment]
This will be fixed by https://github.com/pg-irc/pathways-frontend/issues/1158

**Comment by rasmus-storjohann-PG** [comment]
Confirm that this can be closed out

**Comment by tomy-pg** [comment]
No longer seeing this.
