### ISSUE TITLE
String translation for production release

### ISSUE THREAD

**Issue by ArtiBPG** [pg-irc/pathways-frontend#907]
Prepare strings for translation for the next release:

@tomy-pg 

- [x] Upload new and updated app strings to weblate so that can be downloaded as csv

@cherrielam 
- [x] [Write copy for App Store and play store listings](https://github.com/pg-irc/pathways-frontend/issues/704#workspaces/arrival-advisor-5977956f40fbe90e67bb4155/reports/release?release=5da0ecf7ed3ed500011e06f7)

@ArtiBPG 

- [ ] Translate app strings and play store listing text

### Acceptance Criteria 
- All new/updated strings should be translated and tested

**Comment by tomy-pg** [comment]
@ArtiBPG to update this issue and then assign to @tomy-pg.

**Comment by ArtiBPG** [comment]
One round of translation done, some issues found:

-Latest translations corresponding to source strings wtih changes do not appear on Staging: 1.18.0
Translations are in Weblate but can also be found [here](https://drive.google.com/drive/folders/1tgl6Hcz7oyzSloLcWOvKF6lg7JsfhMqK) in files with Edit in the filename i.e. ui-strings-jsx_strings-fr_Edit

- String not available for translation on Weblate, should added to the next translation drop:
![20200203_162306](https://user-images.githubusercontent.com/44411551/73702725-76343280-46a2-11ea-9353-2f0b57cef30c.jpg)

**Comment by tomy-pg** [comment]
- _Near my location_ was not available for translation when I extracted ui-strings as it was not wrapped by a Lingui trans tag. I

**Comment by tomy-pg** [comment]
Remaining strings for the production release are now on Weblate. After this translation period, we will be on string freeze.
