### ISSUE TITLE
Show phone numbers in Algolia search results in the client

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#908]
With a recent change we have included phone numbers in the service data in Algolia. This story is about the client reading that data and showing it in the UX.

### Acceptance Criteria 
- [x]  Search results contain phone numbers for services.

**Comment by jparlina** [comment]
Tested Staging V1.13.0, Server V1.3.19 on iOS 13.3: phone numbers show up (see screenshots below)
![IMG_3736](https://user-images.githubusercontent.com/48343061/71042103-b1bd7200-20df-11ea-8a4c-697645f58c6e.jpg)
![IMG_3737](https://user-images.githubusercontent.com/48343061/71042104-b2560880-20df-11ea-8277-9290b782defc.jpg)
![IMG_3738](https://user-images.githubusercontent.com/48343061/71042105-b2560880-20df-11ea-9ea7-1a5d6aa817c6.jpg)
