### ISSUE TITLE
Keyword search polish:  Hide "near My Location" when not allowing location access

### ISSUE THREAD

**Issue by aron-chen-pg** [pg-irc/pathways-frontend#913]
When location permission is declined, the app still put down "near My Location" in the location input. This will cause great confusion to the users thinking the app might be actually using their location. Moreover, it gets more confusing the fact that users can click on My Location afterwards.

Bug founded on Samsung 8

### Acceptance Criteria 
- [x] The location input field should remain empty upon declining the location permission.
- [x] Subsequent clicks on use my location button when location permission is denied brings up the app settings.

### Steps for QA: 
1.  Make sure location permission is turned off for AA staging app
2. Go to search, and click on the location input field
3. Click on "My location"
4. Deny access to the device's location
5. Observe that Location field remains empty. Old buggy behaviour was that the field ended up populated with "Near my location"
6. Click on "My location" button again opens the app settings so that you can permit the app to access the device location.

Video showing the problem:
![My location bug](https://user-images.githubusercontent.com/54860686/69710172-b92ac600-10b3-11ea-933f-790f241f8333.gif)

**Comment by ArtiBPG** [comment]
@aron-chen-pg I dont really understand why this is a bug. I dont get why we need to remove Near my location.

**Comment by aron-chen-pg** [comment]
When we display "Near My Location" within the location input field despite the users had just declining the location access, it confuses them in the sense that might think "Is the app still searching using my location? even though I literally just decline the access?"

**Comment by rasmus-storjohann-PG** [comment]
Integrate this with the work to complete the search UX, see issue https://github.com/PeaceGeeksSociety/pathways-ux-ui/issues/111.

**Comment by ian-lin-PG** [comment]
@aron-chen-pg Android phones behave as intended where if one denies the permission without checking off `Do not show this again` the button will ask for permission every time. Responding yes to the permission request will fill in the location input field, and responding no will leave the location input field empty.

However, the behaviour is vastly different in iOS. The permission request will only show up once and gets saved until you go into the setting and reset all permissions. Allowing location permissions fills in the location input field every time it's filled, denying location permission button renders the button useless.

**Comment by tomy-pg** [comment]
Staging version 1.22.0:
Passes.
