### ISSUE TITLE
Add algolia service search results to Redux store 

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#915]
Currently, search for services related to a given topic causes the returned services to be stored in the redux store. Services returned from Algolia is kept in the component and not saved to the redux store. This stops us from putting a service from Algolia into a service detail screen.

### Acceptance Criteria 
- [x]  Service search results from Algolia are added to the Redux store
- [x] Can open a service detail screen with a service from the algolia search result.
- [x] Add google analytics hooks on how many services are stored, with the view to understand whether services take up too much memory on users' phones, send an event for each time more services are added to the store.

### Testing steps
To get started testing you'll need to first add a test `GOOGLE_ANALYTICS_TRACKING_ID` key to your `.env`, this work sends events to GA so we don't want them going to the production GA account. Now, in GA, open the Reports > Realtime > Events tab so you can monitor events in realtime (see screenshot below). Finally you'll want to adjust the value of `MEMORY_REPORT_SEND_EVERY_SERVICES_COUNT` to be something smaller and easier to test with, say 1 or 2, you can refer to the PR for more implementation details. Confirm the following:

- [x] Search results now click through to their detail screen, services are added to Redux when you tap their title in the search results
- [x] `MemoryReport` Events are sent to GA every `MEMORY_REPORT_SEND_EVERY_SERVICES_COUNT` count, for example, if this was set to 2 we'd see a report every time the number of new services in Redux is divisible (no remainder) by 2, so, 2, 4, 6 etc...
- [x] `MemoryReport` Events are only sent when NEW services are added to Redux, we shouldn't see a report just because the current Redux count is divisible
- [x] Topic service results also trigger `MemoryReport` events in GA

Here's an example of what you should start to see in GA when you start clicking on services:

<img width="1894" alt="Screen Shot 2019-12-04 at 9 44 55 AM" src="https://user-images.githubusercontent.com/3228323/70167108-e1e62900-167a-11ea-9171-e8fcd45793ed.png">

**Comment by tomy-pg** [comment]
Passes QA in Staging Version 1.12
