### ISSUE TITLE
Algolia search results contain just 5 services

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#916]
We need to see more than 5 service search results in the app. This is blocking testing and is also not usable for end users. Change the value to 100.

ACs:
- [ ] Keyword search in the app returns more than five results

**Comment by jparlina** [comment]
Tested on iPhone 7 Plus (iOS 13.2.3) and on Nexus 5 (Android 6.0.1) - AA Staging V1.12.0, server V1.3.18: keyword search in the app returns more than five results - tested "LINC" in Vancouver and "ICBC" in Surrey - PASSED
