### ISSUE TITLE
Search UX update: empty state, paging, search input, analytics

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#918]
Change the UX so it works with dense and sparse results: No radius so we get results even if the results are few and far between. Paging gives us good performance when there are many results.

### Acceptance Criteria 
- [ ]  Service search related to topic (our server): Remove search argument setting the radius to 25km
- [ ]  Service search related to topic: Set parameter per_page to 10 results
- [ ]  Service search related to topic: Add a button "More results" to the client service list. Clicking the button loads the next page of data from the server and adds it to the list in the client, i.e. after clicking the "more" button twice, the list will contain 30 results
- [ ]  Service search related to topic: Add google analytics hook to the "More" button

- [ ]  Service search by keyword (algolia): Make sure no max radius is used (it's an option, but we're not using it, so no change required)
- [ ] Algolia also implements paging, explore whether it makes sense to match the algolia search result paging behaviour to the service search for topic ... we would prefer the user not noticing that the are different.

**Comment by rasmus-storjohann-PG** [comment]
Outstanding issues related to search:
- [ ] Me: Algolia search order bug https://github.com/pg-irc/pathways-frontend/issues/919
- [ ] Aron: Empty screen for when the search term is empty, with mocks
- [ ] Aron: Search input (both items) on the main search screen
- [ ] Me: Remove max radius on search result in both algolia and our server, implement paging with a load more button with analytics on it https://github.com/pg-irc/pathways-frontend/issues/918
- [ ] Arti: Search results analytics (edited)

**Comment by ArtiBPG** [comment]
tracked under #936
