### ISSUE TITLE
Fix sort order from Algolia

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#919]
Based on QA from test round 1 #889 

We are likely going to discover/resolve more than one problem under this issue.

* For now the issue is that when searching for "ICBC" the result "ICBC Language Services" with search term in service name, service description and organization name, is ranked below "Living Through Loss Counselling Society of BC" with the search term just in service description. Seems like an Algolia bug at this point.

**Comment by rasmus-storjohann-PG** [comment]
Current configuration on index dev_phones look promising (service_name, organization.name, service_description), please test there. Go to Browse -> Add query parameters -> Geo-search -> Radius precision -> 5000 (5 km). See if that works.

**Comment by jparlina** [comment]
Tested on Algolia by adding Radius precision -> 5000 (5 km):
see worksheets "Testing Sort Order on Algolia_Jean" and "Testing Sort Order on Algolia_Aron" [here](https://docs.google.com/spreadsheets/d/1ndHTUapYrGx5glqd0GhHBI6cXURXNws1WNmclGgiv4I/edit#gid=1343060228) for detailed test results.

As discussed among Arti, Rasmus, Aron, and Jean on Jan 8, the search results should be in the following order:
1. keyword matches to Service Name first, then
2. keyword matches to Org Name, then
3. keyword matched to Service Description

**Comment by ArtiBPG** [comment]
@jparlina @aron-chen-pg when this has been fixed and this issue is in Staging/QA please test against the same keywords and location and note if there has been an improvement.

**Comment by ian-lin-PG** [comment]
A new index with taxonomy term is created [here](https://www.algolia.com/apps/MMYH1Z0D3O/explorer/browse/dev_services_with_taxonomies). The documentation for this new index is available [here](https://docs.google.com/document/d/127COcm5rIAsx0hKFCzTZ1RK__sMM29ISmwWvig6a3WM/edit#).
The new index relies on creating synonyms that matches existing bc211 taxonomies. An example will be searching for 'english classes' and services with 'language-english' taxonomy will show up.

**Comment by tudatn** [comment]
Thanks @ian-lin-PG . Using an index relies on creating synonyms that matches existing bc211 taxonomies is really helpful. [Here](https://docs.google.com/document/d/1FJ4u6Vmm4XHa6oKRbsbGvFgAnnj1jkX2N6IQ-Fk7sUY/edit#)  is my understanding about the Algolia and some suggestions that may improve the search result . [A new index](https://www.algolia.com/apps/MMYH1Z0D3O/explorer/browse/dev_optimize) is created for testing.

**Comment by tudatn** [comment]
I notice that the geolocation (latlong) from geocoder.ca API is not at the center of the city but closer to the city boundary. Here what we got if we search for Surrey:
<img width="688" alt="Screen Shot 2020-03-26 at 11 15 06 AM" src="https://user-images.githubusercontent.com/26643781/77682029-7e4a7900-6f53-11ea-9c50-bef30e61b96b.png">
The return location is very close to the boundary with New Westminster. Cause we are passing 'aroundLatLng' to Algolia with precision of 5000m, it's highly likely the top records may be in New Westminster. A similar problem can happens to other cities.
Currently I don't see any parameter that we can pass to geocoder.ca API to enforce it to return the center coordinate of the city. We may want to consider using different services or even manually create a dictionary <City, Latlng> to solve this problem.

**Comment by ian-lin-PG** [comment]
@jparlina Have a try at the `dev_optimize` index on algolia [here](https://www.algolia.com/apps/MMYH1Z0D3O/explorer/browse/dev_optimize).

**Comment by jparlina** [comment]
Discussed with @ian-lin-PG and @tudatn whether the following is technically possible to make the search results more relevant for AA target users:
1. match the search term with the “taxonomy terms” 
2. out of those search results from #1, show first service records that also have “immigrantsethnocultural-groups” in the bc211 taxonomy
3. then out of those in #2 show service records in the order of closest to farthest in geolocation

Not all service data on bc211 dataset has “immigrantsethnocultural-groups” taxonomy e.g. library, recreation centre, housing, health clinics. Those are for general public. But when the service data also has “immigrantsethnocultural-groups” in the taxonomy (in addition to the one matching the search term), we should prioritize services that are specific to “immigrantsethnocultural-groups” before others. 

For example, if a user is searching “job search” in Vancouver (49.2827, -123.1207), among all search results that has the taxonomy term “employment-search-assistant”, prioritize those that also has the taxonomy “”immigrantsethnocultural-groups”.  So in this example, #12 BC Settlement and Integration Service” is more relevant for AA target audience than #11 EMBERS - employment program for male parolees. 

![Screen Shot 2020-03-26 at 3 24 31 PM](https://user-images.githubusercontent.com/48343061/77706842-b4eab880-6f80-11ea-9b81-76cb2df987cb.png)

![Screen Shot 2020-03-26 at 3 24 59 PM](https://user-images.githubusercontent.com/48343061/77706804-9d133480-6f80-11ea-913a-df4e4b7d0239.png)

**Comment by tudatn** [comment]
@ian-lin-PG create a new index [dev_for_newcomers](https://www.algolia.com/apps/MMYH1Z0D3O/explorer/browse/dev_for_newcomers) with a new field `for_newcomers` having a value of 1 or 0 to indicate if a service is specific to newcomers. We applied a sort attribute on this new field and placed it at the top of the current ranking formula. @jparlina please give it a try when you have time. Also please set the radius precision to 5000 to minimize the geo filter noise while testing.

**Comment by jparlina** [comment]
@tudatn @ian-lin-PG I tried to test [dev_for_newcomers](https://www.algolia.com/apps/MMYH1Z0D3O/explorer/browse/dev_for_newcomers) and [dev_for_newcomers_optimize](https://www.algolia.com/apps/MMYH1Z0D3O/explorer/browse/dev_for_newcomers_optimize),  but the search doesn't work when I added parameters (lat long and radius precision). I can't click enter after entering the keyword search. When I removed the parameter, the search is working again. Do you know why that is? To test, I need to enter the lat long. I also tried to test on [dev_phones](https://www.algolia.com/apps/MMYH1Z0D3O/explorer/browse/dev_phones), same issue. I didn't have this problem before. Did I miss any step? I just added the lat long and radius precision here (see screenshot below).

<img width="612" alt="Screen Shot 2020-04-06 at 6 47 15 PM" src="https://user-images.githubusercontent.com/48343061/78621475-81891300-7837-11ea-87c2-decdd3a6b023.png">

**Comment by jparlina** [comment]
Tested on Algolia using index `ArrivalAdvisorProductionVersion1`

**Comment by rasmus-storjohann-PG** [comment]
So we could try to filter the results in cases where a recognized city, such as "Surrey", is entered as the location, we can only show results with "Surrey" in the city field of the address. For location strings that are not recognized as cities (e.g. street addresses or postal code) we fall back on geocoder. Also for cities, we find that geocoder tends to use poorly chosen lat/longs for the city, we can hard-code our own values. Tricky to make this work in algolia.

**Comment by rasmus-storjohann-PG** [comment]
Geocoder is throttling results leading to very slow UX for search. Client side caching of commonly used location strings could make this a lot better. Alternatively we could start paying for GeoCoder.

**Comment by rasmus-storjohann-PG** [comment]
Closing this story as done, see #1140 and #1141 which are the only unresolved issues from this story.

**Comment by ian-lin-PG** [comment]
We are deleting `dev_last_verified_recommended` and `dev_last_verified_recommended` today. The two indices are fundamentally the same with the minor difference in the tie breaker priorities.
![image](https://user-images.githubusercontent.com/52009863/83696345-12b70480-a5b1-11ea-96bf-6243a7d46114.png)
By default we have the `for_newcomer` tag lower than the default tie breaker, opposite from this screenshot. Our newest staging index and production index follow the newcomer recommended pattern.
