### ISSUE TITLE
Google store warning: Your app could be smaller if you used the Android App Bundle

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#920]
Warning from Google Store:

This APK results in unused code and resources being sent to users. Your app could be smaller if you used the Android App Bundle. By not optimizing your app for device configurations, your app is larger to download and install on users' devices than it needs to be. Larger apps see lower install success rates and take up storage on users' devices.

Resolution:

Use the Android App Bundle to automatically optimize for device configurations, or manage it yourself with multiple APKs.

**Comment by tomy-pg** [comment]
When we run `expo ba` we are presented with two options:
```
Choose the build type you would like:
apk - Build a package to deploy to the store or install directly on Android devices
app-bundle - Build an optimized bundle for the store
```
We have usually just chosen the `apk` option, but I think we can use the `app-bundle`.

I will try this for Staging version 1.32.0

**Comment by tomy-pg** [comment]
Chose to build using the `app-bundle` type. 

- Warning is no longer there
- App download size reduced close to half

Previous size using `apk` type: 
![Screen Shot 2020-05-07 at 3 53 14 PM](https://user-images.githubusercontent.com/47794846/81352317-15d6d780-907b-11ea-9e3f-c309c3223173.png)

Current using `app-bundle` type:
![Screen Shot 2020-05-07 at 3 53 10 PM](https://user-images.githubusercontent.com/47794846/81352332-1cfde580-907b-11ea-9357-da97f79263d9.png)
