### ISSUE TITLE
Remove answer Id from google analytics event

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#926]
There is no reason to be collecting ids of chosen answers in google analytics.

### Acceptance Criteria 
- [ ]  Answer Id is no longer collected through google analytics.

**Comment by ArtiBPG** [comment]
@rasmus-storjohann-PG Please reverse this ASAP. This was not approved. 
We need that data to know general demographics and status of our users. It was discussed yesterday that the messaging on our presentation will be updated to reflect what how we treat data collected through .

**Comment by rasmus-storjohann-PG** [comment]
Note: I asked Ian to close this issue.
