### ISSUE TITLE
Service Address is different from Contractor/Sub-contractor's location - e.g. SWIS in New Westminster by MOSAIC (Vancouver)

### ISSUE THREAD

**Issue by jparlina** [pg-irc/pathways-frontend#931]
For some service records, the physical address (and lat long) is not where the service is actually offered, so the service record won't show up accurately on Arrival Advisor - e.g. when the service is provided by a contractor/sub-contractor whose office is at a different location. 

Example: Settlement Workers in Schools (SWIS) Program in New Westminster School District (SD40) is provided by MOSAIC. The service record on bc211 database shows the address of MOSAIC's head office in Vancouver (see Figure 1a). Users searching in New Westminster won't be able to find this service. The New Westminster School District's organization record mentions "Settlement Workers in School (SWIS) Program" in the organization description, but not as a service record (see Figure 1b). 

**FIGURE 1a:** 
![Screen Shot 2019-10-10 at 4 37 12 PM](https://user-images.githubusercontent.com/48343061/66615571-1a3d1f80-eb82-11e9-8aba-4e3f4265c8e0.png)

**FIGURE 1b:** 
![Screen Shot 2019-10-10 at 5 03 34 PM](https://user-images.githubusercontent.com/48343061/66616933-adc51f00-eb87-11e9-9613-e7157f6f72aa.png)

**Comment by jparlina** [comment]
Emailed bc211 about this and issues related to SWIS records on Nov 6, 2019. bc211 will look into the inconsistencies related to SWIS records. It takes more time to correct because there are so many records.

**Comment by rasmus-storjohann-PG** [comment]
Review BC211 data, when done close this story

**Comment by alysha-PG** [comment]
included in #595
