### ISSUE TITLE
Keyword search polish: Analytics

### ISSUE THREAD

**Issue by ArtiBPG** [pg-irc/pathways-frontend#935]
Analytics should capture:
- Keywords used for search
- Keyword and location combinations 
- Make sure to be aware what Algolia stores so we don't re-implement their analytics

Search results:
- Which search results are users clicking on? We should be able to see the actual links clicked.
- Which search results are users saving? We should be able to see the name of the service saved.
- What is the rank of the search result users are clicking on? We should be able to see the name of the service and its rank in the search results.
- What is the rank of the search result users are saving?
- Which search results did a user see on entering a certain keyword or keyword/location?

### Acceptance Criteria 
- GA should be set up to answer the questions above. 

### Steps for QA: 
0. Change GA tracking ID to `UA-30770107-5` and run `yarn start -c`
1.  Bookmark a service, check that an Service Bookmarked event is triggered in GA
2. Conduct a search, check that a Search Queried event is triggered
3. Open a service from search, check that an Open Service event is triggered 
4. Open a different service from a topic, check that an Open Service event is triggered 
5. Open a different service from bookmark, check that an Open Service event is triggered 

*Note the same service opened multiple times will only be counted once per device. Have different services for the open service event to trigger multiple times.

**Comment by ian-lin-PG** [comment]
Created a plan in the google doc [here](https://docs.google.com/document/d/1GMvv1sFP8n3mWFcHhPboqGPiZtT5wHNmwy9LdCnnJbM/edit#).
The current plan is 5 distinct google analytics events, for searching, opening and saving of services.

**Comment by jparlina** [comment]
@ian-lin-PG Also consider to track:
- What locations entered in relation to _Topic > Find services near me_
- What locations entered in relation to _keyword search_
- What locations are search for which topic 
- What locations are search for what keyword(s)
- Number of times where a user enters a location search after seeing service listing from _Topic > Find services near me_ (to assess whether the default search by latlong with 25km radius give results that users need or do they still need to enter location search after seeing the results from Topic>Find services near me)
- Number of services clicked from service listing under a topic vs from keyword search
- Number of services saved from service listing under a topic vs from keyword search
- On service detail, track users' click on Phone (all types?), Website, Email to assess users' preference in accessing services or their next step after finding a service (call/website/email). 

- Not sure if this is the same as the "rank" that Arti mentioned above: 
where in the search results do users click the service to get more details - e.g. do users go all the way down to click search result #45 or they find a relevant service at search result #3? This will help us assess how good the search results are and the sorting of relevant services.

**Comment by tomy-pg** [comment]
Staging release 1.29.1:
Passes QA.
