### ISSUE TITLE
Keyword search polish: Error screens review

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#940]
**3.** _Updated_
Different error states to guide users to search. For example, when wifi is not on, or when location access isn't granted. Whenever an error occurs, users will want to know how to fix it (or even better, prevent the error from ever happening again). Therefore, it is our responsibility to provide guidance for users to take action. 

### Acceptance Criteria:
- [x]  No matching results
https://zpl.io/V0jkkpR
- [x] No internet access, note this state already exists for "Search service near me" and can be reused
https://zpl.io/V15kWoJ
- [x] Invalid location
https://zpl.io/b6okR8N
- [x] Empty search screen
https://zpl.io/VkzBBWW

### Steps for QA:

1.  No matching results: 
In the search input bar with the text _Search for services_: type in random gibberish and then click on the _Search_ button 
- [x] Ensure you see the No Matching results screen _as discussed with Aron and Cherrie, the copy on this screen has been changed to No results found._
2. No internet access: 
Turn on airplane mode on your device and then navigate to the search page
- [x] Ensure you see the No internet access screen

Turn off air plane mode and then click on Try Again
- [x] Ensure search works as normal
3. Invalid location
In the search input bar with the text Enter city, address, or postal code: type in random gibberish and then click on the _Search_ button
- [x] Ensure you see the Invalid location screen
4. Empty search screen
Start the app and navigate to search
- [x] Ensure you see the empty screen

**Comment by aron-chen-pg** [comment]
Upon investigation, three error states have been determined. I have updated the issue with Zeplin uploads.

**Comment by ArtiBPG** [comment]
Lets work only on these:
> * No matched results
>   https://zpl.io/V0jkkpR

> * Invalid location
>   https://zpl.io/b6okR8N

**Comment by ian-lin-PG** [comment]
2 issues with `Can't reach the internet` screen, one specific to iOS, one specific to android:
* iOS simulator has trouble with `Try again` after internet is restored. Need to test on iOS devices.

* The icon won't show up on android for some reason. The problem exists for topic-service recommendation page, so it may be an old bug with the screen.

**Comment by tomy-pg** [comment]
@ian-lin-PG - in regards to the image not showing up on Android, I believe this problem exists only when we are building off of expo. If you go on to our staging app and try the same thing for topic services on Android, you will see the icon.

**Comment by ian-lin-PG** [comment]
@tomy-pg `Try again` works as expected on Cherrie's iphone after turning on and off airplane mode. This in addition with your previous comment seem to be minor gripes with Expo or iOS simulators. Therefore, I believe this PR is ready to merge. The two issues will be revisited for QA in the next staging release.

**Comment by aron-chen-pg** [comment]
Test device: Samsung 8
AA version: 1.19.0
Server version: 1.3.23

No result error screen and Invalid location error screen function just fine.

Issues:

- Bullet points for Empty screen has false text string (refer to mocks - https://zpl.io/VY7zD9p)
- Couldn't recreate No internet access screen. I have tried both airplane mode and just simply search with no internet. Both scenarios return me with the No result page.

**Comment by jparlina** [comment]
Tested on Staging V1.19.0, server V1.3.23 on iPhone 7s at the HiVE

1. No matching results:
In the search input bar with the text Search for services: type in random gibberish and then click on the Search button
- [x]  Ensure you see the No Matching results screen as discussed with Aron and Cherrie, the copy on this screen has been changed to No results found.
![IMG_4014](https://user-images.githubusercontent.com/48343061/74181380-0e2ba200-4bf6-11ea-86b9-eb4c86e024f0.PNG)


2. No internet access:
Turn on airplane mode on your device and then navigate to the search page
- [x]  Ensure you see the No internet access screen
![IMG_4018](https://user-images.githubusercontent.com/48343061/74181447-2c919d80-4bf6-11ea-958c-3851d3c27bd7.PNG)

Turn off air plane mode and then click on Try Again
- [x]  Ensure search works as normal
![IMG_4017](https://user-images.githubusercontent.com/48343061/74181424-27cce980-4bf6-11ea-8fbf-c859c74f6c9d.PNG)

3. Invalid location
In the search input bar with the text Enter city, address, or postal code: type in random gibberish and then click on the Search button
- [x]  Ensure you see the Invalid location screen
![IMG_4021](https://user-images.githubusercontent.com/48343061/74181769-b3df1100-4bf6-11ea-80ef-deafeb647ef0.PNG)


4. Empty search screen
Start the app and navigate to search
- [x]  Ensure you see the empty screen
![IMG_4022](https://user-images.githubusercontent.com/48343061/74181890-e426af80-4bf6-11ea-8d49-22971399ad35.PNG)

**Comment by aron-chen-pg** [comment]
Test Device: iPhone X
AA version: 1.19.0
Server version: 1.3.23

Was able to recreate all error screens with the correct condition. 

Issue:
Text string for empty screen requires changes (refer to https://zpl.io/VY7zD9p)

**Comment by jparlina** [comment]
Test Device: Nexus 5, Android 6.0.1
AA version: 1.19.0
Server version: 1.3.23

Was able to recreate all error screens with the correct condition.

Issue:
Text string for empty screen requires changes (refer to https://zpl.io/VY7zD9p)

**Comment by aron-chen-pg** [comment]
Upon checking other applications, I realize one of the ideal experience we're missing in terms of error screens is to show the No internet access screen when the users first landed on the search tab with no internet access. If users have internet access at the time when they open Search, then we show them the empty screen. That way, users can learn that they need internet access from the get-go instead of finding out after attempting to search.

**Comment by jparlina** [comment]
Tested on Staging V1.21.0, Server V1.3.23 on iPhone 7 Plus at the HiVE:
Text string for empty screen is now consistent with [https://zpl.io/VY7zD9p](https://zpl.io/VY7zD9p)

![Screen Shot 2020-02-28 at 12.25.00 PM.png](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/9c3e9f83-9c40-4132-af4b-4c77e0e686b0)

**Comment by jparlina** [comment]
See comment from @aron-chen-pg on Feb 12, 2020 above. This issue has not been fixed. Moving this to  Staging Bug.

**Comment by rasmus-storjohann-PG** [comment]
Closing out this old issue, tracking [in release todo](https://github.com/PeaceGeeksSociety/content/issues/748)
