### ISSUE TITLE
README for locale directory 

### ISSUE THREAD

**Issue by tomy-pg** [pg-irc/pathways-frontend#946]
Create a README to document our string localization process.  

### Acceptance Criteria 
Instructions for:
- [ ]  exporting jsx strings from the app into .po files
- [ ] how importing translated strings works and where to find the strings 

### Steps for QA: 
1.  Update the locale strings following the instructions in the README

**Comment by tomy-pg** [comment]
This issue will be QA'd as part of the next production release.

**Comment by rasmus-storjohann-PG** [comment]
Docs look good, closing this issue
