### ISSUE TITLE
Collapse search input fields

### ISSUE THREAD

**Issue by ian-lin-PG** [pg-irc/pathways-frontend#957]
When scrolling down to view service listing, the two search input fields should collapse into one and the bottom navigation bar should hide.

### Acceptance Criteria 
- [x]  The search input field should look like this mock https://zpl.io/bejYYgD

### Steps for QA: 
1.  Go to Search page
2. Type in `Government of British Columbia` in first input
3. Click on `My Location` in second input
4. Click on `Search`
5. The search input show be only one line with `Government of British Columbia near My Lo...`. Notice that everything fits in one line and replace with `...` where appropriate.
6. Click on the 1 line search input. The original 2 input fields should be back
7. Click on `x` in the  location input field. The field should be clear now.
8. Click  on `Search`. The 1 line input should be `Government of British Columbia` without `near`
9. Click on `x` in the 1 line input. The 2 input fields should both be empty

**Comment by tomy-pg** [comment]
Staging vesion 1.22.0:
Passes
