### ISSUE TITLE
Hide header and navigation tab on scroll

### ISSUE THREAD

**Issue by ian-lin-PG** [pg-irc/pathways-frontend#958]
The header and navigation tab are always present on the search page. They should disappear when scrolling.

### Acceptance Criteria 
- [ ]  On scroll should look like this: https://zpl.io/VkzBNkK
Video demo: https://drive.google.com/open?id=1UYm9VnwCy0fEdp0WG6uRN9PuVXdS6SJn

### Steps for QA: 
1.  Go to search page
2. Type in a search term
3. Type in a search location
4. Scroll through the search results and see the page looks like the mock

**Comment by ArtiBPG** [comment]
@aron-chen-pg can you add the mock here?

**Comment by aron-chen-pg** [comment]
Updated the issue with Zeplin mockup and video demonstration.

**Comment by niko-pg** [comment]
Hey, is the header supposed to be hidden as well when scrolling? The mock shows otherwise.

**Comment by ian-lin-PG** [comment]
@niko-pg sorry for taking so long to get back to you. The header typically means the bar that includes the hamburger on the top. In the mock the hamburger was hidden before the scrolling action. I will have @aron-chen-pg to clarify the specifications.

**Comment by aron-chen-pg** [comment]
@niko-pg Like Ian explained, we refer the header as the horizontal space that contains the hamburger menu and the "Find a service" header string. I have updated the video demo so you could see how the part should be hidden when scrolling. Let me know if you have any more questions.

**Comment by aron-chen-pg** [comment]
Tested on Samsung 8, version 1.33.0
When clicking onto the minimized input field while the header and the bottom footer are hiding, they should resurface. Like this:
![98526207_672349580268683_3742676850111938560_n](https://user-images.githubusercontent.com/54860686/82099010-0b3fc200-96bb-11ea-9da2-0d214de7aee2.jpg)

Instead, right now the app does not re-surface the header nor the footer when input field is being clicked on:
![96841367_247454109696562_7580288085376630784_n](https://user-images.githubusercontent.com/54860686/82099054-2b6f8100-96bb-11ea-8ba6-67f536e3d66d.jpg)

**Comment by tomy-pg** [comment]
Staging version 1.33.0:

After scrolling down and a search service list and seeing the header and footer disappear, clicking the back button on my Samsung s9 to navigate to a previous screen also shows the screen without a footer.

![Screenshot_20200520-094222_Arrival Advisor](https://user-images.githubusercontent.com/47794846/82473615-b3200b80-9a7e-11ea-981d-2cbb57676454.jpg)

**Comment by niko-pg** [comment]
@aron-chen-pg Should the header and footer re-appear if the search inputs are clicked in expanded mode?

**Comment by aron-chen-pg** [comment]
@niko-pg Yes, since the users aren't scrolling/looking at individual services, the header and the footer should remain open.

**Comment by aron-chen-pg** [comment]
Tested on Samsung S8, version 1.34.0
