### ISSUE TITLE
Missing Email Field on Service Detail Page

### ISSUE THREAD

**Issue by jparlina** [pg-irc/pathways-frontend#964]
The Email field should show up on the service detail page under the Website field. 

### Acceptance Criteria 
- [x]  Ensure you see the email field on the service detail page below the Website field

### Steps for QA: 
1.  Select a Topic
2. Click Find related services near me
3. Click on a Service to see the Service Detail page
4. Make sure you see the email field on on the service detail page below the Website field

![IMG_3827.jpg](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/6c083118-ad66-4539-9f59-90cda26bc61f)

**Comment by tomy-pg** [comment]
Screenshot of the email included in the service detail component.
![Screenshot_20200108-140513_Expo](https://user-images.githubusercontent.com/47794846/72020166-086e2580-3220-11ea-879f-02c9d3ae0eb7.jpg)

**Comment by jparlina** [comment]
Tested on Staging V1.17.0, Server V1.3.23 on iPhone 7s (iOS 13.3) and Android 6.0.1:
email now shows up on the service detail page below the website.
