### ISSUE TITLE
Back to App Button from Web Browser, Map, Email should go back to Service Detail Page (instead of Home)

### ISSUE THREAD

**Issue by jparlina** [pg-irc/pathways-frontend#965]
Clicking back to app button from Web Browser, Google Map, or Email should bring user back to the Service Detail page where the user came from instead of going back to the Home page. 

As you can see on [this video](https://drive.google.com/file/d/1xsGbWbz8QT3Gbg70ToOf4weIAYGTBkhv/view?usp=sharing), this issue does not occur consistently for every service record tested from the HiVE on Staging V1.15.0, server 1.3.21 on iPhone 7s). In the video: 
Test 1. Applying for a driver's license - ICBC Royal Centre: from Map goes back to Service Detail page (good); from **Web Browser** goes back to Home (NOT good)
Test 2. Contact workers at your local settlement agency - SUCCESS BC SIS: **BOTH** Map and Web browser go back to Home (NOT good)
Test 3. Get your BC Services Card - ICBC North Vancouver: from **Map** goes back to Home (NOT good)
Test 4. Get your BC Services Card - ICBC Commercial Drive: from **Map** goes back to Home (NOT good)
Test 5. Community and recreation centres - Carnegie Community Centre: both map and web browser go back to Service Detail page (good)
Test 6. Community and recreation centres - La Boussole: from Map goes back to Service Detail page (good), but from **Web Browser** goes back to Home (NOT good)
Test 7. Public libraries - VPL: from **Map** goes back to Home (NOT good), web browser go back to Service Detail page (good)
Test 8. Public libraries - Decoda Literacy Solutions: **BOTH** Map and Web browser go back to Home (NOT good)
  
### Acceptance Criteria 
- [ ]  Clicking the back to app button from Web Browser should bring user back to the corresponding Service Detail page from where the website URL was clicked
- [ ]  Clicking the back to app button from Google Map should bring user back to the corresponding Service Detail page from where the address was clicked
- [ ]  Clicking the back to app button from Email app should bring user back to the corresponding Service Detail page from where the email address was clicked 

### Steps for QA: 
**MAP:**
1. Select a topic
2. Click Find related services near me
3. Click on a service to go to Service Detail page
4. Click on the address to open **Map** on your device 
5. Click on back to app button from your Map app 
- [ ] You should be directed back to the Service Detail page from where you clicked the address

**WEB BROWSER:**
Repeat Steps 1-3 above, then:
4. Click on the Website URL to open your web browser and the website
5. Click on back to app button from your web browser
- [ ] You should be directed back to the Service Detail page from where you clicked the website URL

**EMAIL:**
Repeat Steps 1-3 above, then:
4. Click on the Email address to open your email app and create a new email with the address filled in
5. Click on back to app button from your email app
- [ ] You should be directed back to the Service Detail page from where you clicked the email address

**Comment by cherrielam** [comment]
Tested it on iPhone 6 - staging v1.15.0, on a variety of Service Detail pages for website and open in map. Could not reproduce the issue that @jparlina described, including on the same services Jean put above.

**Comment by jparlina** [comment]
Tested on Staging V1.19.0, server 1.3.23 using iPhone 7s:
can no longer recreate the issues. Closing this for now.
