### ISSUE TITLE
Clickable Card to Access Service Detail Page from Service Listing

### ISSUE THREAD

**Issue by jparlina** [pg-irc/pathways-frontend#966]
On the Service Listing, users should be able to click the whole card to access the Service Detail page for each service record. Currently on Staging V1.15.0, Server 1.3.21, users can only access the Service Detail page by clicking on the Service Name, which is in black font - i.e. not obvious that it's clickable. 

**_Note_**: Based on discussion with Cherrie and Aron, ideally the whole card should be clickable to open the Service Detail page, and clicking the Org Name should open the Org Detail page - is this technically possible? (if not, pls revise ACs and Steps for QA below accordingly)

![IMG_3829.jpg](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/5d6cb7dc-2e94-4fbd-93a8-2b0d85efc787)

### Acceptance Criteria 
- [x]  On the service listing/search result page, you should be able to click the whole card to open the Service Detail page
- [ ]  and clicking the Org Name should open the Org Detail page

### Steps for QA: 
1.  Select a Topic or use the search feature
2. Click Find related service near me 
3. On the service listing/search result, click the full card to open the Service Detail page
4. Go back to the service listing/search result, click the Org Name to open the Org Detail page

**Comment by tomy-pg** [comment]
The acceptance criteria: 

>  and clicking the Org Name should open the Org Detail page

 will not be met as part of this issue as organizations data are not part of the app yet.

**Comment by jparlina** [comment]
Tested on Staging V1.17.0, Server V1.3.23 on iPhone 7s (iOS 13.3) and Android 6.0.1:
- [x] On the service listing/search result page, you should be able to click the whole card to open the Service Detail page

As noted above by @tomy-pg on Jan 21 above, the acceptance criteria "clicking the Org Name should open the Org Detail page" has not been met as part of this issues as organizations data are not part of the app yet.
