### ISSUE TITLE
Algolia Proximity Distance for Multi-Word Searches

### ISSUE THREAD

**Issue by jparlina** [pg-irc/pathways-frontend#971]
When a user enters multiple words in the search field (e.g. "english class", "job search"), the search results should show those words side-by-side not further apart. 

Example of issue: when searching "english class" in Victoria (lat/long: 48.428421, -123.365644), the second result shows "FOODSAFE" program (service ID: 58392342) where the words "english" and "class" are mentioned in the service description in different places.

### Acceptance Criteria 
- [ ]  Search results for the two words side by side (as entered in the search field) should be prioritized over those where the two words searched appear further apart from each other

### Steps for QA: 
1.  Search on Algolia for two words such as "english class" or "job search"
2. Search results for the two words side by side (as entered in the search field) should be prioritized over those where the two words searched appear further apart from each other.

**Comment by rasmus-storjohann-PG** [comment]
@jparlina to please try this out in Algolia web interface and determine what the setting should be, then we can easily implement it. Let me know if you have any questions.

**Comment by jparlina** [comment]
The Word Proximity default value on Algolia is 1, so this issue should be resolved once the sorting order (issue #919) is fixed. i.e. search results must be in prioritized in the following order:
1. keyword(s) matching Service Name first, then
2. keyword(s) matching Org Name, then
3. keyword(s) matching Service Description

Example: 
When searching keywords "english class" in Victoria (48.428421, -123.365644), with Radius Precision 5000 (5km), and Word Proximity as default (1): 

The service record "FOODSAFE", where the words "english" and "class" are only in the **_Service Description_**, came out higher (#2) on the search results than "**English** Conversation **Class**es" provided by Richmond Multicultural Services (#5), where the words "english" and "class" are in the **_Service Name_**. 

![Screen Shot 2020-02-04 at 12 12 32 PM](https://user-images.githubusercontent.com/48343061/73782972-bf8a8d80-4747-11ea-92c6-2ba785f30e79.png)

![Screen Shot 2020-02-04 at 12 12 47 PM](https://user-images.githubusercontent.com/48343061/73782999-c6190500-4747-11ea-8fe0-929d0d669f42.png)
