### ISSUE TITLE
Translation bug: Incorrect translation for Q10 in Tagalog

### ISSUE THREAD

**Issue by ArtiBPG** [pg-irc/pathways-frontend#976]
There was a copy paste error in the translation spreadsheet from the time we were using the spreadsheets.

**Question 10 in the Questionnaire for Tagalog:**
English: Anything else you're interested in? Select all that apply.
Current Tagalog translation: Kailangan mo ba ng pinansiyal na tulong o suporta sa mababang kita?
Change to: Iba pang mga bagay na interesado ka? Piliin ang lahat ng naaangkop
 
**Help and Support section in Chinese Trad:**
English: If you are having difficulty with settlement in Canada, we suggest getting in touch with a settlement worker.
Current zh_Hant: 幫助和支持
Change to: 如果您在加拿大有安居上的困難，我們建議您與安置服務人員聯繫。

Fixed in Weblate

### Steps for QA: 
1.  Check for updated translation in the next build and prod build

**Comment by tomy-pg** [comment]
Tested this locally:
```
git submodule update --remote --merge

in package.json change:
"build-strings": "lingui compile --strict"
to

"build-strings": "lingui compile"

because we are currently waiting for translations

./bin/strings.sh --combine-pos
yarn build-strings
```
Passes. Will test again next staging and production build.

**Comment by tomy-pg** [comment]
Staging version 1.18.0:
Pass
