### ISSUE TITLE
Google Analytics - IP Excluded provides the same numbers from May-Dec 2019 as the one without IP Excluded

### ISSUE THREAD

**Issue by jparlina** [pg-irc/pathways-frontend#977]
Does the Google Analytics - IP Excluded actually exclude IP from our office location? The numbers from May-Dec 2019 are the same from _Google Analytics-IP Excluded_ and as those from _Google Analytics-Arrival Advisor._ 

**Example 1:** The number of users from May-Dec 2019 are exactly the same (highlighted in red)from both the "IP Excluded" and the regular "Arrival Advisor" analytics:
![Screen Shot 2020-01-14 at 9.43.50 AM.png](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/bd5453e3-2320-4cda-ac00-38acfcf6e056)

**Example 2:** Sessions by Device and Top Screens Views from the last 90 days also show the same numbers from both the "IP Excluded" (screen shot 2a) and the regular "Arrival Advisor" (screen shot 2b) analytics: 

**_Screen shot 2a:_**
![Screen Shot 2020-01-14 at 10.18.05 AM.png](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/f9a06b27-aabf-44ff-b234-e784db861017)

**_Screen shot 2b:_**
![Screen Shot 2020-01-14 at 10.17.57 AM.png](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/14f98128-182f-45d6-a7f7-9b61af5faa31)

### Acceptance Criteria 
- [ ]  

### Steps for QA: 
1.

**Comment by ian-lin-PG** [comment]
I created a no filter view on the app now, it should show whether if a filter is wrongly applied or if none of the filters are working.

**Comment by ian-lin-PG** [comment]
Upon checking the results with the `No filter` view and compared to the existing `IP Excluded` and `ArrivalAdvisor` view it was apparent that the stats on all three views are the same. In essence, none of the filters are working correctly. 

The reason could be best described with this Google support page [here](https://support.google.com/analytics/thread/7960451?hl=en). As far as I know we don't collect the IP addresses and send them to Google as part of every google analytics event, this might explain why the filters don't work.

We might have to enact a policy of enabling the easter egg on staff phone, and during testing to reduce the noise. We might also have to move easter egg to the home page to cut down on the number of requests to enable easter egg on the search page.

**Comment by rasmus-storjohann-PG** [comment]
The fix is to use the easter egg.
