### ISSUE TITLE
Link from app feedback UI to web page describing how our feedback system works

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#982]
### Acceptance Criteria 
- [ ] There is a link in the app for more information about the feedback system
- [ ] The link opens a page in the app with localized information about this, similar to the About page

### Questions
- [x] Mock is needed, link will probably be on [this](https://zpl.io/bPn5L4m) modal.

**Comment by cherrielam** [comment]
Just checking the backlog and noticed this — is this still needed? @rasmus-storjohann-PG If so, I/ @aron-chen-pg should hop on this soon?

**Comment by cherrielam** [comment]
### String added on the Feedback Options Modal:
Add "Learn more" (see below)
> Your suggestions will be reviewed by our team before making final changes to the service information. **Learn more**

### Feedback system explainer:

> # Services listed on Arrival Advisor
>  
> ### Where do the services listed on Arrival Advisor come from?
> The services listed on Arrival Advisor come from [bc211](http://www.bc211.ca), a nonprofit information and referral organization that publishes a searchable online directory of community, government, and social services in British Columbia. bc211’s staff members collect and update this services information.
> 
> ### I found some inaccurate or missing services information in the app. What do I do?
> You can make a suggestion by clicking “Suggest an update” at the bottom of a service’s detail page in Arrival Advisor. Then, you can provide more information in the form to let us know what needs to be updated. You can choose to leave your contact email so that our team can follow up with you. The Arrival Advisor team will work with bc211 to review your suggestions before we make the final changes.
> 
> ### How can I get my organization or service listed?
> You can read [bc211’s Inclusion Policy here](http://www.bc211.ca/inclusion-policy/) to see what organizations and services are listed. If you believe that your organization or service fits the inclusion criteria, you can email updates@bc211.ca so the bc211 team can review your organization or service. You can also visit http://www.bc211.ca for more information.

Here's what I've got so far. I'd like to get some eyes to review for any edits before it goes forward for translation (@jparlina @tomy-pg @ian-lin-PG @rasmus-storjohann-PG)? 

Also, content-wise, am I missing anything?

**Comment by rasmus-storjohann-PG** [comment]
That looks good to me

**Comment by jparlina** [comment]
Looks good @cherrielam. Where does the link to the explainer appear on the app?

**Comment by tomy-pg** [comment]
This should be high priority as it is blocking translation QA.

**Comment by cherrielam** [comment]
@jparlina in case this is still unclear, the link is written as "Learn more" on the Feedback Options modal. It should say:

_Your suggestions will be reviewed by our team before making final changes to the service information. **Learn more**_

**Comment by ian-lin-PG** [comment]
Here is screenshot with `Learn More`, probably needs to be tweaked as the 2 existing link styles don't fit with this particular situation. Also need the link that leads to the explainer.
![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-07-20 at 14 44 02](https://user-images.githubusercontent.com/52009863/87989804-8e084300-ca97-11ea-8694-a473bc6ed695.png)

**Comment by cherrielam** [comment]
Agreed on the link styles, I think it would look find though just without the icon? The explainer should be in the form of an in-app modal/page (like "About Arrival Advisor")

**Comment by ian-lin-PG** [comment]
@cherrielam here is what the explain feedback page looks like. Let me know your thoughts!
![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-07-27 at 11 05 07](https://user-images.githubusercontent.com/52009863/88575836-564e4d80-cff9-11ea-9cdd-76972661cd97.png)
![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-07-27 at 11 02 32](https://user-images.githubusercontent.com/52009863/88575858-5ea68880-cff9-11ea-883c-712b6ef312bc.png)
![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-07-27 at 11 02 36](https://user-images.githubusercontent.com/52009863/88575866-61a17900-cff9-11ea-9108-7f598bf1d046.png)

**Comment by cherrielam** [comment]
Looking OK so far, can we:

- Add a space before "Learn more"
- Make sure the padding/margin in the body text of the Explainer lines up with the header?

**Comment by ian-lin-PG** [comment]
@cherrielam Addressed your comments, see these screenshots.
![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-07-27 at 12 28 45](https://user-images.githubusercontent.com/52009863/88583247-d332f480-d004-11ea-8141-ff8002835171.png)
![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-07-27 at 12 28 50](https://user-images.githubusercontent.com/52009863/88583252-d4fcb800-d004-11ea-9a4d-f56d6469d079.png)
![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-07-27 at 12 28 54](https://user-images.githubusercontent.com/52009863/88583260-d928d580-d004-11ea-9abd-5a7e77de1ad9.png)

**Comment by cherrielam** [comment]
the left and right sides aren't balanced
can we add padding/margin above the first question?

**Comment by ian-lin-PG** [comment]
@cherrielam The bottom now have `paddingHorizontal: 15` on both sides now, it used to be 15 to the left and 5 to the right, that was on me. The margin above the first question is currently `marginTop: 5` I can certainly increase it.

![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-07-27 at 16 09 43](https://user-images.githubusercontent.com/52009863/88600725-d4bfe500-d023-11ea-91cc-2db0708bc915.png)

**Comment by cherrielam** [comment]
the latest one looks fantastic!

**Comment by cherrielam** [comment]
actually sorry do you mind if we also add a little bit of spacing between the question and the answer? thank you!

**Comment by ian-lin-PG** [comment]
> actually sorry do you mind if we also add a little bit of spacing between the question and the answer? thank you!

@cherrielam Here are options with `marginTop:10` and `marginTop:20`. More or less margins are possible, just providing options for now.
![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-07-28 at 11 57 26](https://user-images.githubusercontent.com/52009863/88709201-b1e80c00-d0c9-11ea-8c05-207359487997.png)
![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-07-28 at 11 56 32](https://user-images.githubusercontent.com/52009863/88709216-b57b9300-d0c9-11ea-924c-cb5bccd08f96.png)

**Comment by cherrielam** [comment]
MarginTop: 10 is best. Thank you!!

**Comment by jparlina** [comment]
Looks fine to me on Staging V1.42.0 server V 1.3.35. Sending them for language QA.

**Comment by tomy-pg** [comment]
Staging version 1.44.0 - PASS
