### ISSUE TITLE
Save feedback data to airtable or similar cloud service

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#985]
### Acceptance Criteria 
- [x] When clicking the submit button on the modal ([mock](https://zpl.io/VOnjoDl)), submit the suggested updates to the server.
- [x] There is some form of schema or plan for how the data is stored in the server, including suggested changes to specific fields, suggestions to remove a service, general "other" feedback on a server, user email, full name, SPO role.
- [x] Suggested changes are submitted only for the fields where the check box is selected ([mock](https://zpl.io/anQ019J)). (So if you check a checkbox, type in something, uncheck the checkbox and hit submit, what you just typed in is not included in the submitted data) 
- [x] After saving is complete, clear fields (to avoid spamming the same data), and show message "Thank you for your contribution" ([mock](https://zpl.io/VDd674q)).

**Comment by bensinjin** [comment]
Questions:

Currently the "Remove this service" and "Other" links from the "Suggest an update" modal take you to a new screen which would have its own feedback state, then, after you press submit, and the content is sent to Airtable, you're taken back to the service detail to submit your email. If we want the email address to be submitted along with the feedback we'll likely have to move feedback into Redux so it can be accessed from both screens or if this is not how it works we'll have a new table in Airtable for email addresses + service ids?

**Comment by bensinjin** [comment]
Talked to Rasmus a bit:


Ben  11:50 AM
Ok .. so currently the other feedback options actually take you to new screens in the app

rasmus  11:51 AM
We want the email attached to the feedback so we can use it to assess the feedback reliability and respond to the user as well.






Ben  11:51 AM
yeah that's what I was thinking
11:51
we may need to move the feedback into Redux then because we actually jump between different screens now to give feedback
11:52
the "other" non-field feedback is actually done on a new screen, which is kinda awkward

rasmus  11:56 AM
It's a bit of a pain to put the feedback data in redux now, but it'll give us flexibility, such as other feedback being its own screen is no longer a problem.

**Comment by bensinjin** [comment]
For now I'm waiting a bit for changes from Niko and Tomy to come in as we're all needing to work on the same screens. I've got a hook in `feature/Issue_985_Send_feedback` for sending feedback. For the new Feedback screens ("Other" and "Remove service") we're going to try sending the feedback text back to the service detail screen as a query parameter which will populate the feedback object.

**Comment by bensinjin** [comment]
### Testing setup
You'll need to add values for `AIRTABLE_BASE_ID`, `AIRTABLE_TABLE_ID`, and `AIRTABLE_API_KEY` to your .env file before you get started. To find these values:

1. Make sure you've accepted the invite from Ian to the Airtable account.
2. Head to https://airtable.com/login, once logged in head to https://airtable.com/account look under the "API" heading for your `AIRTABLE_API_KEY`.
3. Head to https://airtable.com/api and click the "Arrival Advisor" base. This sends you to the API docs for our Arrival Advisor database. In the introduction you should see "The ID of this base is appTjP8xcGuZWfQ3b.", use `appTjP8xcGuZWfQ3b` as the `AIRTABLE_BASE_ID`.
4. Still in the API docs from the previous step you'll see a heading on the left: "<TABLE_ID>_TABLE", there will be one of these for each table in our database. The table we want to write to has the heading "SERVICES_FEEDBACK_TABLE", use `services_feedback` as the `AIRTABLE_TABLE_ID`.

### Testing instructions
**_Note: We do not yet have a button to submit field level feedback. The functionality is done in this PR but the button will come in another PR. For now you are testing only the "Remove this service" and "Other" feedback._**

- [ ] Submitting: "Suggest an update" > "Remove this service" pushes provided data to `services_feedback` table
- [ ] Submitting: "Suggest an update" > "Other" pushes provided data to `services_feedback` table
