### ISSUE TITLE
Scroll bar cannot scroll to the end of search results

### ISSUE THREAD

**Issue by ian-lin-PG** [pg-irc/pathways-frontend#989]
Scroll bar currently changes size as we scroll. We cannot reach the bottom of the search result to load more services.

### Acceptance Criteria 
- [x]  Scroll bar does not change size as we scroll
- [x]  Scroll bar go down till `Show more services`

### Steps for QA: 
1.  Go to search page
2. Scroll all the way to the bottom of results
3. Click on `Show more services`
4. Observe new services loading and the scroll bar reflect the extra services.

**Comment by tomy-pg** [comment]
Staging version 1.18.0:

- [x]  Scroll bar does not change size as we scroll
- [x]  Scroll bar go down till Show more services
PASS
