### ISSUE TITLE
Monitor impending jsLingui release

### ISSUE THREAD

**Issue by tnightingale** [pg-irc/pathways-frontend#99]
A release of jsLingui which fixes the babel dependency issue is [on the horizon]( https://github.com/lingui/js-lingui/pull/220#issuecomment-395113127). As soon as this is out we can update our pinned version and get back on the SemVer releases.

**Comment by tricoder42** [comment]
jsLingui **2.1.0** has just been released, please check it out 👍

**Comment by tnightingale** [comment]
Thanks for the update @tricoder42 !! We're very happy with jsLingui, please keep the good work coming :)

**Comment by tricoder42** [comment]
Good to hear! I need schedule some time to work on jsLingui, it seems it finally got a tracking and backlog of issues is growing :) Ping me if you need anything
