### ISSUE TITLE
Investigate additional refresh after search button is clicked

### ISSUE THREAD

**Issue by ian-lin-PG** [pg-irc/pathways-frontend#990]
Right now there is at least 3 additional refreshes for each search button click, many of which changes the search results but not in meaningful ways (irrelevant to the search term). Additional issue is that geocoder may take up to 2 seconds to refresh with the relevant results, determine if this becomes an usability issue.

### Acceptance Criteria 
- [ ]  Find out where the additional refreshes are from and stop them if possible
- [ ] Decide if loading state is necessary if geocoder takes too long to return

### Steps for QA: 
1.  Go to search page
2. Type `ICBC` into search term field
3. Type 'Vancouver' into search location field
4. Press search button
5. Observe if there are multiple refreshes till the final result loads
6. Observe how long till the final result loads

**Comment by ian-lin-PG** [comment]
@jparlina @aron-chen-pg See if this is still an issue, if not please close the issue.

**Comment by tomy-pg** [comment]
Issue #1030 should address this as we refactored the search entirely to remove the additional refreshes coming from Algolia instant search and our useEffects.
