### ISSUE TITLE
Email/Phone/Website row on Service Detail Page should not be clickable when there's no corresponding data 

### ISSUE THREAD

**Issue by jparlina** [pg-irc/pathways-frontend#995]
When there's no data for Email/Phone/Website on the Service Detail Page, the Email/Phone/Website row or card should not be clickable. From the user experience perspective, we should not provide functions/options that are not usable for the users. 

For example, Service Canada record does not have an email address, so the Email row should not be clickable, which then triggers the creation of a new email with the "To" address filled in as "Null" - see screenshots below. 

### Acceptance Criteria 
- [ ]  When there's no data for Email/Phone/Website on the Service Detail Page, the Email/Phone/Website row or card should not be clickable. 

### Steps for QA: 
1.  Select the topic "Applying for a Social Insurance Number (SIN)" on the home page
2. Click "Find related services near me button"
3. Select one of the Service Canada records on the service listing 
4. Scroll down to the Email field and confirm that there's no email address
5. Click on the Email row/card - it should not be clickable (i.e. creating a new email message) when there's no email address

![Screen Shot 2020-01-27 at 2.55.54 PM.png](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/4d1ad6f3-9bb7-4c24-8d3b-89c9f81eb01e)

**Comment by ArtiBPG** [comment]
@cherrielam for each field that does not have data, should we disable or remove the icon?

**Comment by cherrielam** [comment]
I think we should remove the icon since it's not usable at all, and perhaps make the Label greyed out to reinforce for users that this field does not have any data.

**Comment by ian-lin-PG** [comment]
The missing contact fields are greyed out and unclickable.
![Screenshot_20200306-093307](https://user-images.githubusercontent.com/52009863/76107501-9dc23780-5f8d-11ea-975b-9271f1d0646c.jpg)
