### ISSUE TITLE
JSX strings marked as fuzzy are not translated

### ISSUE THREAD

**Issue by tomy-pg** [pg-irc/pathways-frontend#998]
The following locales and strings need to be fixed:
French
- [x] FIND A SERVICE
- [x] Multilingual health information services
- [x] New topics have been recommended based on your answers!
- [x] Save important topics and services to build your personal plan for settlement.
- [x] Search for services

Korean
- [x] FIND A SERVICE
- [x] Multilingual health information services
- [x] New topics have been recommended based on your answers!
- [x] Save important topics and services to build your personal plan for settlement.
- [x] Search for services

Punjabi 
- [x] FIND A SERVICE NEAR YOU
- [x] New topics have been recommended based on your answers!
- [x] Save important topics and services to build your personal plan for settlement.
- [x] Search for services

Tagalog
- [x] New topics have been recommended based on your answers!
- [x] Search for services

Simplified Chinese
- [x] FIND A SERVICE
- [x] New topics have been recommended based on your answers!
- [x] Save important topics and services to build your personal plan for settlement.
- [x] Search for services

Traditional Chinese 
- [x] FIND A SERVICE
- [x] Multilingual health information services
- [x] New topics have been recommended based on your answers!
- [x] Save important topics and services to build your personal plan for settlement.
- [x] Search for services

**Comment by tomy-pg** [comment]
All unchecked strings above have _target_ strings that are not the correct translation.

**Comment by ArtiBPG** [comment]
Tagalog done

**Comment by ArtiBPG** [comment]
Korean , Hans and Hant done.

**Comment by tomy-pg** [comment]
Staging version 1.19.0 - missing strings now in app.
